### ISSUE TITLE
correctly identify and handle failed transactions

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1017]
Completed Transactions may have two states: Successful and Failed. Successful ones are already being handled correctly. 

We also need to introduce a FAILED state for transactions.

Potential cases when transactions may have failed is when transaction is included in blockchain but has errors (i.e. out of gas error on Ethereum) the transaction is displayed as PENDING which is incorrect. The client needs to be able to identify such transactions and display them accordingly.

*FAILED Transactions**

- [ ] At the moment when transaction is included in blockchain but has a failed state (i.e. out of gas error on Ethereum) the transaction is displayed as PENDING which is incorrect. 
--  such transactions can definitely happen on Ethereum blockchain. Not sure about EOSIO and Binance DEX. Need to be looked at as well. 
-- any transaction that is valid but failed to transfer the funds due to some error then it should appear as FAILED in transactions tab (see below).
-- it should also have FAILED status in transactions list >> tx info (see below).  
-- failed transaction (when transaction is in blockchain) should be displayed in transactions list even after the wallet restore.
-- failed transaction (when transaction is NOT in blockchain) won't be visible after restore
-- the amount of failed transactions should not affect the available balance amount.
- [ ] In certain cases transactions are rejected by network nodes (i.e. bitcoin blockchain). Depending on the blockchain the rejection may occur for various reasons. Rejected transactions are not included in the blockchain.
-- add logic to ensure that transaction has reached the mempool but was rejected by multiple different nodes. That would be ensure that it's not just one add that rejected the transaction

![failed1](https://user-images.githubusercontent.com/8611762/69050888-1fb54180-0a2d-11ea-9a5a-11b8b8f759b1.jpg)
![failed2](https://user-images.githubusercontent.com/8611762/69050889-1fb54180-0a2d-11ea-9090-9b4178baa498.jpg)

**Comment by Dianaaiym** [comment]
failed transaction (when transaction is in blockchain) don't display in transactions list after the wallet restore.
