### ISSUE TITLE
Error Create Wallet

### ISSUE THREAD

**Issue by codeBrice** [horizontalsystems/unstoppable-wallet-android#1021]
Hi, I'm having a problem when generating the wallet. I debug a bit the code and the same throws a catch on the next line.

![image](https://user-images.githubusercontent.com/30805278/61234441-158ed980-a701-11e9-8326-57c8ad75af57.png)

can you help me? thanks!

**Comment by abdrasulov** [comment]
HI @codeBrice,

Thanks for your feedback. Could you please let us know if you have made any changes to the source code? It may be related to Android OS. There are cases when the same exception is thrown when the setUserAuthenticationValidityDurationSeconds is a small value, for ex. 5.

**Comment by codeBrice** [comment]
> HI @codeBrice,
> 
> Thanks for your feedback. Could you please let us know if you have made any changes to the source code? It may be related to Android OS. There are cases when the same exception is thrown when the setUserAuthenticationValidityDurationSeconds is a small value, for ex. 5.

Hi,

If I have modified the source code, but the setUserAuthenticationValidityDurationSeconds I keep it in 24h reflected in seconds as it appears in its original source code. The truth is very strange, since it happens to me sometimes and not always.

**Comment by abdrasulov** [comment]
Hi @codeBrice,

That is strange. It should not throw this type of error. We'll include this issue into our current iteration. Can you please provide us the Android OS version of the device where you catch it and what the device is?

**Comment by codeBrice** [comment]
> Hi @codeBrice,
> 
> That is strange. It should not throw this type of error. We'll include this issue into our current iteration. Can you please provide us the Android OS version of the device where you catch it and what the device is?

yes, sure. 

OS: Android 8.0.0
Device: ASUS_Z017D

**Comment by rafaelekol** [comment]
@codeBrice Is your phone has screen lock enabled(PIN or pattern)?

**Comment by codeBrice** [comment]
> @codeBrice Is your phone has screen lock enabled(PIN or pattern)?

Hi friend. I had some time without going through here, if 
 i have it activated

**Comment by rafaelekol** [comment]
> i have it activated

Did it help? Do you still see exceptions?

**Comment by codeBrice** [comment]
for now everything is right. The application works correctly @rafaelekol
