### ISSUE TITLE
Wallet Backup Enforcement protocol

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1023]
- [x] If the state of the wallet is "not backed up" for the given coin. Then click on receive buttons should trigger controller that would require user to backup the wallet before s/he can proceed (see attached). Note: there can be case when the user has backed some keys but not the other ones. Such cases should be handled accordingly.

- [x]  if wallet not backed up, don't display the  red exclamation mark on Settings tab bar icon. Since we are asking user to backup before funds can be received the red alert icon on tab bar becomes redundant. The exclamation mark should be removed only from settings icon but should remain in all other places(settings controller, security controller, manage keys).

- [ ] title : Backup Required 

- [x] description text string: You need to backup the [key_name] key before you may receive [coin_name]. @Dianaaiym localize texts

![6521B903-93DA-4DCC-B987-13C4AE02B265](https://user-images.githubusercontent.com/8611762/61531624-32047c00-aa49-11e9-8ee8-d569d8a3b9ab.JPG)

- @TalgatNurdinov provide layout.

**Comment by TalgatNurdinov** [comment]
https://zpl.io/2pkvLZ8
<img width="747" alt="Screen Shot 2019-07-26 at 4 01 37 PM" src="https://user-images.githubusercontent.com/42367908/61944089-a9dd2400-afbe-11e9-9544-d6c93e1d9e3e.png">

**Comment by esengulov** [comment]
> https://zpl.io/2pkvLZ8
> <img alt="Screen Shot 2019-07-26 at 4 01 37 PM" width="747" src="https://user-images.githubusercontent.com/42367908/61944089-a9dd2400-afbe-11e9-9544-d6c93e1d9e3e.png">

@TalgatNurdinov 
why not to use bottom controller (i.e. Receive)?

**Comment by horsys** [comment]
@rafaelekol @TalgatNurdinov this alert should be similar to bottom controller that's triggered on Delete Key action which asks user to backup first.

**Comment by Dianaaiym** [comment]
1. If wallet not backed up, the red exclamation mark not display on all settings controller
**Ticket requirement:** The exclamation mark should be removed only from settings icon but should remain in all other places(settings controller, security controller, manage keys).
