### ISSUE TITLE
Finalize Manage Keys

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1025]
- [x] add text block between page title and keys. Text "Anyone with access to your Keys can steal your wallet funds. Store them safely and never show them to anyone. [2 line breaks] Backup each key to be able to restore funds if you loose or break your phone, or simply the wallet app gets deleted." (@Dianaaiym the text should be localized.)
- [x] make sure that text has two line breaks between the sentences.
- [x] remove word 'Key' from key headers. Should look like "Binance Chain", "EOS Blockchain" etc
- [x] rename Import to Restore 
- [x] rename New to Create 
- [ ] @Dianaaiym when doing localizations make sure that the wording on this controller is translated as close as possible to the original. this is the most important controller in whole app.
- [x] create button on EOS. The "create" action for EOS is not yet implemented. Therefore, when clicked the user should see following alert "At this point, the wallet is not able to create new EOS wallet accounts. You're only able to restore the existing one." @Dianaaiym the text needs to be localized

**Comment by TalgatNurdinov** [comment]
https://zpl.io/bAl6oyx
https://zpl.io/Vke56wv
