### ISSUE TITLE
Failed to create apk production mode 

### ISSUE THREAD

**Issue by codeBrice** [horizontalsystems/unstoppable-wallet-android#1026]
Greetings friends, I have a problem when generating my apk. In production debug mode it works correctly, but when I go to production release the balances of the coins do not show neither the Tx

**Comment by rafaelekol** [comment]
Hi,
In case you have issue only with Ethereum and Erc20 coins. Then for release build you need enter your keys for Infura and Etherscan in gradle file:

```
release {
            debuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            resValue "string", "infuraProjectId", "[YOUR_INFURA_PROJECT_ID]"
            resValue "string", "infuraSecretKey", "[YOUR_INFURA_SECRET_KEY]"
            resValue "string", "etherscanKey", "[YOUR_ETHERSCAN_KEY]"
            resValue "string", "is_release", "true"
        }
```

**Comment by codeBrice** [comment]
thank you very much friend!
