### ISSUE TITLE
Add Share This Wallet cell to Settings

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#1034]
- layout ready, https://github.com/horizontalsystems/HS-Design/issues/14
- click on the button should open native share controller
- share text: "Here is the app I use to store and manage my crypto" https://unstoppable.money
- @Dianaaiym the share text above should be localizable

**Comment by Dianaaiym** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/964
