### ISSUE TITLE
Price Alerts (Push Notifications)

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1039]
**Activating Alerts:**

- [x] Settings tab: add new section to settings from where user can set the price change alerts.
-- title: Notifications (@Dianaaiym, localizable text)
- [x] Settings tab: display number of activated notifications on the right side of the cell. The number should be shown when the user has set the alerts.
- [x] click on Settings >> Alerts: opens a screen that lists all coins with an option to enable/disable alerts for the coin.
- [ ] permission to show notification should be shown when user tries to enable pushes
- [ ] if the coin is disabled and has set alerts then it should be set to Off.
- [x] when the user Turns Off (denies) notification from OS settings: show following text and "turn on" button.
> The notifications for Unstoppable Wallet app are disabled. You need to turn them on in order to be able to receive price change alerts. (@Dianaaiym button text is localizable)
>
> Button (Turn On) (@Dianaaiym button text is localizable)
- [x] new: change the text on top section to (@Dianaaiym)
>Set price change alerts for the coins you would like to watch.
>
>You will be alerted when the change in price for the last 24 hours exceeds selected threshold.

**Push Behavior** 

- [x] fetch price data once every 60 minutes
- [x] click on push should open open: 
-- lock screen if the pin lock is enabled on app level
-- balance tab if the pin lock is disabled
- [x] on app open dismiss/clear all pushes 

**Push Template:**

- [x] push look:
-- title: Unstoppable
-- icon: app icon
- [x] sounds: use standard system sound

**Push Texts:**

- [x] when one coin is UP (over 5%)
-- push subtitle: Bitcoin 🚀🌙
-- push body: Up 5% 😎

- [x] when one coin is UP (over 3%)
-- push subtitle: Bitcoin 🚀
-- push body: Up 3% 😉

- [x] when one coin is UP (over 2%)
-- push subtitle: Bitcoin 🚀
-- push body: Up 2% 🙂

- [x] when one coin is DOWN (over 5%)
-- push subtitle: Bitcoin 💔
-- push body: Down 5% 😩

- [x] when one coin is DOWN (over 3%)
-- push subtitle: Bitcoin 💔
-- push body: Down 3% 😧

- [x] when one coin is DOWN (over 2%)
-- push subtitle: Bitcoin 💔
-- push body: Down 2% 😔

- [x] when more than two coins is UP/DOWN: group all notifications into a single notification.
-- push subtitle: Notifications 📈📉 (@Dianaaiym, localizable text, should be same to 'Notifications' in Settings)
-- push body: list coins from up to down by value: [coin_symbol_1] up x%,  [coin_symbol_2] up y%, [coin_symbol_3] down z%, ... etc

- [ ] @Dianaaiym: in push texts above there are only two localizable elements
-- up / down
-- Portfolio Notifications

**@TalgatNurdinov** 

Enable user to set price change alerts. There should be a section in settings from where wallet user able to configure price change alerts. It should list all coins with following options for each:

- alerts Off
- alert on 2% change
- alert on 3% change
- alert on 5% change

**Comment by TalgatNurdinov** [comment]
<img width="790" alt="Screen Shot 2019-09-19 at 4 00 13 PM" src="https://user-images.githubusercontent.com/42367908/65234770-078d7880-daf7-11e9-8188-4b0ae608d249.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3164%3A149

**Comment by d4f5409d** [comment]
Can we get this back?

**Comment by esengulov** [comment]
> Can we get this back?

we will reconsider it in the near future. The previous implementation was problematic and had to be disabled.
