### ISSUE TITLE
Manage Keys >> Delete

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1052]
**Delete Button**

- [x] if the key is not backed up then click on this button should trigger following alert with 'Backup' button. "You need to backup this key before you may delete it." Clicking on Backup button would open the Backup (intro step) for that key. @Dianaaiym this alert should be localized 
- [x] added new sketch for the bottom alert controller (@TalgatNurdinov provide the layout asap)

- [x] @Dianaaiym following three text blocks should be localized as well
-- text1: This action will delete the [key_title] key (wallet) from this device.
-- text2: Coins that will be disabled: [same coin list as on the key cell on KEYs page]
-- text3: If you don't have a backup of this key you will loose the respective funds. 
-- title : Delete Key (localizable)
-- button title : Delete from Phone (localizable)
- ~~[ ] redesign the controller that is shown on the click of this button (see below).~~

**Comment by esengulov** [comment]
> * if the key is not backed up then click on this button should trigger following alert with OK button. "You need to backup this key before you may unlink it."

we need design for this alert @TalgatNurdinov

**Comment by crwatkins** [comment]
I think this is a good idea.  It occurred me the first time I touched the wallet and wondered what "Unlink From This Device" meant so I tried it and the message said "Make sure you have backed up..." and I thought "Don't you know?".

In any case, this is a request for different terminology than "Unlink".   As a user, that word doesn't really mean anything to me (as a developer, it means all sorts of things).

**Comment by esengulov** [comment]
> I think this is a good idea. It occurred me the first time I touched the wallet and wondered what "Unlink From This Device" meant so I tried it and the message said "Make sure you have backed up..." and I thought "Don't you know?".
> 
> In any case, this is a request for different terminology than "Unlink". As a user, that word doesn't really mean anything to me (as a developer, it means all sorts of things).

Good point! 

Potentail options:

- Disconnect Key
- Remove Key
- Delete Key

I think "Delete Key" would sort of convey the right message. Thoughts?

**Comment by crwatkins** [comment]
I think 

* Delete Wallet 

would give users the best impression of what is going to happen next (some people refer to the app as the "wallet", but I don't think that is a problem here).

I'll point out that after this operation, the next thing they can do is [Create Wallet], so it is reasonable to assume they just deleted it.

**Comment by esengulov** [comment]
@Dianaaiym note the text changes:

-  changed the alert fort text1
- changed the alert for a case when the key is not backed up

In both cases changed the word unlink to delete.

Also, note that both the title and button text on bottom alert controller should be localizable

**Comment by esengulov** [comment]
![IMG_8718](https://user-images.githubusercontent.com/8611762/62023215-b1384380-b1f1-11e9-8856-3475149399cb.JPG)

**Comment by TalgatNurdinov** [comment]
https://zpl.io/bAl6oyx
