### ISSUE TITLE
Manage Keys >> Show

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1056]
**Show Button**

- [x] the show button should be shown when user has backed up the key

- [x] show intro: display similar intro controller as on Backup action but with different title (should be 'Show Key') and buttons ("Close", "Show Key") 

- [x] the text (identical to backup intro text)

> "_The key that will be shown next is the only way to restore your funds if your phone is ever lost, stolen, broken etc. Make sure that no one is watching your screen. <br><br>The coins controlled by this key: [same coin list as on the key cell on KEYs page]_".  <br><br>

- [x] should ask for pin if pin exists.

- [x] on the page that shows the key the bottom button should say "Close".

**Comment by Dianaaiym** [comment]
when you click "Show key", the title is not visible, you need to scroll

**Comment by Dianaaiym** [comment]
fixed on samsung
but the same problem is on Huawei, Xiaomi
