### ISSUE TITLE
thoroughly check the library for generating/parsing QR codes

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1078]
It's essential that library that's used for QR scanning/generating purposes is throughly checked.

**Comment by rafaelekol** [comment]
The library that we use for QR code scanning and generating QR codes
https://github.com/journeyapps/zxing-android-embedded
is popular among Android developers and seems to be reliable.
I checked code for external http request, and didn't find any.
