### ISSUE TITLE
Transactions Tab: displays transactions from previously restored accounts

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1079]
That bug was spotted on IOS first. I heaven't tested it on Android as such but it should be an issue on Android as well. https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/809

Been testing EOS restore feature and have repeatedly noticed the case when the transactions list for EOS displayed transactions from both account but should have been one.

Upon further testing it seems to be a bug with GUI cache. The GUI controller cache is not being cleared upon unlinking. If the users adds a new account before the GUI is cleared then a transactions list for the coin will be displaying transactions from the newly linked as well as the unlinked accounts.

Killing the app displays the GUI properly

**Comment by omurovch** [comment]
Solution is partially correct, but should consider cases when transactions are filtered by coin.
