### ISSUE TITLE
EOS Transactions >> add ability to Verify TX status on EOS block explorer

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1083]
We need to provide users with ability to verify EOS transactions on a public block explorer as we do for other blockchains.

- [ ] the default option should be 'eosnode.tools' . This API will route requests to the nearest  available block producer and return the requested data. https://eosnode.tools/proxy
- [ ] apart from the default one there should be two other alternatives (should be same both on iOS and Android). You can select any explorer from the top 10 list here, https://eostracker.io/producers . The details about how to interact with the API can be found here, https://www.eosdocs.io/resources/apiendpoints/

**Comment by Dianaaiym** [comment]
unable to open link to EOS-block explorer
