### ISSUE TITLE
Binance Integration: Supported tokens

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1085]
- [x] GTO (Gifto)
https://community.binance.org/topic/93/binance-dex-now-list-gifto-gto

- [x] ANKR (Ankr Network)
https://community.binance.org/topic/107/binance-dex-list-ankr-nework-ankr

- [x] BTCB (Bitcoin BEP2)
https://community.binance.org/topic/234/binance-dex-list-bitcoin-bep2-btcb

- [x] CRPT (Crypterium)
https://community.binance.org/topic/814/binance-dex-has-listed-crypteirum-token-crpt

- [x] CAS (Cashaaa)
https://community.binance.org/topic/752/binance-dex-will-list-cashaa-cas

- ~~[ ] XBASE https://community.binance.org/topic/1030/binance-dex-will-list-eterbase-coin-xbase~~

**Comment by nk-the-crazy** [comment]
By using existing CryptoCompare, support can be added for following tokens:
1. GTO
2. ANKR
3. CRPT
4. CAS

**Comment by nk-the-crazy** [comment]
Added xrates support for:
1.GTO
2.ANKR
3.BTCB
4.CRPT
5.CAS
