### ISSUE TITLE
Question for navigation button

### ISSUE THREAD

**Issue by codeBrice** [horizontalsystems/unstoppable-wallet-android#1110]
If I would like to modify the background of the menu incorporated in the wallet. The correct form would be directly from the Layout XML or from the mainActivity.kt?

**Comment by rafaelekol** [comment]
Can you show with screenshot which part of the app you want to change.

**Comment by codeBrice** [comment]
> Can you show with screenshot which part of the app you want to change.

![Screenshot_20190806-053412_1](https://user-images.githubusercontent.com/30805278/62529219-3e8c2100-b80c-11e9-8480-78af22dfe6b5.jpg)

**Comment by esengulov** [comment]
@rafaelekol could you address and close the issue ;)

**Comment by rafaelekol** [comment]
In MainActivity class, there is function `loadViewPager()`
In this function you can add line like this, to change background color:
`ahBottomNavigation.setDefaultBackgroundColor(ContextCompat.getColor(this, R.color.red_warning))`
