### ISSUE TITLE
balance tab flickers between multiple states on Welcome >> New Wallet action

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1122]
At first the wallet loads empty balance tab with no cells. Then it shows coin cell placeholders with loading animation. And only after it shows the coin cells.

**Comment by rafaelekol** [comment]
@esengulov 
Can't reproduce

**Comment by esengulov** [comment]
> @esengulov
> Can't reproduce

Must have been fixed with the refactoring of accounts
