### ISSUE TITLE
EOS-based Tokens send validation issue 

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#1131]
While trying to send EOS token, user see error

! Tried to send:
all supported tokens
to several different address
different amount (max amount incl)

the same in iOS https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/855

**Comment by Dianaaiym** [comment]
![IMG_6285](https://user-images.githubusercontent.com/22589457/62755331-50ccc000-ba95-11e9-84d2-63d23697d0ec.JPG)

**Comment by rafaelekol** [comment]
Duplicate of #https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1134
