### ISSUE TITLE
EOS-based Tokens send validation issue

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1134]
The send works intermittently depending on various factors. Tre are a number of potential problems at the moment that needs to be handled when user trying to send EOS or EOS based token.

- [ ] certain EOS tokens require more RAM than other and infant more RAM that's needed to create EOS account. To ensure that Unstoppable functions correctly it needs to handle following scenarios:
-- (in the future)when user creates an EOS account from within Unstoppable, we should stake enough tokens to ensure that user has enough RAM at stake to send any token that supported by Unstoppable.
-- for cases when user imports his/her account to Unstoppable. It's likely that the service user used to create an EOS account staked the minimum amount necessary to have an account but not enough for sending some of the EOS-tokens. Therefore, when a respective error received we should show user a following error. "Your EOS account doesn't have enough RAM to send this token. You need to increase RAM stake to proceed." 
-- @Dianaaiym note the text above. it should be localized.
- [ ] at the moment the Send doesn't work for tokens that have decimal count different from 4 i.e. Everipedia's IQ token which has 3. Try sending an IQ token with decimal count exceeding 3. Such cases should be handled by Send controller. As in the case of ERC20 token we may have to store decimal count for each supported EOS based token.
- [ ] catch and display all potential errors returned by EOS on send action. Errors should be shown on GUI popup alert.

**Comment by rafaelekol** [comment]
EOS Error parsing class
https://github.com/radius-labs/Droidcon2019/blob/master/app/src/main/java/com/example/droidconke/ErrorUtils.java

**Comment by rafaelekol** [comment]
To get tokens symbol precision 
https://github.com/EOSIO/eos/issues/7740#issuecomment-521633972
