### ISSUE TITLE
Start integrating support for detailed price change graphs/charts

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1135]
This is a starter ticket for the issue which will be expanded (or broken down into smaller issues as we get ready for integration) 

@TalgatNurdinov link all design mockups

**Comment by TalgatNurdinov** [comment]
<img width="1110" alt="Screen Shot 2019-08-16 at 10 38 30 AM" src="https://user-images.githubusercontent.com/42367908/63143825-02c63800-c012-11e9-968e-2d5aacf3a9dd.png">


https://app.zeplin.io/project/5c613d586eccb775599ef710/dashboard?seid=5d5631123edbc29bdace5f9c

**Comment by TalgatNurdinov** [comment]
- [ ] Price changes in precent by default 
- [ ] Time stamp logic (only day chart show time)
- [ ] New tabs
- [ ] Change M.Cap / 52 wk values font size
- [ ] Rename 1w to 7d

<img width="511" alt="Screen Shot 2019-08-26 at 3 43 19 PM" src="https://user-images.githubusercontent.com/42367908/63681779-4130d380-c818-11e9-902f-7b6bb2dd6029.png">
