### ISSUE TITLE
Display approx. transaction duration on fee slider

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1136]
The approximate duration can be calculated depending on:

- [x] (in progress) wait for the IPFS will also provide the duration along with each rate, https://github.com/horizontalsystems/blockchain-meta/issues/78
-  [ ] apply new layout:
- remove slider and instead display "Transaction speed" row with only three options Slow, Medium, Fast in drop-down menu. Default "Medium"
- unlike the fee amount, the transaction speed value should be visible even before the user enters any amount input. 
- in cases where blockchain doesn't have TX fees and transactions are instant, the duration should be shown as "instant"
- [ ] transaction duration wording
-- in 'transaction speed' selector menu display values with ~ (ex: ~4 hours)
-- on send controller the values should be shows as "within 4 hours"

@TalgatNurdinov

- [x]  please upload designs
- send controller (for BTC)
- send controller (for EOS)
- send controller (for Dash)
- speed selector menu
- confirmation controller

@Dianaaiym 

- [x] the texts below should be localized
- transaction speed
- slow / medium /  fast
- instant 
- [ ] the word "within" should be localized as well 
- Russian: в течении 1ч.

[Add duration fields to response from FeeRateKit](https://github.com/horizontalsystems/blockchain-fee-rate-kit-android/issues/11)

**Comment by TalgatNurdinov** [comment]
<img width="1104" alt="Screen Shot 2019-08-16 at 10 20 19 AM" src="https://user-images.githubusercontent.com/42367908/63143327-8f232b80-c00f-11e9-817d-09312ded061b.png">
<img width="1105" alt="Screen Shot 2019-08-16 at 10 20 52 AM" src="https://user-images.githubusercontent.com/42367908/63143334-96e2d000-c00f-11e9-952e-5ec8799417f3.png">

https://app.zeplin.io/project/5c613d586eccb775599ef710/dashboard?seid=5d562f6e859f2851f9eae77b

**Comment by Dianaaiym** [comment]
drop down menu for Transaction Speed not work
relevant only for ERC20 Tokens
