### ISSUE TITLE
Add: Settings >> Report A Problem 

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1137]
We need to enable users to send bug reports to our email and/or Telegram group
@TalgatNurdinov we need a look for this one as well

- Telegram group link https://t.me/unstoppable_wallet
- email should open default mail app if such exists. if not it should copy the value and show "copied" checkmark (standard copy behavior in the app)

**Comment by TalgatNurdinov** [comment]
<img width="365" alt="Screen Shot 2019-08-15 at 3 03 03 PM" src="https://user-images.githubusercontent.com/42367908/63085206-cab9e900-bf6e-11e9-91f3-a78a7a6ea7c5.png">

https://zpl.io/Vx6Kj9x

**Comment by esengulov** [comment]
> <img alt="Screen Shot 2019-08-15 at 3 03 03 PM" width="365" src="https://user-images.githubusercontent.com/42367908/63085206-cab9e900-bf6e-11e9-91f3-a78a7a6ea7c5.png">
> 
> https://zpl.io/Vx6Kj9x

also provide the design to the destination screen

**Comment by TalgatNurdinov** [comment]
https://zpl.io/ameKvde
