### ISSUE TITLE
'Sort by' menu improvement

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1146]
- [x] new sort menu option  
-- 24h Price (%)
- [x] 24 change option would sort the coins depending on the % of price change over the last 24 hours, from positive to negative % changes. 
- [x] when app killed the sorting reverts to "sort by name". The sorting should be retained. Observe behavior on iOS build

**Comment by rafaelekol** [comment]
On iOS and Android after killing app we decided to revert sorting to lastly saved sort type(we store only Name and Value types). 24h change type is not stored to storage.
