### ISSUE TITLE
Consistent usage of 'Cancel' text & 'Cancel' icon

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1161]
- [ ] Cancel icon should appear on all bottom controllers: 
- graph view
- create key 
- delete key
- transaction info
- receive

- [ ] Cancel text should appear on all full screen presenters
- send controller
- full transaction info

**Comment by esengulov** [comment]
@TalgatNurdinov need design guidelines

**Comment by Dianaaiym** [comment]
Cancel icon not appear on graph view controller

**Comment by TalgatNurdinov** [comment]
<img width="510" alt="Screen Shot 2019-08-27 at 11 43 56 AM" src="https://user-images.githubusercontent.com/42367908/63744040-f9658700-c8bf-11e9-95cb-7935a7740a1d.png">
https://zpl.io/V4OdNW0
https://zpl.io/VQQ1Oj9
