### ISSUE TITLE
TX info : Outgoing Transactions should display fee

### ISSUE THREAD

**Issue by horsys** [horizontalsystems/unstoppable-wallet-android#1174]
- [ ] Outgoing transactions should display fee in tx info controller.
- [ ] The fee should be shown in the coin that was used for the fee. in other words the ERC20 tokens will have fee shown in ETH.

outgoing transactions to your own address:

- [ ] should have asterisk icon after the amount (ex: 0.00*)
- [ ] there should be an extra field/cell at the bottom of controller (refer to iOS) that would show:

> * The value of this transaction appears as 0 because it was sent to your own address

- [ ] @Dianaaiym the text above should be localized

[Add field "fee" in TransactionInfo](https://github.com/horizontalsystems/bitcoin-kit-android/issues/408)

**Comment by omurovch** [comment]
Need to add field "fee" in TransactionInfo class in BitcoinKit. Related issue https://github.com/horizontalsystems/bitcoin-kit-android/issues/408
