### ISSUE TITLE
Bottom controller should standout from bg on dark/light modes

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1245]
- receive controller
- all alert-style bottom controllers (ex: manage keys >> add/delete etc) 

@TalgatNurdinov provide the layout/specs for background

**Comment by TalgatNurdinov** [comment]
Make 2 layer dimming backgrounds.
First layer - Black 50
Second layer - Grey 50

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=1406%3A237

**Comment by abdrasulov** [comment]
Need to apply to all other bottom sheets (chart, create wallet alerts, etc.)

**Comment by TalgatNurdinov** [comment]
wrong right paddings on chart, delete, create bottom sheets. Only Delete Wallet checkmarks forms have 24px paddings, others 16px
