### ISSUE TITLE
Minor Changes to Titles all bottom controllers

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1249]
- [ ] apply subtitle to Receive controller
- [ ] apply subtitle to Price_chart controller
- [ ] display address in full 

@TalgatNurdinov 
- [ ] please attach the layouts
- [ ] other changes for receive controller

@Dianaaiym  
- [ ] make sure that newly added texts are localized

**Comment by TalgatNurdinov** [comment]
* Transaction Info: "Time" cell moved to header
* Rate: Last update of data

<img width="766" alt="Screen Shot 2019-09-05 at 4 23 42 PM" src="https://user-images.githubusercontent.com/42367908/64334039-9085b980-cff9-11e9-8951-2ab5a5be71e4.png">
<img width="757" alt="Screen Shot 2019-09-05 at 4 23 50 PM" src="https://user-images.githubusercontent.com/42367908/64334046-967b9a80-cff9-11e9-8a94-1639955f1d1d.png">


https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=1406%3A237

**Comment by Dianaaiym** [comment]
Need to apply to delete key
