### ISSUE TITLE
Layout Changes for Welcome >> Restore

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1254]
**Welcome >> Restore page** 

- [x] apply new design for the wallet Welcome >> Restore process
-- add additional info to Restore Options screen for Unstoppable. Additional options would allow user to choose the period when unstoppable was created (Before Oct. 2019, After Oct. 2019). 
-- all cell titles should be in the following format "[wallet_name] wallet" i.e. Unstoppable Wallet
-- allow "[wallet_name] Wallet" cells to be bigger in height in case when the coin list spans more than a single line. Potentially coins can span more than one line.

**Settings >> Manage Keys page**

- [x] slightly modify the layout for Manage Keys
-- rename title of 'Manage Keys' to 'Manage Wallets'. 
-- add additional info to Restore Options screen for Unstoppable. Additional options would allow user to choose the period when unstoppable was created (Before Oct. 2019, After Oct. 2019). . The screen would appear after the input screen for 12 words. Same behavior on Welcome >> Restore >> Unstoppable
-- all cell titles should be in the following format "[wallet_name] Wallet" i.e. Unstoppable Wallet. 
-- allow "[wallet_name] Wallet" cells to be bigger in height in case when the coin list spans more than a single line. Potentially coins can span more than one line.

@TalgatNurdinov

- [ ] provide the layout for Welcome >> Restore screen. It should have titles i.e. Unstoppable Wallet.
- [ ] provide the layout for Manage Keys screen. It should have titles i.e. Unstoppable Wallet.
- [ ] layout for the new restore Options that would appear Restore >> Unstoppable >> 12 words >> [restore_options]. Same controller would open from Settings >> Manage Wallets >> Unstoppable >> 12 words >> restore button
- [ ] layout for cell view that displays a lot of supported coins spanning more than a single line

@Dianaaiym 

- [ ] find all references to 'Manage Keys' in localized strings and change it to 'Manage Wallets'. There were a number of alerts where we showed a text instructing user to go to 'Manage Keys' section.
- Settings >> Manage Keys changed to Settings >> Manage Wallets. The title of the resulting controller should be "Wallets" (make sure that coin manager controller doesn't have such title in other locales)
- [ ] text string for the main restore controller should remain as is
- [ ] localize additional text strings that were added to 'restore options' screen.  Unstoppable >> 12 words >> Restore_Options
- [ ] new text strings that need to be added to restore options 
-- text above the selection menu ("Select the time period when you first created the wallet in Unstoppable app")
-- option 1, text (Before Oct, 2019)
-- option 2, text (After Oct, 2019)

**Comment by TalgatNurdinov** [comment]
<img width="760" alt="Screen Shot 2019-09-11 at 5 03 56 PM" src="https://user-images.githubusercontent.com/42367908/64692138-303dbe80-d4b6-11e9-98a2-c1fedef4e70a.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=2938%3A5872

**Comment by horsys** [comment]
> <img alt="Screen Shot 2019-09-11 at 5 03 56 PM" width="760" src="https://user-images.githubusercontent.com/42367908/64692138-303dbe80-d4b6-11e9-98a2-c1fedef4e70a.png">
> 
> https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=2938%3A5872

The bottom controller will not work (as per our meeting discussion). I edited the issue and proposed to have a full screen instead. After the user enters the words he would be asked to choose the period.

**Comment by tmedetbekov** [comment]
Ref #1350
