### ISSUE TITLE
Unstoppable Derivation Paths : Full BIP44 / BIP49 compliance

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1255]
- [x] Unstoppable wallet should be able to operate either in BIP44 or BIP49 manner.  It should be possible to migrate your Unstoppable wallet to external BIP44 or BIP49 compliant wallet without issues and vice versa.
- [x] existing users should be able to update from version 0.8 to 0.9 and continue using wallet in BIP 44 complaint manner.
- [ ] new users setting up the wallet for the first time will use the wallet in BIP49 compliant manner.
- [x] hd-wallet-kit-android: [Ability to create HDWallet with 49' and 84' purpose in derivation path](https://github.com/horizontalsystems/hd-wallet-kit-android/issues/3)
- [x] bitcoin-kit-android: [Segwit mode which uses BIP49 paths (or BIP84 paths as appropriate)](https://github.com/horizontalsystems/bitcoin-kit-android/issues/403)

- [ ] Change text restore option
-- Before November 2019
-- After November 2019

**Comment by tmedetbekov** [comment]
#1350

**Comment by esengulov** [comment]
@tmedetbekov in version 0.9 new wallets are created in BIP44 manner while it should be BIP49
