### ISSUE TITLE
Refactor headers and titles

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1259]
The current layout keeps the titles/headers fixed sized and while this looks nice on larger screens for smaller not so good. as an example refer to Settings tab.

@TalgatNurdinov provide screenshots and guidance on how it should behave on scroll.

**Comment by TalgatNurdinov** [comment]
duplicate
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1312#issue-490267031
