### ISSUE TITLE
ETH is not correctly showing

### ISSUE THREAD

**Issue by coderzstas** [horizontalsystems/unstoppable-wallet-android#1278]
http://imgsafe.org/image/93f49bcb81
http://imgsafe.org/image/93f48426b3
http://imgsafe.org/image/93f49bcb81

**Comment by coderzstas** [comment]
Status is always pending . also balance is not showing correctly

**Comment by esengulov** [comment]
> http://imgsafe.org/image/93f49bcb81
> http://imgsafe.org/image/93f48426b3
> http://imgsafe.org/image/93f49bcb81

thanks, we will debug it on Monday. Does it happen consistently or sporadically? 
@rafaelekol refer to tx id from screenshot http://imgsafe.org/image/93f48426b3

**Comment by rafaelekol** [comment]
What build variant you are building? Is it devMainnetRelease, devTestnetRealse, detTestnetDebug, etc?

**Comment by coderzstas** [comment]
Devmainnetrelease

**Comment by coderzstas** [comment]
merged all fixes today and rebuilded , Ethereum still showing wrong balance , see first image

**Comment by rafaelekol** [comment]
In gardle file there are lines

```
buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            resValue "string", "infuraProjectId", "2a1306f1d12f4c109a4d4fb9be46b02e"
            resValue "string", "infuraSecretKey", "fc479a9290b64a84a15fa6544a130218"
            resValue "string", "etherscanKey", "GKNHXT22ED7PRVCKZATFZQD1YI7FK9AAYE"
            resValue "string", "is_release", "false"
        }
        release {
            debuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            resValue "string", "infuraProjectId", ""
            resValue "string", "infuraSecretKey", ""
            resValue "string", "etherscanKey", ""
            resValue "string", "is_release", "true"
        }
    }
```

When you are building `release` builds you should put your own keys for 
`infuraProjectId` 
`infuraSecretKey`
`etherscanKey`
Since they are empty, Ethereum and ERC20 tokens can't sync.

**Comment by coderzstas** [comment]
Big thanks :) fixed )

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @rafaelekol)
