### ISSUE TITLE
Balance tab: minor changes

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1298]
States of chart overview 
- No rate (before downloading data)
- Current Rate 
- Error ( data error )

**Comment by esengulov** [comment]
![IMG_D4E9BCCA05E1-1](https://user-images.githubusercontent.com/8611762/64168749-fb09ee80-ce6d-11e9-84ee-37097489cfc0.jpeg)

**Comment by TalgatNurdinov** [comment]
<img width="685" alt="Screen Shot 2019-09-09 at 10 23 33 AM" src="https://user-images.githubusercontent.com/42367908/64503262-0042bf80-d2ec-11e9-91a8-2bc914a795bd.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=1458%3A440
