### ISSUE TITLE
BTC.com block explorer shows as offline when accessed via Bitcoin TX Info >> Verify

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1343]
It works as expected for BCH transactions but shows as offline for BTC transactions

**Comment by esengulov** [comment]
seems like it's an API issue. Will keep an eye on this for a few weeks and if the problem not fixed on their end then we'll remove it from transaction verification sources

**Comment by Dianaaiym** [comment]
all works for BTC and BCH
