### ISSUE TITLE
Settings >> Report >> App Status

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1374]
- [ ] Settings >> Report :  add "App Status" standalone cell above the existing two entires at the top (email/telegram). @Dianaaiym, localizable element

- [ ] Settings >> Report :  display following text above the "App Status" cell. Having problems with the app? Let us know below. To speed things up please send us some generic data about your app that you can copy from App Status section below. @Dianaaiym, localizable element

- [ ] App Status screen should display following data on the screen. The elements on the App Status page are not going to be localizeable.

App Status:

- time: timestamp
- version: x.y.z
- device: Samsung A1
- Android OS: x.y.z
- installed: Jan 2nd, 2019
- installed version: x.y.z
- update 1: version x.y.z
- update 2:  version x.y.z
... 

Blockchain Status:

- Bitcoin
-- synced until Jul 2nd, 2019
-- wallet type: BIP44 / BIP49
-- restored: true/false
-- peer 1 status:
-- peer 2 status:
-- ...

- Bitcoin Cash
-- synced until Jul 2nd, 2019
-- restored: true/false
-- peer 1 status:
-- peer 2 status:
--  ...

- Dash
-- disabled

- Ethereum
-- synced until Jul 2nd, 2019
-- restored: true/false
-- RPC host: infura
-- Transactions history: ....

- EOS
-- synced until Jul 2nd, 2019
-- restored: true/false
-- RPC host: infura

- Binance DEX
-- synced until Jul 2nd, 2019
-- restored: true/false
-- RPC host:

**Comment by TalgatNurdinov** [comment]
<img width="785" alt="Screen Shot 2019-10-03 at 4 33 42 PM" src="https://user-images.githubusercontent.com/42367908/66119962-97edb200-e5fb-11e9-8831-8504063715e2.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3467%3A658
