### ISSUE TITLE
Settings >> Manage Wallets : minor changes

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1375]
- [x] Settings >> Manage:  Rename '12-words' to 'Unstoppable'
- [x] Settings >> Manage Wallets >> Backup >> Intro >> Key: change the page title to 'Private Key'. same title for all keys
- [x] Settings >> Manage Wallets list should titles in the following format
-- [account_type_unstoppable] wallet
-- [account_type_binance] wallet
-- [account_type_eos] wallet
-- the text wallet ihe wallet names will be localizable

@Dianaaiym 

- [x] Settings >> Manage Wallets >> Create : slightly change top section of the text to
> This action will generate a new wallet for the following coins: ....
- [x] Settings >> Manage Wallets >> Delete (pre backup): 
> You need to backup the private key for this wallet before it can be deleted from this phone.
- [x] Settings >> Manage Wallets >> Delete (after backup): 
-- checkmark 1: The action will delete the [wallet_name] wallet from this device.
-- checkmark 2: _no changes_
-- checkmark 3: If you didn't backup the private for this wallet, you will loose access to your funds.

**Comment by Dianaaiym** [comment]
1) Backup Intro: title "Backup" for all cases
2) Key page: title "Private Key" for all cases
