### ISSUE TITLE
Active pending indicator for PENDING transactions

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1378]
At the moment we display static pending icon on pending transactions. The purpose of this issues  is to change static icon to an animated one .

**Comment by TalgatNurdinov** [comment]
<img width="360" alt="Screen Shot 2019-10-23 at 2 03 58 PM" src="https://user-images.githubusercontent.com/42367908/67371294-017b3380-f59e-11e9-8377-c38523f126f7.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3713%3A1612

**Comment by TalgatNurdinov** [comment]
https://figmotion-renderer.freighter.studio/videos/3792:666:dbc45116-5b46-45eb-8a67-3ffa80086700-fdcb901f-3fac-4619-ab1d-e02c22f1ca66.gif

**Comment by esengulov** [comment]
@rafaelekol added two minor points, check the first comment
