### ISSUE TITLE
UI Improvements for Notifications manager

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1403]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=2975%3A68

**Comment by TalgatNurdinov** [comment]
If description text position under cells that  top padding should be 8dp

**Comment by TalgatNurdinov** [comment]
Reset all cells height is wrong. It should be same as single line cell
