### ISSUE TITLE
Minor layout change for Restore Options screen

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1404]
Welcome >> Restore >> Restore From >> Restore Options

We have a minor problem on the screen where two blocks (BIP selection, sync mode speed) are positioned too close to each other. As a result it's not clear that the text below the BIP selector belong to the above selection menu. We need to increase the margins in a. couple of places so that it's clear to which section the text belongs to.

**Comment by TalgatNurdinov** [comment]
Add new paddings set for footer description (top-8 / r-l 24 / bottom 48)

<img width="366" alt="Screen Shot 2019-10-03 at 4 00 30 PM" src="https://user-images.githubusercontent.com/42367908/66117820-fa907f00-e5f6-11e9-85e7-c19cf65701cd.png">
