### ISSUE TITLE
UI Improvements for Prices on Lock Screen

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1412]
- [x] prices 
-- do not show cent values for prices below 1000. values should be rounded
- [x] swap font sizes and placements for % price change and price amount
- [x]  instead of +/- symbols use up/down arrows (will be provided)

**Comment by TalgatNurdinov** [comment]
<img width="365" alt="Screen Shot 2019-10-03 at 3 49 46 PM" src="https://user-images.githubusercontent.com/42367908/66116962-712c7d00-e5f5-11e9-8ab7-08ef64fe2fe3.png">


https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=1633%3A92

**Comment by TalgatNurdinov** [comment]
- wrong color of price font
- bottom cell divider should be steel20
- Instead black50 divider on bottom cells use steel20
