### ISSUE TITLE
ERC20 tokens: Get gas price / limit values from the Infura (or equivalent alternative)

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1418]
Recently we increased gas limit for specific ERC20 token, called DGX. The reason for what was an "out of gas" error . It worked OK for one of the transaction but failed for another... It looks like the 150,000 limit may not be enough... https://etherscan.io/tx/0x4248a77e28acb484657783e659541d18db57a535c9619a977c2b985f583b490b

At the same time the transaction fee shown for ETH/ERC20 transfers is an estimate value.

**To Do:**

- [x] The client needs to calculate and show the exact fee by requesting gas limit as well as the gas price from the RPC-enabled client like infura.io.

- [x] @TalgatNurdinov provide the details in regards to how it will look in the UI. This applies to all coins that leave on blockchain where there are transaction fees (Bitcoin, Ethereum). Take into account that fee values and total available balance can be shown only after the client gets response from the fee rate provider. The response will be sent to provider upon controller open and until the response arrives it's impossible to display:
-- the available balance
-- the fee/duration
-- Send button (will remain disabled)

**Comment by TalgatNurdinov** [comment]
<img width="358" alt="Screen Shot 2019-11-15 at 2 45 33 PM" src="https://user-images.githubusercontent.com/42367908/68929500-b0ceb300-07b6-11ea-8f36-7587e0c62edd.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=4095%3A5511
