### ISSUE TITLE
Onscreen fingerprint

### ISSUE THREAD

**Issue by coderzstas** [horizontalsystems/unstoppable-wallet-android#1431]
If i turning on pin lock and fingerprint unlock - fingerprint icon on number 0 , need some layout edits.

**Comment by rafaelekol** [comment]
Can show screenshot of this issue. I can't reproduce it.

**Comment by coderzstas** [comment]
> Can you show screenshot of this issue. I couldn't reproduce it.

sure https://imgur.com/a/tiJsQ8X

**Comment by rafaelekol** [comment]
In our case fingerprint scanner shows as popup dialog. On screenshot I guess I see on screen fingerprint scanner.
How does it work? Can you cancel it, to use number pad for pin?

**Comment by coderzstas** [comment]
> In our case fingerprint scanner shows as popup dialog. On screenshot I guess I see on screen fingerprint scanner.
> How does it work? Can you cancel it, to use number pad for pin?

Strange .. nope i can't (( device oneplus 6t with stock oxygenos

**Comment by coderzstas** [comment]
> In our case fingerprint scanner shows as popup dialog. On screenshot I guess I see on screen fingerprint scanner.
> How does it work? Can you cancel it, to use number pad for pin?

1 intresting thing . This bug only on OxygenOS , on lineageos shows as popup dialog. Magic :)

**Comment by rafaelekol** [comment]
We have suspicion that other phones with screen fingerprint scanner, may also have similar issues. Thats why we want to change layout for fingerprinting.

**Comment by esengulov** [comment]
@coderzstas we have fixed the issue here, https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1441

Could you check if the problems persists after the next release (sometime next week) and close the issue if all good ;)

**Comment by coderzstas** [comment]
> @coderzstas we have fixed the issue here, #1441
> 
> Could you check if the problems persists after the next release (sometime next week) and close the issue if all good ;)

Tested , all fine now , thanks alot
