### ISSUE TITLE
Wallet Restore >> Input Form

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1475]
At the moment the form allows multiple space and invalid characters. Those should be handled properly when converting mnemonic to the key

Some of the issues at the moment which increase the likelihood of the incorrect key error even when words are correct

- double/extra space allowed
- handle capital letters as small

**Comment by rafaelekol** [comment]
User should not be restricted by allowed characters.

**Comment by Dianaaiym** [comment]
Should be no difference between capital and small letters

**Comment by esengulov** [comment]
@rafaelekol tried restoring Binance DEX account by entering some of the mnemonic words in capital. The restored account was incorrect.

**Comment by rafaelekol** [comment]
@esengulov Can't reproduce the bug
