### ISSUE TITLE
Add total supply for each supported coin

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1485]
- [x] remove decimal values from the  "in Circulation"
- [x] on coin chart controller: add "Max. Supply" cell under the "in Circulation"
- [x] the max. supply values for supported tokens are listed below. For tokens where max. supply not provided display "n/a".

Bitcoin - 21,000,000 BTC
 Bitcoin Cash - 21,000,000 BCH
Dash - 18,900,000 DASH
Ox - 1,000,000,000 ZRX
Aelf - 880,000,000 ELF
Ankr Network  - 10,000,000,000 ANKR
 Crypto.com Chain - 100,000,000,000 CRO
 Gifto - 1,000,000,000 GTO
Golem - 1,000,000,000 GNT
Basic Attention Token - 1,500,000,000 BAT
Huobi Token - 500,000,000 HT
Digix DAO - 2,000,000 DGD
Enjin Coin - 1,000,000,000 ENJ
Cashaa - 1,000,000,000 CAS
ChainLink - 1,000,000,000 LINK
Maker - 1,000,000 MKR
Loom - 1,000,000,000 LOOM
Paytomat - 3,600,000,000 PTI
Polymath - 1,000,000,000 POLY
Walton - 70,000,000 WTC
MEET.ONE - 10,000,000,000 MEETONE
Mithril - 1,000,000,000 MITH
Orbs - 10,000,000,000 ORBS
Nexo - 1,000,000,000 NEXO 
Zilliqa - 21000000000
Prospectors Gold - 220,000,000 PGL
Holo - 177,619,433,541 HOT
Decentraland - 2,644,403,343 MANA
Status - 6,804,870,174 SNT
Pundi X - 259,810,708,833 NPXS
Bancor - 67,721,371 BNT
Everpedia - 10,006,128,771 IQ
Newdex - 10,000,000,000
EOS - 1,035,000,004 EOS
Binance Chain DEX - 187,536,713 BNB 
Binance Token (BNB-ERC20) - 187,536,713 BNB
Kucoin Shares (KCS) - 176,863,551 KCS
Aurora DAO (AURA) - 1,000,000,000 AURA 
IDEX Token (IDEX) - 1,000,000,000 IDEX

**Not Available:**

Reputation (Augur) (REP) | n/a
Native Utility Token (NUT) | n/a
Ethereum -  | n/a
Loopring - n/a
Kyber Network (KNC) - n/a
Tether USD (USDT) - n/a
TrueUSD(TUSD) - n/a 
STASIS EURS (EURS) - n/a 
Gemini Dollar (GUSD) - n/a
 Paxos Standart(PAX) - n/a
Dai (DAI) - n/a
 EOSDT (EOSDT) - n/a 
USD Coin(USDC) - n/a
Digix Gold (DGX) - n/a 
Bitcoin BEP2 (BTCB) - n/a
Kyber Network - n/a
Ripple (BEP2)
OmiseGO(OMG)
Wax Token(WAX)
Paxos Gold (BEP2)
Binance USD (BEP2)
IDEX Memebership (IDXM) 
Crypterium (CRPT)

**Comment by tgc12** [comment]
This is only thing I'm missing, nice work.

**Comment by esengulov** [comment]
@rafaelekol add total supply for Populous. We somehow missed in the original list.

53,252,246 PPT
