### ISSUE TITLE
Huawei allows user to switch to the custom keyboard 

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#1498]
at the moment Huawei allow to use 3rd party keyboard (Swiftkey)
reproduce on Huawei P8 Lite

**Comment by rafaelekol** [comment]
I tried to debug it, but no success.

**Comment by rafaelekol** [comment]
With available tools I can't detect 3rd party keyboard on Huawei phone. I think it's a bug with Huawei software.

**Comment by rafaelekol** [comment]
After research and testing another Huawei phone, I found out that SwiftKey is actually a system keyboard for Huawei phones and  its preinstalled on some Huawei phones. I tried to install other keyboard, and Warning was displayed in Restore page.
