### ISSUE TITLE
a Question about the address of transaction fees receiver

### ISSUE THREAD

**Issue by Gmlogy** [horizontalsystems/unstoppable-wallet-android#1509]
where can i find the settings for transactions fees? for example if i want change the receiver of transaction fees 
thanks

**Comment by esengulov** [comment]
> where can i find the settings for transactions fees? for example if i want change the receiver of transaction fees
> thanks

Hi @Gmlogy 

Not really sure what you mean by "settings for transactions fees..." but I am assuming you're referring to an option of being able to change the receive address that are usually available in mining enabled desktop wallets. Note that such option is usually relevant only to wallets that remain online 24/7 and used for mining (i.e. Bitcoin Core wallet). It's not really applicable to mobile wallets as those are only online when the app is being used.

**Comment by Gmlogy** [comment]
@esengulov 
thank you this is exactly what i want to know

**Comment by esengulov** [comment]
> @esengulov
> thank you this is exactly what i want to know

good to hear. Let us know in case you have some other questions. 

closing the issue!
