### ISSUE TITLE
Add New Binance Tokens to the Wallet

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1512]
**Paxos Gold**

- name: Paxos Gold (erc20)
- symbol: PAXG
- ERC20: https://etherscan.io/token/0x45804880De22913dAFE09f4980848ECE6EcbAf78
- ex rates: https://www.cryptocompare.com/coins/paxg/overview
- icon: @TalgatNurdinov 

**Ripple**

- name: Ripple (BEP2)
- symbol: XRP-BF2
- ex rates: https://www.cryptocompare.com/coins/xrp/overview
- icon: @TalgatNurdinov 

**Binance USD**

- name: Binance USD (BEP2)
- symbol: BUSD
- ex rates: https://www.cryptocompare.com/coins/busd/overview
- icon: @TalgatNurdinov

**Comment by TalgatNurdinov** [comment]
added new icon for BUSD. Others use the same icons

**Comment by Dianaaiym** [comment]
not available exchange rate for Ripple BEP2

**Comment by Dianaaiym** [comment]
can not send BUSD (Binance USD)

**Comment by rafaelekol** [comment]
I can't reproduce "BUSD not sending issue". I can send it without a problem.
