### ISSUE TITLE
Bitcoin / Blockchain Sync Bug on Restore

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1537]
It has been observed (by @esengulov @ealymbaev) that in some cases when restoring the wallet the Bitcoin fails from start (shows red "alert" icon). 

- [ ] The issue is likely due to unavailability (at that particular moment) of the FAST RESTORE API for Bitcoin. Moving forward we need to be able to identify the issue from within the client and for that we need display that information on the APP STATUS section. 
- [ ] "App Status" should display "Restore API Source" for each each blockchain where it's available (i.e. Bitcoin, Bitcoin Cash etc).
- [ ] pull to refresh should retry sync in such cases

**Comment by tmedetbekov** [comment]
This was only IOS bug and can't reproduce on android.
