### ISSUE TITLE
Charts: exchange rate, price change % values not update on app open from background

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#1539]
The coin exchange rate, price change % value and price graph coordinate don't update when app opens from background. In order to force the update the user need  pull to refresh on balance tab. 

As a result the user may see old exchange rate, price change value, update time on chart.

**Comment by tmedetbekov** [comment]
Currently we have 10 minute expiration interval for latest rates, within this time interval app will not sync rates and that's why it seems like not updating. But opening app from background after 10mins automatically updates chart data and market info.
