### ISSUE TITLE
Balance Tab : minor design improvement

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1575]
both in collapsed/expanded coin cell: append coin type next to coin symbol

-- if token is on Ethereum  >> coin symbol (ERC20)
-- if token is on EOS >> coin symbol (EOS)
-- if token is on Binance DEX >> coin symbol (BEP2)

@TalgatNurdinov attach the designs

**Comment by TalgatNurdinov** [comment]
<img width="359" alt="Screen Shot 2019-11-15 at 3 15 44 PM" src="https://user-images.githubusercontent.com/42367908/68931526-ebd2e580-07ba-11ea-86d9-bf748adb8b05.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3553%3A289

**Comment by esengulov** [comment]
The issue is already implemented and no longer relevant

**Comment by TalgatNurdinov** [comment]
missing background on badges 
<img width="703" alt="Screen Shot 2019-11-22 at 10 58 09 AM" src="https://user-images.githubusercontent.com/42367908/69399090-01925e80-0d17-11ea-9c95-4d17cd401199.png">
