### ISSUE TITLE
Change Layout on Wallet Create/ restore pages

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1592]
**Welcome >> Create New Wallet**

- [x] 'New Wallet' screen: list all tokens and allow multiple coin selection. 
- [x]  Add following text below the title.
> Select cryptocurrencies for the wallet. You will be able to add or remove coins later as well.
- [x] no coins should be selected by default. The coin list should be shown in alphabetical order, with the top section listing the primary tokens (BTC, BCH, DASH, ETH, Binance DEX, EOS)
- [x] display "blockchain" label next to tokens, like it's on balance tab.
-- ERC20 for Ethereum tokens
-- BEP2 for Binance tokens
-- EOSIO for EOS tokens
- [x] selected coins should appear on balance tab upon completion
- [x] if user tries to activate an EOS or any EOS based token show an error which tells that create not possible for EOS at this time.
- [x] if user selects BTC then show screen with address setting for the Bitcoin blockchain. 
-- page title: Bitcoin
-- that page should have one section: 'Address Format' should list BIP44/BIP49/BIP84. 
-- text to display below the  'Address Format' section
- [x] The BIP49 format should be preselected.
>
> If you're creating a new wallet and not sure about this setting than select BIP49.
>
> If you're restoring an existing wallet with bitcoins on it then you should select the correct address type.
- [x] if user tries to activate any other token apart from EOS and Bitcoin then emnable the coins without additional steps.

**Welcome >> Restore Wallet**

- [x] in the first screen that lists all wallet types, rename Unstoppable to Standard Wallet
- [x] next screen 'wallet_name' should list filtered list of coins depending on selection. 
--  screen title should be [wallet_name] wallet
-- If user selected EOS Wallet then only EOS and EOS based tokens should be shown, with a separator between EOS and other tokens.
-- If user selected Binance Wallet then only Binance DEX BNB and BEP2 tokens should be shown, with a separator between BNB and other tokens.
-- If user selected Standard Wallet then BTC, BCH, DASH, ETH and ERC20 tokens should be shown, with a separator between BTC, BCH, DASH, ETH and ERC20 tokens.
-- at least one coin ON selection is required before user may proceed to the next step.

- [x] when user restoring Standard Wallet >> BTC, BCH or DASH then show them screen with settings for the selected blockchain. 
-- page title: coin name (ex: Bitcoin, Bitcoin Cash or DASH)
-- (for Bitcoin) that page should have two sections: First section header 'Address Format' should list BIP44/BIP49/BIP84. Second section header 'Network Synchronization' for choosing initial sync mode for the blockchain. 
-- keep BIP 49 and FAST mode preselected.
-- (for BCH / DASH) that page should have just one section 'Network Synchronization' for choosing initial sync mode for the blockchain. 
-- Keep FAST mode preselected.
- [x] text to display below the  'Address Format' section
> If you're creating a new wallet and not sure about this setting than select BIP49.
>
> If you're restoring an existing wallet with bitcoins on it then you should select the correct address type.
- [x]  text to display below the 'Network Synchronization' section
> Fast: Restores [coin_name] transaction history via secure third party server. Less private but fast.
>
> Slow:  Restores [coin_name] transaction history directly from the blockchain. More private but slow.

**Settings >> Manage Wallets**

- [x] 'wallet_type >> create' : title should be ''New Wallet"
- [x] 'wallet_type >>  restore' : title should be ''wallet_type" wallet.
- [x] for 'wallet_type >> create' screen the text on top right button should be 'Create'
- [x] for 'wallet_type >>  restore' screen the text on top right button should be 'Next', not proceed
- [x] change 'below the title' text on the main screen
> Highlighted below are your active wallets where each wallet controls a set of cryptocurrencies.
>
> You must backup each highlighted wallet by backing up the private key for it. This key is the only way to restore and access your funds if your phone is ever lost, stolen or the app malfunctions.

**Coin Manager**

- [x] page title : Coin Manager
- [x] should display labels on all coins
- [x] when coin doesn't have an active key associated with it show the arrow ">" instead of there ON/OFF selector. Clicking on it would trigger create/restore bottom controller for the respective key.
- [x] apply text changes bottom controller which shown on activation of the coin that doesn't have an active key:
-- subtitle: add 'wallet' text string next to the [wallet_name] (ex: EOS Wallet)
> You need to set up [wallet_name] wallet to be able to send or receive [coin_name].
>
> Use the Create button below to set up a new [wallet_name] wallet, or Restore button to import the existing one.
>
> You will be able to use this wallet for: [supported_coins_tokens].

 
**Other Relevant changes**

- [x] adjust text on the 'Lock Bitcoins' controller. The second paragraph should say:
>The receiver of such transaction should use Unstoppable wallet  app version 0.10 or newer with BIP44 address format for the Bitcoin.

**@TalgatNurdinov** 

- [x] reattach new screenshots taking into account newly updated description text

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=2902%3A7093

<img width="680" alt="Screen Shot 2019-11-18 at 5 27 28 PM" src="https://user-images.githubusercontent.com/42367908/69048863-b6cbca80-0a28-11ea-9a97-a80fd7f6aa1e.png">

**Comment by TalgatNurdinov** [comment]
updated
<img width="642" alt="Screen Shot 2019-11-19 at 1 57 12 PM" src="https://user-images.githubusercontent.com/42367908/69127484-82154d00-0ad4-11ea-99e4-b17bd7270df6.png">

**Comment by TalgatNurdinov** [comment]
**NEW**

<img width="1248" alt="Screen Shot 2019-11-22 at 5 26 51 PM" src="https://user-images.githubusercontent.com/42367908/69422268-78e2e500-0d4d-11ea-9521-67a543b4a46d.png">

**RESTORE**

<img width="852" alt="Screen Shot 2019-11-22 at 5 28 01 PM" src="https://user-images.githubusercontent.com/42367908/69422285-81d3b680-0d4d-11ea-8118-b0b943bd7149.png">

**COIN MANAGER**

<img width="366" alt="Screen Shot 2019-11-22 at 5 32 41 PM" src="https://user-images.githubusercontent.com/42367908/69422520-1b9b6380-0d4e-11ea-843f-2da4bc75be5d.png">

**Comment by esengulov** [comment]
@TalgatNurdinov token labels (ERC20, BEP2 etc) are missing

**Comment by esengulov** [comment]
- [ ] apply text changes bottom controller which shown on activation of the coin that doesn't have an active key. The subtitle should have following format '[wallet_name] wallet' (ex: EOS Wallet). Currently it's ''[coin_name] wallet"

- [ ] coin manager: each cell currently shows [coin_symbol] as title and [coin_name] as subtitle. it should be the other way around.

- [ ] welcome >> restore: under each wallet type where coin types are listed the "ERC-20 tokens", "EOS tokens" and "BEP-2 tokens" should be spelled as "ERC20 tokens", "EOSIO tokens" and "BEP2 tokens", respectively. All other appearances of the coin types (ex: on Manage Wallets screen) should use same version (ERC20, BEP2, EOSIO).

- [ ] the labels on coin manager (both on full and filtered versions) should be: "ERC20", "BEP2", "EOSIO" 
- [ ] Welcome >> New >> EOS wallet: the alert that appears on EOS activation, currently has 'Warning' as title.  Change title to “EOS Wallet”. The body of the description text to “At this point Unstoppable is not able to create new EOS wallets. You’re only able to restore the existing one.” 
- [ ] change styling and text on the settings screen for Bitcoin / Bitcoin Cash / Dash screens. For you reference attaching screenshots from iOS. The layout and text should be exactly like on the iOS for consistency.
-- for 'create' : Wellcome >> Create >> Standard >> BTC/BCH/DASH selection
-- for 'create' : Manage Wallets >> standard >> create >> BTC/BCH/DASH selection)
![IMG_0583](https://user-images.githubusercontent.com/8611762/70121413-b7a36400-1698-11ea-9a62-2192ba45b130.PNG)
-- for 'restore' : Wellcome >> Restore >> Standard >> BTC/BCH/DASH selection
-- for 'restore' : Wellcome >> Create >> Standard >> BTC/BCH/DASH selection
![IMG_0580](https://user-images.githubusercontent.com/8611762/70121385-a9edde80-1698-11ea-8483-2eaee352a2bb.PNG)

**Comment by Dianaaiym** [comment]
Change color for API link on coin ssettings
color: liah

**Comment by esengulov** [comment]
@rafaelekol @Dianaaiym one of the tasks listed in the issue is not addressed. See my comments with tasks for reference, https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1592#issuecomment-561523304

the very first entry "coin manager" is not addressed

**Comment by Dianaaiym** [comment]
Change text: 
CoinOption_SyncModeDescription = 'Select the source the Unstoppable should use to download your balance and transactions.
\n\nHorizontal Systems %2s API:\n%3s'
