### ISSUE TITLE
Timelocked transactions fixes

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1607]
Timelocked transactions to yourself:

- [x] When user sends a regular transaction to self, the amount in transactions tab (and tx info) is currently shown as 0. Should be real value.

- [x] When user sends a locked transaction to self, the amount in transactions tab (and tx info) is currently shown as 0. Should be real value.

- [x] on tx info for **all** timelocked transaction, display the locked date with hours. At the moment it just shows the date, month, year. Ex: Dec 19, 2019, 3 PM

**Comment by esengulov** [comment]
@tmedetbekov in TX info change text string from 'Timelock' to 'Locked until'

**Comment by esengulov** [comment]
@TalgatNurdinov upon testing this we decided to change some more things. Please review the list below and make changes where relevant.

Transactions to yourself:

- [ ] When user sends a regular transaction to himself the amount in transactions tab (and tx info) should appear 0.
-- the message on tx info: The value of this transaction appears as 0 because it was sent to your own address

- [ ] When user sends a locked transaction to himself, transactions tab (and tx info) should appear as is (not 0)
-- the message on tx info:  This transaction was sent to your own address.

- [ ] In both cases transactions should appear as outgoing payment.

- [ ] on tx info for **all** timelocked transaction, display the locked date with hours. At the moment it just shows the date, month, year. Ex: Dec 19, 2019, 3 PM

**Comment by esengulov** [comment]
@tmedetbekov I have reassigned the issue to @omurovch

**Comment by TalgatNurdinov** [comment]
<img width="733" alt="Screen Shot 2019-12-05 at 11 07 16 PM" src="https://user-images.githubusercontent.com/42367908/70257174-042f9200-17b4-11ea-8ddd-b3521cc62ffd.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=4446%3A17389

ignore color changes
