### ISSUE TITLE
Add new token to the wallet

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#1622]
**DAI**

- name: Dai Stablecoin (erc20)
- symbol: DAI
- ERC20: https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f
- ex rates: not available
- icon: @TalgatNurdinov 
- Total Supply: not available

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=7%3A48

**Comment by esengulov** [comment]
@Dianaaiym when accepting this issue make sure to test following.

- [ ] previous DAI balance should appear under SAI. 
- [ ] test SAI token transfers*
-- between Unstoppable wallets
-- between Unstoppable and some other wallet
-- between Unstoppable and crypto exchanges 
- [ ] *keep in mind that most wallets/exchanges didn't change name from DAI to SAI. In other words when you transfer DAI (from the wallet that didn't update) to Unstoppable (receive address from SAI). The transfer should work.
- [ ] contract crypto compare about rates for DAI and SAI.
-- first they should be returning the rates for SAI
-- second, ask them about when the rates for DAI will be available
