### ISSUE TITLE
Custom language doesn't work for App context

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#1625]
When App is used for translations it ignores the custom language. It uses system language instead.

Need to fix it. Use the following lib https://github.com/zeugma-solutions/locale-helper-android. 

After fixing it check if custom language works on older devices. If so then enable switching language on them too.

**Result**

The solution doesn't fix the custom language on older devices issue. So older devices still don't support language switch.

**Test Scenario**

In balance tab, check if the phrase "Syncing..." is correctly translated.

**Comment by rafaelekol** [comment]
Googlers said that they already fixed this issue with context in AppCompat. We can wait when it will be available. [Issue link](https://issuetracker.google.com/issues/141861586)

**Comment by abdrasulov** [comment]
Fixed using the own customized version of LocaleHelper. It doesn't fix the issue for old devices.
