### ISSUE TITLE
Chart View Improvements

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#1634]
- [x] Extend the chart area to cover the whole width of the scree
- [x] Remove the numbers on the vertical axis
- [x] Display the max/low values on the graph itself

<img width="358" alt="Screen Shot 2019-11-25 at 6 24 20 PM" src="https://user-images.githubusercontent.com/42367908/69540451-d0cd5600-0fb0-11ea-8e45-cffc052265f6.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3878%3A694

**Comment by esengulov** [comment]
@tmedetbekov  more issues were discovered during testing:

- [ ] review high/low price rounding logic for cases when the diff between highest/lowers points is less than 5. When the diff is less than 5 we sendup with the values which are way to close to each other. To avoid this, keep adding decimal point until the diff exceeds 5. below you will find two screenshots that show the current look (currently observed on Android) vs desired look of the graph (implemented on iOS).

![IMG_0570](https://user-images.githubusercontent.com/8611762/70040543-ec0a1800-15e5-11ea-9461-4b46b585150a.PNG)

![IMG_3143](https://user-images.githubusercontent.com/8611762/70040582-fc21f780-15e5-11ea-8449-3b9876db7174.PNG)

- [ ] the price that's shown on chart tap and hold, can have up to 8 decimal points. It should be rounded only after 8'th decimal point.

![IMG_3143](https://user-images.githubusercontent.com/8611762/70040907-7a7e9980-15e6-11ea-9d5b-b24744e41d7e.PNG)

![IMG_9054](https://user-images.githubusercontent.com/8611762/70040908-7a7e9980-15e6-11ea-9c24-94fa1c528336.PNG)

**Comment by Dianaaiym** [comment]
need to test

**Comment by Dianaaiym** [comment]
Display max value over the line, min value under the line. 
on Android and iOS to looks as similar 

![IMG_0132](https://user-images.githubusercontent.com/22589457/70592658-c80d8e80-1c04-11ea-8a37-59dffcf9129d.PNG)
