### ISSUE TITLE
Following System DayNight mode.

### ISSUE THREAD

**Issue by coderzstas** [horizontalsystems/unstoppable-wallet-android#1661]
Its possible to add support for android darkmode (DayNight) ? I mean if system theme are light - app theme also will be light and vice versa. Thanks

**Comment by esengulov** [comment]
> Its possible to add support for android darkmode (DayNight) ? I mean if system theme are light - app theme also will be light and vice versa. Thanks

thanks, good idea! Will look into it

**Comment by coderzstas** [comment]
> > Its possible to add support for android darkmode (DayNight) ? I mean if system theme are light - app theme also will be light and vice versa. Thanks
> 
> thanks, good idea! Will look into it

Я как то делал это , на сколько я помню там чисто родительским стилем все делается . Могу ошибаться

**Comment by esengulov** [comment]
> > > Its possible to add support for android darkmode (DayNight) ? I mean if system theme are light - app theme also will be light and vice versa. Thanks
> > 
> > 
> > thanks, good idea! Will look into it
> 
> Я как то делал это , на сколько я помню там чисто родительским стилем все делается . Могу ошибаться

Спасибо! Разберемся)

**Comment by abdrasulov** [comment]
Duplicates #3453
