### ISSUE TITLE
TX Fees Rate : Allow user to set custom fee

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1695]
BTC / LTC
- uses HS Bitcoin node to obtain recommended values for the present 
- fallbacks to hardcoded values

BCH / DASH
- use hardcoded values

ETH
- uses Infura to obtain recommended values for the present 
- fallbacks to hardcoded values

**To Do**

- [x] allow user to set custom fee for Bitcoin

**Comment by esengulov** [comment]
being already implemented on iOS, refer to @ant013

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=7709%3A469

<img width="1526" alt="Screen Shot 2020-03-30 at 2 24 11 PM" src="https://user-images.githubusercontent.com/42367908/77891010-2339be80-7292-11ea-97d9-c217007e9d52.png">
