### ISSUE TITLE
Chart minor fixes

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#1713]
- [x] Add currency sign to high/low price in chart bottom sheet
- [x] Also don't hide chart when coin card is expanded

**Comment by TalgatNurdinov** [comment]
Wrong font used. it should be "Subhead 1"
also check the paddings. (top-8 / bottom-4) for High, (4/8) for low price

**Comment by Dianaaiym** [comment]
Wrong font style  for high/low price
