### ISSUE TITLE
All BTC block explorers show as offline when transaction hasn't reached the mempool

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#1731]
BTC block explorers show as offline when accessed via Bitcoin TX Info >> Verify, if transaction hasn't reached the mempool.  We need  to show  the full information

**Comment by omurovch** [comment]
@TalgatNurdinov @Dianaaiym please provide design for the case when the transaction cannot be found in block explorer

**Comment by TalgatNurdinov** [comment]
![Not Found TX](https://user-images.githubusercontent.com/42367908/70994704-fc97b380-20f8-11ea-88c2-23be694945c7.png)
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=4621%3A4360
