### ISSUE TITLE
Handle double spend transactions

### ISSUE THREAD

**Issue by omurovch** [horizontalsystems/unstoppable-wallet-android#1769]
Currently double spend transactions, received from mempool, are not handled properly. Need to:
- show all double spend transactions received from mempool
- make first received double spend transaction "more valid", meaning that it will be used for calculation of wallet balance 
- mark all conflicting transactions as "double spend" in GUI
- after one of the transactions "win" and is included in block, mark all other conflicting transactions as "failed"

**Comment by omurovch** [comment]
@esengulov @TalgatNurdinov please provide design for marking double spend transactions and grouping them accordingly

**Comment by TalgatNurdinov** [comment]
@omurovch 
- Need to remove attention icon from transactions list and from transaction info when it failed
- Text color should be Lucian
- Fix the bottom padding of failed text
