### ISSUE TITLE
randomizing the order of inputs and outputs (per BIP69 guidelines)

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1773]
details : https://github.com/bitcoin/bips/blob/master/bip-0069.mediawiki

Consult with Android team and ensure identical implementation across iOS/Android platforms

**Comment by rafaelekol** [comment]
Beside the list of BIP69 implementers that can be found here
https://github.com/bitcoin/bips/blob/master/bip-0069.mediawiki#Implementations

I found other wallets who solved sorting by just shuffling:
Bitcoin
https://github.com/bitcoin/bitcoin/pull/12699
Bread Wallet
https://github.com/breadwallet/breadwallet-core/commit/62f0d513c2b539ae1ed6478981056f844eece04a
Wasabi Wallet
https://github.com/zkSNACKs/WalletWasabi/blob/574d367821f4fb812d9238c241763197449cf8a8/WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs

Who use sorting by BIP69:
Samourai Wallet
https://github.com/Samourai-Wallet/ExtLibJ/commit/40efc3e50ee213adc82a858bb65886ddd9699914
