### ISSUE TITLE
Onboarding Improvements: Wallet Settings Redesign

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1782]
Prototype attached below. Or see on Figma, https://www.figma.com/proto/RDIKlTdIejA9cir83By3gS/Unstoppable-UX-Area?node-id=38%3A765&viewport=978%2C426%2C0.25&scaling=min-zoom

 - [x] Welcome >> New Wallet
-- when user creates wallet we never show him/her coin settings screen. the wallet should be set up with default values FAST SYNC (for all blockchains) and BIP49 (for bitcoin)

- [x] Coin Manager >> Bitcoin Activation / Deactivation
-- In case where existing wallet user has active Standard wallet and disables Bitcoin (via coin manager), the wallet should keep track of the disabled ADDRESS format. 
-- On reactivation, we should auto-set to the previous value. 
-- Changing this would only be possible from Settings >> Security >> Blockchain Settings

- [x] Welcome >> Restore Wallet
-- Change title to 'Choose Wallet'
-- remove the description text below the title
-- steps: welcome > restore > wallet type > enter key > blockchain settings (bip49 and fast preselected) > coin selector.

- [x] Settings >> Security Center
-- add Blockchain Settings
-- rename Wallet Settings >> Manage Wallets

- [x] Settings >> Security Center >> Manage Wallets
-- clicking on Unlink (in not backed up state) should show same alert controller that's shown on Coin >> Receive (in non backed up state)
-- apply new layout (see below)
-- restore steps (from manage wallets): wallet restore > enter key > blockchain settings  (bip49 and fast preselected) > coin selector.

![3](https://user-images.githubusercontent.com/8611762/72317556-df3c1200-36c3-11ea-9710-35b3f17c5312.jpg)

- [x] Settings >> Security Center >> Blockchain Settings
-- remove the text block below the address format selection as shown one attached prototype.
-- Bitcoin/Dash/Bitcoin_Cash sync parameters: display api link url instead of 'Horizontal Systems API' on all respective cells.
-- When user tries to change the address format for Bitcoin.  If bitcoin enabled then show  notification (text below) that the wallet will be re-synced.
>
> This action will require Unstoppable app to resync itself with Bitcoin blockchain. Your current Bitcoin transactions will no longer be visible. Changing it back to previous setting will bring everything back after the app resyncs with blockchain.
>
> Button 1 : Change to BIP 44 / 49 / 84 (depending on setting)
> Button 2: Cancel

-- When user tries to change the restore source. If any of three coins enabled (bitcoin, bitcoin cash or DASH) enabled then show notification (text below).
>
> This action will require Unstoppable app to resync itself with Bitcoin, Bitcoin Cash and Dash blockchains, if you have enabled any of these tokens. Your balance or transactions won't be affected. 
>
> We recommend not to change this setting if not sure what it does.
>
> Button 1 : Change Source
> Button 2: Cancel

- [x] apply a new left padding on all cells

**Comment by TalgatNurdinov** [comment]
for these components need to
add +8px padding

<img width="280" alt="Screen Shot 2020-01-21 at 6 32 36 PM" src="https://user-images.githubusercontent.com/42367908/72805149-69fcae00-3c7c-11ea-9083-ad45e7cb2d6b.png">

**Comment by Dianaaiym** [comment]
Incorrect color used for Button "DONE

![2020-02-05 11 30 19](https://user-images.githubusercontent.com/22589457/73813696-eb227c00-480a-11ea-8417-63895ded809b.jpg)

**Comment by Dianaaiym** [comment]
Settings >> Security Center >> Manage Wallets
-- clicking on Unlink (in not backed up state)  should show alert controller 
!! replace %s to Standart/Binance (depending on setting)
![2020-02-05 11 30 19](https://user-images.githubusercontent.com/22589457/73814038-13f74100-480c-11ea-92d2-b72c438cb3bc.jpg)
