### ISSUE TITLE
EOS block producer Greymass not reachable 

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#1790]

**Comment by nk-the-crazy** [comment]
Error was caused by too high value for parameter offset when requesting history.
Fixed problem by lowering value to 100 (from 1000).

**Comment by esengulov** [comment]
@nk-the-crazy tried restoring account. Got balance but no transactions.

**Comment by Dianaaiym** [comment]
transactions take a long time to load
