### ISSUE TITLE
Research TOR network capability for the wallet

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1805]
Research what can be done on the client side to mask user's public data such as IP address. 

ideally we want all network requests in the app to go through the TOR network.

Report in comments in details post research.

**Comment by nk-the-crazy** [comment]
1. BIP 150/151 should be implemented to achieve end2end encryption between nodes.
2. We should add support for TOR and SOCKS proxy to gain complete privacy.
(For Android we can use :
https://github.com/guardianproject/tor-android library)
