### ISSUE TITLE
Implement simple demo TOR application for Android Platform

### ISSUE THREAD

**Issue by nk-the-crazy** [horizontalsystems/unstoppable-wallet-android#1813]
- Choose Open-Source Android Platform compatible TOR library
- Integrate Bitcoin-Kit to work with TOR.

**Comment by esengulov** [comment]
@Dianaaiym let me review/accept that one. Want to play around with it

**Comment by nk-the-crazy** [comment]
Implemented a simple TOR application , that creates SOCKS/HTTP proxies.
Testing bitcoin-kit by changing Wi-FI proxy settings of the mobile device , didn't give expected result. Because changing Proxy for Device,  effects only Browsers. All other apps in a device continue using their own connection settings.
So, after some research, discovered that there are 2 possible solutions (at least from my research)
1. Implement custom Socket and HTTPClient connections and pass them as arguments to all Kits.
2. Create TOR over VPN.
--------------------
Ignored first solution as it seemed to bring heavy refactoring on all Kits (and possible architectural changes).
So, now decided to continue with the second solution.
