### ISSUE TITLE
tx info: display fiat value next to fee

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1819]

**Comment by TalgatNurdinov** [comment]
<img width="362" alt="Screen Shot 2020-01-21 at 5 00 39 PM" src="https://user-images.githubusercontent.com/42367908/72799509-978f2a80-3c6f-11ea-8d3f-6de404c30584.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=4446%3A17389
