### ISSUE TITLE
Display Info button on currencies with 0 balance

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#182]
- [ ] currencies with 0 balance should display info button
- [ ] click on the info button (https://zpl.io/aMvOZAz) should open  controller with all the info about the currency. That information would be downloaded from IPFS (similar to transactions controller)
- [ ] when user changes language setting in Settings: the info would be provided on selected language as well. In other words, when language setting changed the info shown for currency should be changed as well. refer to @nk-the-crazy about how to retrieve that info for each language
- [ ] @TalgatNurdinov provide design/layout for the info button as well as the controller that would open after the click on the button.

- [ ] The info for each coin is by default in English and stored on IPFS. Depending on the selected languages in the app Setting a translation of the coin info will be provided.

- [ ] By default we will provide the info on English. The translations for each coin will be gradually added later on. What we need at this step is a an automated decentralized workflow for keeping coin info translations.

**Comment by TalgatNurdinov** [comment]
@esengulov 
under development
<img width="1195" alt="screen shot 2018-12-04 at 11 30 45 am" src="https://user-images.githubusercontent.com/42367908/49421467-3f227280-f7ba-11e8-8863-e52ef9b8d4b6.png">

https://app.zeplin.io/project/5b18ecff68e34a92986b0224/dashboard?seid=5c06131da424142fbfda345d

**Comment by esengulov** [comment]
This issues was dropped from the list due to lack of team consensus on the importance/need of the described feature
