### ISSUE TITLE
coin charts : add trading volume indicator

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1820]
Display trading volume indicators on the chart view.

24 HOURS
https://min-api.cryptocompare.com/data/symbol/histohour?fsym=BTC&tsym=USD&limit=24

We use 48 price point for price chart. 
For volume, display one volume bar graph for the given hour. 
As a result for each two price points, there will be one volume bar. So, 24 bars in total.
The parameter to look for : top_tier_volume_total

7 DAYS https://min-api.cryptocompare.com/data/symbol/histohour?fsym=BTC&tsym=USD&limit=168

We display 56 price points for weekly chart. 
Combine three hourly volume points for each bar graph. 

1 month:
https://min-api.cryptocompare.com/data/symbol/histoday?fsym=BTC&tsym=USD&limit=30

We use 60 points for monthly chart. Display volume bars. Same logic as above.

 6 month:
https://min-api.cryptocompare.com/data/symbol/histoday?fsym=BTC&tsym=USD&limit=180

We use 60 points for monthly price chart. Display 60 volume bars.  Same logic as above.

1 year:
https://min-api.cryptocompare.com/data/symbol/histoday?fsym=BTC&tsym=USD&limit=360

**Comment by TalgatNurdinov** [comment]
<img width="361" alt="Screen Shot 2020-01-22 at 6 28 25 AM" src="https://user-images.githubusercontent.com/42367908/72855078-892d2700-3ce0-11ea-802a-4e3eec021a1d.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=1406%3A237

**Comment by TalgatNurdinov** [comment]
also change CryptoCompares color to grey50
