### ISSUE TITLE
Implement network routing (TOR) kit for Android

### ISSUE THREAD

**Issue by nk-the-crazy** [horizontalsystems/unstoppable-wallet-android#1823]
- Implement TOR support

**Comment by Dianaaiym** [comment]
change title on Welcome Screen -> "Unstoppable Wallet"

**Comment by Dianaaiym** [comment]
Welcome Screen: Enable TOR does not work

**Comment by rafaelekol** [comment]
That build is not debuggable. I enable debug in AppCenter builds. Let catch same issue in new builds.

**Comment by esengulov** [comment]
@Dianaaiym some things to pay attention to when testing TOR mode:

- network restore for main blockchains
- api restore for main blockchains
- fee service for BTC (may try a couple of other as well)
- transaction sending
- transaction receiving

**Comment by Dianaaiym** [comment]
when to enable tor:

- api restore (litecoin) doesn't work

**Comment by nk-the-crazy** [comment]
HTTPS should be configured for all API sources.
