### ISSUE TITLE
Improve deterministic builds

### ISSUE THREAD

**Issue by Giszmo** [horizontalsystems/unstoppable-wallet-android#1847]
I tried to verify your build on Google Play but failed due to probably very minor issues. You can find what I did [here](https://walletscrutiny.com/posts/io.horizontalsystems.bankwallet/). Please let me know when those issues are resolved.

**Comment by esengulov** [comment]
> I tried to verify your build on Google Play but failed due to probably very minor issues. You can find what I did [here](https://walletscrutiny.com/posts/io.horizontalsystems.bankwallet/). Please let me know when those issues are resolved.

Much appreciated! We will address the issues you pointed out shortly ;)

**Comment by omurovch** [comment]
@Giszmo Thanks for pointing out those issues! In fact, the differences are only because of versionCode. Three other differences exist because we don't include api credentials in the repository. According to your methodology is it still possible to become verifiable with api credentials not exposed?

**Comment by Giszmo** [comment]
@omurovch I'm in the process of establishing standards but tend to discourage such obfuscations. Any interested party trying to verify the build will see the api keys stick out like in the diff we got if you don't include them, so for verification I could take the api keys from that diff and build it once more and thus verify it but what's the point of not including the api keys in the first place if they are not hidable in the binary anyway? If verifiability matters to you, obfuscating the binary should not be an option.

In fact it's theoretically impossible to hide the api keys even if you obfuscated your binary and pulled the key from a company server. Any interested party can install the app on a rooted phone and observe the api calls.

**Comment by omurovch** [comment]
@Giszmo Yes, you're right. Obfuscation won't make the api keys totally hidden, it will just make the process of finding them harder. :)

Anyway, Unstoppable wallet is on the way to becoming fully decentralized and getting rid of any dependencies on external apis. And since verifiability matters to us, we decided to include the api keys in the repository.

We have updated master branch and recreated tag 0.11 to match the app released on Google Play. Please take a look at it.

Thanks.

**Comment by Giszmo** [comment]
https://walletscrutiny.com/posts/io.horizontalsystems.bankwallet/ updated.

**Comment by omurovch** [comment]
> https://walletscrutiny.com/posts/io.horizontalsystems.bankwallet/ updated.

Great! Thank you!

**Comment by Giszmo** [comment]
Again there is a tagging issue. The versionName is 0.12.0 yet there is no revision with that name. Could you please make sure the versionName matches the tag? It would help to automate testing.

**Comment by Giszmo** [comment]
I tried with 0.12 and failed to verify the build. 638 files differ.
