### ISSUE TITLE
https://btc.horizontalsystems.xyz/apg unreachable

### ISSUE THREAD

**Issue by elon-k-park** [horizontalsystems/unstoppable-wallet-android#1861]
BCH mainnet api not working
https://btc.horizontalsystems.xyz/apg
https://blockdozer.com/

**Comment by nk-the-crazy** [comment]
1. "https://btc.horizontalsystems.xyz/apg" API Url is related to BTC  only(!). 
2. For BCH , blockdozer was replaced By  "https://bch.coin.space/api/sync"
