### ISSUE TITLE
coin charts : add more info

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1881]
- [x] add option to view price charts for 3M (3 months) and 2Y (2 years)
- [x] add background on selected time period (1d)
- [x] add volume info on selected state
- [x] display volume without combined points (48 bars on 1d)
- [x] change CryptoCompare.com text color to grey50

**Comment by TalgatNurdinov** [comment]
<img width="368" alt="Screen Shot 2020-02-09 at 9 51 29 PM" src="https://user-images.githubusercontent.com/42367908/74105313-e2bd9e80-4b86-11ea-97b4-3107307765d3.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=1406%3A237
