### ISSUE TITLE
Security Center >> activating TOR setting does nothing and hides on/off controller

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1902]
Build 0.12 (242)

Security Center >> activating TOR setting does nothing and hides on/off controller

After killing the app, I can see that TOR is enabled by going to Settings >> Security Settings screen.

![IMG_3815](https://user-images.githubusercontent.com/8611762/74628923-1a2cdc00-5181-11ea-96bf-3bc05376b607.JPG)

**Comment by rafaelekol** [comment]
We should show alert when user enables Tor but Notifications are disabled.
