### ISSUE TITLE
Binance DEX : certain transactions that require memos return error if yx sent without memo

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1907]
When depositing to Binance the user required to enter memo text. When not entered the transaction fails. See image below.

![IMG_0983](https://user-images.githubusercontent.com/8611762/74638534-4737b980-5196-11ea-918c-83c994c7014b.jpg)

However, when sending BNB transaction to some other BNB address transaction goes without issues (without memo).

- [x] understand why the issues occurs. 
- [x] if certain addresses require the MEMO to be present in transaction then the wallet need to be able to parse/handle the returned error correctly. the user should see an alert "Provide memo text for transaction."

**Comment by esengulov** [comment]
ok, looks like Binance has one BNBDEX address for all its users, that is bnb136ns6lfw4zs5hg4n85vdthaad7hq5m4gtkgf23

most likely it's an error returned by centralized Binance API which handled BNB deposits to user's account

**Comment by Dianaaiym** [comment]
Localize Binance Error when memo is required
