### ISSUE TITLE
TOR : spinner for initializing tor connection

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1916]
When user enables TOR setting the app will require to connect to TOR every time it comes from background. That step may take a few seconds and before it's completed the user should not be able to do anything in the app. As a result, we need an overlay spinner that will be shown while the app is connecting to the TOR network.

- [x] implement the overlay screen (ask @TalgatNurdinov for details)
- [x] in case when the connection initialization doesn't complete successfully the user should see an alert with an option to Disable (TOR) and Retry button.

**Comment by TalgatNurdinov** [comment]
<img width="748" alt="Screen Shot 2020-02-25 at 11 21 37 AM" src="https://user-images.githubusercontent.com/42367908/75218103-68fef500-57c3-11ea-91de-f88f43e3c01c.png">
