### ISSUE TITLE
coin charts: display latest coin news

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1923]
Cryptocompare API provides an endpoint to get latest news for the asset.

We would like to have the latest news for the asset in the coin chart controller. 

- [x] For BTC, BCH, ETH, DASH, USDT use a quarry in the following format:

https://min-api.cryptocompare.com/data/v2/news/?categories=[coin_symbol], regulation&excludeCategories=Sponsored

- [x] For other currencies use

https://min-api.cryptocompare.com/data/v2/news/?categories=altcoin,trading,regulation&excludeCategories=Sponsored

- [x] Request 50 articles in each query. 
- [x] Set the expiration that would trigger new request to 30 minutes

**Comment by TalgatNurdinov** [comment]
<img width="837" alt="Screen Shot 2020-02-25 at 11 37 48 AM" src="https://user-images.githubusercontent.com/42367908/75218188-b4190800-57c3-11ea-836a-aac11b3b785a.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=6487%3A664

**Comment by TalgatNurdinov** [comment]
- Need to change news cells background color to Lawrance
- color of news spinner change to grey50 
- Check specs of periods tabs, fonts style should be Subhead1

**Comment by TalgatNurdinov** [comment]
- "latest news" font color should be "Leah"
- News titles color "Leah"

currently on light mode titles are grayed
