### ISSUE TITLE
Litecoin Infrastructure Setup

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1943]
- [x] find block explorer (@esengulov )
- [x] setup fee service (@esengulov )
- [x] setup fast restore API (@nk-the-crazy )

**Comment by esengulov** [comment]
- [ ] for block explorer we can use https://blockchair.com/api/docs

- [ ] fee service

 curl -v --data-binary '{}' http://134.209.138.9/ltc/fee_low
 curl -v --data-binary '{}' http://134.209.138.9/ltc/fee_avg
 curl -v --data-binary '{}' http://134.209.138.9/ltc/fee_high
 curl -v --data-binary '{}' http://134.209.138.9/ltc/gbc
 curl -v --data-binary '{}' http://134.209.138.9/ltc/gbb

**Comment by nk-the-crazy** [comment]
Block-Explorer/API for Litecoin:

curl -v http://67.205.140.41/api/sync/

based on Insight-API. 
(Docs : https://blockexplorer.com/api-ref)

**Comment by Dianaaiym** [comment]
Need to test

- [ ] fee service
- [ ] network restore
- [ ] api restore
- [ ] tx info >> litecoin tx block explorer
