### ISSUE TITLE
add Share button to tx info controller

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1944]

**Comment by TalgatNurdinov** [comment]
Clicking on the transaction ID's copyist should open system share controller
(see in design group)

**Comment by TalgatNurdinov** [comment]
button size is wrong
<img width="732" alt="Screen Shot 2020-03-16 at 2 35 34 PM" src="https://user-images.githubusercontent.com/42367908/76737691-73ddf180-6793-11ea-9d23-26ccd040eefd.png">
<img width="530" alt="Screen Shot 2020-03-16 at 2 35 22 PM" src="https://user-images.githubusercontent.com/42367908/76737701-7a6c6900-6793-11ea-9eaf-ec1e22c5b54e.png">
