### ISSUE TITLE
Tor requirements description for Xaomi devices 

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#1949]
<img width="360" alt="Screen Shot 2020-03-05 at 12 02 41 PM" src="https://user-images.githubusercontent.com/42367908/75952648-7dd13c00-5ed9-11ea-9110-fe38db12c0e6.png">
<img width="357" alt="Screen Shot 2020-03-05 at 12 02 25 PM" src="https://user-images.githubusercontent.com/42367908/75952652-80339600-5ed9-11ea-9c4c-586049e3af7b.png">

**Comment by rafaelekol** [comment]
After testing, I found out that Tor also works without Auto Start enabled. Thus we don't need to implement it now.
