### ISSUE TITLE
How is tor works ?

### ISSUE THREAD

**Issue by coderzstas** [horizontalsystems/unstoppable-wallet-android#1953]
![Screenshot_20200305-170912_Unstoppable](https://user-images.githubusercontent.com/3104406/75989318-1aa8cf00-5f04-11ea-8356-672acbacc7cf.png)

Cant connect to tor , allways getting this message .
Lineage 17.1 , oneplus 6t

**Comment by rafaelekol** [comment]
We can't reproduce this behavior. Also we don't have phone with Lineage. Can you try to run demo app from this repo: https://github.com/horizontalsystems/net-kit-android
To see whether Tor can start and connect.

**Comment by coderzstas** [comment]
yeah it working fine with demo app . trying to rebuild with recent changes .

**Comment by coderzstas** [comment]
E/TorOperator: Error starting Tor
E/TorOperator: Error!!! Tor.so file notfound.

for some reason it cant find that lib

**Comment by rafaelekol** [comment]
We also have same issue with loading tor.so file. Meanwhile I can advice you these:
- Make sure that you don't upgrade to Gradle 3.6.0. I even posted [question on stackoverflow about this problem](https://stackoverflow.com/questions/60446501/after-upgrading-gradle-to-3-6-0-native-library-not-found).
- Try to clean build via `Build` -> `Clean project`

**Comment by coderzstas** [comment]
bit strange because i didnt touched gradle - all default         
classpath 'com.android.tools.build:gradle:3.5.3'

**Comment by rafaelekol** [comment]
In near future we are planning to change [NetKit](https://github.com/horizontalsystems/net-kit-android) structure, that should fix this issue too.
Meanwhile you can try to clear gradle cache, to clear downloaded project libraries, and download them again. 
the problem is in this dependency
`api 'com.github.horizontalsystems:net-kit-android:a186723'`

**Comment by nk-the-crazy** [comment]
Refactored the Project (gradle) structure. This should resolve your issue @coderzstas. Let us know if you encounter any issue.

**Comment by coderzstas** [comment]
> Refactored the Project (gradle) structure. This should resolve your issue @coderzstas. Let us know if you encounter any issue.

Solved for me :) thanks
