### ISSUE TITLE
BCH: Transaction info >> Verify: API for Coin.space block explorer seems down

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1956]
I recommend to remover this provider entirely as it's expriencing frequent outages. The remaining two will suffice for the time being.

**Comment by Dianaaiym** [comment]
Cashexplorer.bitcoin.com seems as offline

![2020-03-09 11 37 19](https://user-images.githubusercontent.com/22589457/76185769-65736100-61fa-11ea-8e77-753919d36101.jpg)


but when user choosing this source, it works
