### ISSUE TITLE
further onboarding improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1958]
This is a followup issue to the previous onboarding ticket from weeks back, https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1782

We had some time to play around with the app and based on the experience would like to make some more changes:

## RESTORED WALLET USERS

Welcome >> Restored Wallet behavior

- [x] the steps for restoring wallets should be in the following order: Welcome > Restore > Choose Wallet > Key > Coin Selector > [coin] Settings. 
- [x] the list coins that will show [coin] settings are: BTC, BCH, DASH, LTC. For Bitcoin and Litecoin the preselected settings are BIP49 and FAST. For other coins, keep the Fast sync preselected.
- [x] when the user reactivates the coin which was deactivated earlier s/he should again see [coin] settings. 
-- the behavior for user that have initially restored wallet would be different than for those who are creating a new one 
-- users that have setup wallet as new and not restored it, re-activating the coin would apply default settings without showing user [coin_settings]. 
-- refer to @mNizhurin if not clear, we have discussed this with him already

## SETTINGS / MANAGE WALLETS

- [x] place Manage Wallets as the first item on settings page, above security settings
- [x] apply changes to Manage Wallets layout (refer to @TalgatNurdinov )

### Manage Wallet >> Wallet Item >> Restore

- [x] restore steps: Restore > Key > Coin Selector > [coin] Settings

### Manage Wallet >> Standard Wallet >> Advanced Settings

- [x] apply the layout for this screen
- [x] advanced settings for Standard should display [coin] cells for all coins. If the [coin] not enabled then show cell as inactive.
- [x] when user tries to change the address format for Bitcoin/ Litecoin show notification
> > After this change the wallet will have to resync itself with the [coin_name] blockchain. 
> >
> > When you change the address format for [coin_name] the current balance and transaction history will no longer be visible on balance tab. Changing it back to previous setting will bring everything back after the wallet resyncs itself with the blockchain. We recommend not to change it if not sure what that is.
> > Button 1 : Change to BIP 44/49/84 (depending on the setting)
> > Button 2: Cancel

- [x] when user tries to change the sync mode format for Bitcoin/ Litecoin / Dash / Bitcoin Cash show notification
> > After this change the wallet will have to resync itself with the [coin_name] blockchain. 
> > Button 1 : Change
> > Button 2: Cancel

- [x] do not show DONE button on top right as user already confirms the change in the previous alert. Done button only shown during restore where alert not shown.

- [x] coin manager: move EOS cell to top section below Binance DEX

**Comment by rafaelekol** [comment]
Link to design prototype
figma.com/proto/RDIKlTdIejA9cir83By3gS/Unstoppable-UX-Area?node-id=336%3A4379&viewport=1528%2C431%2C0.25&scaling=scale-down

**Comment by TalgatNurdinov** [comment]
<img width="1402" alt="Screen Shot 2020-03-09 at 11 44 23 AM" src="https://user-images.githubusercontent.com/42367908/76186108-7d97b000-61fb-11ea-879a-5c07af74bf55.png">

**Comment by esengulov** [comment]
minor issues :

- [ ] Coin Manager title should be "Choose Coins"
- [ ] in Blockchain Settings remove "...Settings" from cell titles. Instead of  "[coin] Settings" just show "[coin]"
- wallet list / manage wallets : add LTC to tokens to the list of the coins.
