### ISSUE TITLE
add option to hide balance

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1980]
There will be a slightly visible button next to balance amount on Balance tab. Clicking on that should substitute all values for * symbols.

- this should apply top the values on balance tab and transactions tab.
- clicking on the icon in activated state (i.e. balance hidden) should deactivate the setting and reveal all values

@TalgatNurdinov will provide the design for the feature

**Comment by TalgatNurdinov** [comment]
![hidebalance](https://user-images.githubusercontent.com/42367908/76653523-0499af00-6593-11ea-93ab-a42e4ca920d5.gif)

**Comment by Dianaaiym** [comment]
change icon color to grey50
