### ISSUE TITLE
add Synthetix token

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1983]
- rates https://www.cryptocompare.com/coins/snx/overview/USDT
- @TalgatNurdinov please prepare icon

**Comment by TalgatNurdinov** [comment]
added
<img width="149" alt="Screen Shot 2020-03-16 at 3 52 52 PM" src="https://user-images.githubusercontent.com/42367908/76744331-42b6ee80-679e-11ea-96e6-a07c6249626a.png">

**Comment by esengulov** [comment]
@rafaelekol chart view for the token missing data:
- mkt cap
- in circulation
- total supply
