### ISSUE TITLE
display syncing indicator on Transactions tab when wallet is in syncing state (for any of the coins)

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#1987]

**Comment by TalgatNurdinov** [comment]
- On syncing state need display "Please wait for the sync to finish" and add spinner to top of screen.
- When transactions appears on screen remove text and show spinner while syncing
- If does'nt have any transaction show placeholder text "You don’t have any pending or past transactions yet"

**Comment by Dianaaiym** [comment]
need to reduce spinner speed
