### ISSUE TITLE
Performance enhancements

### ISSUE THREAD

**Issue by omurovch** [horizontalsystems/unstoppable-wallet-android#2010]
Need to find out bottlenecks and optimize. For instance,  in PeerConnection reconsider connection polling with sleep().

**Comment by abdrasulov** [comment]
I've found out the following:

1. The main bottlneck is querying database. The first one is selecting public key by its key or keyhash. It's run for each of transaction outputs in the transaction to find out if they are "mine". When there is a transaction with a bunch number of outputs it may take about 3-5 seconds to handle it.

2. The current implementation of Peer with PeerConnection is not optimized in the context of threads. We create a new thread for each PeerConnection. In addition it is created before the socket connection is established. So when the remote host doesn't respond thread will be stopped instantly. Also there is a timer for each of Peer. The timer uses System.getCurrentTimeMillis(). They say this method may be slow.

3. Do we really need parallel peers? At the end we handle peers in the one place or synchronized. At a given time we work only with one peer. The only reason to have parallel peers is to detect the peer connection speeds. We sync peers in the same order as they are connected.

**Comment by tmedetbekov** [comment]
I made some performance analysis with dev build on emulator: android 10, api 29 

 * bindApplication: 5s 101ms 681us
    fetching apk: 823ms

  * startActivity: 906ms (LaunchActivity)
  * startActivity: 1.31s (MainActivity)
     inflate: 832ms
       NestedScrollView: 43ms
       CoordinatorLayout: 232ms
       TransactionInfoView: 412ms
     inflate: 625ms
       BottomNavigationView: 381ms
       ViewPager2: 217ms
 * Choreographer#doFrame: 1s 538ms
 * Choreographer#doFrame:  650ms
    Toolbar: 135ms
    SwipeRefreshLayout: 64ms
 * SettingsView: 1s 318ms
 * SettingsViewSwitch: 198ms
