### ISSUE TITLE
Intro Module

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#2017]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=156%3A0

**Comment by TalgatNurdinov** [comment]
- [ ] Need to add new color Darkest -#0F1014 for background
- [ ] Image position is should be centered on half of the screen
- [ ] Images should be changed with fade out and fade in animation 
- [ ] Update welcome screens design
