### ISSUE TITLE
Lock screen enhancements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2019]
- [x] add button to numbed for triggering touch/face ID.
- [x] change title to Prices on the following screen. Also change the time format.
- [x] list of your coins should be placed under 'Portfolio' section.
- [x] also add another section, the Top 100 list. You will need to make two requests to CC api to get this data.
-- the top 100 coins by market cap https://min-api.cryptocompare.com/documentation?key=Toplists&cat=TopTotalMktCapEndpointFull
-- send another batch request to get the price data for that list. 
- [x] add @cryptocompare.com as the source to the bottom, like it's in charts controller

**Comment by Dianaaiym** [comment]
Please apply new ui for lock screen (see below) and change title to 'Prices'. Also change time format

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=8323%3A167
