### ISSUE TITLE
Would you publish to F-Droid？

### ISSUE THREAD

**Issue by ivysrono** [horizontalsystems/unstoppable-wallet-android#2023]
https://f-droid.org/

**Comment by ivysrono** [comment]
https://android.izzysoft.de/repo/apk/io.horizontalsystems.bankwallet

**Comment by trymeouteh** [comment]
The app is no longer on izzysoft. Please publish the app on F-Droid and keep it maintained on F-Droid

**Comment by rafaelekol** [comment]
We are already on F-Droid
https://f-droid.org/en/packages/io.horizontalsystems.bankwallet/
