### ISSUE TITLE
How to add multi wallet for the same coin?

### ISSUE THREAD

**Issue by ivysrono** [horizontalsystems/unstoppable-wallet-android#2024]
For example, 1 BTC wallet, 2 ETH wallets, 3 EOS wallets.

**Comment by Aimeelu668** [comment]
自己开发的钱包都是热钱包机制，节点同步慢，归集非常麻烦，最重要的是这些私钥存在服务器上很危险，天天被黑客盯着。当时我们平台有50多万会员，为了解决钱包问题折腾了一年，最终放弃了，选择了优盾钱包 https://www.uduncloud.com  。通过API直接接入就行，有独立客户端操作审核、归集等，私钥也是自己在客户端上管理，服务器上不存。用了快一年，没有出现安全问题，财务都反馈说体验很好。我们也终于可以专注于业务开发了。推荐试试

**Comment by Aimeelu668** [comment]
自己开发的钱包都是热钱包机制，上游同步慢，归集非常麻烦，最重要的是这些私钥存在服务器上很危险，天天被黑客盯着。当时我们平台有50多万会员，为了解决钱包问题折腾了一年，最终放弃了，选择了优盾钱包https://www.uduncloud.com  。通过API直接接收就行，有独立客户端操作审核，归集等，私钥也是自己在客户端上管理，服务器上不存。用了快一年，没有出现安全问题，财务都反馈说体验很好。我们也终于可以专注于业务开发了。还可以多Token多地址统一管理，比较方便，推荐试试

**Comment by Aimeelu668** [comment]
自己开发的钱包都是热钱包机制，上游同步慢，归集非常麻烦，最重要的是这些私钥存在服务器上很危险，天天被黑客盯着。当时我们平台有50多万会员，为了解决钱包问题折腾了一年，最终放弃了，选择了优盾钱包https://www.uduncloud.com 。通过API直接接收就行，有独立客户端操作审核，归集等，私钥也是自己在客户端上管理，服务器上不存。用了快一年，没有出现安全问题，财务都反馈说体验很好。我们也终于可以专注于业务开发了。还可以多Token多地址统一管理，比较方便，推荐试试

**Comment by Aimeelu668** [comment]
自己开发的钱包都是热钱包机制，节点同步慢，归集非常麻烦，最重要的是这些私钥存在服务器上很危险，天天被黑客盯着。当时我们平台有50多万会员，为了解决钱包问题折腾了一年，最终放弃了，选择了优盾钱包 https://www.uduncloud.com 。通过API直接接入就行，有独立客户端操作审核、归集等，私钥也是自己在客户端上管理，服务器上不存。用了快一年，没有出现安全问题，财务都反馈说体验很好。我们也终于可以专注于业务开发了。推荐试试

**Comment by Aimeelu668** [comment]
楼主大大总结的很到位！不过自己开发的钱包都是热钱包机制，节点同步慢，归集非常麻烦，最重要的是这些私钥存在服务器上很危险，天天被黑客盯着。当时我们平台有50多万会员，为了解决钱包问题折腾了一年，最终放弃了，选择了优盾钱包 https://www.uduncloud.com  。通过API直接接入就行，有独立客户端操作审核、归集等，私钥也是自己在客户端上管理，服务器上不存。用了快一年，没有出现安全问题，财务都反馈说体验很好。我们也终于可以专注于业务开发了。推荐试试

**Comment by esengulov** [comment]
> For example, 1 BTC wallet, 2 ETH wallets, 3 EOS wallets.

We are moving towards a multi-wallet app where any number of number of keys can be present in the wallet; with each key potentially controlling any desired set of coins. This setup involves several incremental steps the are hard to roll out all at once, I would say mainly in terms of UI.

The version 0.13 took significant steps in that direction by standardizing wallet create/restore steps.

In 0.14 we are likely to expand on restore/creation feature by enabling seeds in the form of not just 12 words but also 24 as well as the ability to include password.

Once that complete we are going to look at the multi-account feature you mentioned :) It will be easier to properly plan it once the above features are in place.

So hopefully coming soon, thanks for bringing it up!



 regardless of the bl
