### ISSUE TITLE
feature request: restore ETH wallet by import keystore

### ISSUE THREAD

**Issue by ivysrono** [horizontalsystems/unstoppable-wallet-android#2025]

**Comment by esengulov** [comment]
hi @ivysrono we'll look into it soon, most probably we will add it in the near future. Thanks for heads up. Meanwhile, add 'postponed' label to the ticket

**Comment by esengulov** [comment]
Duplicate of https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2542
