### ISSUE TITLE
Incorrect exchange rate for Single Collateral DAI (SAI)

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2027]
- [x] Do not show current real-time rate for Single Collateral DAI (SAI) Token. Ignore value returned by CC as it's incorrect.

The current exchange rate returned by CryptoCompare for SAI token is not correct. Real time rate API Call returns: 0.7523$

https://min-api.cryptocompare.com/data/price?fsym=Sai&tsyms=USD

check it on https://coinmarketcap.com/currencies/single-collateral-dai/

**Comment by nk-the-crazy** [comment]
No mismatch on Coin names. 
Incorrect xrate values for SAI coin.
