### ISSUE TITLE
Intro Module >> Add Privacy Settings

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#2028]
- [ ] In the security center add privacy settings screen. It includes settings for: Tor, bitcoin initial sync modes, sorting of transaction inputs and outputs, Ethereum HTTP provider.

<img width="836" alt="Screen Shot 2020-03-31 at 3 02 59 PM" src="https://user-images.githubusercontent.com/42367908/78007881-b9d4b100-7360-11ea-8559-6b45be5fcf4c.png">

- [ ] Apart from app settings, this screen must be accessible from the welcome screen

<img width="847" alt="Screen Shot 2020-03-31 at 3 02 22 PM" src="https://user-images.githubusercontent.com/42367908/78007895-be996500-7360-11ea-9228-df5b28b7a36b.png">

**Comment by Dianaaiym** [comment]
Security Center -> Privacy 
remove selection for EOS/Binance
