### ISSUE TITLE
In ETH change in3 to Infura when Tor enabled

### ISSUE THREAD

**Issue by nk-the-crazy** [horizontalsystems/unstoppable-wallet-android#2045]
- if ETH is active, change in3 to  Infura when Tor enabled

**Comment by esengulov** [comment]
Build 0.14.352

My understanding is that when TOR activated the ethereum connection mode should be set to Infura. I have incubed enabled and when activating TOR the Privacy settings still shows the Incubed setting.

If the user has Incubed activated than TOR activation should display alert. 

> Activating TOR will reset Ethereum blockchain connection back to Infura.
> 
> OK

**Comment by nk-the-crazy** [comment]
> Build 0.14.352
> 
> My understanding is that when TOR activated the ethereum connection mode should be set to Infura. I have incubed enabled and when activating TOR the Privacy settings still shows the Incubed setting.
> 
> If the user has Incubed activated than TOR activation should display alert.
> 
> > Activating TOR will reset Ethereum blockchain connection back to Infura.
> > OK

How to combine below alert with Tor notification ?

<img width="317" alt="Screen Shot 2020-04-16 at 10 39 36 PM" src="https://user-images.githubusercontent.com/11713346/79482900-4fe02b00-8033-11ea-8c1e-5b53e3fbe75c.png">
