### ISSUE TITLE
balance tab: handle click on sync error/exclamation icon shown on coin cell

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2068]
- [x] change header text on Privacy Screen from "Blockchain Connection" to "Blockchain Sync" @Dianaaiym 
- [x] change Source should be shown for all tokens/blockchains except Binance Chain (+tokens) and EOS(+tokens)

**Comment by TalgatNurdinov** [comment]
<img width="387" alt="Screen Shot 2020-05-07 at 9 03 25 PM" src="https://user-images.githubusercontent.com/42367908/81310660-35cfc080-90a6-11ea-90d1-a869903c6d00.png">


https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=9433%3A3723

**Comment by rafaelekol** [comment]
Если нет интернета то при нажатии на что либо будет NO INTERNET error 

Если интернет есть , и коин/ы не синкуются:

Нажатие на алерт показывает этот контроллер с тремя кнопками:

1) Retry: делает рефреш коина. Возможно в процессе тестирования мы поменяем требования и будем просить рефрешить все коины которые подвязаны к источнику для синка данных  (тоесть можем потом сказать рефрешьте все активные ерс 20, а не один)

2) change source: перекидывает в security >> privacy где можно поменять источник синка. 

3) репорт: открывает страничку репорт в сеттингах и копирует ошибку в буфер /clipboard

**Comment by TalgatNurdinov** [comment]
- [ ] Change Source should be shown only on Ethereum and ERC-20 Tokens @rafaelekol
