### ISSUE TITLE
a question about the total balance 

### ISSUE THREAD

**Issue by aflamzone** [horizontalsystems/unstoppable-wallet-android#2087]
Hi there, 

i want to know if i receive bitcoins in the wallet it will be displayed in total balance, and what if i want send it as ethereum from the total balance is the app able to do exchange between coins ?

thank you

**Comment by esengulov** [comment]
> Hi there,
> 
> i want to know if i receive bitcoins in the wallet it will be displayed in total balance, and what if i want send it as ethereum from the total balance is the app able to do exchange between coins ?
> 
> thank you

Hi there, right now the app not able to exchange. In the near future we are going to work on that capability.
