### ISSUE TITLE
after phone awake/unlock briefly seeing the screen that was seen last in the app, then the lock screen is shown

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2103]
Build 0.14.0 (353)
Device: Xiaomi Mi Max

The bug was demonstrated in Android team chat on April 15th

**Comment by rafaelekol** [comment]
I tried other apps to see they behave in same situation.
Bread Wallet and Telegram also shows last screen, then shows PIN screen,
Samourai wallet shows screen without locking it(maybe they have longer time for unlocked state)
