### ISSUE TITLE
How to remove whole EOS and Binance Chain thing from the app?

### ISSUE THREAD

**Issue by wolfenix** [horizontalsystems/unstoppable-wallet-android#2112]
Hi there, first of all I'm extremely impressed by the app and the devs who are still active and maintaining the repository, plus everything is smooth and beautiful in the app. Now the thing is, I want to modify this app for my college project and just want Bitcoin, Ethereum and some ERC-20 tokens in the app, and I'm a beginner noob, so I looked everywhere but still can't find a way to remove the binance and eos blockchain from the app completely, like from the restore and backup options, I've successfully remove both from AppconfigProviders coin list, but can't figure out how to remove from the restore option and backup options.

Plz help me, I've only got 3 days before my submission and If I'll not get the resolution I'll be doomed :(... plz help me!!!

**Comment by rafaelekol** [comment]
Hi,
take a loot at class `PredefinedAccountTypeManager` which has variable `allTypes`, try removing Binance and EOS from there.

**Comment by wolfenix** [comment]
> Hi,
> take a loot at class `PredefinedAccountTypeManager` which has variable `allTypes`, try removing Binance and EOS from there.

...and in which folder and line is this "PredefinedAccountTypeManager" ?
and does that remove EOS and Binance from recover and backup options visually too?

**Comment by wolfenix** [comment]
Holllyyyyyyy Shitttttt dudeeee...................It FRIGGIN WORKED!!!!!!!!!!!!!!!!

Thankyou so much dude, You saved my friggin life, goddddd you're a frigging genius brooooooooo, I owe you a big time bro, damnnnn!!!!

Thankyou so much man!!!!!!!
Love you 30000000!!!!
