### ISSUE TITLE
How can I remove "Latest news" from chart area?

### ISSUE THREAD

**Issue by wolfenix** [horizontalsystems/unstoppable-wallet-android#2113]
What should I do to remove the whole "Latest News" section whenever the chart sections gets opened?

**Comment by tmedetbekov** [comment]
Currently, you can't remove this section but in a future version, we'll redesign this page. Maybe we can move this part into a tab something like that

**Comment by tmedetbekov** [comment]
But if you want to remove it from the code you can do it by removing this chunk of code: https://github.com/horizontalsystems/unstoppable-wallet-android/blob/1389cf5aaf165c1e239c8fc1ba7160c97d97c795/app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt#L51-L54
