### ISSUE TITLE
Restore Ethereum wallet with Private Key.

### ISSUE THREAD

**Issue by wolfenix** [horizontalsystems/unstoppable-wallet-android#2125]
Hi, the wallet backup and restore system of mnemonic phrase is good but we need view wallet private key option somewhere in settings fragment, so that one can see their eth wallet private key too, adding the option of restore Ethereum wallet with Private key will be much better, safe and universal I guess.

Please try to add this feature soon, it's really and important feature.

Thank you.

**Comment by Dianaaiym** [comment]
> Hi, the wallet backup and restore system of mnemonic phrase is good but we need view wallet private key option somewhere in settings fragment, so that one can see their eth wallet private key too, adding the option of restore Ethereum wallet with Private key will be much better, safe and universal I guess.
> 
> Please try to add this feature soon, it's really and important feature.
> 
> Thank you.

Hi @wolfenix  we'll look into it soon, most probably we will add it in the near future. Thanks for the heads up.

**Comment by wolfenix** [comment]
Sure, that's amazing, looking forward to see the feature soon.
