### ISSUE TITLE
Weird bottom navigatin behavior on Android 10

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#2132]
Reproduced on Pixel 2 API 29 (Emulator), Samsung A6

![Screenshot_1587636380](https://user-images.githubusercontent.com/5284600/80090576-89f48400-8581-11ea-974b-afdd74ae43ff.png)

**Comment by nk-the-crazy** [comment]
Issue resolves by downgrading :
```com.google.android.material:material:1.2.0-alpha06``` dependency
to version  **1.2.0-alpha05**
