### ISSUE TITLE
How to add a new token/coin icon for another erc20 token?

### ISSUE THREAD

**Issue by wolfenix** [horizontalsystems/unstoppable-wallet-android#2133]
Hi, I've tried online svg to xml converter, ever android studio add new vector asset, but can't add a new icon to the the app, it won't show!
Is there anyway i can use png file of to create xml file the logo in correct way?

Thankyou.

**Comment by esengulov** [comment]
Hi @wolfenix if you want to add new erc20 token you need to use exactly same estepa/elements as on the other tokens. That were added by us.

If you do the other way it may or may not work) This question is beyond the scope of our code and hence I can’t really answer in detail here.

**Comment by wolfenix** [comment]
No, I have successfully added the token through AppConfigProvider.kt but I was just asking for the icon, I can't configure the icon XML settings, I mean how can I add a new icon?

**Comment by rafaelekol** [comment]
Try add coin image to drawable directory. Make sure its name to have this format `coin_coincode.png`(like coin_btc.png)
It either can be `.jpg` or `.png` format. Or if you have vector format(SVG) like we do you can import it to project, and it will have `.xml` extension.

**Comment by wolfenix** [comment]
That means, I can use a PNG file.instead of XML for token icon?
Damn!
And should I keep the size to 24×24 or a different size?
