### ISSUE TITLE
How to remove "Address Format" from Manage Wallets, backup option box?

### ISSUE THREAD

**Issue by wolfenix** [horizontalsystems/unstoppable-wallet-android#2134]
Hi, I tried to remove address format option but can't figure out how to do it correctly, the app was crashing, that option is not really necessary, is there any way how to remove that option from the manage wallet option box?

Thank you.

**Comment by esengulov** [comment]
Hi @wolfenix that section went through major updates in the latest release (0.13). I suggest you try it on the new version.

That said address format is critical component and used in many steps for the app, for coins like Bitcoin.

**Comment by wolfenix** [comment]
Ohh, than I should not remove that, I thought it was unnecessary!
Well, thanks!
