### ISSUE TITLE
AAPT: error

### ISSUE THREAD

**Issue by tradexic** [horizontalsystems/unstoppable-wallet-android#2147]
.gradle\caches\transforms-2\files-2.1\ace6d71cf28bec3f3d4f636570db1dd9\constraintlayout-2.0.0-beta1\res\values\values.xml:271:5-277:511: AAPT: error: resource attr/motionProgress (aka io.horizontalsystems.bankwallet:attr/motionProgress) not found.

**Comment by nk-the-crazy** [comment]
> .gradle\caches\transforms-2\files-2.1\ace6d71cf28bec3f3d4f636570db1dd9\constraintlayout-2.0.0-beta1\res\values\values.xml:271:5-277:511: AAPT: error: resource attr/motionProgress (aka io.horizontalsystems.bankwallet:attr/motionProgress) not found.

Hi @tradexic please , give detailed information about error, platform and if possible steps to reproduce.

**Comment by nk-the-crazy** [comment]
Issue is not reproducible (incomplete error details).
Closing issue.
