### ISSUE TITLE
Restore: No coins are selected, but button 'Next' appears as enabled

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2160]
to reproduce: 

Restore > Key > Enable BTC, LTC > disable BTC, LTC

**Comment by uber9** [comment]
This is probably related to issue #2162 

How to reproduce this bug:
When enabling BTC, LTC press on the toggle buttons.
When disabling BTC, LTC do not press, toggle (slide fingers) instead.
"Next" button should be still active, press on it, choose BIPs, and these coins will appear on Balance tab.
