### ISSUE TITLE
Toggle button bug on Choose Crypto menu

### ISSUE THREAD

**Issue by uber9** [horizontalsystems/unstoppable-wallet-android#2162]
Choose Crypto menu appears when:
- Add Coins (on Balance tab)
- Create wallet
- Restore wallet

When you press on toggle button, it changes its state and everything works as expected.
But when you toggle (slide with finger to switch) it, button changes its state, but it won't have affect it is supposed to.

For example, "Add Coins menu":
1. Press "Add Coins" button on Balance tab.
2. Add/Remove coins by toggling (sliding switch).
3. Press "Done", and you will see no changes on Balance tab.

**Comment by nk-the-crazy** [comment]
When multiple switches selected and all deselected , restore button stays as an active/enabled.
