### ISSUE TITLE
Double clicks on many buttons in the app are not prevented.

### ISSUE THREAD

**Issue by uber9** [horizontalsystems/unstoppable-wallet-android#2170]
Person can double click on a button by accident. As a result screens are opening several times in a row, and many other buggy behaviors.

Double click on chart button:
http://vgifbot.online/gif/BAACAgIAAxkBAAEmxAVeqrnPk6mX-ECU7_AafWcd_wUE8wACFwYAAvrKWEn8hXzOp0CgHxkE_1588247020.37.gif

Tripple click on currency button:
http://vgifbot.online/gif/BAACAgIAAxkBAAEmxAleqrob2__iFAd4UAeWf0fWsArQnQAC8wUAAvrKWEkiSitg79ifoxkE_1588247145.87.gif

**Comment by Dianaaiym** [comment]
Settings >> Security Center

after click on 'enable passcode', screens are opening several times in a row.
