### ISSUE TITLE
Buttons redesign 

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#2178]
Update 
- [x] Primary Buttons (Yellow, Green, Grey YGGpressed / disabled )
- [x] Secondary Buttons (Default, Pressed, Disabled, highlighted, TransparentBG - default, pressed , disabled, highlighted)

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=8777%3A489

**Comment by TalgatNurdinov** [comment]
- Secondary TransparentBG Active
    border - 0.5
    height - 28

**Comment by nk-the-crazy** [comment]
Update left-right padding for transaction filter tabs
right : 24dp
left: 24 dp
