### ISSUE TITLE
Enable Face Unlock

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2201]
- [x] show 'Biometric Authentication' in Security Settings module
- [x] add 'Biometric Authentication' button to num pad for triggering biometric unlock
- [x] add following text below the Biometric Auth setting

> Enabling Biometric Authentication may potentially weaken the security of your device when compared to plain PIN lock code.

**Comment by rafaelekol** [comment]
This can be useful
https://handstandsam.com/2020/05/07/unlocking-biometric-prompt-fingerprint-face-unlock/
