### ISSUE TITLE
Change address format visibility in Manage Accounts

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2213]
Address format for Standard Wallet should display format only for activated Bitcoin/Litecoin. If the Bitcoin/Litecoin is disabled then don't show format. Only related options for active coin will be shown.

**Comment by herou** [comment]
In this case, what should we show if the Bitcoin/Litecoin is disabled?
What about having just one of them enabled? What should we show in this case?

**Comment by nk-the-crazy** [comment]
> In this case, what should we show if the Bitcoin/Litecoin is disabled?
1. In case BTC/LTC disabled no "Address Format" option will be shown.

> What about having just one of them enabled? What should we show in this case?
2. Only related options for active coin will be shown.
