### ISSUE TITLE
Failed Transactions: enable user to obtain and forward raw transaction

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2218]
When BTC / BCH / LTC / DASH transactions fail the app currently shows Transaction Status as failed. 

We should enable user to report that to HS and forward raw transaction. On transaction info somewhere near the status cell there should be "raw transaction' button. When user clicks on that button we should provide two options:

- Copy
- Report

Click on report should open Contact section in the app settings and copy raw transaction to the clipboard

**Comment by esengulov** [comment]
@TalgatNurdinov please provide the design for this

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=10237%3A487
<img width="752" alt="Screen Shot 2020-05-13 at 2 05 44 PM" src="https://user-images.githubusercontent.com/42367908/81787482-f03a4a00-9522-11ea-915e-3dbe60ba8ab2.png">
