### ISSUE TITLE
Instructions to add a new altcoin to unstoppable wallet

### ISSUE THREAD

**Issue by akshaynexus** [horizontalsystems/unstoppable-wallet-android#2221]
Is there any documentation or procedure one should follow while adding a altcoin to this mobile wallet ,ie on iOS or Android? If not what are the requirements explorer wise /backend wise to add new altcoins to this codebase?

**Comment by esengulov** [comment]
> Is there any documentation or procedure one should follow while adding a altcoin to this mobile wallet ,ie on iOS or Android? If not what are the requirements explorer wise /backend wise to add new altcoins to this codebase?

Hi there,

We have added contribution guidelines, check them out here https://github.com/horizontalsystems/unstoppable-wallet-android/blob/master/CONTRIBUTE.md
