### ISSUE TITLE
Use seeds instead of words for mnemonic Account Types

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#2222]
As for now, we store words for mnemonic account types. Every time when bitcoin kit is initialized it converts words to seed that takes time. It is better to store seeds instead of words.

**Comment by omurovch** [comment]
The speed up in bitcoin-kit initialization when passing seed instead of mnemonic was not satisfactory. It was decided not to do it because of potential risks of keeping both mnemonic and seed.
