### ISSUE TITLE
Fix paddings of  tx. input button's text

### ISSUE THREAD

**Issue by nk-the-crazy** [horizontalsystems/unstoppable-wallet-android#2228]
![photo_2020-05-13_17-47-00](https://user-images.githubusercontent.com/11713346/81810418-b8dc9500-9544-11ea-9aed-4c616e9fd0dc.jpg)

**Comment by Dianaaiym** [comment]
![2020-05-14 10 20 42](https://user-images.githubusercontent.com/22589457/81892335-aad25700-95cc-11ea-83c9-50cedf09f29d.jpg)
