### ISSUE TITLE
Can I switch network?

### ISSUE THREAD

**Issue by herou** [horizontalsystems/unstoppable-wallet-android#2229]
I would like to see what is wrong with this ticket #2228 but I do have any transaction history on my main net.
Is it a way to switch to test networks like Kovan? I guess you have a way because you do not make tests on the main network.

**Comment by abdrasulov** [comment]
Hi @herou,

You can build the app in test mode using the devTestnet productFlavor.

As for the #2228, there is a UI issue. Some letters do not fit
