### ISSUE TITLE
integrate guides into wallet

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2242]
The way it's currently envisioned there will be a separate Guides tab in the app. From when're user will be able to navigate all guides.

We should aim to provide a smooth reading experience allowing user to change font type and size. 

The list of guides should be be filtrable allowing user to view all guides on a specific subject such as "Bitcoin" etc.

The current consensus is that guides are going to provided in markdown format. The sample can be found here, https://github.com/horizontalsystems/blockchain-crypto-guides/blob/master/tether.md

On the publishing side we expect to have not more than different text elements i.e. headers (h1 ,h2, h3), links, quotes, lists
- [ ] research implementation
- [ ] divide the feature into multiple issues
- [ ] provide guidelines to the publishing team.

**Comment by TalgatNurdinov** [comment]
last version 
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=10527%3A2208
