### ISSUE TITLE
review Send Controller

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2254]
- [ ] Add new component that called "additional data cell" 

<img width="836" alt="Screen Shot 2020-05-20 at 2 06 38 PM" src="https://user-images.githubusercontent.com/42367908/82422456-491a5d00-9aa4-11ea-8b21-bf99a5e82919.png">

- [x] make sure that the fee related fields match with iOS. Android version shows some words capitalize and displays ":" in some cases. Also the fee value in fiat and its crypto equivalent are positioned differently

**Comment by TalgatNurdinov** [comment]
Change the Tx speed and TimeLock buttons color to Leah
