### ISSUE TITLE
When connection is lost Bitcoin based wallets may stuck in syncing state

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#2258]
I could reproduce it restoring wallet with BTC and BCH enabled. BCH mode was FullSync. Then when the internet is lost BCH stuck at syncing state.

The reason is that the kit sent NotSynced state and then Syncing state to BCH.

**Comment by esengulov** [comment]
@Dianaaiym use the reproduction steps outlined above to test this issue
