### ISSUE TITLE
Replace Toast to Snackbar

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#2268]
<img width="372" alt="Screen Shot 2020-05-21 at 1 21 43 PM" src="https://user-images.githubusercontent.com/42367908/82533924-0751eb00-9b66-11ea-9334-004f1923aab7.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=9348%3A10516

**Comment by TalgatNurdinov** [comment]
- [ ] try to make disappear snackbars when bottom sheet controller closing
- [ ] when entering wrong phrases snackbar should be shown above keyboard

**Comment by rafaelekol** [comment]
When showing success and then closing activity, it happens too quickly to read or even see the success message. Because message is closing together with activity
