### ISSUE TITLE
First shows system font in title when opening Coin manager

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2279]
Invalid display behavior in AppBarLayout.  When AppBar is displayed Title font is system and then set to actual font.
1.
<img width="357" alt="Screen Shot 2020-05-24 at 5 05 14 PM" src="https://user-images.githubusercontent.com/11713346/82752600-e9dc8580-9de0-11ea-9c55-8291530dba19.png">
2.
<img width="357" alt="Screen Shot 2020-05-24 at 5 05 25 PM" src="https://user-images.githubusercontent.com/11713346/82752603-f1039380-9de0-11ea-8707-f6ddd94069a7.png">

**Comment by nk-the-crazy** [comment]
Only in Android 10
