### ISSUE TITLE
apply new graphics on welcome screens

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2303]

**Comment by TalgatNurdinov** [comment]
- [ ] Image area is placed at the height of 70% of the screen (currently 50%)
- [ ] replace images and circle

<img width="651" alt="Screen Shot 2020-05-28 at 10 19 18 AM" src="https://user-images.githubusercontent.com/42367908/83098510-b47bb480-a0cc-11ea-8129-612d9fb15c5c.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=9239%3A1526

**Comment by TalgatNurdinov** [comment]
Need to replace knowledge images
[welcome-images.zip](https://github.com/horizontalsystems/unstoppable-wallet-android/files/4711121/welcome-images.zip)
