### ISSUE TITLE
move news to lock screen

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2304]

**Comment by TalgatNurdinov** [comment]
- [ ] Place the news below the portfolio changes
- [ ] Add new page for Top 100
- [ ] Add cell for Title and placing sort button. Portfolio sorting should be same as in balance tab, on top 100 - sorting by m.cap, top losers and winners (change price up/down)

<img width="819" alt="Screen Shot 2020-05-28 at 10 27 42 AM" src="https://user-images.githubusercontent.com/42367908/83099010-e17c9700-a0cd-11ea-9a9e-3f1df87df6ca.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=9284%3A583

**Comment by abdrasulov** [comment]
Replace sorting by market cap with sorting by rank. Rank data should be taken from the initial top list.
