### ISSUE TITLE
Add new ERC20 Tokens

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2341]
**SwissBorg**

- name: SwissBorg
- symbol: CHSB
- contract address: 0xba9d4199fab4f26efe3551d490e3821486f135ba
- decimals: 8
https://etherscan.io/token/0xba9d4199fab4f26efe3551d490e3821486f135ba
https://www.cryptocompare.com/coins/chsb/overview
- icon: @TalgatNurdinov 

**Civic**

- name: Civic
- symbol: CVC
- contract address: 0x41e5560054824ea6b0732e656e3ad64e20e94e45
- decimals: 8
https://etherscan.io/token/0x41e5560054824ea6b0732e656e3ad64e20e94e45
https://www.cryptocompare.com/coins/cvc/overview
- icon: @TalgatNurdinov 

**Orchid**

- name: Orchid
- symbol: OXT
- contract address: 0x4575f41308EC1483f3d399aa9a2826d74Da13Deb
- decimals: 18
https://etherscan.io/token/0x4575f41308EC1483f3d399aa9a2826d74Da13Deb
https://www.cryptocompare.com/coins/oxt/overview/USD
- icon: @TalgatNurdinov 

**District0x**

- name: District0x
- symbol:DNT
- contract address: 0x0abdace70d3790235af448c88547603b945604ea
- decimals: 18
https://etherscan.io/token/0x0abdace70d3790235af448c88547603b945604ea
https://www.cryptocompare.com/coins/dnt/overview
- icon: @TalgatNurdinov

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=13268%3A645

**Comment by Dianaaiym** [comment]
**Aragon**

- name: Aragon
- symbol: ANT
- contract address: 0x960b236A07cf122663c4303350609A66A7B288C0
- decimals: 18
https://etherscan.io/token/0x960b236A07cf122663c4303350609A66A7B288C0
https://www.cryptocompare.com/coins/ant/overview
- icon: @TalgatNurdinov
