### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#2348]
See details in telegram group message @ June 17, 14:28

**Comment by TalgatNurdinov** [comment]
- [ ] margins of dialogs not fixed yet
- [ ] default state the privacy settings buttons on the welcome page have a missing gradient
- [ ] input the account name in EOS is not allowed multi-line, but you can typing it. Can we make the enter button disable?

**Comment by nk-the-crazy** [comment]
> * [ ]  margins of dialogs not fixed yet
This issue is closed in #2365
