### ISSUE TITLE
Push Notification on price change

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#2349]
**price chart screen**
When notification denied alert icon is not shown in chart screen. If notifications allowed by device settings alert icon is appear near price change value with inactive (grey) color
After setting some alert the icon is should be active and filling Jacob color

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=9731%3A5406

**Prototype:**
https://www.figma.com/proto/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=13070%3A214&viewport=-4858%2C-11149%2C0.5&scaling=scale-down

**In Settings**
In settings page should be listed only added coins
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=13539%3A2265

## push alert template

- [ ] price change alert template >> [coin_symbol] price: [direction] x% [emoji]
- [ ] price trend change alert >> [coin_symbol] trend: [direction]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=17117%3A160

**Comment by TalgatNurdinov** [comment]
can we make click effect with changing colors, not ripples?

pressed state example
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=17164%3A0

**Comment by abdrasulov** [comment]
When notifications are disallowed on OS level the icon is shown
