### ISSUE TITLE
Set AlertDialog margins 

### ISSUE THREAD

**Issue by nk-the-crazy** [horizontalsystems/unstoppable-wallet-android#2365]
- Set left/right  margins (40dp) for AlertDialog fragments

![photo_2020-06-22_14-41-52](https://user-images.githubusercontent.com/11713346/85268013-c405d780-b497-11ea-93a3-203178f71474.jpg)

**Comment by abdrasulov** [comment]
This is the default style for DialogFragment. It doesn't provide methods to customize these margins.
