### ISSUE TITLE
update listing on Play Market

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2391]
- [x] text available below

- [x] refer to @TalgatNurdinov for new screenshots

----

Title: 
UNSTOPPABLE - Cryptocurrency for Investors

Subtitle: 
Bitcoin & Crypto Investments Made Easy

Description:

Unstoppable cryptocurrency wallet is built for the new comers looking to invest in cryptocurrencies and blockchain based projects on ongoing basis in a safe, independent and private manner. 

This wallet has everything you need to learn, monitor, grow and exercise exclusive control over your cryptocurrencies. It has a nice UI and likely the most advanced cryptocurrency wallet to date.

1. ONE WALLET FOR ALL CRYPTO

Transfer, store, and monitor prices for all major cryptocurrencies like Bitcoin and Ethereum as well as cryptocurrency tokens.

Full Support:

- Bitcoin (BTC)
- Ethereum (ETH) + ERC20 tokens
- EOS (EOS) + tokens
- Binance Chain (BNB) + BEP2 tokens
- Dash (DASH)
- Litecoin (LTC)
- Bitcoin Cash (BCH)

2. BECOME INFORMED & LEARN

Unstoppable breaks down cryptocurrency essentials and provides coin overviews in simple terms.

- learn about instruments 
- master cryptocurrency fundamentals
- understand major cryptocurrencies
- discover decentralized finance

You can’t proceed successfully in crypto ecosystem without understanding the essentials.

3. KEEP CRYPTO SAFE 

The Unstoppable is a non-custodial wallet. The private keys never leave user’s phone.

Following guidelines from Google and Apple, Unstoppable secures the sensitive data (private keys) residing in the app using Secure Storage mechanisms provided by Android and iOS, respectively. As a result, no one  able to access wallet funds if the phone is lost or stolen. 

Unstoppable supports all wallet standards allowing the wallet user to easily migrate from Unstoppable to another wallet and vice versa, at any time. 

4. GET PRICE INSIGHTS

Follow cryptocurrency market news, monitor top 100 rankings, daily top winners and more. 

- setup alerts for price changes
- watch price trends and get alerted on reversals
- historical price charts 

Know when is the right time to buy, sell or hold for each cryptocurrency.

5. TRADE CRYPTOCURRENCIES

Integrated decentralized cryptocurrency trading for Ethereum and Ethereum-based tokens. Buy nearly any Ethereum-based token  without leaving the wallet app.

- Trade between Ethereum and ERC20 tokens
- Exchange ERC20 to ERC20 tokens

Unstoppable integrates a decentralized finance protocol known as Uniswap to enable cryptocurrency swaps in a safe, private and non-custodial manner. No account setups or KYC checks involved.

6. ACCESS EVERYWHERE

No entity can censor you from sending or receiving crypto or block Unstoppable wallet app. 

The wallet was engineered in a way where there is no dependence on a centrally managed servers. So it should work everywhere as long as there is internet connection.

7. REMAIN PRIVATE

When using UNSTOPPABLE, you are connecting directly to decentralized blockchains without intermediaries. Exceptions apply to certain blockchains like Binance Chain where decentralized network connectivity not available yet.  There are no accounts, emails, phone numbers, identity checks, or third-party servers storing any of your data.   Not all blockchains are private out of the box. We took some steps to remedy that by adding additional privacy features like transaction input/ output randomize and ‘no address reuse’.

8. ADVANCED BITCOIN WALLET

While UNSTOPPABLE supports a lot of cryptocurrencies, it was primarily designed for Bitcoin. With Unstoppable you get the most advanced Bitcoin wallet available:

- HD Wallet & BIP44/49/84 compliance
- SPV enabled
- BIP 69 support
- Ability to send time locked transactions
- Real time transaction fee estimator

Peace!

**Comment by TalgatNurdinov** [comment]
[Unstoppbale-StoreScreenshots.zip](https://github.com/horizontalsystems/unstoppable-wallet-android/files/4878637/Unstoppbale-StoreScreenshots.zip)
