### ISSUE TITLE
Adjust rounding logic for exchange rate values on balance tab

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2401]
For values above 1000(in base currency) do not show cents at all

---

The current logic is as follows:

Balance Tab
* total balance - 2:2
* balance cell rate - 2:4
* balance cell fiat value - 0:2

Chart
* current rate - 2:4
* coinMarketCap - shortened:0:2
* volumeValue - shortened:0:2
* point price (on click) - 2:4
* pointInfoVolume - 0:2
* min rate - 0:2
* max rate - 0:2

Lock screen
* rate - 0:2

Send
* hint (bottom of amount input) - 2:2
* available balance - 2:2
* fee - 2:2
* error - 2:2

Send Confirmation
* amount in fiat - 2:2

Transaction Info
* amount in fiat - 0:significantDecimals

Full Transaction Info
* rate - 2:4
* fiat fee - 0:2

Transactions Tab
* Fiat value - 0:2

significantDecimals = 
* if value == 0 or value >= 1 then 2
* if the index of the first non zero value after dot is <= 4 then 4 (ex, 0.0001234 and 0.001234 matches criteria, whereas 0.00009876 does not)
* else 4 values starting from first non zero value after dot

**Comment by Dianaaiym** [comment]
Send Controller

For values above 1000(in base currency) show cents for available balance

**Comment by abdrasulov** [comment]
After discussing we decided to leave available balance as is. Instead, apply the same logic for the max button in fiat mode
