### ISSUE TITLE
Add new erc20 token

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2426]
**Compound**

- name: Compound
- symbol: COMP
- contract address: 0xc00e94cb662c3520282e6f5717214004a7f26888
- decimals: 18
- Project website: https://compound.finance/ 
- Total Supply: 10.000.000 COMP
- Launch Date: 04/03/2020

https://etherscan.io/token/0xc00e94cb662c3520282e6f5717214004a7f26888
https://www.cryptocompare.com/coins/comp/overview

- icon: @TalgatNurdinov

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=17323%3A25
