### ISSUE TITLE
Allow connecting to my own full node/electrumx server

### ISSUE THREAD

**Issue by Giszmo** [horizontalsystems/unstoppable-wallet-android#2435]
The current configuration window is misleading with its privacy promises and lacking with its information.

It's great I can select these things before creating a wallet! Privacy cannot be re-gained once lost and other wallets clearly lack in this part but:

Please explain what you mean with "API" and "From Blockchain". I suppose "API" means that the wallet connects to electrumx instances run by the provider and "From Blockchain" connects to random Bitcoin full nodes? Both is terrible for privacy and to claim that "From Blockchain" was "More Private" is wrong. Half of "full nodes" are run by blockchain analysis companies that will collect your users' BIP37 filters or address lists together with their IP address if TOR is not used. This means that Blockchain Analysis companies and their clients (exchanges, law enforcement, tax authorities, ...) are able to correlate all transactions of each user as belonging to the same wallet, so one use of a KYC service will lead to all their addresses being tied to a national ID.

I prefer to leak my wallet addresses to one company dedicated to privacy than to different random full nodes all the time. In the worst case, they also sell the data but in the best case they don't.

There are currently two possible fixes to this:

1. Connect to your own full node using SSL
1. Download compact block filters like in neutrino and then full blocks over TOR from distinct full nodes, ideally with low time correlation.

Compact block filters would be the preferred default for those who don't have a full node.
Own full nodes would considerably improve the performance.

**Comment by horsys** [comment]
@Giszmo thanks for the input, we will get working on this in 0.17, next couple of weeks

You're right, nether restore options are privacy-safe. The current implementation was out first step towards enabling flexible restore options. We tried to ensure the restore option always works by integrating 'from blcokchain' capability. It makes sense to expand this now to enable restoring from your own node. In the future we are planning to add support for neutrino protocol. It was a bit raw when we checked it last few months back.
