### ISSUE TITLE
Settings >> About layout redesign

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2438]
- [x] apply minor changes on Settings Tab. Should have following format:

-- Manage Wallets
-- Security Center
-- App Status (more level up, currently located in Contact)

-- Based
-- Language 
-- Mode
-- Experimental

-- Contact
-- Tell Friends
-- Terms

- [x] apply new layout to Terms page @TalgatNurdinov 

The Unstoppable wallet is built for those looking to invest and store cryptocurrencies in a private and independent manner.

It's a non-custodial, peer-to-peer wallet where only the user has control over funds. It doesn't collect any data and keeps user independent by not locking his/her wallet to a specific wallet app. 

The Unstoppable wallet is fully open-source and anyone can confirm that the app works exactly as it claims to.

We built Unstoppable for ourselves as the available solutions were not up to par. Both from engineering and usability perspective we believe this wallet to be significantly ahead of alternative products.

button1: site link
button2: GitHub link

Terms:

-- I went through the Academy section of this app and got familiar with the fundamental aspects of storing cryptocurrencies.

-- I have backed up the private key(s) for my wallets that were shown to me in a form of 12-24 words. I understand that these private keys are stored on my smartphone and not elsewhere.

-- I understand that only the owner of my private key(s) can access and spend funds on my wallet and therefore these keys should never be shared with anyone.

-- I understand that I will need my private keys in order to restore access to my funds should I loose my phone or if the app malfunctions. Without my private keys it will be impossible to recover access to my wallet.

-- I understand that passing my phone to untrusted entities or leaving the wallet app without safe PIN lock may potentially endanger the safety of my funds.

-- I understand that jail breaking (rooting) my phone, installing third party apps from unknown sources, keeping the operating system outdated can potentially endanger the safety of my funds.

-- I understand there may be undiscovered software issues in the code powering this wallet app which may lead to unexpected behavior or the app malfunctioning.

Thank you for choosing this wallet!

**Comment by TalgatNurdinov** [comment]
**Settings Page**
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=9365%3A3405

**Terms**
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=17338%3A57322

**Comment by TalgatNurdinov** [comment]
Unchecked boxes icons should be grey
