### ISSUE TITLE
Add a coin guide to the bottom of the coin chart screen

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#2449]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=9731%3A5406

**Comment by herou** [comment]
@TalgatNurdinov Can I work on this?

**Comment by esengulov** [comment]
This issues was dropped from the list due to lack of team consensus on the importance/need of the described feature
