### ISSUE TITLE
Add new erc20 token - Ampleforth

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2451]
**Ampleforth**

- name: Ampleforth
- symbol: AMPL
- contract address: 0xd46ba6d942050d489dbd938a2c909a5d5039a161
- decimals: 9
- Project website: https://www.ampleforth.org/
- Total Supply: 38,207,563.0 AMPL
- Launch Date: 14/06/2019

https://etherscan.io/token/0xd46ba6d942050d489dbd938a2c909a5d5039a161
https://www.cryptocompare.com/coins/ampl/overview

- icon: @TalgatNurdinov

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=17756%3A10
