### ISSUE TITLE
Add erc20 tokens: ren, renBTC, renBCH, renZCASH

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2460]
**Ren**

- name: Ren
- symbol: REN
- contract address: 0x408e41876cccdc0f92210600ef50372656052a38
- decimals: 18
- Project website: https://renproject.io/
- Total Supply: 999,999,633 REN
- Launch Date: 31/12/2017

https://etherscan.io/token/0xd46ba6d942050d489dbd938a2c909a5d5039a161
https://www.cryptocompare.com/coins/ren/overview

- icon: @TalgatNurdinov 

**renBTC**

- name: renBTC
- symbol: RENBTC
- contract address: 0xeb4c2781e4eba804ce9a9803c67d0893436bb27d
- decimals: 8
- Project website: https://renproject.io/
- Total Supply: n/a
- Launch Date: n/a

https://etherscan.io/token/0xeb4c2781e4eba804ce9a9803c67d0893436bb27d
ex rates not available

- icon: @TalgatNurdinov 

**renBCH**

- name: renBCH
- symbol: RENBCH
- contract address: 0x459086f2376525bdceba5bdda135e4e9d3fef5bf
- decimals: 8
- Project website: https://renproject.io/
- Total Supply: n/a
- Launch Date:  n/a

https://etherscan.io/token/0x459086f2376525bdceba5bdda135e4e9d3fef5bf
ex rates: not available

- icon: @TalgatNurdinov 

**renZEC**

- name: renZEC
- symbol: RENZEC
- contract address: 0x1c5db575e2ff833e46a2e9864c22f4b22e0b37c2
- decimals: 8
- Project website: https://renproject.io/
- Total Supply: n/a
- Launch Date: n/a

https://etherscan.io/token/0x1c5db575e2ff833e46a2e9864c22f4b22e0b37c2
ex rates: not available

- icon: @TalgatNurdinov

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=17921%3A41
