### ISSUE TITLE
Desktop support and other questions...

### ISSUE THREAD

**Issue by tuqueque** [horizontalsystems/unstoppable-wallet-android#2463]
Hello, I stumbled upon this awesome project when I added a new repository in my F-droid app store and I'm delighted to see an open source multi-currency wallet!

I really like the Exodus wallet, because it's probably the only standalone, multi-currency, multi platform, non-custodial wallet out there... but sadly, is not open source and little by little it feels more and more like a commercial product from a faceless company than a tool to bank the unbanked... Until you appeared in the horizon!

The 3 things that I LOVE about this new project are:

1.- Being open source.
2.- Connecting through TOR.
3.- Support bc1 and lc1 address format (BIP 84) for BTC and LTC

Having said that, I have a million questions (and a couple suggestions) and it would be great to have answers to at least most of them, so here we go:

1.- Do you plan to support the desktop? Particularly Linux (my system).
2.- Do you plan to add more cryptocurrencies to the list? (IOTA, NANO, SC...).
3.- Could you add Unstoppable directly to the F-droid store without having to add (and trust) another 3rd party repository?
4.- Do you plan to add some kind of exchange service between cryptocurrencies?
5.- Could you consider making a more "verbose" status window/panel/banner that show what's going on under the hood? (TOR/connection statistics, blockchains sync progress and so on... I noticed my phone was downloading a lot of data and I could only guess it was synchronizing blockchains, but I could only guess).
6.- Do you plan to remain free and open source or do you plan to go commercial/paid and/or closed source at some point?

I'm not expecting all these things to come to Unstoppable next week... but maybe add a few other cryptocurrencies this year, initial desktop support by the end of 2021... and so on.

Thank you in advance and I really hope this project becomes my replacement to Exodus soon enough!

**Comment by esengulov** [comment]
Hi @tuqueque 

thanks for the kind words!

>v1.- Do you plan to support the desktop? Particularly Linux (my system).

We would like to have the desktop version as well. We haven't started on this yet though and no plans for next few months as there are a. number of critical features still missing)

> 2.- Do you plan to add more cryptocurrencies to the list? (IOTA, NANO, SC...).

Yes, the next on the line is ZCash. We are yet to look into IOTA and NANO, generally we work with blockchains that already support (or working on the way to support) lite clients. 

> 3.- Could you add Unstoppable directly to the F-droid store without having to add (and trust) another 3rd party repository?

We will check .... not sure as we don't have any experience with F-droid store.

> 4.- Do you plan to add some kind of exchange service between cryptocurrencies?we are currently integrating Uniswap V2. Expecting to release it end of next week or week after. Once that in place the app would allow decentralized ETH <-> ERC 20 swaps. We also currently looking into integrating REN protocol for decentralized BTC <-> ERC20 swaps. If all goes well, both feature will be online within 3-4 weeks.

> 5.- Could you consider making a more "verbose" status window/panel/banner that show what's going on under the hood? (TOR/connection statistics, blockchains sync progress and so on... I noticed my phone was downloading a lot of data and I could only guess it was synchronizing blockchains, but I could only guess).

It's already there, the section called App Status and can be located under Settings >> Contact. We are currently redesigning it bit. The goal is exactly what you asked to give a clear idea of what's happening under the hood.

> 6.- Do you plan to remain free and open source or do you plan to go commercial/paid and/or closed source at some point?

No plan for closed source. As you can see we are not just keeping the code public, the entire development workflow is on Github from discussions, design to release processes. We plan on integrating paid features on top of the standard feature set. Fo instance, we are currently working on on-chain analytics (number of transactions, volume, active addresses etc) and to view those from within the app a crypto payment (or holding UNSTOPPABLE token) would be required. We are yet to figure out the preferred way)

Let me know if something is unclear or if have any other suggestions

**Comment by tuqueque** [comment]
**1.- We would like to have the desktop version as well. We haven't started on this yet though and no plans for next few months as there are a number of critical features still missing)**

	I completely understand… I have to admit that currently this is a "deal breaker" for me, but at least on mobile I'll recommend Unstoppable to my friends.

**2.- Yes, the next on the line is ZCash. We are yet to look into IOTA and NANO, generally we work with blockchains that already support (or working on the way to support) lite clients.**

	Lets hope more and more projects add light client support to their pipeline.

**3.- We will check .... not sure as we don't have any experience with F-droid store.**

	Please, this one is also almost a "deal breaker" for me, having to trust an unknown repository for such a critical app in my system is very uncomfortable for me… Maybe the following conversation about supporting F-droid for another project might help you or get you in contact with the right people: https://github.com/Gedsh/InviZible/issues/5

**4.- we are currently integrating Uniswap V2. Expecting to release it end of next week or week after. Once that in place the app would allow decentralized ETH <-> ERC 20 swaps. We also currently looking into integrating REN protocol for decentralized BTC <-> ERC20 swaps. If all goes well, both feature will be online within 3-4 weeks.**

	That sounds like a great start!… I hope more conversion options appear, but this will be a fantastic start!

**5.- It's already there, the section called App Status and can be located under Settings >> Contact. We are currently redesigning it bit. The goal is exactly what you asked to give a clear idea of what's happening under the hood.**

	That's great!… Although, that placement inside the "contact" section in the settings is terrible!… That App Status option should be in its own section (Settings > App Status) and yes, a redesign is also necessary. There's a lot of information, but some coloring and visual separation of assets would be very helpful.

**6.- No plan for closed source. As you can see we are not just keeping the code public, the entire development workflow is on Github from discussions, design to release processes. We plan on integrating paid features on top of the standard feature set. Fo instance, we are currently working on on-chain analytics (number of transactions, volume, active addresses etc) and to view those from within the app a crypto payment (or holding UNSTOPPABLE token) would be required. We are yet to figure out the preferred way).**

That's a reasonable way of generating income for you. I have no problem with that, as long as you remain open source and keep the "bank the unbanked", "privacy/anonymity first" and "non-custodial" mottos as your main and inalienable goals!

Exodus (and other wallets) have made partnerships with the likes of Changelly or Shapeshift to offer their users decentralized exchange capabilities into their wallets. You could try the same, although I wouldn't make partnerships with those exchanges because of their KYC/AML bullshit. I'd suggest you to check partnerships with https://stealthex.io/ , https://godex.io/ or https://bitconvert.app/ since they (claim to) offer anonymous exchanges. These could be other reasonable ways of generating income while respecting your user's privacy and anonymity.

Greets!

**Comment by esengulov** [comment]
@tuqueque thanks for the followup and recommendations! 
We will look into FDroid shortly

**Comment by trymeouteh** [comment]
Would love to see a desktop app someday!

**Comment by nahuhh** [comment]
+1 for F-droid inclusion

**Comment by bradley-r** [comment]
> Would love to see a desktop app someday!

> +1 for F-droid inclusion

Seconded on both counts; I'd love a (Linux) desktop version, especially considering Unstoppable is one of the few fully open-source wallets that supports (in my case, at least) a suitably wide array of coins. Would also like F-Droid availability, especially considering my current and all future mobile devices are/will be completely rid of Google services. In the case it's of any use, the [F-Droid documentation appears](https://f-droid.org/en/docs/FAQ_-_App_Developers/) quite useful, especially the [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/).

**Comment by trymeouteh** [comment]
When the desktop app gets started on development, please design it to also work on linux phones and tablets by having a mobile friendly GUI. This way once the desktop app is finished it can support Windows, Mac, Linux and mobile Linux devices.
