### ISSUE TITLE
Add new erc20 token - Balancer, DIA, Monolith

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2478]
**1. Balancer**

- name: Balancer
- symbol: BAL
- contract address: 0xba100000625a3754423978a60c9317c58a424e3D
- decimals: 18
- Project website: https://balancer.finance/
- Total Supply: 35,725,000 BAL
- Launch Date: 20/06/2020
https://etherscan.io/token/0xba100000625a3754423978a60c9317c58a424e3D
https://www.cryptocompare.com/coins/bal/overview

- icon: @TalgatNurdinov

**2. DIA Token**

- name: DIA
- symbol: DIA
- contract address: 0x84ca8bc7997272c7cfb4d0cd3d55cd942b3c9419
- decimals: 18
- Project website: https://diadata.org/ 
- Total Supply: 200,000,000 DIA
- Launch Date: 27/11/2019

https://etherscan.io/token/0x84cA8bc7997272c7CfB4D0Cd3D55cd942B3c9419
ex rates not available

- icon: @TalgatNurdinov 

**3. TrustSwap Token**

- name: TrustSwap
- symbol: Swap
- contract address: 0xCC4304A31d09258b0029eA7FE63d032f52e44EFe
- decimals: 18
- Project website: https://trustswap.org/ 
- Total Supply: 100,000,000 SWAP
- Launch Date: 09/07/2020

https://etherscan.io/token/0xCC4304A31d09258b0029eA7FE63d032f52e44EFe
ex rates not available

- icon: @TalgatNurdinov 

**4. Monolith**

- name: Monolith
- symbol: TKN
- contract address: 0xaaaf91d9b90df800df4f55c205fd6989c977e73a
- decimals: 8
- Project website: https://monolith.xyz/
- Total Supply: 39,406,760 TKN
- Launch Date: 25/04/2017
https://etherscan.io/token/0xaaaf91d9b90df800df4f55c205fd6989c977e73a
https://www.cryptocompare.com/coins/tkn/overview
- icon: @TalgatNurdinov

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=20601%3A73
