### ISSUE TITLE
Add new erc20 token -  DOS Network, Parachute

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2483]
**1. DOS Network**

- name: DOS Network
- symbol: DOS
- contract address: 0x0A913beaD80F321E7Ac35285Ee10d9d922659cB7
- decimals: 18
- Project website: https://dos.network/
- Total Supply: 949,292,114 DOS
- Launch Date: 11/03/2019
https://etherscan.io/token/0x0A913beaD80F321E7Ac35285Ee10d9d922659cB7
https://www.cryptocompare.com/coins/dos/overview
xrate not available

- icon: @TalgatNurdinov

**2. Parachute**

- name: Parachute
- symbol: PAR
- contract address: 0x1beef31946fbbb40b877a72e4ae04a8d1a5cee06
- decimals: 18
- Project website: https://www.parachutetoken.com/
- Total Supply: 999,628,334 PAR
- Launch Date: n/a
https://etherscan.io/token/0x1beef31946fbbb40b877a72e4ae04a8d1a5cee06

xrate not available

- icon: @TalgatNurdinov

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=20613%3A44
