### ISSUE TITLE
When sending erc20 token, two transactions appear on the tx tab

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2484]
![2020-08-13 14 58 52](https://user-images.githubusercontent.com/22589457/90115227-9b9ea900-dd75-11ea-8b8d-a1812791bff5.jpg)

**Comment by rafaelekol** [comment]
I moved transaction filter from app to EthereumKit. @Dianaaiym you should test this issue again.
