### ISSUE TITLE
System pin requirement: After setting the system pin, cannot log into app

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2497]
To reproduce:

- disable system pin
- install Unstoppable app and open it (a warning screenshot will be shown) go to background
- setting the system pin
- go to app 

Samsung A20s

**Comment by tmedetbekov** [comment]
Fixed by reloading the warning screen https://github.com/horizontalsystems/unstoppable-wallet-android/pull/2508
