### ISSUE TITLE
Crash each time after having entered the passcode

### ISSUE THREAD

**Issue by erAck** [horizontalsystems/unstoppable-wallet-android#2509]
Installed from F-Droid repo. It worked for a while but now crashes each and every time after I entered the last digit of the passcode after start. Unusable.

**Comment by rafaelekol** [comment]
Did you change your screen password, after you started using Unstoppable Wallet?

**Comment by erAck** [comment]
> Have you changed your screen password, after you started using Unstoppable Wallet?

No.
