### ISSUE TITLE
DAPP browser

### ISSUE THREAD

**Issue by mcooos** [horizontalsystems/unstoppable-wallet-android#2514]
When can DAPP browser be supported? Is there any plan?

**Comment by mcooos** [comment]
还有DOT

**Comment by mcooos** [comment]
When importing ERC wallet, the token of other ERC under this address will be automatically brought out

**Comment by esengulov** [comment]
> When importing ERC wallet, the token of other ERC under this address will be automatically brought out

Hi there, we are planning to add this feature in the future. We need more time for that)

**Comment by esengulov** [comment]
> When can DAPP browser be supported? Is there any plan?

No plan for having an all purpose DApp browser but instead we are planning to offer standalone apps for top DeFi services/protocols. We might also add additional features (STAKING, BORROWING, LENDING ETC) for some currencies int he wallet app.

**Comment by esengulov** [comment]
> When is dot / KSM accessible?

We haven't had a chance to study/integrate polkadot yet but I hope we will get on it soon.
