### ISSUE TITLE
Add new erc20 token to the wallet - Akropolis, Aave

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2529]
**Akropolis**

- name: Akropolis
- symbol: AKRO
- contract address: 0x8ab7404063ec4dbcfd4598215992dc3f8ec853d7
- decimals: 18
- Project website: https://akropolis.io/
- Total Supply: 4,000,000,000
- Launch Date: 06/07/2019
https://etherscan.io/token/0x8ab7404063ec4dbcfd4598215992dc3f8ec853d7
https://www.cryptocompare.com/coins/akro/overview

ex rates not available

icon: @TalgatNurdinov

**Aave**

- name: Aave
- symbol: LEND
- contract address: 0x80fB784B7eD66730e8b1DBd9820aFD29931aab03
- decimals: 18
- Project website: https://aave.com/
- Total Supply: 1,299,999,942.0
- Launch Date: 15/08/2017
https://etherscan.io/token/0x80fB784B7eD66730e8b1DBd9820aFD29931aab03
https://www.cryptocompare.com/coins/lend/overview

icon: @TalgatNurdinov

**Comment by writyou** [comment]
ADD Add AKRO - Erc20 token OCT

name: OneChanceToken
symbol: OCT
contract address: 0xcc1146994253356ec40930f9753c6b97869cc530
decimals: 2
Project website: https://onechance.io/
Total Supply: 6,000,000,000
Launch Date: 08/08/2018
https://etherscan.io/token/0xcc1146994253356ec40930f9753c6b97869cc530
LOGOurl:https://gateway.pinata.cloud/ipfs/QmQ9D2MvXmbJnDJNF6wbTVSXcBQ5zkJ2V79Ttn2KvNCMb3

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=21534%3A24

**Comment by Dianaaiym** [comment]
> ADD Add AKRO - Erc20 token OCT
> 
> name: OneChanceToken
> symbol: OCT
> contract address: 0xcc1146994253356ec40930f9753c6b97869cc530
> decimals: 2
> Project website: https://onechance.io/
> Total Supply: 6,000,000,000
> Launch Date: 08/08/2018
> https://etherscan.io/token/0xcc1146994253356ec40930f9753c6b97869cc530
> LOGOurl:https://gateway.pinata.cloud/ipfs/QmQ9D2MvXmbJnDJNF6wbTVSXcBQ5zkJ2V79Ttn2KvNCMb3

Hi,

It looks like a new project, we need to learn more about it.
You can add this token yourself (go to Balance tab -> Add coins )

**Comment by Dianaaiym** [comment]
![2020-09-04 13 16 58](https://user-images.githubusercontent.com/22589457/92210693-08a6e980-eeb1-11ea-8d09-ebc5c44898f1.jpg)

when trying to send LEND
