### ISSUE TITLE
It is suggested to add a search function to the token list. It is not easy to find more tokens

### ISSUE THREAD

**Issue by mcooos** [horizontalsystems/unstoppable-wallet-android#2532]
It is suggested to add a search function to the token list. It is not easy to find more tokens

**Comment by mcooos** [comment]
For currency, whether you can use JSON to add freely, such as https://github.com/Uniswap/token-lists

**Comment by esengulov** [comment]
> For currency, whether you can use JSON to add freely, such as https://github.com/Uniswap/token-lists

thanks, we we will add Uniswap's token list in version 0.17

**Comment by esengulov** [comment]
Issue Merged Into https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2570
