### ISSUE TITLE
import private key……

### ISSUE THREAD

**Issue by mcooos** [horizontalsystems/unstoppable-wallet-android#2542]
- [ ] When importing other existing wallets that are not created on unstoppable, they cannot be imported through private key or keystore
- [ ] It is recommended to add, because I can import the existing wallet directly without creating a new one
- [ ] In addition, only one ERC wallet address can be created at present. Can multiple ERC wallet addresses be created at the same time? It is suggested that multiple addresses can be created, and there are notes for different addresses

![image](https://user-images.githubusercontent.com/70244469/92136197-4d456d00-ee3e-11ea-8aff-47aa6e787496.png)
![image](https://user-images.githubusercontent.com/70244469/92136226-58000200-ee3e-11ea-887a-68ec392ca5e6.png)
![image](https://user-images.githubusercontent.com/70244469/92136266-65b58780-ee3e-11ea-9f70-5c3d370da99a.png)

**Comment by esengulov** [comment]
this is already being worked on
