### ISSUE TITLE
Swap : Approvals / Allowances improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2546]
- [ ] Allow user to change approve amount (see image below)

- [ ] click on edit may open a simple popup with input filed and numbed allowing user to adjust the amount as needed.

- [ ] change text to the version below: 
> You should grant permission to a smart contract to swap given token on your behalf. This permission sets amount that can be used by a smart contract. It doesn't affect your balance but requires a small fee to execute approval transaction. 
> 
> While it may be done on demand before each trade, it's cheaper to approve higher amount in advance for us in future trades.

- [ ] @Dianaaiym note above text changes 

![IMG_2054](https://user-images.githubusercontent.com/8611762/93756016-2cdf2600-fc26-11ea-916a-cadc0c27b0ec.jpg)

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=22688%3A55301
