### ISSUE TITLE
re-evaluate current font on the app

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2554]
- [ ] The numbers on balance / transactions tab fee a bit squashed.

- [ ] It's been also reported that on some devices on app open there is a visible change from default Android OS font to ours.

**Comment by writyou** [comment]
@TalgatNurdinov 
Could you give me the UI(https://www.figma.com/) permission to download or modify the cutaway?
We can design and add some applications based on this, my figma account wsd@ziranyidu.com

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=8871%3A747

**Comment by writyou** [comment]
@TalgatNurdinov add Cross chain switching
https://www.figma.com/file/iXKJAaMl6LkiUleRTF66tT/Cross-chain-switching
