### ISSUE TITLE
Implement accelerate/cancel feature for eth based transactions

### ISSUE THREAD

**Issue by mNizhurin** [horizontalsystems/unstoppable-wallet-android#2565]
When transaction is stuck in pending state, user might need to rebroadcast it with same or higher fee.
User can accelerate only one oldest pending transaction

related issues: 
https://github.com/horizontalsystems/ethereum-kit-android/issues/132
https://github.com/horizontalsystems/ethereum-kit-android/issues/131
https://github.com/horizontalsystems/ethereum-kit-android/issues/130

ex. of drop-replaced tx: https://etherscan.io/tx/0xa59d1da57e80aee221ea3aea6ea5f5dd71850d9505ad1554090fa871ed288759

**Comment by esengulov** [comment]
UI / UX guidelines:

- [ ] SpeedUp and Cancel buttons should appear in TX info, only for pending transactions
- [ ] SpeedUp and Cancel buttons should appear on all TX types (send, approve, contract call except SWAP transaction types)
- [ ] the client should double recheck status of the pending TX when user clicks on Cancel/SpeedUp buttons.
-- let user proceed to confirm screen only if original TX still pending.
-- If transaction has been confirmed then show following UI alert (This transaction has been already confirmed and can no longer be accelerated or cancelled.) with OK button.  
- [ ] SpeedUp option uses same transaction and same nonce, but with higher fee
- [ ] Cancel  option creates new empty transaction to self and same nonce, but with higher fee
- [ ] On  speedup/cancel confirmation screens, the client should again check the status of original TX and let user proceed only if TX is pending
- [ ] @Dianaaiym add info texts to both speedup/cancel screens. These texts will explain the purpose/terms of the transaction to the sender.

**Comment by TalgatNurdinov** [comment]
<img width="750" alt="Screen Shot 2021-08-11 at 10 41 48" src="https://user-images.githubusercontent.com/42367908/128970702-46ceaf67-6aa6-4ebe-849f-fbb082d9194b.png">
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=39764%3A320096

**Comment by esengulov** [comment]
@omurovch  @Dianaaiym 

- [ ] update info texts for speedup / cancel controllers 

SpeedUp

`This action will attempt to invalidate previous transaction by resending it with a higher fee. If the original transaction remains pending when a new one sent there is s a high chance (not guaranteed) that it will be invalidated and replaced. Only one of these two transactions will be included in the blockchain.`

Cancel

`This action will attempt to invalidate previous transaction by resending as a new 0 ETH transaction to self. If the original transaction remains pending when a new one sent there is s a high chance (not guaranteed) that it will be invalidated and replaced. Only one of these two transactions will be included in the blockchain.`
