### ISSUE TITLE
Add Token Search to various modules

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#2570]
- [x] balance tab coin manager as per suggestion https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2532
- [x] restore wallet coin selector
- [x] create wallet coin selector
- [x] swap controller.

**Comment by esengulov** [comment]
@rafaelekol noticed an issue on swap controller

steps to reproduce

1. open swap
2. search token
3. click done.
4. keyboard remains visible on swap controller
