### ISSUE TITLE
Fix the bottom navigation, don't slide.Page content can slide left and right

### ISSUE THREAD

**Issue by writyou** [horizontalsystems/unstoppable-wallet-android#2572]
Fix the bottom navigation, don't slide.Page content can slide left and right

**Comment by rafaelekol** [comment]
You mean content, shouldn't slide?

**Comment by writyou** [comment]
![mmexport1600060447239](https://user-images.githubusercontent.com/6188238/93046551-a5753e00-f68c-11ea-8887-1afb13b3fb78.jpg)

**Comment by writyou** [comment]
> Do you mean that. content shouldn't slide?

Look at the picture below

**Comment by rafaelekol** [comment]
Thats how navigation designed to work. At the bottom we have main navigation, which you. can browse by clicking on relative icon, or by swiping these pages(Balance, Transactions, Academy, Settings).
Academy screen has filters at the top. And by clicking on filter button you just get filtered content. Maybe the problem is these filter buttons looks like navigation buttons?

**Comment by writyou** [comment]
> I am sorry, my English is not good.

The main navigation at the bottom switches the page by clicking;
The sub navigation on the top can slide and switch, so the operation experience will be better

**Comment by writyou** [comment]
@rafaelekol 
Could you give me the UI(https://www.figma.com/) permission to download or modify the cutaway?
We can design and add some applications based on this, my figma account wsd@ziranyidu.com

**Comment by esengulov** [comment]
@mNizhurin @TalgatNurdinov

**Comment by TalgatNurdinov** [comment]
> @rafaelekol
> Could you give me the UI(https://www.figma.com/) permission to download or modify the cutaway?
> We can design and add some applications based on this, my figma account [wsd@ziranyidu.com](mailto:wsd@ziranyidu.com)

I sent a invite to our Figma document, but we can't grant you editing rights, you can create your own files and share them with us, and then we will add your corrections to our document

**Comment by esengulov** [comment]
@rafaelekol we had a chat with @TalgatNurdinov and we feel there is little benefit in removing right/light swipe navigation option from the primary nav bar. 

Our recommendation is to bring it back and revisit the idea when/if the swipe navigation is added to individual tab that have tab filters at the top i.e. Academy and Transactions. Unless you disagree we would like to have it back.

**Comment by TalgatNurdinov** [comment]
@writyou we disabled swiping between tabs, but we can't swipe to switch filters at now. We will done it on the next step
