### ISSUE TITLE
Transaction not displayed or unsuccessful

### ISSUE THREAD

**Issue by mcooos** [horizontalsystems/unstoppable-wallet-android#2575]
When the mnemonic words are restored to the wallet, the transaction records will not be displayed;
After the transfer, the transaction record is always in dynamic progress, but the blockchain browser shows that it has succeeded.

![image](https://user-images.githubusercontent.com/70244469/93010187-26b0d000-f5bc-11ea-83e2-a13104a04f58.png)

![image](https://user-images.githubusercontent.com/70244469/93010211-7ee7d200-f5bc-11ea-90f4-c2a7068f0315.png)

**Comment by esengulov** [comment]
> When the mnemonic words are restored to the wallet, the transaction records will not be displayed;
> After the transfer, the transaction record is always in dynamic progress, but the blockchain browser shows that it has succeeded.
> 
> ![image](https://user-images.githubusercontent.com/70244469/93010187-26b0d000-f5bc-11ea-83e2-a13104a04f58.png)
> 
> ![image](https://user-images.githubusercontent.com/70244469/93010211-7ee7d200-f5bc-11ea-90f4-c2a7068f0315.png)

Hi there

The image shows that transaction is in progress. The fact that it shows two bars colored means transaction already in blockchain but the wallet wait until 12 blocks has passed to show transaction as final/completed. Maybe that's what confused you.... :)  the wallet behavior is expected in this case, although I can see how it may confuse readers. We will look into it.

**Comment by Dianaaiym** [comment]
dublicated #2547

**Comment by Dianaaiym** [comment]
This issue was fixed with web socket ticket
