### ISSUE TITLE
Add new page and change texts on wallet welcome screen

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2578]

**Comment by kansalt** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=22219%3A801
изменения в дизайне интро скринах:
- [ ] добавить новый начальный скрин (лого+текст)
- [ ] заменить главные картины на 2 (Invest Wisely) и на 4 (Stay Private) скринах
- [ ] заменить текста на всех скринах 
- [ ] изменить цвета текста подзаголовка с “Light Grey” на “Grey”
- [ ] добавить на 5й скрин лого (Unstoppable Wallet)
