### ISSUE TITLE
Fastlane structure partly broken (translations)

### ISSUE THREAD

**Issue by IzzySoft** [horizontalsystems/unstoppable-wallet-android#2588]
Could you please check [this Fastlane directory](https://github.com/horizontalsystems/unstoppable-wallet-android/tree/master/fastlane/metadata)? All the languages need to be moved inside the `android` directory – and `description.txt` would be needed to rename to `full_description.txt`. Thanks!

**Comment by abdrasulov** [comment]
Hi @herou,

This ticket you can take care of if you are interested

**Comment by herou** [comment]
> Hi @herou,
> 
> This ticket you can take care of if you are interested

@abdrasulov You have it #2863

**Comment by licaon-kter** [comment]
can you move all the languages from https://github.com/horizontalsystems/unstoppable-wallet-android/tree/master/fastlane/metadata to https://github.com/horizontalsystems/unstoppable-wallet-android/tree/master/fastlane/metadata/android ?
