### ISSUE TITLE
EOS accounts that cause errors can also be imported

### ISSUE THREAD

**Issue by writyou** [horizontalsystems/unstoppable-wallet-android#2589]
EOS imports the account and key, but does not verify the matching between the account and the key，EOS accounts that cause errors can also be imported

![image](https://user-images.githubusercontent.com/6188238/93729371-c5f64880-fbf6-11ea-8787-0af72e7fcd1f.png)

**Comment by writyou** [comment]
Construction:
The user directly imports the private key or mnemonic words, deduces the public key, and then finds the account name through the public key. If there are multiple account names, the user can choose which one to import. If there is only one account name, the wallet will be imported directly by default.

**Comment by Dianaaiym** [comment]
should be applied for iOS too
