### ISSUE TITLE
Swap : Apply Updated layout to Swap Controller

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2594]
- [ ] allow user to adjust TX cost for Swap transaction.
- [ ] provide means to the user to reverse currency bought/sold , preferable in a single click.
- [ ] provide means to the user to enter swap amount in base currency.
- [ ] currently, when swapping from ETH to token the allowance entry is shown but not relevant. decide on it.
- [ ] when user clicks on approve, the numbed should collapse and user should be taken back to balance tab. 
- [ ] rename 'Cancel' button on navigation bar to 'Close'
- [ ] display fiat value on each coin cell in 'select token' controller

text changes:

- [ ] change texts 'Minimum Got' to 'Guaranteed Amount'
- [ ] change 'Maximum Paid' to 'Maximum Spend'

**Comment by TalgatNurdinov** [comment]
### New Swap Layouts 

**UI improvements**

- [ ] Card cell
- [ ] Moved "Select Token" button
- [ ] Yellow "Select Token" button
- [ ] Switch button between cards
- [ ] Spinner and price positions
- [ ] Grey "approve" buttons for the differences with the yellow "proceed"
- [ ] Show hud after clicking swap


https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=22077%3A10557
