### ISSUE TITLE
design advanced settings for Uniswap swap controller

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2598]
Refer to settings and options available on Uniswap's Settings page. We need a place to add following settings somewhere:

-  price slippage : there is a default option, as well as other presets.

- deadline setting to specify validity period for the swap

- option to select the swap beneficiaries which is different from the address of the sender

Errors:

slippage settings:

- [ ] if user tries to enter an amount lower than 0.01% then show 'Your transaction is likely to fail.'
- [ ] if user tries to enter an amount higher than 20% then show 'Max. allowed value 20%.'

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=23276%3A321

**Comment by TalgatNurdinov** [comment]
Need to add highlighted state of advanced settings cell. Cell that have Lawrence backgrounds highlighted state called Lawrence Pressed. We should to use for highlighting of transparent cell Lawrence pair.

Icons colors of the top (info/close) seems like Yellow, instead Jacob.
