### ISSUE TITLE
Adding FCM dragged in Firebase Analytics

### ISSUE THREAD

**Issue by IzzySoft** [horizontalsystems/unstoppable-wallet-android#2601]
With the latest release you've added Push Notifications – unfortunately deciding to use Google's non-Free FCM for that (so your app is no longer "free/libre software").

FCM has an intended trap-door that, if the developer does not explicitly disables it, it drags in Firebase Analytics (Google loves to collect data). Can you please at least remove that again? Apps dealing with sensitive data as the user's finances should rather not involve 3rd party analytics.

If it would be possible to have a separate build flavor (and corresponding APK at `releases/`) shipping entirely without those Google libraries, that would be very welcome.

Thanks!

**Comment by esengulov** [comment]
Thanks for heads up, we will have this addressed in the next release. 

If we can't come up with something your suggestion to provide different releases with without push service might be an option. Thanks, stay tuned.

Add the issue to current sprint

**Comment by IzzySoft** [comment]
Thanks, that sounds great! Looking forward to your update here (no pressure, just "happy expectance" :smile:).

**Comment by nk-the-crazy** [comment]
> With the latest release you've added Push Notifications – unfortunately deciding to use Google's non-Free FCM for that (so your app is no longer "free/libre software").
> 
> FCM has an intended trap-door that, if the developer does not explicitly disables it, it drags in Firebase Analytics (Google loves to collect data). Can you please at least remove that again? Apps dealing with sensitive data as the user's finances should rather not involve 3rd party analytics.
> 
> If it would be possible to have a separate build flavor (and corresponding APK at `releases/`) shipping entirely without those Google libraries, that would be very welcome.
> 
> Thanks!

Temporary basic solution was to completely disable Firebase-Analytics from Firebase-Project settings and disabling analytics from android client.

Farther plans are to use Android Dynamics Features and completely isolate all firebase dependencies.

Thanks for Heads Up !!!

**Comment by IzzySoft** [comment]
Thanks a lot! Just for clarification: are the libraries still included with the app (just "silenced") at the moment? Because then my library scanner will still complain, so I should add a note to the description why that AntiFeature is still mentioned…

**Comment by nk-the-crazy** [comment]
> Thanks a lot! Just for clarification: are the libraries still included with the app (just "silenced") at the moment? Because then my library scanner will still complain, so I should add a note to the description why that AntiFeature is still mentioned…

Libraries are still included, we just disabled Analytics via config (Firebase Dependency isolation with the Dynamic-Features are future plans).

**Comment by IzzySoft** [comment]
OK, thanks. Guess that applies to v0.17, according to the "automation note" above my last comment? I've put a note to the metadata and look forward to v0.17 then. AFAIK, disabling Firebase Analytics as described by you should remove the corresponding library, so my scanner should inform me it's gone then. :crossed_fingers:
