### ISSUE TITLE
Wallet restore via API does not restore balance (BTC)

### ISSUE THREAD

**Issue by erAck** [horizontalsystems/unstoppable-wallet-android#2608]
After having upgraded to 0.16.0 (F-Droid) it told me it couldn't access the secret storage because screen password was changed (no, it was not; but maybe because of OS updates?) and I had to restore the wallet. Ok, did so, but the balance was 0.00 and the transactions list was empty.

Today installed 0.16.1 but same.
Switched to Blockchain Restore under Settings -> Security Center -> Privacy and after waiting 2 hours or so the correct balance amount appeared and transactions listed.

**Comment by Dianaaiym** [comment]
> After having upgraded to 0.16.0 (F-Droid) it told me it couldn't access the secret storage because screen password was changed (no, it was not; but maybe because of OS updates?) and I had to restore the wallet. Ok, did so, but the balance was 0.00 and the transactions list was empty.
> 
> Today installed 0.16.1 but same.
> Switched to Blockchain Restore under Settings -> Security Center -> Privacy and after waiting 2 hours or so the correct balance amount appeared and transactions listed.

Hi,

Where did you find .apk file (F-droid) for Unstoppable Wallet?

**Comment by Dianaaiym** [comment]
We were unable to reproduce this issue. Since there are no steps for reproduce, we remove the ticket from 0.17

**Comment by erAck** [comment]
> Where did you find .apk file (F-droid) for Unstoppable Wallet?
Current version 0.16.2 is from the IzzyOnDroid F-Droid Repository, https://android.izzysoft.de/repo/apk/io.horizontalsystems.bankwallet
I'd say the other two were as well..
