### ISSUE TITLE
change ethereum fees to max

### ISSUE THREAD

**Issue by wolfenix** [horizontalsystems/unstoppable-wallet-android#2631]
Hi, I just created a ERC20 Token for my client and added that token to the wallet, It is a crowdsale/ICO Token and when while using metamask with high fees, every transaction is getting cleared but while sending ethereum from this wallet to the contract address, each and every transaction is failing, plz help me, if I don't change the ethereum fees to 0.009 atleast, my client will seriously kill me, I can't find any way to change the ethereum sending fees.

Plz provide a system there to set a custom fees.

Plz help me, I need immediate help, I'm begging to you.

**Comment by wolfenix** [comment]
each and every transaction is getting failed and each transaction is going with 0.002436 eth as fees, I need to change this to 0.009 eth.

The contract address - https://etherscan.io/address/0x839412659f6d8e11b8c54665795eefa1f25d7ee1

Trust me sir, it's not just me, this is a huge issue of this wallet, provide us a way to change the max eth fee through the code for permanently.

**Comment by esengulov** [comment]
> each and every transaction is getting failed and each transaction is going with 0.002436 eth as fees, I need to change this to 0.009 eth.
> 
> The contract address - https://etherscan.io/address/0x839412659f6d8e11b8c54665795eefa1f25d7ee1
> 
> Trust me sir, it's not just me, this is a huge issue of this wallet, provide us a way to change the max eth fee through the code for permanently.
> 
> (5-10-2020) Edit - *I just tested the wallet by sending just ethereum and tether through my this wallet to other unstoppable wallet, 8/10 transaction got failed, almost every transaction is failing just because of gas/fees issue, every transaction showed "Out of gas error" on etherscan, Damn.
> 
> Plz give me a way to set a permanent fees of 0.009 eth in the wallet code plz.

thanks for heads up, one of us will look into it soon!

**Comment by wolfenix** [comment]
Damn, You guys are really amazing and fast, I'm impressed.

there can be 2 things that can be done, either you can add custom gas setting for the user so that he can customize and set gas fees manually or just provide a way to change transaction fees in the code itself just like crypto echanges, except all that huge fees will go to the ethereum network for a faster transaction and not any entity.

and plz try to fix this as soon as your team can, not just my client buy many people using this wallet are facing this issue.

**Comment by esengulov** [comment]
> Damn, You guys are really amazing and fast, I'm impressed.
> 
> there can be 2 things that can be done, either you can add custom gas setting for the user so that he can customize and set gas fees manually or just provide a way to change transaction fees in the code itself just like crypto echanges, except all that huge fees will go to the ethereum network for a faster transaction and not any entity.
> 
> and plz try to fix this as soon as your team can, not just my client buy many people using this wallet are facing this issue.

Thanks, yep, this is a priority issue for us, we're looking into it now.

So, first could you please tell us what version of the app you're using? We suspect that your version is slightly behind. Our latest version should already be estimating gas limit values correctly. We have double checked.

here is a transaction we have just sent, https://etherscan.io/tx/0xd63afb1eb6bc42e49838abf9b269cfec272cb99f423bd87de54d05333206b270

**Comment by esengulov** [comment]
Oh and we will try to add custom gas setting to Ethereum transactions in the next (0.17) release. It may get delayed until 0.18 if there are some issues along the way.

**Comment by wolfenix** [comment]
That's hell of an amazing response, wow, you guys are pros, well I'm using 0.12 and I've been using that since May 2020, and actually this is the first time I created a Crowdsale contract for somebody otherwise all the transactions were really fine for just token to token or eth to eth transfers, contract interaction takes some extra eth to get verified quickly.

So as I can see that you sent a transaction and it was successful, may I know which version you used?
and when should I expect for the next version (0.17) to be released, I'm really excited to see a custom fee option, Make sure to put both options i.e; Custom Gas limit set and Custom Gas Price, that would be one heck of a amazing.

**Comment by esengulov** [comment]
May I know the reason behind using the version 0.12 as we are currently at 0.16 :)

You should be able to update your app to version 0.16 unless you are using an unsupported Android OS. Once you update to the latest version the sending should work without issues. You will also find a lot of enhancements not present in your current app!

let me know

**Comment by wolfenix** [comment]
Actually I was not really aware of this fee situation until I created the wallet for my client after june, when ethereum fees was like crazy hell, and I was not aware about your latest releases, and I really feel awful now.
I just tested the new version and goddamn, It works crazy awesomely good, damn I  Lovethe new version, and that swap feature....OOoohhh Mannnn, I love it!!!!

btw I've raised another ticket on how to remove that academy/guide system from the app, kindly reply to that, I need to remove that for my version.

**Comment by esengulov** [comment]
sounds good! followed on other issues as well  ;)
