### ISSUE TITLE
How to Remove Academy/guide section from the app?

### ISSUE THREAD

**Issue by wolfenix** [horizontalsystems/unstoppable-wallet-android#2643]
Hi, how can I remove the guide section from app completely, I really don't want it, Can you tell me the code to hide it?
and where should i put or remove that code to remove the academy section?

**Comment by esengulov** [comment]
> Hi, how can I remove the guide section from app completely, I really don't want it, Can you tell me the code to hide it?
> and where should i put or remove that code to remove the academy section?

we can add a button to hide/remove it from Settings, would that work?

**Comment by wolfenix** [comment]
Sure, is there any code that i have to add or remove from the kotlin files to hide or remove his as of now?

**Comment by wolfenix** [comment]
can i get a solution for this plz?

**Comment by wolfenix** [comment]
plz help

**Comment by herou** [comment]
If this ticket is done, please close it.
