### ISSUE TITLE
Handle errors statuses for failed transactions 

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2679]
https://etherscan.io/tx/0xf56ff39f6eadf02202ca04bb8a3779e26e14f11d6234621268c4e1c59a0f45fd
 'UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT'

**Comment by esengulov** [comment]
merged into https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2727
