### ISSUE TITLE
ADD uniswap  liquidity Create a pair Add Liquidity

### ISSUE THREAD

**Issue by writyou** [horizontalsystems/unstoppable-wallet-android#2693]
Add uniswap  liquidity Create a pair Add Liquidity，Customizable reward token

**Comment by esengulov** [comment]
> Add uniswap liquidity Create a pair Add Liquidity，Customizable reward token

Are you looking for a way to add liquidity to Uniswap from Wallet app? if so, we are planning to look at it in the near future AFTER we are done with all swap-related features. While we support basic swap functionality we are yet to integrate advanced settings
