### ISSUE TITLE
add https://wallet.loomx.io/wallet

### ISSUE THREAD

**Issue by writyou** [horizontalsystems/unstoppable-wallet-android#2695]
add https://wallet.loomx.io/wallet
API https://loomx.io/developers/en/loom-yaml.html#ethereumuri

**Comment by esengulov** [comment]
thanks, we will check it out

**Comment by herou** [comment]
@esengulov Do you mind if I work on this ticket? Any tips?

**Comment by esengulov** [comment]
> @esengulov Do you mind if I work on this ticket? Any tips?

Hi, I don't mind
Do you know what the original submitted meant here? I couldn't understand it from the links. Is it about adding Loomx support?
