### ISSUE TITLE
Interface optimization highlights Market

### ISSUE THREAD

**Issue by writyou** [horizontalsystems/unstoppable-wallet-android#2696]
Transaction records can be put into wallet management or secondary page;
Take out the market, put it in the current trading record position, highlight the market changes, similar to the exchange market; users pay more attention to the currency price.
![image](https://user-images.githubusercontent.com/6188238/96563635-be5cb900-12f4-11eb-9cc1-9bddc30cb099.png)

**Comment by esengulov** [comment]
@TalgatNurdinov check this out, we can discuss this during our next meeting

@writyou we haven't finalized the placements for various elements and likely to change them as we keep integrating new features. thanks for the feedback!
