### ISSUE TITLE
design full tx info for Zcash

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2704]
here is the data that available to the client from public block explorer API:

https://explorer.zcha.in/v2/mainnet/transactions/2333d7bbed290b5b56e709b72c9d3fadccb6466fda526069b4fe06cc1d9a6a06

- [ ] when done erasing the issue for implementation

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=23406%3A7
