### ISSUE TITLE
Zcash improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2726]
- [ ] support for transparent addresses
- [x] birthday indication on wallet restore
- [ ] sapling data download on restore (or initial wallet sync). If wallet disabled /enabled the payload will have to be redownloaded
- [ ] sending to self currently disabled... work on that.
- [ ] when restoring wallet the coin manager screen shown with just one coin. Perhaps for such cases we should just auto enabled the coin without taking user to the screen.
- [ ] configure zcash client to work hs node.

**Comment by Troglodactyl** [comment]
Also support for viewing Zcash transaction memos.
