### ISSUE TITLE
distribute Unstoppable wallet app via Fdroid

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2729]

**Comment by rafaelekol** [comment]
https://gitlab.com/fdroid/rfp/-/issues/1547

**Comment by rafaelekol** [comment]
To continue, we need to get rid off Firebase dependency first.

**Comment by Dianaaiym** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9105
