### ISSUE TITLE
Fix typo: "lose", not "loose"

### ISSUE THREAD

**Issue by GlenCooper** [horizontalsystems/unstoppable-wallet-android#2759]
I saw this typo on my Pixel3a XL.  Probably exists on other platforms too.  "Loose" should be changed to the correct spelling, "lose" here.

![IMG-1779](https://user-images.githubusercontent.com/967793/98866637-c70c5f00-245c-11eb-9f2f-51276156d671.JPG)

**Comment by esengulov** [comment]
> I saw this typo on my Pixel3a XL. Probably exists on other platforms too. "Loose" should be changed to the correct spelling, "lose" here.
> 
> ![IMG-1779](https://user-images.githubusercontent.com/967793/98866637-c70c5f00-245c-11eb-9f2f-51276156d671.JPG)

thank you! will fix shortly

**Comment by Dianaaiym** [comment]
> I saw this typo on my Pixel3a XL. Probably exists on other platforms too. "Loose" should be changed to the correct spelling, "lose" here.
> 
> ![IMG-1779](https://user-images.githubusercontent.com/967793/98866637-c70c5f00-245c-11eb-9f2f-51276156d671.JPG)

Hi, thanks! Good point! It has already been fixed, new version coming soon

**Comment by GlenCooper** [comment]
Updated app from Google Play Store.  Confirmed corrected.

Thanks!
