### ISSUE TITLE
Allow using third-party keyboard

### ISSUE THREAD

**Issue by eternaltyro** [horizontalsystems/unstoppable-wallet-android#2765]
I think the third-party keyboard check is a little overreaching. I have deliberately installed a third-party keyboard (Anysoft) precisely because I don't trust the built-in default keyboard of my phone. I don't want to outsource trust to my apps exclusively. Additionally, I want to be able to use auto-fill from my password manager too.

So, I think there should be a configuration option that allows the use of third-party keyboards even while typing in sensitive strings like private key phrases.

**Comment by abdrasulov** [comment]
Hi @eternaltyro. Thanks for your feedback. That's a good point. We'll discuss it with a team.

**Comment by TalgatNurdinov** [comment]
Redesigned warning dialogs 

<img width="338" alt="Screen Shot 2020-11-18 at 16 38 23" src="https://user-images.githubusercontent.com/42367908/99520014-caec3400-29bc-11eb-82dc-14da1087c3b4.png">

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=23550%3A479

**Comment by esengulov** [comment]
> Redesigned warning dialogs
> 
> <img alt="Screen Shot 2020-11-18 at 16 38 23" width="338" src="https://user-images.githubusercontent.com/42367908/99520014-caec3400-29bc-11eb-82dc-14da1087c3b4.png">
> 
> https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=23550%3A479

Approved Text:

It looks like your device uses a non-default keyboard. Unstoppable recommends using default keyboard on your device as third party keyboards can potentially collect and expose users' input data.

Click 'Skip' button if you would like to keep using your preferred keyboard.

Buttons: SKIP /

**Comment by rafaelekol** [comment]
In case user selects Skip button, this selection should be stored in SharedPreferences. Hence, next time he gets in Restore screen, we shouldn't show him this alert again.

**Comment by TalgatNurdinov** [comment]
With approved text
<img width="360" alt="image" src="https://user-images.githubusercontent.com/42367908/99527396-f247fe80-29c6-11eb-8fc7-7e6b104dd71c.png">

**Comment by herou** [comment]
The fragment_alert_dialog file is used in many dialogs (not only the dialog which warns the user regarding the keyboard). If I change this file, all the other dialog design would change. Do we want this? If not, what do you suggest? I would suggest creating a new custom dialog only for this case.

**Comment by rafaelekol** [comment]
Yes, you should create new custom layout for this case.

**Comment by herou** [comment]
@rafaelekol Can I have the translation for these texts:

1-It looks like your device uses a non-default keyboard. Unstoppable recommends selecting default keyboard on your device as third party keyboards can potentially collect and expose users' input data.

Click 'Skip' button if you would like to keep using your preferred keyboard.

2- Skip

3- Select

**Comment by rafaelekol** [comment]
Just add the English text to strings.xml file. Translations will be added later.

**Comment by herou** [comment]
@rafaelekol please check the PR #2827
