### ISSUE TITLE
Documentation and tips!

### ISSUE THREAD

**Issue by herou** [horizontalsystems/unstoppable-wallet-android#2787]
Hello, 

I saw the project and I would like to contribute to it. Do you have any documentation for them who likes to contribute?

Any suggestions for issues to take care of?

**Comment by esengulov** [comment]
> Hello,
> 
> I saw the project and I would like to contribute to it. Do you have any documentation for them who likes to contribute?
> 
> Any suggestions for issues to take care of?

Hi Herou,

you're welcome to contribute

Check out https://github.com/horizontalsystems/unstoppable-wallet-android/blob/master/CONTRIBUTE.md
