### ISSUE TITLE
Looking for ticket to work on

### ISSUE THREAD

**Issue by herou** [horizontalsystems/unstoppable-wallet-android#2793]
Hello,

As a new contributor on this repo, I am looking for tickets to start on. I see that most of the tickets are in waiting for testing.

Any suggestion?

**Comment by rafaelekol** [comment]
Hi,
We are planning to give you this ticket(https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2765). I asked our designer to prepare design for this ticket. As soon as it will be ready I will update that ticket and leave a comment here.

**Comment by rafaelekol** [comment]
Ticket is updated and ready, https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2765

**Comment by herou** [comment]
This ticket needs to be closed.
