### ISSUE TITLE
get all ERC20 balances for the address

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2804]
- [x] start working on implementation @nk-the-crazy 
- [x] needs UI elements @TalgatNurdinov 
- [ ] refer to iOS team for imdeplementation details, https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/2298

**Comment by nk-the-crazy** [comment]
Did some research, and found : 
 * No fully complete and working Subgraph was found for Erc2 Balance operations.
 * Until mainnet launch we cant guarantee data integrity

So for now we should delay this issue until we ensure for fully working Graph Network.

Furthermore , we should do research on Geth/Parity GraphQL and EthQL support.
Infura already has support for GraphQL via [EthQL](https://github.com/ConsenSys/ethql)

**Comment by nk-the-crazy** [comment]
<img width="772" alt="Screen Shot 2020-12-02 at 1 58 56 PM" src="https://user-images.githubusercontent.com/11713346/100844912-ac029d00-34a6-11eb-83f2-a878264b5b55.png">

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=23779%3A3

**Comment by Dianaaiym** [comment]
- [ ] wrong icon used for bep2 tokens
- [ ] not all tokens with balance appear
