### ISSUE TITLE
Master does not compile!

### ISSUE THREAD

**Issue by herou** [horizontalsystems/unstoppable-wallet-android#2806]
@Dianaaiym You have added some new translations which cause this issue!

The problem is found in the French file.

![image](https://user-images.githubusercontent.com/13895430/99561591-697d9280-29c7-11eb-9f82-eae507861361.png)

**Comment by Dianaaiym** [comment]
Hi! Thank you, good point!  I will fix it soon.

**Comment by herou** [comment]
I am already on it.

**Comment by herou** [comment]
@Dianaaiym #2810 PR. Check it and merge. If something wrong let me know. I would like to merge my first PR to this awesome repo.

**Comment by Dianaaiym** [comment]
fixed #2813
