### ISSUE TITLE
Walletconnect supports multiple DAPP logins at the same time

### ISSUE THREAD

**Issue by writyou** [horizontalsystems/unstoppable-wallet-android#2824]
Walletconnect supports multiple DAPP logins at the same time

**Comment by abdrasulov** [comment]
Can you please clarify if you like the app to support multiple DAPP logins at the same time?

**Comment by mcooos** [comment]
> Can you please clarify if you like the app to support multiple DAPP logins at the same time?


yes
We also need to call the token of erc20
Including signature and transaction, authorization and other methods

**Comment by abdrasulov** [comment]
We've discussed it with a team. We decided to implement this feature in the near future.

Thanks for your feedback @writyou, @mcooos
