### ISSUE TITLE
add uniswap pool

### ISSUE THREAD

**Issue by writyou** [horizontalsystems/unstoppable-wallet-android#2825]
add uniswap pool

**Comment by abdrasulov** [comment]
Hi @writyou. Thanks for the feedback!

We will discuss this and all other feature requests in the near future. Could you please provide more detailed information and (or) use cases for them?

**Comment by mcooos** [comment]
> Hi @writyou. Thanks for the feedback!
> 
> We will discuss this and all other feature requests in the near future. Could you please provide more detailed information and (or) use cases for them?

![image](https://user-images.githubusercontent.com/70244469/100591724-1c87ad80-3331-11eb-9538-9bf678f5ef5c.png)
![image](https://user-images.githubusercontent.com/70244469/100591869-52c52d00-3331-11eb-9af1-8f0a6c9a172e.png)

https://app.uniswap.org/#/pool

**Comment by esengulov** [comment]
@mcooos 

this feature has been added to the roadmap. We have a number of large features to deliver before we can get started on this feature.
