### ISSUE TITLE
ZEC seed not working

### ISSUE THREAD

**Issue by clayt0nk** [horizontalsystems/unstoppable-wallet-android#2826]
I have tried many times, I have had someone proof read my typing with the two phones side-by-side, but new phone will not accept old phone's ZEC seed. When I hit the "Next" button I get just "Incorrect key". There is only one ZEC in the wallet. If any dev would like to pursue this, I would be happy to provide a private screen shot of the two phones side-by-side.

**Comment by Dianaaiym** [comment]
> I have tried many times, I have had someone proof read my typing with the two phones side-by-side, but new phone will not accept old phone's ZEC seed. When I hit the "Next" button I get just "Incorrect key". There is only one ZEC in the wallet. If any dev would like to pursue this, I would be happy to provide a private screen shot of the two phones side-by-side.

Hi Claytonk,

Thank you for the feedback!  Please check if you insert a space at the end, this may cause a error 'incorrect key'

**Comment by gmale** [comment]
This seems to be related to https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2830

**Comment by omurovch** [comment]
> I have tried many times, I have had someone proof read my typing with the two phones side-by-side, but new phone will not accept old phone's ZEC seed. When I hit the "Next" button I get just "Incorrect key". There is only one ZEC in the wallet. If any dev would like to pursue this, I would be happy to provide a private screen shot of the two phones side-by-side.

Hi @clayt0nk,

It seems you have a typo in word(s) you are entering. Please, make sure words exist in this [https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt](list)

**Comment by clayt0nk** [comment]
All words are in that list. I feel it is unlikely that this is a transcription problem. I am a competent touch typist with a USB keyboard, the source wallet is sitting right beside the new wallet, I can verify every letter that goes down with my eyes without looking at the keyboard. I was also very careful this time to ensure there were no extra spaces anywhere. Of course it is always possible that something is going on that I am for some reason completely blind to, but really, my spelling skills are also good, it gets more and more difficult for me to credit the possibility that my fingers are to blame here.

What about stale / out-of-date libraries on an old Android that has not been updated since December 2018? Could that be an issue (on the "new" phone where I am entering the seed)?

My offer to share a photo of the failed seed replication with a dev still stands.

**Comment by omurovch** [comment]
At the moment entered mnemonic phrase is validated as follows: 
1. correct number of words - for Zcash it should be 24 
2. valid words from wordlist

Actually it is a bit strange. Can you please give more information regarding the following:

- How many words are you entering?
- Are you importing mnemonic phrase from Unstoppable wallet or is it other wallet?

**Comment by clayt0nk** [comment]
I am entering 24 words directly from another Unstoppable wallet into a new Unstoppable wallet, both Android. They sit side-by-side right in front of me, without any intermediate medium. Strange indeed. Cloning wallets to multiple devices is something I do all the time, this is an absolutely routine thing I am doing here.

**Comment by Dianaaiym** [comment]
> I am entering 24 words directly from another Unstoppable wallet into a new Unstoppable wallet, both Android. They sit side-by-side right in front of me, without any intermediate medium. Strange indeed. Cloning wallets to multiple devices is something I do all the time, this is an absolutely routine thing I am doing here.

Hi @clayt0nk ,

This is our support email - hsdao@protonmail.ch, write to us here and we will continue to solve the problem.

Best regards,
Diana
HS Team

**Comment by clayt0nk** [comment]
hsdao@protonmail.ch, I then sent to hsdao@protonmail.com, did you receive?

**Comment by esengulov** [comment]
> [hsdao@protonmail.ch](mailto:hsdao@protonmail.ch) bounced, I then sent to [hsdao@protonmail.com](mailto:hsdao@protonmail.com), did you receive?

Thanks, issue well received and in progress, we are trying to debug it. Thank you!

**Comment by clayt0nk** [comment]
So over two or three days I had tried to replicate (typed in from scratch) the seed numerous times and failed every time. Then there was a pause of a couple days, and I tried again. And it worked, twice in succession on two different Androids. Days after that, neither wallet had succeeded in syncing to the point of showing my balance.

So today I wiped one of those wallets, re-entered the seed, it failed the first time but I immediately spotted the word that was wrong, and it worked after fixing that. This time there was a brand new "wallet birthday" field, and it was not at all obvious what to do with it. I came to the conclusion (more like a guess) that a block height was probably called for, but a cursory search resulted in no place where I could associate ZEC block height and calendar date. So I just typed in a block height of 1,000,000. A couple hours later, the new wallet was synced and showing the correct balance.

The obvious culprit to point at here for my previous problems is my own fingers, but, like I said before, I am a good speller, an excellent touch typist, and I have handled wallet seeds many times before without these difficulties. So, personally I do not find that my own finger problems are a very credible explanation here. That said, I have no idea what else might have caused this.

**Comment by abdrasulov** [comment]
Hi @clayt0nk,

Thanks for your detailed explanations.

We tried to reproduce the issue several times with different mnemonic words. There were no errors. We also checked the source code for the validation logic. As @omurovch mentioned before, at the moment it has only 2 checks - the words count that should be equal to 24 for zcash, and that every word exists in the dictionary. We don't have any other suggestions on why this issue may occur. So based on your feedback, we decided to add a new type of validation. Now when a user enters a mnemonic the app will check every word. It will highlight incorrect word once it is entered. We're planning to release the next version of the app soon. It would be great if you check it on an upcoming version of the app.

As for the syncing issue, could you please let us know if there were a loading spinner icon or red error icon?

As for the wallet birthday field, that is a good point. We will discuss it with a team.

**Comment by clayt0nk** [comment]
Happy to retest on a new version.....

> As for the syncing issue, could you please let us know if there were a loading spinner icon or red error icon?

It would have been a "loading" spinner around the "Z" icon, if there had been an actual error message I am pretty confident I would have noted that. It did not stop, it just kept spinning forever, seemingly with little or no progress. Note that I am in Asia where bandwidth and sometimes even connectivity can be iffy. Just as a general note to any blockchain people in Europe and N.America: many people seem to assume that the whole world has the same access to bandwidth as you do. I think I heard Vitalik say on a podcast that he thought he could sync the whole Ethereum chain in a day, at home. I would expect such a project to take weeks of 24/7 here, and I would not be surprised to fail in the attempt.

**Comment by esengulov** [comment]
> Happy to retest on a new version.....
> 
> > As for the syncing issue, could you please let us know if there were a loading spinner icon or red error icon?
> 
> It would have been a "loading" spinner around the "Z" icon, if there had been an actual error message I am pretty confident I would have noted that. It did not stop, it just kept spinning forever, seemingly with little or no progress. Note that I am in Asia where bandwidth and sometimes even connectivity can be iffy. Just as a general note to any blockchain people in Europe and N.America: I have the impression that many people assume that the whole world has the same access to bandwidth as you do. For instance I think I heard Vitalik say on a podcast that he was confident he could sync the whole Ethereum chain in a day, at home. I would expect such a project to take weeks of 24/7 here, and I would not be surprised to fail in the attempt. If there is no well-connected Asian mirror for whatever endpoint this wallet is connecting to, do not be surprised if there are problems.

Hi there,

re: sync issue
It's hard to say at this point whether the slow sync is due to connectivity issues. From my end, sometimes it's fast and sometimes it's slow. We would like to get more feedback on this and are going to continue testing this. Some of us are in Asia as well and we don't have any issues with syncing at this point. That said, we are going to upgrade the server hosting a Zcash node that's used for syncing restored wallets with the blockchain.

re: words list
At one point in the past I experienced same issue as well where I was fairly certain that words were entered correctly but the wallet still showed them incorrect. However, this was few months back and haven't experienced it since then. It's a strange issue indeed... please let us know should you notice it again.
