### ISSUE TITLE
Settings page redesign

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#2834]
- [x] Move academy to the settings page 

- [x] Add social networks section
       - t.me/unstoppable_announcements
       - twitter.com/UnstoppableByHS
       - reddit.com/r/UNSTOPPABLEWallet/

- [x] About app page include cells below:
       - Contact (support mail)
       - App Status
       - Terms
       - Rate Us

**Design Ticket:**
https://github.com/horizontalsystems/HS-Design/projects/7#card-49524717

**Layouts:**
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=23692%3A15

**Comment by Dianaaiym** [comment]
need to remove telegram support from 'contact'
