### ISSUE TITLE
Execution failed for task ':app:processDebugGoogleServices'.

### ISSUE THREAD

**Issue by foo2021** [horizontalsystems/unstoppable-wallet-android#2840]
When i run 'app'，android studio Build Output show me errors：

Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'io.horizontalsystems.bankwallet.dev'

What shall i do?

**Comment by abdrasulov** [comment]
Hi, @foo2021. Could you please share the info about the Android Studio version and device?

**Comment by foo2021** [comment]
@abdrasulov ok

Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1246M
Cores: 4
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: com.thoughtworks.gauge, com.vladsch.idea.multimarkdown, org.ollide.java2smali, com.intellij.marketplace, org.jetbrains.kotlin

AVD : Nexus 5X API 28

**Comment by abdrasulov** [comment]
I could not reproduce the issue using the same versions of Android Studio and AVD. Please try to clean and rebuild the project (Build -> Clean Project, Build -> Rebuild Project).

**Comment by foo2021** [comment]
OK, I'll try! Thank you!
