### ISSUE TITLE
Dash update support research

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2861]
- Dashpay (blockchain usernames)
- Dash Platform (developer platform with the world's first decentralized HTTP API)

**Comment by abdrasulov** [comment]
The dash kit works well with a new DashCore (v.0.16.1.1 at the moment). We don't need to make any changes.

As for the new features, like usernames and contact-list, it is implemented on the Evonet network. They are planning to release it on the Testnet at the end of the year. 

We'll create appropriate tickets if we decide to have these new features.

**Comment by Dianaaiym** [comment]
duplicated #2908
