### ISSUE TITLE
Navigation menu layout suggestions

### ISSUE THREAD

**Issue by mcooos** [horizontalsystems/unstoppable-wallet-android#2865]
Main menu:
Asset, market, DAPP or Academy (optional), settings:

1、Assets: including balances and transactions.
2、Market: including quotations of various currencies, which can be directly entered into decentralized transactions, such as swap.
3、DAPP:web3 Browser, defi related DAPP, and college course.
4、Settings: all settings related to Wallet

**Comment by TalgatNurdinov** [comment]
Thank you for your suggestions! We are working on it. Could you create questions about ux/ui in the design repository next time?

https://github.com/horizontalsystems/HS-Design/issues
