### ISSUE TITLE
add Dapp

### ISSUE THREAD

**Issue by bxxasn** [horizontalsystems/unstoppable-wallet-android#2870]
When will DAPPS be supported?  like CoinBase Wallet

WalletLink 
 WalletConnect

Thanks

**Comment by esengulov** [comment]
> When will DAPPS be supported? like CoinBase Wallet
> 
> WalletLink
> WalletConnect
> 
> Thanks

Wallet Connect already supported ! :)

**Comment by bxxasn** [comment]
What about the others
Especially dapps
Thanks

**Comment by bxxasn** [comment]
Using browser to operate DAPP

**Comment by esengulov** [comment]
> Using browser to operate DAPP

we are working towards providing support for all major protocols (aka DApps). it needs more time as we are not keen on going the standard route of 'DApp browser' provided by the existing wallet apps.
