### ISSUE TITLE
Add a new coin

### ISSUE THREAD

**Issue by Gmlogy** [horizontalsystems/unstoppable-wallet-android#2874]
Hi there, 

is there any possibility to Add new Coins (not tokens) if yes, is there any documentation or guide to Add new Coin to the wallet.
thank you

**Comment by esengulov** [comment]
> Hi there,
> 
> is there any possibility to Add new Coins (not tokens) if yes, is there any documentation or guide to Add new Coin to the wallet.
> thank you

support for additional blockchain needs to be first integrated into the app itself. there is documentation yet but if you are a developer you can explore support for existing coins and use it as a reference to add new ones.
