### ISSUE TITLE
Need to prepare source for market tab

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#2880]
- [x] Total M.Cap
- [x] Total Volume
- [x] Bitcoin Dominance
- [x] Total DeFi M.Cap
- [x] Total Locked Value in DeFi (USD)

- [x] Coin Info (Details)

Global Markets |  Top markets | Coin-Info
:--------------:|:-------------:|:-------------
<img width="180" alt="Screen Shot 2021-02-01 at 12 11 27 PM" src="https://user-images.githubusercontent.com/11713346/106421321-b3362f00-6486-11eb-9bf2-c823b90f3f21.png"> |<img width="180" alt="Screen Shot 2021-02-01 at 12 11 44 PM" src="https://user-images.githubusercontent.com/11713346/106421345-bc270080-6486-11eb-85c7-2d07c13d62d0.png">|<img width="180" alt="Screen Shot 2021-02-01 at 12 08 08 PM" src="https://user-images.githubusercontent.com/11713346/106421050-31de9c80-6486-11eb-8e2c-16e8b6e3ca4e.png">

**Comment by nk-the-crazy** [comment]
We could use Free API 
api.coinpaprika.com along with UniswapGraph and binance.exchange api.

**Comment by nk-the-crazy** [comment]
For
**Global market info:**
coinpaprika.com
**Top Markets:**
coingecko.com

**Top Defi Markets:**
Uniswap GraphQL

**Comment by nk-the-crazy** [comment]
**Coin-Info**
coingecko.com
