### ISSUE TITLE
Invalid state of Switch for Passcode

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#2906]
**Steps to Reproduce**

1. Go to Settings -> Security Center
1. Enable Passcode. It opens Set Passcode Screen
1. Click to back

**Expected Behavior**

The Passcode switch should stay disabled

**Incorrect Behavior**

The Passcode switch is enabled

**Comment by herou** [comment]
@abdrasulov That's true, I was able to reproduce it. I will work on this one if you do not mind. Please, assign it to me.

**Comment by rafaelekol** [comment]
@herou we fixed this issue by ourselves. Sorry )
