### ISSUE TITLE
Amounts inputs Redesign

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#2914]

**Comment by herou** [comment]
@abdrasulov Do you have already the design?

**Comment by abdrasulov** [comment]
Not yet. @TalgatNurdinov will provide it soon

**Comment by TalgatNurdinov** [comment]
@herou here is design issue, it's done 
https://github.com/horizontalsystems/HS-Design/issues/105#issuecomment-742314346

**Comment by herou** [comment]
@abdrasulov Please assing it to mem @TalgatNurdinov Can you provide to me the old design.

**Comment by herou** [comment]
@abdrasulov Could you please tell me which file contains the old design? Since I am not very familiar with the project I do not know which input file should I redesign.

**Comment by abdrasulov** [comment]
Hi @herou, it's out of habit :) The issue is related to fields in a form that are used for amounts. They are shown with calculated value in the currency if the user inputs the amount in coins. And vice versa. As I remember, there are 2 layout files with amount input field:

* `app/src/main/res/layout/view_amount_input.xml`
* `app/src/main/res/layout/view_card_swap.xml`

You can start with these files now. I will check with a team if there are any other layouts.

**Comment by herou** [comment]
@abdrasulov @TalgatNurdinov Currently there is a switch button and I see that we need to remove it. How the switch is going to happen if we remove it?

**Comment by herou** [comment]
> * view_card_swap

I checked and it seems only those two files need to be redesigned.

**Comment by abdrasulov** [comment]
The converted amount should act as a switch button.

**Comment by herou** [comment]
@abdrasulov @Dianaaiym This issue should be close because its PR has been merged.

**Comment by TalgatNurdinov** [comment]
Wrong paddings in input, @herou please check the sizes. Also increase clickable area (from divider to the bottom)

<img width="709" alt="Screen Shot 2021-01-05 at 17 31 18" src="https://user-images.githubusercontent.com/42367908/103641364-d8b14500-4f7b-11eb-8830-67d04deb6923.png">

**Comment by herou** [comment]
@TalgatNurdinov Do you want to set a fixes size 85dp for the height ??

**Comment by TalgatNurdinov** [comment]
> @TalgatNurdinov Do you want to set a fixes size 85dp for the height ?? If the top padding of the second text input would 8dp and the bottom 12 than it would not look centered.

Yes, it for easy clicking

**Comment by herou** [comment]
@TalgatNurdinov Check this PR: #3043

**Comment by TalgatNurdinov** [comment]
also need to add view when rate is not loaded
<img width="388" alt="Screen Shot 2021-01-08 at 14 56 41" src="https://user-images.githubusercontent.com/42367908/103994819-bc064e80-51c1-11eb-9815-8f1f0f016233.png">

**Comment by herou** [comment]
@TalgatNurdinov May I do not get you. What do you mean by "rate is not loaded"?  Can you give a brief explanation?

**Comment by TalgatNurdinov** [comment]
> @TalgatNurdinov May I do not get you. What do you mean by "rate is not loaded"? Can you give a brief explanation?

It happens when you have some problems with connection, if coin rate is not loaded we can't convert inserted value. At this time we need show that switching is disabled

**Comment by TalgatNurdinov** [comment]
@rafaelekol can you change the color of second amount to Bran instead Grey if rate is available?
