### ISSUE TITLE
Show memo in Transaction Info for Binance, Eos and Zcash

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#2916]
Show memo of the transaction if it exists and is not empty as designed here https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=23950%3A81965

**Comment by herou** [comment]
@abdrasulov Can you write a short description of what should be done here?

**Comment by abdrasulov** [comment]
@herou, I've updated the description.

**Comment by herou** [comment]
@abdrasulov Does Bitcoin transaction show the memo information?

**Comment by rafaelekol** [comment]
@herou sorry I didn't see that you are already on this issue, you can move on.

**Comment by abdrasulov** [comment]
@herou, there is no memo field in any type of transaction at the moment. It should be added.

**Comment by herou** [comment]
@abdrasulov Assign this to me.

**Comment by herou** [comment]
@abdrasulov Please, check this PR: #2982

**Comment by abdrasulov** [comment]
Hey @herou. Looks great! I left one little comment. Please check PR
