### ISSUE TITLE
Branch version/0.18 can not build!

### ISSUE THREAD

**Issue by herou** [horizontalsystems/unstoppable-wallet-android#2919]
I pulled the latest changes and I could not build the project as it is shown below: 

![version_0_18](https://user-images.githubusercontent.com/13895430/101545164-23549700-39a7-11eb-8282-28cf08abb297.png)

**Comment by abdrasulov** [comment]
That's strange. We could not reproduce it. Can you please try to build a new branch version/0.19?

**Comment by herou** [comment]
Invalid cache and restart solve this issue, I raised this issue because I was able to build the master branch. I am closing this one.
