### ISSUE TITLE
Optimize custom views

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#2938]
**What's the problem**

* There are custom views, for instance, AddressInputView.
* They are extended from ConstraintLayout or LinearLayout.
* They inflate some layout file. For AddressInputView it's `view_input_address.xml`
* The `view_input_address.xml` layout root tag is also ConstraintLayout.
* It resulted in double nested ConstraintLayout

**How to resolve**

Use merge tag in all such layout files. Check SwapAllowanceView for reference.

**Comment by abdrasulov** [comment]
Hi @herou. Please take this ticket, if you're interested.

**Comment by herou** [comment]
@abdrasulov Please assing it to me because I can not self assign it.

**Comment by herou** [comment]
@abdrasulov Please, take a look: #2948

**Comment by herou** [comment]
@Dianaaiym @abdrasulov This one should be closed

**Comment by abdrasulov** [comment]
![image](https://user-images.githubusercontent.com/5284600/102450461-a2f5fc00-4060-11eb-94c9-7c91c045b273.png)

@herou, there are some issues with layouts after replacing layouts with merge tags. We've found out that the root tags of layout files had some properties set before. After replacing them with the `merge` tag those properties are ignored. It can be resolved by setting properties in:
1. The custom view programmatically
1. Or in the places where the custom views are used

We should decide how to resolve it.

Also, there are some custom views left. Here is the list:

```
BackupWordView.kt  (1 usage found)
    11 inflate(context, R.layout.view_backup_word_text, this)
ConfirmationPrimaryView.kt  (1 usage found)
    14 inflate(context, R.layout.view_confirmation_primary_item_view, this)
ConfirmationSecondaryView.kt  (1 usage found)
    16 inflate(context, R.layout.view_confirmation_secondary_item_view, this)
ConfirmationSendButtonView.kt  (1 usage found)
    14 inflate(context, R.layout.view_button_with_progressbar, this)
FeeSelectorView.kt  (1 usage found)
    28 inflate(context, R.layout.view_send_fee, this)
FullTransactionInfoItemView.kt  (1 usage found)
    15 inflate(context, R.layout.view_transaction_full_info_item, this)
InputWithButtonsView.kt  (1 usage found)
    36 inflate(context, R.layout.view_input_with_buttons, this)
SettingItemWithCheckmark.kt  (1 usage found)
    13 inflate(context, R.layout.view_setting_item_with_checkmark, this)
SettingsView.kt  (1 usage found)
    26 inflate(context, R.layout.view_settings_item, this)
SettingsViewDropdown.kt  (1 usage found)
    22 inflate(context, R.layout.view_settings_dropdown, this)
SettingsViewSwitch.kt  (1 usage found)
    52 inflate(context, R.layout.view_settings_item_switch, this)
SwapAllowanceView.kt  (1 usage found)
    19 inflate(context, R.layout.view_swap_allowance, this)
SwapCoinCardView.kt  (1 usage found)
    47 inflate(context, R.layout.view_card_swap, this)
TransactionInfoItemView.kt  (1 usage found)
    12 inflate(context, R.layout.view_transaction_info_item, this)
TransactionInfoStatusView.kt  (1 usage found)
    29 inflate(context, R.layout.view_transaction_info_status, this)
TransactionProgressView.kt  (1 usage found)
    27 inflate(context, R.layout.view_transaction_progress, this)
TransactionStatusWithTimeView.kt  (1 usage found)
    27 inflate(context, R.layout.view_transaction_status, this)
```
