### ISSUE TITLE
Long text in Settings is overflowing controls on the right side

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#2939]
Layout has `merge` inside ConstraintLayout

![photo_2020-12-10 11 57 05](https://user-images.githubusercontent.com/1390965/101727561-e8557f00-3ade-11eb-9a84-20bffcf1c021.jpeg)

**Comment by herou** [comment]
@rafaelekol Please, take a look at this PR: #2955 . I fix this issue but I had to modify a lot of files since they are dependent.

This one has the same issue: 
https://stackoverflow.com/questions/46290667/constraintlayout-problems-using-include
