### ISSUE TITLE
Add more fiat currencies to base currency list

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2944]
## We need to add the following fiat currencies to base currency list 

AUD - Australian Dollar

CAD - Canadian Dollar

SGD - Singapore Dollar

BRL - Brazilian Real

CHF - Swiss Franc

CNY - Chinese Yuan

HKD - Hong Kong Dollar

ILS - Israeli New Shekel

RUB - Russian Ruble

TRY - Turkish Lira

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=33766%3A306361

**Comment by herou** [comment]
@Dianaaiym Can you assign it to me?

**Comment by trymeouteh** [comment]
Please add AUD and CAD

**Comment by Dianaaiym** [comment]
> Please add AUD and CAD

Hi,

We plan to add it in upcoming updates.

**Comment by kansalt** [comment]
New Layouts
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=33840%3A308382

**Comment by trymeouteh** [comment]
Please add more currencies when there is time from coingecko
