### ISSUE TITLE
Tx Info: If there is no rate, then the coin value is displayed not completely

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2947]
![2020-12-10 18 33 17](https://user-images.githubusercontent.com/22589457/101772895-38036d00-3b16-11eb-83d0-27c7e9e9bc56.jpg)

**Comment by herou** [comment]
@Dianaaiym I made a transaction in order to reproduce your bug but it did not happen: 
![20201213_221149](https://user-images.githubusercontent.com/13895430/102024135-6b513080-3d90-11eb-9c1e-ccc230e373fe.jpg)

**Comment by Dianaaiym** [comment]
> @Dianaaiym I made a transaction in order to reproduce your bug but it did not happen:
> ![20201213_221149](https://user-images.githubusercontent.com/13895430/102024135-6b513080-3d90-11eb-9c1e-ccc230e373fe.jpg)
> Can you describe the steps that you follow?

Hi @herou 

You need to turn off Internet - find a tx (without fiat value) - open a tx info

**Comment by herou** [comment]
@Dianaaiym I got thatbI need to turn off the internet before opening the transaction details but I am not clear for the tx.How can I obtain a transaction without fee cost?

**Comment by abdrasulov** [comment]
Hi @herou. You can reproduce it by changing the base currency in the settings when there is no internet.
