### ISSUE TITLE
Redesign android modules

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#2951]
The library core should be moved into the app. Modules that depend on the core module should be redesigned to be fully standalone.

**Comment by herou** [comment]
@abdrasulov Lot of work to be done in here.

**Comment by abdrasulov** [comment]
@herou, yeah, you're absolutely right. We'll work on it on the next sprints

**Comment by herou** [comment]
@abdrasulov Can you split in small tickets? I would like to work on this as well because it is really interesting.

**Comment by abdrasulov** [comment]
Let's discuss it next sprints. We need to make research on how to decompose this task
