### ISSUE TITLE
Not able to send Ethereum coins

### ISSUE THREAD

**Issue by herou** [horizontalsystems/unstoppable-wallet-android#2954]
Hello,

I modified the EthereumKitManager class in order to be connected to the Kovan Network and when I tried to send some eth to an address I got this error: 

![20201213_204805](https://user-images.githubusercontent.com/13895430/102022151-37bcd900-3d85-11eb-9a41-0880f7036abd.jpg)

**Comment by herou** [comment]
I tried on ropsten network and everything worked out

**Comment by esengulov** [comment]
should work now!
