### ISSUE TITLE
Happy to see 0.18.0

### ISSUE THREAD

**Issue by herou** [horizontalsystems/unstoppable-wallet-android#2958]
Hello @rafaelekol @abdrasulov (All the team)

I just got the latest version I am so happy that I have contributed to making this happen even though I have done small things. I am enjoying contributing to this repo because you guys are so helpful and the code quality is very high and I see there is a lot to learn. I hope you find my contribution very helpful so I can continue helping you out :)

**Comment by Dianaaiym** [comment]
> Hello @rafaelekol @abdrasulov (All the team)
> 
> I just got the latest version I am so happy that I have contributed to making this happen even though I have done small things. I am enjoying contributing to this repo because you guys are so helpful and the code quality is very high and I see there is a lot to learn. I hope you find my contribution very helpful so I can continue helping you out :)

Thank you, @herou , for all your contributions and all the little things you do to help us.

**Comment by esengulov** [comment]
> Hello @rafaelekol @abdrasulov (All the team)
> 
> I just got the latest version I am so happy that I have contributed to making this happen even though I have done small things. I am enjoying contributing to this repo because you guys are so helpful and the code quality is very high and I see there is a lot to learn. I hope you find my contribution very helpful so I can continue helping you out :)

hey @herou 

it's a pleasure to have you as contributor!

**Comment by abdrasulov** [comment]
Hi @herou. Thanks for the kind words. We're glad to have you as a contributor.
