### ISSUE TITLE
Bitcoin Cash wallets do not match with the seed

### ISSUE THREAD

**Issue by syberia1** [horizontalsystems/unstoppable-wallet-android#2959]
Bitcoin Cash wallets do not match with the seed provided by the application. You can tell by looking at this page:

https://iancoleman.io/bip39/

**Comment by rafaelekol** [comment]
Do you mean generated BCH wallet receive address are different?

**Comment by syberia1** [comment]
> Do you mean generated BCH wallet receive address are different?

Yes. The wallets to receive are different, they do not correspond with the seed.

**Comment by rafaelekol** [comment]
We are aware of this bug. We are working to fix this issue.

**Comment by rafaelekol** [comment]
dublicate of #2960
