### ISSUE TITLE
implement device root detection

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2961]
This was a recommendation from a security audit. Refer to the last point in the audit document for the potential ways to address the issue.

**Comment by esengulov** [comment]
@TalgatNurdinov this needs design

**Comment by herou** [comment]
@esengulov I would like to work on this one.

**Comment by herou** [comment]
@esengulov Can I start implementing the functionality on this one until the design is ready?

**Comment by esengulov** [comment]
> @esengulov Can I start implementing the functionality on this one until the design is ready?

@abdrasulov are we good to go with this one on Android ?

**Comment by herou** [comment]
@esengulov Well, I made some researches, and yeah, I can go with it. If somebody wants to give me some hints before starting I would really appreciate it because I would know that I on the right path.

**Comment by abdrasulov** [comment]
@herou, we can prepare the functionality for the root detection while the design is getting ready. Let's make a new manager called something like `RootManager` and place it in `app/core/managers` and implement root detection functionality there.

**Comment by TalgatNurdinov** [comment]
We dicided blocking app with this screen. Same behavior we have when devise pin is disabled

<img width="356" alt="Screen Shot 2021-01-05 at 17 49 54" src="https://user-images.githubusercontent.com/42367908/103643197-773ea580-4f7e-11eb-9279-5fa3262cf00e.png">

**Comment by herou** [comment]
@abdrasulov, @rafaelekol Took it.

**Comment by AkiraNoSushi** [comment]
I think it would be better if this feature could be disabled by the user. Root isn't inherently insecure and power users can have a healthy and secure rooted device. Modern root solutions like Magisk are quite safe when used correctly. In the case of Magisk, I was able to disable this alert by activating the MagiskHide functionality to hide the root status for specific applications, but this is **only possible with Magisk**, not with other solutions such as phh's SuperUser.
