### ISSUE TITLE
get xrates for all bep20 token from binance

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#2962]
- [ ]  The price of BTC and BTCB (Bep2) are different

**Comment by Dianaaiym** [comment]
![2020-12-15 15 10 06](https://user-images.githubusercontent.com/22589457/102194622-bb8ed680-3ee7-11eb-9482-9bca525e5b47.jpg)

**Comment by herou** [comment]
@Dianaaiym Do they have to be the same?

**Comment by nk-the-crazy** [comment]
> @Dianaaiym Do they have to be the same?

No. Bitcoin prices vary depending on the exchange

**Comment by nk-the-crazy** [comment]
Implemented CoinGecko as Charts, xrates provider for all Coins
