### ISSUE TITLE
insufficient warning / alert for disabling the OS passcode

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2963]
In its current stance the warning(s) for disabling the passcode are somewhat easily ignored.

As a result users who disable the pin lock (or an alternative screen lock mechanism) on Android OS return to the blank wallet and are forced to restore the wallets one by one.

Let's try to make this warning standout more. Consider putting it FAQ as well as Terms sections, in addition to the current locations.

**Comment by TalgatNurdinov** [comment]
In FAQ - need to write a description text
<img width="357" alt="Screen Shot 2021-01-05 at 16 18 46" src="https://user-images.githubusercontent.com/42367908/103634784-c6caa480-4f71-11eb-9918-e5f9c4e46a89.png">

in Terms
<img width="357" alt="Screen Shot 2021-01-05 at 16 19 16" src="https://user-images.githubusercontent.com/42367908/103635086-350f6700-4f72-11eb-99e5-a1005cfffeee.png">

**Comment by rafaelekol** [comment]
Warning about disabling phone system PIN, will reset wallet is already in Terms.
