### ISSUE TITLE
Show the full address on receive bottom sheet

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#2965]
<img width="792" alt="Screen Shot 2020-12-15 at 15 52 21" src="https://user-images.githubusercontent.com/42367908/102199508-e845ec80-3eed-11eb-8e4e-8e417dfad6b1.png">

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=1450%3A78

**Comment by herou** [comment]
@TalgatNurdinov Assign this to me: #2969

**Comment by herou** [comment]
@TalgatNurdinov Assign it to me: #2970
