### ISSUE TITLE
Add a new item to the checkbox selections on Terms page

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2973]
Place the item below right before the last item.

" I understand that disabling the phone unlock PIN (or its equivalent) in Settings of Android OS will erase wallet private keys from my device. I will need my private keys to regain access to my wallet."

**Comment by herou** [comment]
@esengulov Check out this PR: #2975

**Comment by TalgatNurdinov** [comment]
Screen design
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=25082%3A0

**Comment by esengulov** [comment]
@Dianaaiym we need translations for this text!

**Comment by esengulov** [comment]
> @esengulov Check out this PR: #2975 The translation texts are missing.

thanks, I referenced @Dianaaiym on the issue

**Comment by herou** [comment]
@esengulov You already have it in English, I do not know if you want to merge it or not.
