### ISSUE TITLE
Change Source does not work

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#2978]
_Steps_

1. Open Verify Transaction for some pending ETH transaction
1. It shows a warning "Transaction not found"
1. Click on the Change Source

_Expected behavior_

Change source screen should be opened

_Incorrect behavior_

It does nothing

![image](https://user-images.githubusercontent.com/5284600/102471349-4eae4480-407f-11eb-8258-426629a79ed0.png)

**Comment by herou** [comment]
@rafaelekol What is supposed to happen?
