### ISSUE TITLE
1 month as contributor

### ISSUE THREAD

**Issue by herou** [horizontalsystems/unstoppable-wallet-android#2981]
Hello  @rafaelekol @abdrasulov @tmedetbekov @esen @TalgatNurdinov 

I checked when I started to contribute to this amazing repo and working with this amazing team and I saw it has been one month contributing every single day.
I would like somebody of you to contact me at elioprifti@gmail.com because I have some private questions.

Looking forward to being contacted by somebody from the team.

**Comment by esengulov** [comment]
> Hello @rafaelekol @abdrasulov @tmedetbekov @esen @TalgatNurdinov
> 
> I checked when I started to contribute to this amazing repo and working with this amazing team and I saw it has been one month contributing every single day.
> I would like somebody of you to contact me at [elioprifti@gmail.com](mailto:elioprifti@gmail.com) because I have some private questions.
> 
> Looking forward to being contacted by somebody from the team.

Hi @herou 

Sending you an email shortly, thanks for contributing!
