### ISSUE TITLE
Address not valid!

### ISSUE THREAD

**Issue by herou** [horizontalsystems/unstoppable-wallet-android#2986]
Hi,

I wanted to send some ether from one smartphone to another one and the receiver one had not set up ethereum token, so I added the ethereum token and clicked on the receive buttoning in order to see the barcode/address and then with the other smartphone I chose to scan the bar code to send ether but I was having the address not valid alert, I close the app (On the receiver cellphone) and this time worked.

**Comment by Dianaaiym** [comment]
not reproduced
