### ISSUE TITLE
Add 'sending' / 'receiving' status to transaction

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2990]
Currently wallet assumes following statuses for transaction

- pending
- receiving / sending (might be called 'processing')
- completed
- failed

- [x] Add another status, 'sending' or 'receiving'. It will be shown when transaction was included in the block but not confirmed yet.
- [ ] @Dianaaiym add 'sending' status text to transaction status info page. The text needs to be localized. Use the text below

> Transaction has been included in the blockchain but has not reached finality yet. At this point, it's safe to consider transaction completed for smaller payments. For larger payments it's recommended to wait until the status changes to completed.

- [ ] @Dianaaiym make sure there is an info text for 'receiving' status as well

**Comment by herou** [comment]
@esengulov Assign this to me please, I know what to do.

**Comment by herou** [comment]
@esengulov @Dianaaiym The Pendding text is not translated as well.

**Comment by herou** [comment]
@esengulov Check this: #3014

**Comment by abdrasulov** [comment]
Hi @herou. I've assigned you to this ticket. We're planning it in the next version. We'll check PR then

**Comment by herou** [comment]
@abdrasulov How is the status of this PR?
