### ISSUE TITLE
Change fee estimation logic for recommended tx fee values for Ethereum and Bitcoin blcokchains

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#2993]
Unstoppable uses public fee estimate services to help user determine appropriate transaction fees for the moment. The transaction fees are higher when there are a lot of transactions taking place and lower when the blockchain is less busy. 

This currently applies only to Bitcoin and Ethereum and ERC20 transactions.

**1)) FOR ETHEREUM:** 

For Ethereum the fee is determined by the following formula: fee = gas_cost * gas_limit. Both of these values are provided by fee provider service, i.e. via Infura’s gasPrice and estimateGas API methods. 

Upon further testing it was discovered that during times when network becomes suddenly busy the returned values are often insufficient, in some cases the transactions fail with out of gas (insufficient gas limit) or remain pending for hours (insufficient gas price). 

Currently the client gets both values from Infura and recommends a fee by multiplying these two values. I propose to add a certain % to the values returned by Infura to ensure transactions have higher probability of being processed fast. The % will depend on the amount being sent.

If exchange rate available AND transaction amount/value is available/identifiable:

- [x] for amounts <= 500$ add 5% to the values returned by fee provider (gas price and gas limit).
- [x] for amounts <= 1000$ add 10%
- [x] for amounts > 1000 and <= 5000 add 15%
- [x] for amounts > 5000 and <= 10000 add 20%
- [x] for amounts > 10000 add 25%

if exchange rate not available OR if amount value is not available:

- [ ] use the values returned by fee provider + 10%

**2)) FOR BITCOIN**

If exchange rate available AND transaction amount/value is available/identifiable:

- [x] for amounts <= 500$ add 5% to the values returned by fee provider (fee rate).
- [x] for amounts <= 1000$ add 10%
- [ ] for amounts > 1000 and <= 5000 add 15%
- [ ] for amounts > 5000 and <= 10000 add 20%
- [ ] for amounts > 10000 add 25%

if exchange rate not available OR if amount value is not available:

- [ ] use the values returned by fee provider + 10%

**3)) OTHER CONSIDERATIONS** 

- [ ] it's likely that we are going to be adjusting the logic above based on usage and feedback from community.
- [ ] ensure that there are max limits on the transaction fee value that can be set by the client, regardless of the recommended values returned by third party api calls. Ensure that values which fall outside of what the client considers safe are disregarded. That will ensure that client never pays extremely high fee amounts.

**Comment by uber9** [comment]
Parameters values look rational. I approve this ticket.
