### ISSUE TITLE
Review and refactor logic for obtaining current token rates

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#3006]
- [ ] get current rates from single source, there is a unanimous consensus to use CoinGecko.

- [ ] Review why following tokens currently do not have rate (checked on iOS)

Compound Sai
DigixDAO
EURBASE Stablecoin
Fulcrum Dai (iDAI)
Golem
HEDG
IDEX Membership
KuCoin Shares
Liquidity Network (LQD)
Loopring
MCO
Mithril
Modum Token
Orbs
PieDAO USD
POA ERC20
Populous
QChi
Revain
Sai
SelfKey
Synth sXAU
Trust Swap
WBTC
WETH

**Comment by nk-the-crazy** [comment]
Implemented CoinGecko as Charts, xrates provider for all Coins .
So all problems with rates should be resolved
