### ISSUE TITLE
Crash on creating Zcash wallet or loading app after creation on Android 11

### ISSUE THREAD

**Issue by Troglodactyl** [horizontalsystems/unstoppable-wallet-android#3013]
Issue seems to be well explained here: https://github.com/square/okhttp/issues/5816

Here's the log:

`12-25 08:53:31.720 18568 19281 W tems.bankwalle: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (greylist-max-q,core-platform-api, reflection, denied)
12-25 08:53:31.720 18568 19281 W tems.bankwalle: Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->getAlpnSelectedProtocol()[B (greylist-max-q, reflection, denied)
12-25 08:53:31.725 18568 19281 E AndroidRuntime: FATAL EXCEPTION: grpc-okhttp-0
12-25 08:53:31.725 18568 19281 E AndroidRuntime: Process: io.horizontalsystems.bankwallet, PID: 18568
12-25 08:53:31.725 18568 19281 E AndroidRuntime: java.lang.AssertionError: Method getAlpnSelectedProtocol not supported for object SSL socket over Socket[address=zcash.horizontalsystems.xyz/167.99.236.5,port=9067,localPort=42608]
12-25 08:53:31.725 18568 19281 E AndroidRuntime:        at io.grpc.okhttp.internal.OptionalMethod.invoke(OptionalMethod.java:114)
12-25 08:53:31.725 18568 19281 E AndroidRuntime:        at io.grpc.okhttp.internal.OptionalMethod.invokeWithoutCheckedException(OptionalMethod.java:135)
12-25 08:53:31.725 18568 19281 E AndroidRuntime:        at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.getSelectedProtocol(OkHttpProtocolNegotiator.java:183)
12-25 08:53:31.725 18568 19281 E AndroidRuntime:        at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.negotiate(OkHttpProtocolNegotiator.java:145)
12-25 08:53:31.725 18568 19281 E AndroidRuntime:        at io.grpc.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:63)
12-25 08:53:31.725 18568 19281 E AndroidRuntime:        at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:568)
12-25 08:53:31.725 18568 19281 E AndroidRuntime:        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
12-25 08:53:31.725 18568 19281 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-25 08:53:31.725 18568 19281 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-25 08:53:31.725 18568 19281 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
`

**Comment by gmale** [comment]
The underlying library is stuck on an older version of gRPC (which pulls in an older version of OkHTTP). Upgrading may create breaking changes on iOS and lightwalletd. A bit more investigation is needed. I'll post any updates on [the related issue](https://github.com/zcash/zcash-android-wallet-sdk/issues/198).

**Comment by gmale** [comment]
I updated the related libraries but when I went to confirm that this fixed the root problem, I could not reproduce in our ECC Wallet. So I pulled the source of this project and ran it, as is, and ALSO could not reproduce on my Android 11 emulator nor on my Pixel 4 XL (running Android 11).

So I believe this is fixed but I cannot confirm because I cannot reproduce with the existing code and thereby cannot confirm that the new changes make a difference. I will publish the updated library to jcenter, shortly.

**Comment by gmale** [comment]
Confirmed that the updated SDK works in your wallet. However, it does introduce a clash with binancechainkit, which is [pulling in an older version](https://github.com/horizontalsystems/binance-chain-kit-android/blob/master/binancechainkit/build.gradle#L97) of `protobuf-lite`.

Modifying the [build file](https://github.com/horizontalsystems/unstoppable-wallet-android/blob/master/app/build.gradle#L190) with the following worked around the problem:
```
    implementation('com.github.horizontalsystems:binance-chain-kit-android:6ab731c') {
        exclude group: 'com.google.protobuf'
    }
```

I would have submitted a PR with both changes here. However, it would probably be better to update the protobuf-related dependencies in the binance library, instead. In the meantime, updating the SDK to beta04 and then excluding the protobuf group from binance-chain-kit should work.
