### ISSUE TITLE
eth transaction some bug

### ISSUE THREAD

**Issue by bxxasn** [horizontalsystems/unstoppable-wallet-android#3025]
![image](https://user-images.githubusercontent.com/7637679/103495065-60139100-4e74-11eb-8bbc-b9da962db3e9.png)

![image](https://user-images.githubusercontent.com/7637679/103495365-8be34680-4e75-11eb-8a36-7067c37f06c3.png)

eth address:0xA1d4fbAa9ea47a058EE73D4228D5c1b4A18029e5 

1. Failure status is not displayed 
 txHash:0xf25dc23d13b76a0790dcac636df33e8af7a8912581ac985eaf6e6c0711c13852

2. Some transactions are not shown
txHash:0xd4632e01f2f0d17a1991e27fcb4c0bb55303033e99ff95693ed3008fd36176e7

3. The transaction always shows the transaction status
 txHash:0xb14b0389d59bd77b137e3338695a005a9ba7800fa55571b7d45711d693092c87

**Comment by omurovch** [comment]
Hi @bxxasn,
Thank you for detailed bug report! We are looking into it. 

Can you please clarify, were all the transactions (including failed ones) sent in unstoppable wallet?

**Comment by bxxasn** [comment]
> Hi @bxxasn,
> Thank you for detailed bug report! We are looking into it.
> 
> Can you please clarify, were all the transactions (including failed ones) sent in unstoppable wallet?

Not all of them. Some of them are unstoppable and some use imtoken

**Comment by bxxasn** [comment]
@omurovch  Not all of them. Some of them are unstoppable and some use imtoken

**Comment by omurovch** [comment]
Hi @bxxasn,

1. Failure status is not displayed

At the moment wallet displays only those failed transactions that are sending Ether, i.e. standart ethereum transactions. But Erc20 and Uniswap transactions that are failed not shown for now. In your case these failed transactions are Uniswap transactions. We are working on improving Uniswap related UX, there will be separate screen for viewing Uniswap transactions, including failed ones.

2. Some transactions are not shown

It is a transaction sent to 1Inch swap. It is also not shown in the current version 0.18. We are shipping a new release version 0.19 in a few days, with many improvements and bug fixes where such transactions will also be shown. 

3. The transaction always shows the transaction status

Status is shown as Sending while it is not included in block.
