### ISSUE TITLE
Check account when returning cached kits

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#3027]
In `EthereumKitManager`, `BinanceKitManager` and `EosKitManager` methods that return appropriate kits should check if the cached kit was created for the same account. If it's a different account then the cached kit should be updated.

**Comment by herou** [comment]
@abdrasulov Can I try this one?

**Comment by herou** [comment]
@abdrasulov Where the cache kit gets stored?

**Comment by abdrasulov** [comment]
@herou Each of these managers has a property named `kit`. This property is used as a cache.

The same task has been done on the iOS app. So you can check the solution here 
https://github.com/horizontalsystems/unstoppable-wallet-ios/pull/2467/commits/4230ead93b6321cce41896d7eb9540744b17ddc6#diff-16a02749a5905ff206a0c7a26c73b6ecb941d309a333856f88c545a0394c512f

One more point, in android the `kit` should be stopped before it is replaced
