### ISSUE TITLE
Remove Full Info Page

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#3029]
We need minor improve the transaction info

Instead of the "Verify" button, make the "View in Explorer" button, which will bring to inserted explorer.
With this change, we don't need the full transaction info page also ability of changing explorer source

**Comment by herou** [comment]
@TalgatNurdinov Do you have any mock up for that?

**Comment by TalgatNurdinov** [comment]
@herou Sorry for the late response, link is below
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=9354%3A1332

**Comment by herou** [comment]
@abdrasulov Can you give to me a simple explanation from the technical point of view?

**Comment by Dianaaiym** [comment]
all links should open in app browser
