### ISSUE TITLE
Adding some Cryptos and abort transactions?

### ISSUE THREAD

**Issue by pabatribick** [horizontalsystems/unstoppable-wallet-android#3085]
Hey, first: Great App!

I would like to know if and when you will integrate the Ravencoin RVN, Polkadot, Cardano, Stellar,  into the app?

And: Is it possible, if my transaction will not be confirmed, to cancled it?

Thanks!

**Comment by esengulov** [comment]
> Hey, first: Great App!
> 
> I would like to know if and when you will integrate the Ravencoin RVN, Polkadot, Cardano, Stellar, into the app?
> 
> And: Is it possible, if my transaction will not be confirmed, to cancled it?
> 
> Thanks!

thanks for reaching out)

We are likely going to integrate support for tokens you mentioned in the future. Polkadot likely being the first one among the bunch.

As for cancelling uncofmrimed transactions we intent to add such features where it's possible i.e. Bitcoin and Ethereum blockchains. This will probably be available in a version 0.20 or 0.21.
