### ISSUE TITLE
Bitcoin fee and available balance is error when total balance is smaller than fee.

### ISSUE THREAD

**Issue by bitcard** [horizontalsystems/unstoppable-wallet-android#3110]
In send bitcoin view,  bitcoin fee and available balance are both zero when total balance is smaller than fee, when debug it, found throw SendValueErrors$Dust exception. The expected results is available balance view is zero and fee view display the correct fee value. 

The ethereum send view is correct.

**Comment by abdrasulov** [comment]
Hello @bitcard,

To calculate fee for a bitcoin transaction we need to build the transaction first. If there is not enough funds for sending amount + fee we cannot build the transaction. So we cannot calculate fee. That is why we show 0 in this case.

**Comment by bitcard** [comment]
> Hello @bitcard,
> 
> To calculate fee for a bitcoin transaction we need to build the transaction first. If there is not enough funds for sending amount + fee we cannot build the transaction. So we cannot calculate fee. That is why we show 0 in this case.

Ok, I got it, thank you.
