### ISSUE TITLE
does android version support bitcoin lightning network?

### ISSUE THREAD

**Issue by bitcard** [horizontalsystems/unstoppable-wallet-android#3114]
It seems iOS version already support lighting network, https://github.com/horizontalsystems/lightning-wallet-ios, there is a plan to support it?

**Comment by abdrasulov** [comment]
Hello @bitcard. The lightning-wallet is a separate project. The android version is https://github.com/horizontalsystems/lightning-wallet-android. As of now, working on those projects have been idled.
