### ISSUE TITLE
Why is the address different if I build it with testnet?

### ISSUE THREAD

**Issue by eggham0518** [horizontalsystems/unstoppable-wallet-android#3122]
It is the same mnemonic, but it shows a different address.
Is it normal?

The mainnet address matches the address shown in the Metamask.

**Comment by abdrasulov** [comment]
Hello @eggham0518. Yes, it is supposed to be a different.

**Comment by eggham0518** [comment]
Metamasks gave the same address on all networks, so I got confused.

**Comment by abdrasulov** [comment]
They should be different according to bip44.
