### ISSUE TITLE
Dash Api Sync doesn't work

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#3128]
Wallets Status:
   - Standard:
     - Mnemonic: 12

Blockchain Status:
   - Dash:
     - Synced Until: N/A
     - Syncing Peer: N/A
     - Derivation: BIP44
     - Sync State: NotSynced-Exception
     - Last Block Height: N/A

IOException: https://dash.horizontalsystems.xyz/apg, Unexpected Error:Response{protocol=http/1.1, code=502, message=Bad Gateway, url=https://dash.horizontalsystems.xyz/apg/addrs/XvQdoyktA59PLEKYFaJrZU2BrL55UzdeTx,XpeKSDDSv9pTdFCSFVYoYMggKUpCiQjC6a,XpXzQoEBketyM3PHRgZAxKxky1Ecb69WnE,XtMjzBxs5DV3cCRfw89AwGsH2uanDmqFPH,Xgu323biUzhfK2rUJGeLVGgCeXRmwvUR2R,XwWzyiQE1TBSnAamy4hu3ZdggZYQLUm5uN,XiR2ANpKbXavDL8xNySWJ34X5TYLUHhb75,XnKpvQ2t99QnxvaWCADQdMeYJKoUXBA8RC,XySAZG9JRgt5gCk8hKxaw7PnBYpbL7mXGV,XkFvKYRvGpADYEPpgfgxeZxuyRZvAiepBq,XtQ6Tynke8cXsydAT2w5yGGmJkJJjQ4msD,XwdtospUdGQ4DHCLA7x5kXvFQzNPfMCSVt,Xc26f6WBehbWtYQmceuLmfMD2iJ4xMJ3xY,Xr1PT68s8KECwFA5sD2Zb3ZZaan1wRp2cT,Xsp3TapuyWoxPVdZ5mYd6VneTXHXuuhhCt,XvTk8yDpdnY7mhSJJrRRvZu48LgwHcmEtd,XqTqrrUNBrd3DdjSf2xjuSEiKniJRUQtZW,Xx83GbCGSM9hX38YKhxyZeL1NK3oB4MCN7,XncPLWnswciuMHUJLsNXarfYoRDPGV5bEg,Xmx58mv59sJnG7dGsbqE21SsC4GiYwuWs7,XehkWwmsaxDkx1CKGbLNU2LRdtJzk81o3c,Xp8XEnNuz51tanYU7Zr7besBG5tj8mn4YX,Xb1HN8L62dWpTpiJ7gHEp3Yv9NkDsHxkhj,XrxnMwUC1h2LdnDA3y2zpYoZgTfipNo6xE,XbQwQY6zGeJdEJC22L614dv5oE4ZCNc14F,Xn78eJufjE9HrYZdsC7TcU17y6p7NDtskD,XcXjrb9yfETP8X2gJTuLLYkSebAYgeyaYP,Xp4xqbr18Uqc3Mu7G4hkc7gHprd3qGEa9y,XfGEPuH3vJEkc9JtiQFbQBw1vbjCSqJv1g,XwJudEbmgeZhnHazTKxbMe5Ps3RUKYkpZC,XjbgJAKkAP78XFYtLqyBb3WjCWGXpQ4vXa,XwN9eyZ6vtwKsPMLRDBRQfNqELMGjgmKDB,XnKVBnXPtFNHyceYxWT5n4Pinq9jHCkq5M,Xrw4HMwaYFTusnMgHuK9k6n83XS3qxdxsG,XeQijC7Re87HMDRDP6ddx9oZNJ914tcmzF,XysnztHLPvr5bcikeWdSanHe7P7zmVojfB,Xwoye2rYzB1hiYaYa11HNNZU4mmWJfsUJt,Xg2cTLyJ8XLYdPEFSPXXtvYbpRixk4W4Yt,XscaXz9BoibX62FVb7HP5X91yd8wwQnVHh,Xqfiazoi9jhEwQJUBPZG1jEdjNCHS38dtF/txs?from=0&to=50}

**Comment by nk-the-crazy** [comment]
Issue fixed By increasing node volume size

**Comment by Dianaaiym** [comment]
> I can't sync Dash neither from API nor from Blockchain, It stops at Sep 14, 2021 from API, from Blockchain it doesn't sync at all.
> 
> I have the last version 0.22.1
> 
> I have a 12 word wallet if it matters.

We tried to reproduce, our wallet was synced via api and blockchain sync.
To check your case, send us your app status (Settings - About App) here or via support email (support.unstoppable@protonmail.com
