### ISSUE TITLE
Can't change the app package name for play store upload, Please help.

### ISSUE THREAD

**Issue by wolfenix** [horizontalsystems/unstoppable-wallet-android#3132]
Hi, I modified this repository and created my wallet for fun purpose, but now getting this error while uploading the app on the google play store, in past I've changed the package name several times of different apps but i can't change this app name no matter what i try, it gives me the same issue, I've tried many methods from stackoverflow but it didn't worked, so plz help sir.  I'm attaching the developer console screenshot.

this is the error - "You need to use a different package name because "io.horizontalsystems.bankwallet" already exists in Google Play."

Plz help me to fix this.

Thankyou.

![issue1](https://user-images.githubusercontent.com/55916268/106361254-ee2f4a00-6342-11eb-8a89-e18d2ef118b5.PNG)

**Comment by rafaelekol** [comment]
Basically changing `applicationId` in gradle file should be enough.

```
android {
    ...
    defaultConfig {
        applicationId "io.horizontalsystems.bankwallet"
        ...
    }
}
```
