### ISSUE TITLE
mnemonics words saved no encryption

### ISSUE THREAD

**Issue by bitcard** [horizontalsystems/unstoppable-wallet-android#3145]
mnemonics words save database directly no encryption, there are serious security issues, hope to encrypt it by PIN.

**Comment by abdrasulov** [comment]
We do encrypt the mnemonic words. Can you please share how you came to that conclusion?

**Comment by bitcard** [comment]
> We do encrypt the mnemonic words. Can you please share how you came to that conclusion?

I debug the app on android emulator, APP not set PIN, when get account info from database, I can see the mnemonic words no encryption.

**Comment by abdrasulov** [comment]
It's encrypted and decrypted in a database layer. It uses Android keystore system for encryption. It doesn't depend on the PIN. Moreover, the pin is also encrypted/decrypted using the same mechanism.

**Comment by bitcard** [comment]
> It's encrypted and decrypted in a database layer. It uses Android keystore system for encryption. It doesn't depend on the PIN. Moreover, the pin is also encrypted/decrypted using the same mechanism.

That's great, I did set the device gesture password, thank you for your explanation.
