### ISSUE TITLE
Support xdai network 

### ISSUE THREAD

**Issue by dinarpay** [horizontalsystems/unstoppable-wallet-android#3183]
Hello
Can support xdai network and smart contracts
I have a currency project for payments and transfers
I want to use the xdai network
I will be using relays to pay network fees instead of users, so no xdai money is required
I want the app to be fully localized in Arabic with directions support
I'm ready to pay to add xdai network and add Arabic language, skin changes to app logo, name, icon etc.

**Comment by esengulov** [comment]
Hi, we plan to add xdci support to Unstoppable in a few months time. 

Arabic language support is already in the app but only in android version for now.
