### ISSUE TITLE
Coin Page v2

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#3210]

**Comment by TalgatNurdinov** [comment]
coin page design:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=28034%3A16420

**Comment by esengulov** [comment]
- [ ] for UI questions consult @kansalt 
- [ ] for data to be shown in About section contact @Dadybayo or @esengulov 
- [ ] for data shown above  About section contact @nk-the-crazy

**Comment by esengulov** [comment]
- [ ]  for UI questions consult @kansalt 
- [ ] certain sections will not be shown when data not available i.e. coin rating, coin markets etc
- [ ] data that will be shown in About section will be taken from JSON file. For questions contact @Dadybayo or @esengulov
- [ ]  for data that is shown above the About section contact @nk-the-crazy
- [ ] [coin_ markets] entry/cell will only be shown only for ERC20 tokens for the time being.

**Comment by TalgatNurdinov** [comment]
**Need to fix points** 

- [ ] Expanding of descriptions. If description less than 16 lines "read more" button should be removed
- [ ] Fix the tabs buttons (width and margins)
- [ ] In Markets page (from coin page) displayed contract address instead coin code

**Need to change points** 
- [ ] Remove icons from market cell in markets
- [ ] Add Investors cell near Markets
- [ ] Given the recent problems with volume datas and indicators, need to change charts of volume and indicators, their should be overlayed on the price chart (tomorrow I will prepare finalized design)

**Comment by nk-the-crazy** [comment]
Add Investors info page to Coin Tab :

<img width="168" alt="Screen Shot 2021-03-18 at 11 20 16 AM" src="https://user-images.githubusercontent.com/11713346/111577181-04eb0c80-87dc-11eb-91ae-cf16e29e4c96.png">
