### ISSUE TITLE
Add a warning that rooted devices are unsafe, but leave the ultimate decision up to the user.

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#3255]
Alert text

>>The Unstoppable app works only on non-rooted (not jailbroken) phones.

>>Please note when you use a rooted device the app can no longer guarantee the safety of your cryptocurrency from malicious software.

button text "I UNDERSTAND"

**Comment by clayt0nk** [comment]
![signal-2021-03-13-144100](https://user-images.githubusercontent.com/3198617/111022368-4f037500-840d-11eb-8508-4ff1a7686c83.png)

Something seems to have gone amiss with the "ultimate decision up to the user" part. I have two LineageOS Androids, both with unlocked bootloaders (that is how LineageOS got installed) but the OS itself has no direct access to root. (I can get root only via adb over USB.) Both have version 0.19.1 of the Android Unstoppable wallet. The newer device with the newer version of LineageOS (Android 10 / LOS 17.1) works fine. However, the older device with an older version of LineageOS (Android 8.1.0 / LOS 15.1) displays the attached Screen of Death every time I start the Unstoppable wallet.

One other difference between the two devices is that the latter older device has a minimal install of Google Services, the newer devices has zero Google services / spyware.

**Comment by rafaelekol** [comment]
This task is not implemented yet. It's planned for the next sprint.

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=34032%3A0
