### ISSUE TITLE
global market info should update on app open from background

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#3261]
At the moment the data stays same for hours and requires app kill to force refresh on the UI

- [x] when completed on Android the issue should be created for iOS team as well

**Comment by abdrasulov** [comment]
Implemented solution requires all MarketListService clients trigger refresh method for initial load.

Need to implement it by listening to BackgroundManager. So when BackgroundManager informs app entered foreground global market info should refresh the data.
