### ISSUE TITLE
Feature Request: Multiple Wallets

### ISSUE THREAD

**Issue by trymeouteh** [horizontalsystems/unstoppable-wallet-android#3296]
Please allow for multiple wallets by being able to import multiple 12 word phrases and naming each 12 word phrase wallet. This way you can have one 12 word phrase and all of its wallets BTC, ETH, LTC be for work and another 12 word phrase wallet BTC, BCH, LTC be used for personal use

**Comment by esengulov** [comment]
coming soon! This is one of the key features for the current sprint, 0.21.

Issue Merged Into https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3456
