### ISSUE TITLE
Feature Request: Unstoppable Domains Support 

### ISSUE THREAD

**Issue by trymeouteh** [horizontalsystems/unstoppable-wallet-android#3297]
I know some will prefer FIO or something else, but I would like to suggest adding support on integrating Unstoppable Domains

- Ability to buy multiple unstoppable domains with crypto in the app 
- Ability to transfer multiple unstoppable domains to another address in the app
- Ability to add crypto addresses to multiple unstoppable domains in the app
- Ability to send crypto to an unstoppable domain address in the app

I prefer Unstoppable Domains since they are a one time purchase and you have it for life unlike FIO addresses, they are human readable and can help with adoption by being able to tell others were to send crypto to. Unstoppable domains can be used for other things like hosting IPFS stuff but I dont see a need for Unstoppable to support all of that, just for the ability to register, transfer domains and be able to easily accept crypto using a unstoppable domain.

**Comment by esengulov** [comment]
> I know some will prefer FIO or something else, but I would like to suggest adding support on integrating Unstoppable Domains
> 
> * Support .zil and .crypto addresses (Will need to add ZIL coin support for .zil domains)
> * Ability to buy multiple unstoppable domains with crypto in the app
> * Ability to transfer multiple unstoppable domains to another address in the app
> * Ability to add crypto addresses to multiple unstoppable domains in the app
> * Ability to send crypto to an unstoppable domain address in the app
> 
> I prefer Unstoppable Domains since they are a one time purchase and you have it for life unlike FIO addresses, they are human readable and can help with adoption by being able to tell others were to send crypto to. Unstoppable domains can be used for other things like hosting IPFS stuff but I dont see a need for Unstoppable to support all of that, just for the ability to register, transfer domains and be able to easily accept crypto using a unstoppable domain.
> 
> Will need to support Zilliqa
> #3305

thanks, sending to Unstoppable domains is already supported. unstoppable doesn't yet support storage/viewing your domains but we intend to add this soon as well. Domains are essentially NFT type tokens and we don't want to rush with that before we think through all user use cases with these token types.

**Comment by trymeouteh** [comment]
ZIL support is not really need as much since Unstoppable Domains now supports up to 9 different domain extensions that are available on the Ethereum blockchain which are

.crypto
.coin
.wallet
.bitcoin
.x
.888
.nft
.dao
.blockchain
