### ISSUE TITLE
Feature Request: Watch Only Wallets

### ISSUE THREAD

**Issue by trymeouteh** [horizontalsystems/unstoppable-wallet-android#3299]
Please allow users to import cryptocurrency addresses and be able to receive crypto to an address. No sending ability required and no need to enter in the private key/word seed.

**Comment by esengulov** [comment]
> Please allow users to import cryptocurrency addresses and be able to receive crypto to an address. No sending ability required and no need to enter in the private key/word seed.

noted!

**Comment by esengulov** [comment]
implemented for EVM chains!
