### ISSUE TITLE
Feature Request: Set Receive Amount Request

### ISSUE THREAD

**Issue by trymeouteh** [horizontalsystems/unstoppable-wallet-android#3300]
Please add the ability to be able to receive the amount requested. When you go to receive for any crypto wallet, you can optionally enter in how much in that cryptocurrency or in fiat currency (which will be converted to crypto) you want to recieve. By filling in the requested amount it will update the QR code and address text which can be copied with the amount so when someone pastes the amount in their wallet or scans the QR code, the amount to pay will be automatically filled into the field and all that is needed by the user is to verify the amount and approve the transaction.

This is how it will look without an amount set
bitcoin:12dRugNcdxK39288NjcDV4GX7rMsKCGn6B

This is how it will look with an amount set to 0.25 BTC

bitcoin:12dRugNcdxK39288NjcDV4GX7rMsKCGn6B?amount=0.25

**Comment by esengulov** [comment]
thanks for breaking it down, we are going to work on it too

**Comment by abdrasulov** [comment]
Hi @naconner. Thanks for the feedback. We have a separate issue for this #4653.
