### ISSUE TITLE
Feature Request: Zilliqa

### ISSUE THREAD

**Issue by trymeouteh** [horizontalsystems/unstoppable-wallet-android#3305]
Please support Zilliqa by using the 12 word phrase from the BTC, LTC, ETH wallets. This can be added to support .ZIL Unstoppable Domains.

https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3297

**Comment by trymeouteh** [comment]
This is not really need as much since Unstoppable Domains now supports up to 9 different domain extensions that are available on the Ethereum blockchain which are

.crypto
.coin
.wallet
.bitcoin
.x
.888
.nft
.dao
.blockchain

**Comment by esengulov** [comment]
> This is not really need as much since Unstoppable Domains now supports up to 9 different domain extensions that are available on the Ethereum blockchain which are
> 
> .crypto
> .coin
> .wallet
> .bitcoin
> .x
> .888
> .nft
> .dao
> .blockchain

thanks for heads up!
