### ISSUE TITLE
can i also download the wallet outside the googleplaystore

### ISSUE THREAD

**Issue by Salsachak** [horizontalsystems/unstoppable-wallet-android#3336]
The idea that you have to have a gmail - google account to download Google playstore , to download a wallet that is completely private, feels a bit odd since gmail - google's Cookies save info that they may hand over to any third parties when activities go against regulations (i expect also from the government too; so the scenerio they might ban crypto..hmmm makes me think).
Or is there smth I'm forgetting in this story?

x

**Comment by omurovch** [comment]
Hi @Salsachak,
Wallet can also be installed by downloading apk file on github. 
Please see https://github.com/horizontalsystems/unstoppable-wallet-android/releases
