### ISSUE TITLE
Private Key Show / Restore Screen Fixes

### ISSUE THREAD

**Issue by csensitive** [horizontalsystems/unstoppable-wallet-android#3438]
Please deviate between seed / mnemonic phrase and private key in settings > manage wallets > show key.

Until it's actually possible to show the 'real' private keys one should simply call them seeds or mnemonic phrases to remove any confusion to what is actually showed.

**Comment by TalgatNurdinov** [comment]
Layout:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=9365%3A6307

You also need to break down the mnemonic phrases into groups.
(for 12 words : 3+3+3+3, for 24 words 4+4+4+4+4+4 for easy memorization)
