### ISSUE TITLE
Add ability to show release notes and important points to users after update

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#3452]
On the first launch after app update we can show some kind of alert that will show:

- release notes, new notable changes in features and UI/UX
- important notes, e.g. dropping support of some features or OS versions

**Comment by esengulov** [comment]
@rafaelekol keep a log of all release notes in Settings >> About app. User should be able to browse all release notes we published so far from that section. It can be added manually on each release on grabbed from Github (needs to be decided).

**Comment by TalgatNurdinov** [comment]
In the settings page I suggest only showing release notes of installed release.
(Next time we'll think about how to display release notes of older versions)

<img width="392" alt="Screen Shot 2021-04-05 at 16 27 24" src="https://user-images.githubusercontent.com/42367908/113564927-fac66c00-962b-11eb-97d9-a378cce09a94.png">

The release notes should use the same styles as the academy guides

<img width="394" alt="Screen Shot 2021-04-05 at 16 27 36" src="https://user-images.githubusercontent.com/42367908/113564962-0a45b500-962c-11eb-9904-f0df7ac88bec.png">

**Comment by rafaelekol** [comment]
Fetch Release notes from Github
