### ISSUE TITLE
Support system dark / light modes

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#3453]
In the current state app does not respect system dark / light modes.

We should support them in the following way:

- instead of dark / light mode switch there should be a setting with 3 options: `dark`, `light`, `system`
- `dark` and `light` modes will force mode and will not respect system setting
- `system` setting will switch app to dark or light mode according to system setting

**Comment by TalgatNurdinov** [comment]
Design
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=31421%3A231708
