### ISSUE TITLE
Multi Wallet

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#3456]
- [ ] Removing types of wallets and combining all chains to multi coin wallet

1) redesign of creating 
- add ability for choosing 12 or 24 mnemonic words
- add passphrase

2) redesign of importing 
- add passphrase
- add birthday height field on switching ZEC (choose coin page)
  

- [ ] Add wallet switcher from main balance tab

- displaying wallet name on the main title
- add bottom sheet switcher

- [ ] Redesign of Manage wallets

- new cells with active wallet indicator
- add field of wallet name in wallet settings where also should be included addresses format, mnemonics and unlink button

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=29564%3A3594

**Comment by kdejaeger** [comment]
Nice, so we will be able to apply the privacy advice here: https://litrex.academy/en/defi/en/6-defi-transactions.md ?
