### ISSUE TITLE
Push notifications service Refactored

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#3477]
Push notifications are now working differently as there is no dependence on Google's firebase.

Firebase was removed from the repo recently as we need to get the app into fdroid.

Decide how to proceed @abdrasulov

**Comment by TalgatNurdinov** [comment]
Design for Chinese brand smartphones
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=32601%3A1735
