### ISSUE TITLE
[feature request] UI suggestions and "lite" mode

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#3479]
I don't need all of the extras, just the wallet and the current price of whatever is in my wallet.

Would like to see
1. Option to choose start tab
2. Option to disable the markets tab altogether "lite mode"
3. Option to disable all 3rd party market data / internet access. Blockchains only, etc. (Privacy tab)

- Without the ability to purchase crypto from the app, the markets tab should take a back seat. The exchange has that info.
- My primary use case is to hold my crypto in a non-custodial, offline manner.
- ideally, when creating a wallet you would be able to choose between a "lite" wallet and a "full". Lite being the barebones I describe in 2+3. (No market tab, market data disabled by default)

**Comment by esengulov** [comment]
good points, we have some tasks planned on all three points!
