### ISSUE TITLE
[Feature request] Disallow screenshot only in screens where keys are shown

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#3480]
Add a toggle for "allow screenshots" to the privacy settings.

Use case: I like taking screenshots of my balance. Sure, certain screenshots can cause security issues but I should be able to accept that risk.
Actual use case: I'd like to report a possible bug and include a screenshot, but cannot.

**Comment by esengulov** [comment]
We will see if this can added to Settings without comprising security precautions. Will followup here

**Comment by abdrasulov** [comment]
Discussed with @esengulov and decided to disallow screenshot only in pages that show keys
