### ISSUE TITLE
[Bug] bitcoin, litecoin balance only showing 4 decimal places

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#3481]
(Update) it appears that litecoin balances are also affected. Both on the transfer screen and the wallet balance. I've only tested those 2 coins, possibly affects more.
---

My bitcoin balance is showing 4 decimal places instead of 8. Unstoppable screenshots on gplay show 8, as well as the exchange app I use. 

Example:
0.0004
Instead of 
0.00045678

App version 0.19.1

---
UPD:

After discussing with @TalgatNurdinov decided to update the rounding logic for coin values.

The maximum decimal points should be calculated based on the value itself. It should be:

1. `0 <= value < 1`, then `8`
1. `1 <= value < 10 and the first 4 digits of fractional part of value is equal to 0`, then `8`
1. `10 <= value < 100`, then `4`
1. `value >= 100`, then `2`

**Comment by esengulov** [comment]
thanks, we will look into it

**Comment by esengulov** [comment]
@kansalt @TalgatNurdinov please look into this

**Comment by TalgatNurdinov** [comment]
This is how our long-balance reductions work
("0.00000123"), "0.00000123")
("0.00001234"), "0.00001234")
("0.00012345”), "0.0001”)
("0.00123456"), "0.0012”)
("0.01234567"), "0.0123")
("0.12345678"), "0.1234")

@abdrasulov Maybe we shouldn't cut balances that start with 0.

**Comment by abdrasulov** [comment]
After discussing with @TalgatNurdinov we add the following for rounding logic in balance cell:

1. If the balance >= 1 then there should be 4 decimal points
2. If the balance <1 then there should be 8 decimal points
