### ISSUE TITLE
Coin Manager UI redesign 

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-android#3489]
- [x] Replace the coin's cells components 
- [x] Remove the "Choose Blockchain" state (Add Token)
- [x] Implement new layouts for "Add Token" page

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=31714%3A1997

**Comment by TalgatNurdinov** [comment]
These improvements will be implemented in the next sprints (keep in mind)

- In Search results should be included coins from JSON file if coin not found in featured list
- After switching on, show spinner when checking decimals and switch on the coin

**Comment by rafaelekol** [comment]
I updated the code, can you test the functionality again.
