### ISSUE TITLE
[Bug] unable to send btc (update 4/17. bch also affected)

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#3490]
I received without an issue. If I try to send, everything looks to be in order - the transaction tab shows pending etc. But the transaction never reaches the blockchain. My balance is updated to reflect the debit but if I clear app data and resync, the transactions disappear and my balance is back to normal.

Account type is bip84 

Android 10 Huawei p30

**Comment by Dianaaiym** [comment]
> I received without an issue. If I try to send, everything looks to be in order - the transaction tab shows pending etc. But the transaction never reaches the blockchain. My balance is updated to reflect the debit but if I clear app data and resync, the transactions disappear and my balance is back to normal.
> 
> Account type is bip84
> 
> Android 10 Huawei p30

Hi,

Thank your for the feedback!
Try to send  the tx again and then send us transaction ID or raw transaction.

Our support email: support.unstoppable@protonmail.com

**Comment by nahuhh** [comment]
02000000000102ccbd27fb85b432bff01bf8674b1cddae3b1c60ef8698480d64a523010995b9e10000000000feffffff93648556263000e6011728455ec1d05ca92eb6923d2f8d02ff5e618f0c0b85810400000000feffffff02fa5b0100000000001600146afdc4a4285137fdaa939dbc723b7bea5cdad10e10270000000000001600146dca30ab8acc0d4d6a7944db67fe177a87efdc910248304502210092a0503f7f52015f592ddd321fd70f28f333fbb5dcc62673488dc6a7add1cca4022025445173c23c5e63ca54ebeb39807d118be48f79a8fb795ec0d7145bb8dfafb3012102011d78168b8f3a06e83a6ae0e6c1b6cd0e1dccda868be63e6886a4bfe5b63b2002483045022100a121633c05677ea27f9dfc6aea6dba8aa4070b8a415d2b77a6e87ef2ec6f33b702205de464bfc136a06f81af73690e118277a69257ca050b9b9960459d832c9d6938012102011d78168b8f3a06e83a6ae0e6c1b6cd0e1dccda868be63e6886a4bfe5b63b20c7540a00

**Comment by abdrasulov** [comment]
Hi @nahuhh,

We checked the transaction. It is most likely that the fee of the transaction was not enough. Please try to send it with a higher fee rate.

**Comment by nahuhh** [comment]
Update: 

Using unstoppable, I was not able to get the transaction to show on the blockchain. 
I tried "mycelium" and received s "signing transaction failed" error. ![Screenshot_20210331_082047_com.mycelium.wallet_1.jpg](https://user-images.githubusercontent.com/50635951/113387398-3e825280-935a-11eb-9349-1545088a572b.jpg)
I was able to move my funds using mycelium by choosing "reload account" and trying again.
I tried to reload unstoppable multiple times with no success.
About an HR ago, unstoppable changed the transfer status to failed. (The app SHOULD check the blockchain and "fail" transactions if they cannot be found on the blockchain. Currently it seems to guess until timing out.)
_No idea why it wouldnt even attempt to send. _


Also, try to create a native segwit account using unstoppable then try importing the seed into "bitpay". Not sure what derivation path unstoppable uses, but it appears that native segwit (bc1address) works on 44'/0'/0' but unstoppable is using 84'/0'/0(?). 

Things I'd like to see:
- mycelium allows you to choose between the 3 account types without a sync.
- Mycelium also shows your balance regardless of which account type is selected. 
- Please allow private / public KEY backup, not just seed.

**Comment by nahuhh** [comment]
I'm going to close this for now. I haven't tried to move funds again but I'm going to wait for the update that allows setting fees / byte. I'll reopen if the problem persists on that version.

**Comment by nahuhh** [comment]
Reopening

@abdrasulov 

Attempting to send a small amount 0.019 (20$) worth of BCH appears to cause the same problem. 

The transaction doesn't get broadcast at all. 

https://bch.btc.com/3a0ff0d99d783ab5413d9fa69bee50f4ee4a44ace9fcc3fbe217d280a2e27063

The fee is auto set to 0.00000678

Raw tx 

0200000001b3bc1eddc3d5310ddde7e998767160f15d587525830224a43dcf46be95af933a010000006a47304402206040c70dacf439d5c3ac472899cc85f5251b1a19b559bc6586491ef3b8375b12022008b287240ea7a455ea098701467043441ce0b3a6cb9c97b1bde735bb71c410d341210259643beaa1050083b4f7bbfad59a12fe816f9a495aca25ef15a6a945714555e6feffffff02de000000000000001976a914e6e7dda16604dfadc1c3f418872e13356807e0d088ac48401d00000000001976a91477174cea99b122ebe650338e58b7290ce30294bc88ac5d6f0a00



Need that screenshot toggle.

**Comment by nahuhh** [comment]
Hi. The transactions are still "stuck". 

The only workaround I'm aware of is to delete the wallet or clear app data, and then sync everything. 

Is there any way to clear only bitcoin cash data? If not, could the feature be added? I'm not sure why, but the bad xfer never appear on the blockchain and this time around, unstoppable doesn't seem to be changing then to failed status. 

The transaction should show as failed if it doesn't appear on the blockchain. Not sure what unstoppable is doing (shows pending with a loading animation, but of course it's not actually doing anything.) 

I think.. 
When you open unstoppable and it resyncs, it should check the blockchain for any pending transfers (and fail ones that aren't on chain). It shouldn't resend pending transactions, but possibly give you the option of attempting to resend *failed* transactions. 

Either way, I've been unsuccessful in sending bch. 
Is it working on your end? Try to send 0.04 bch.

Thanks

**Comment by nahuhh** [comment]
@esengulov 

I'm still unable to send bch. 
The never gets broadcast.

Ongoing for over a month. Am I the only one?

Can you reproduce? 
Using
- "New" address format
