### ISSUE TITLE
Add new tokens

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#3496]
- [x] Pundi (PUNDIX)
- [x] YIELDWATCH

- [x] Binance-Peg Cardano Token (ADA)
- [x] Alice (ALICE)
- [x] AlpaToken (ALPA)
- [x] AlpacaToken (ALPACA)
- [x] MTLX-ERC20 (anyMTLX)
- [x] AS Rome (ASR)
- [x] Atletico de Madrid (ATM)
- [x] Binance-Peg Cosmos Token (ATOM)
- [x] AllianceBlock Token (bALBT)
- [x] bDollar (BDO)
- [x] Beflect.finance (BFI)
- [x] Multiplier(bMXX)
- [x] Bondly Token (BONDLY)
- [x] OPEN Governance Token (bOPEN)
- [x] Sushi (SUSHI)
- [x] BUX Token (BUX)
- [x] CanYaCoin (CAN)
- [x] Contentos (COS)
- [x] dego.finance (DEGO)
- [x] DeXe (DEXE)
- [x] DefiDollar DAO (DFD)
- [x] DODO bird (DODO)
- [x] Binance-Peg Polkadot Token (DOT)
- [x] Dusk Network (DUSK)
- [x] Elrond (EGLD)
- [x] Binance-Peg EOS Token (EOS)
- [x] Ellipsis (EPS)
- [x] The Force Token (FOR)
- [x] fry.world (FRIES)
- [x] Frontier Token (FRONT)
- [x] Fuel Token (FUEL)
- [x] GourmetGalaxy (GUM)
- [x] Hakka Finance on xDai on BSC (HAKKA)
- [x] HARD (HARD)
- [x] Helmet.insure Governance Token (HELMET)
- [x] Hedget (HGET)
- [x] Horizon Protocol (HZN)
- [x] Injective Protocol (INJ)
- [x] Binance-Peg IoTeX Network (IOTX)
- [x] ITAM (ITAM)
- [x] Juggernaut DeFi (JGN)
- [x] Juventus (JUV)
- [x] Wrapped Mirror AMZN Token (mAMZN)
- [x] Math Token (MATH)
- [x] Wrapped Mirror GOOGL Token (mGOOGL)
- [x] Wrapped MIR Token (MIR)
- [x] Wrapped Mirror NFLX Token (mNFLX)
- [x] Wrapped Mirror TSLA Token (mTSLA)
- [x] Lien (LIEN)
- [x] LINK (LINK)
- [x] Litentry (LIT)
- [ ] Lympo Market Token (LMT)
- [x] LTO Newtork (LTO)
- [x] NAR Token (NAR)
- [x] NULS (NULS)
- [x] NerveNetwork (NVT)
- [x] Nyaswop Token (NYA)
- [x] Oddz Token (ODDZ)
- [x] OG (OG)
- [x] Binance-Peg Ontology Token (ONT)
- [x] PolyCrowns (pCWS)
- [x] Perlin (PERL)
- [x] Prometeus (PROM)
- [x] Paris Saint-Germain (PSG)
- [x] QUSD Stablecoin (QUSD)
- [x] RAMP DEFI (RAMP)
- [x] Reef.finance (REEF)
- [x] renBTC (renBTC)
- [x] renDOGE (renDOGE)
- [x] renZEC (renZEC)
- [x] SafeMoon (SAFEMOON)
- [x] bDollar Share (sBDO)
- [x] SafePal Token (SFP)
- [x] SPARTAN PROTOCOL TOKEN (SPARTA)
- [x] StableX Token (STAX)
- [x] Binance-Peg SushiToken (SUSHI)
- [x] Suterusu  (SUTER)
- [x] Swampy (SWAMP)
- [x] SWGb (SWGb)
- [x] Swipe (SXP)
- [x] Tokocrypto Token (TKO)
- [x] Alien Worlds Trilium (TLM)
- [x] TokenPocket Token  (TPT)
- [x] UniTrade (TRADE)
- [x] Tixl Token (TXL)
- [x] Uniswap Finance  (UNFI)
- [x] Binance-Peg Uniswap (UNI)
- [x] Binance-Peg USD Coin (USDC)
- [ ] dForce USDT (USDT)
- [x] Wrapped UST Token (UST)
- [x] VAI Stablecoin (VAI)
- [x] Wrapped SOTE (wSOTE)
- [x] Exeedme (XED)
- [x] Standard on xDai on BSC (xMARK)
- [ ] Binance-Peg XRP Token (XRP)
- [x] Binance-Peg Tezos Token (XTZ)
- [x] Venus (XVS)
- [x] ZeroSwap (ZEE)
- [x] Zilliqa (ZIL)

____

- [ ] Kyber Network Crystal Legacy
- [ ] THORChain ETH.RUNE
- [ ] Rune(RUNE) bep20
- [ ] Erowan (EROWAN) erc20
- [ ] dForce(DF) 0x431ad2ff6a9c365805ebad47ee021148d6f7dbe0 - erc20
- [ ] DeFiner 0x054f76beED60AB6dBEb23502178C52d6C5dEbE40 - erc20
- [ ] NuCypher  0x4fE83213D56308330EC302a8BD641f1d0113A4Cc - erc20
- [ ] Torn Token 0x77777feddddffc19ff86db637967013e6c6a116c - erc20
- [ ] Dusk Token -0x940a2db1b7008b6c776d4faaca729d6d4a4aa551 - erc20
- [ ] Sentinel (SENT) 0xa44e5137293e855b1b7bc7e2c6f8cd796ffcb037 - erc20 (apply changes in market categization)
- [ ] HOPR Token 0xf5581dfefd8fb0e4aec526be659cfab1f8c781da - erc20
- [ ] Parsiq (PRQ) 0x362bc847A3a9637d3af6624EeC853618a43ed7D2 erc20
- [ ] BDP 0xf3dcbc6d72a4e1892f7917b7c43b74131df8480e -  erc20
- [ ] DEXT 0x26ce25148832c04f3d7f26f32478a9fe55197166 - erc20
- [ ] GLQ 0x9f9c8ec3534c3ce16f928381372bfbfbfb9f4d24 - erc20
- [ ] UniWhales (UWL) 0xdbDD6F355A37b94e6C7D32fef548e98A280B8Df5 - erc20
- [ ] Kylin Network (KYL) 0x67b6d479c7bb412c54e03dca8e1bc6740ce6b99c - erc20
- [ ] Umbrella Network (UMB) 0x6fc13eace26590b80cccab1ba5d51890577d83b2 - erc20
- [ ] Razor (RAZOR) 0x50de6856358cc35f3a9a57eaaa34bd4cb707d2cd - erc20
- [ ] Option Room 0xad4f86a25bbc20ffb751f2fac312a0b4d8f88c64 - erc20
- [ ] Polkamarkets (Polka) 0xd478161c952357f05f0292b56012cd8457f1cfbf - erc20
- [ ] Fantom (FTM) 0x4e15361fd6b4bb609fa63c81a2be19d873717870 - erc20
- [ ] Pancake Bunny 0xc9849e6fdb743d08faee3e34dd2d1bc69ea11a51 -bep20
- [ ] Bella 0xa91ac63d040deb1b7a5e4d4134ad23eb0ba07e14 - erc20
- [ ] Vesper Finance 0x1b40183efb4dd766f11bda7a7c3ad8982e998421 - erc20
- [ ] DFI.money 0x4be40bc9681D0A7C24A99b4c92F85B9053Fc2A45 - erc20
- [ ] Value 0x49e833337ece7afe375e44f4e3e8481029218e5c - erc20
- [ ] Shroom 0xed0439eacf4c4965ae4613d77a5c2efe10e5f183 - erc20
- [ ] ppay 0x054D64b73d3D8A21Af3D764eFd76bCaA774f3Bb2 - erc20
- [ ] Blank 0xaec7e1f531bb09115103c53ba76829910ec48966 - erc20
- [ ] DIGG 0x798d1be841a82a273720ce31c822c61a67a601c3 - erc20
- [ ] Benchmark 0x67c597624B17b16fb77959217360B7cD18284253 - erc20
- [ ] Ditto 0x233d91a0713155003fc4dce0afa871b508b3b715 - bep20
- [ ] coil 0x3936Ad01cf109a36489d93cabdA11cF062fd3d48 - erc20
- [ ] Fei 0x956F47F50A910163D8BF957Cf5846D573E7f87CA - erc20
- [ ] Reserve RSV 0x196f4727526eA7FB1e17b2071B3d8eAA38486988 erc20
- [ ] mStable mBTC 0x945facb997494cc2570096c74b5f66a3507330a1 erc20
- [ ] FTT 0x50d1c9771902476076ecfc8b2a83ad6b9355a4c9 - erc20
- [ ] Leo 0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3 - erc20
- [ ] BTMX 0xcca0c9c383076649604eE31b20248BC04FdF61cA - erc20
- [ ] WOO 0x4691937a7508860f876c9c0a2a617e7d9e945d4b - erc20 
- [ ] TKO 0x9f589e3eabe42ebc94a44727b3f3531c0c877809 bep20
- [ ] ZMT
- [ ] OKT
- [ ] MX
- [ ] OXY
- [ ] ROOK 0xfA5047c9c78B8877af97BDcb85Db743fD7313d4a erc20
- [ ] ARMOR 0x1337def16f9b486faed0293eb623dc8395dfe46a erc20
- [ ] NFTX 0x87d73E916D7057945c9BcD8cdd94e42A6F47f776 erc20
- [ ] SDEFI 0xe1afe1fd76fd88f78cbf599ea1846231b8ba3b6b erc20
- [ ] DEGEN 0x126c121f99e1e211df2e5f8de2d96fa36647c855 erc20
- [ ] ERN 0xbbc2ae13b23d715c30720f079fcd9b4a74093505 erc20
- [ ] TVK 0xd084b83c305dafd76ae3e1b4e1f1fe2ecccb3988 erc20
- [ ] Whale 0x9355372396e3F6daF13359B7b607a3374cc638e0 erc20
- [ ] Muse 0xb6ca7399b4f9ca56fc27cbff44f4d2e4eef1fc81 erc20
- [ ] DAO Maker 0x0f51bb10119727a7e5ea3538074fb341f56b09ad. erc20
- [ ] GALA 0x15D4c048F83bd7e37d49eA4C83a07267Ec4203dA erc20
- [ ] GHST 0x3F382DbD960E3a9bbCeaE22651E88158d2791550 erc20
- [ ] REVV 0x557B933a7C2c45672B610F8954A3deB39a51A8Ca erc20
- [ ] CWS 0xac0104cca91d167873b8601d2e71eb3d4d8c33e0 erc20
- [ ] OVR 0x21bfbda47a0b4b5b1248c767ee49f7caa9b23697 erc20
- [ ] CRE 0x115ec79f1de567ec68b7ae7eda501b406626478e erc2
- [ ] Aergo 0x91Af0fBB28ABA7E31403Cb457106Ce79397FD4E6 erc20
- [ ] Metadium 0xde2f7766c8bf14ca67193128535e5c7454f8387c erc20
- [ ] BLZ 0x5732046a883704404f284ce41ffadd5b007fd668 erc20
- [ ] UNFI Protocol 0x441761326490cACF7aF299725B6292597EE822c2 erc20
- [ ] PKF 0x8b39b70e39aa811b69365398e0aace9bee238aeb erc20
- [ ] STETH 0xdfe66b14d37c77f4e9b180ceb433d1b164f0281d erc20
- [ ] SGT 0x84810bcf08744d5862b8181f12d17bfd57d3b078
- [ ] SUPER 0xe53ec727dbdeb9e2d5456c3be40cff031ab40a55 erc20
- [ ] KONO 0x850aab69f0e0171a9a49db8be3e71351c8247df4 erc20

**Comment by nahuhh** [comment]
Can you also look at adding

XRP (native)
XMR
DOGE
