### ISSUE TITLE
Update Categories

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#3499]
- [x] Remove category 'Governance'
- [x] Add Category "Fan Tokens"
>> Digital fan tokens, typically specific to a team or club .
- [x] Add category "Investment Tools"
>> Token-powered analytics and investment instruments.

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=28049%3A656

change "Prediction" category icon to new icon, for "Investment Tools" use market icon which used by Prediction. Added new icons for Prediction and Fan tokens
