### ISSUE TITLE
markets overview: redesign top section of the page

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#3504]
- [x] top section needs to be slightly redesigned. 
- [x] top 4 boxes (Total, Volume, BTC Dominance, DeFi cap, DeFi TVL) need to be clickable and will open a detailed overview of the parameter. Details for those secondary pages will be provided in a separate issue. See prototype here, https://www.figma.com/proto/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=31109%3A234825&viewport=11508%2C-7672%2C0.5&scaling=scale-down&page-id=23685%3A0

**Comment by TalgatNurdinov** [comment]
Please reduce the size of circle indicator to 44px (total market cap change)
