### ISSUE TITLE
markets overview: add standalone pages for Total Volume, BTC Dominance, DeFi cap, DeFi TVL

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#3505]
The top section for markets overview should now allow user to expand the parameter and browse its changes over the extended period of time. The data endpoints are already in place.

These 4 secondary pages will have similar layout with chart on the top and list of items below it. Note that 'view mode' options for the list will change for each page.

- [ ] BTC Dominance

- displays btc dominance chart over 3 months period
- the list shows top tokens by market cap
- sorting option: Market Cap (UP / DOWN)
- the list can have three different view modes for amount values (usd, btc, eth)
- the list can have two different view modes for market cap (Market Cap / Diluted Cap)

- [ ] 24h Volume

- displays volume chart over 3 months period
- the list shows top tokens by volume
- sorting option: Volume Change % (UP / DOWN)
- the list can have three different view modes for amount values (usd, btc, eth)

- [ ] DeFi cap

- displays DeFi cap chart over 3 months period
- the list shows top DeFi tokens by market cap 
- sorting option: Market Cap (UP / DOWN)
- the list can have three different view modes for amount values (usd, btc, eth)
- the list can have two different view modes for market cap (Market Cap / Diluted Cap)

- [ ] DeFi TVL

- displays DeFi TVL chart over 3 months period
- the list shows top DeFi tokens by TVL
- sorting option: TVL Change % (UP / DOWN)
- the list can have three different view modes for amount values (usd, btc, eth)
- the list can have two different view modes for TVL (TVL / Adjusted TVL)

See demo, 
https://www.figma.com/proto/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=31109%3A234825&viewport=11508%2C-7672%2C0.5&scaling=scale-down&page-id=23685%3A0

**Comment by TalgatNurdinov** [comment]
Layouts
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=31782%3A36
