### ISSUE TITLE
[Feature request] custom fees change

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#3507]
Knowing the "total" cost of the transaction is good to know but what is important for setting up a transaction is not the total, but the fee/byte.

- When selecting "low, medium, high" it should show the fee/byte below the total costs.
- for "custom" you should be able to set the fee/byte. 
- I think the slider can be removed

Thanks

**Comment by esengulov** [comment]
thanks noted, this is already planned for the very near future, likely in version 0.22

**Comment by nahuhh** [comment]
Closing as the 0.2 update addresses my major concern with the addition of the popup that shows the fee in sat/byte

Two things I think would work well here 

1. A setting to choose the default fee section (low, rec, high, custom). I'd prefer custom
Or
Always have the slider available and auto switch to custom when it interacted with?
2. In the blank space below the "next' button, display the info in the attached screenshot 

Thank you
![Screenshot_20210414_205140.jpg](https://user-images.githubusercontent.com/50635951/114798656-d6713a80-9d63-11eb-88fe-d378ee001dad.jpg)

**Comment by nahuhh** [comment]
@esengulov 

Attempting to send a small amount 0.019 (20$) worth of BCH appears to cause the same problem. 

The transaction doesn't get broadcast at all. 

https://bch.btc.com/3a0ff0d99d783ab5413d9fa69bee50f4ee4a44ace9fcc3fbe217d280a2e27063

The fee is auto set to 0.00000678

Raw tx 

0200000001b3bc1eddc3d5310ddde7e998767160f15d587525830224a43dcf46be95af933a010000006a47304402206040c70dacf439d5c3ac472899cc85f5251b1a19b559bc6586491ef3b8375b12022008b287240ea7a455ea098701467043441ce0b3a6cb9c97b1bde735bb71c410d341210259643beaa1050083b4f7bbfad59a12fe816f9a495aca25ef15a6a945714555e6feffffff02de000000000000001976a914e6e7dda16604dfadc1c3f418872e13356807e0d088ac48401d00000000001976a91477174cea99b122ebe650338e58b7290ce30294bc88ac5d6f0a00



Need that screenshot toggle.

**Comment by nahuhh** [comment]
![20210417_183159.jpg](https://user-images.githubusercontent.com/50635951/115128460-ea0ee200-9fab-11eb-90ba-01be89da68eb.jpg)
![20210417_183329.jpg](https://user-images.githubusercontent.com/50635951/115128464-eed39600-9fab-11eb-820b-42bb5b6b3080.jpg)
