### ISSUE TITLE
[request] WalletConnect system ui support

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#3530]
When tapping on "connect" in a WalletConnect prompt, I am given examples of compatible apps that I have installed. 

Request is for unstoppable to work the same.

Screenshot attached 
![Screenshot_20210412_193702.jpg](https://user-images.githubusercontent.com/50635951/114475801-f4edff00-9bc6-11eb-82ce-5d550387ea44.jpg)

**Comment by abdrasulov** [comment]
Hi @nahuhh. Thanks for you feedback. We have had a ticket for it already #3284. We'll work on it in the upcoming sprints
