### ISSUE TITLE
Please fix the reproducibility of 0.20.0

### ISSUE THREAD

**Issue by Giszmo** [horizontalsystems/unstoppable-wallet-android#3545]
It's a tiny detail but by the strict rules it's still a diff that makes the app "not reproducible". Apparently you changed the support email address between building the release and tagging the version. You will find the full review in some minutes [here](https://walletscrutiny.com/android/io.horizontalsystems.bankwallet/).

----

The content of the linked page:

Here is the output using our [test script](https://gitlab.com/walletscrutiny/walletScrutinyCom/blob/master/test.sh) on the binary from Google Play:

```
Results:
appId:          io.horizontalsystems.bankwallet
signer:         c1899493e440489178b8748851b72cbed50c282aaa8c03ae236a4652f8c4f27b
apkVersionName: 0.20.0
apkVersionCode: 41
apkHash:        1a98f8bec96d1e50b6aa6fe2cb9116b16ec1b48f71241c9081ac67dadc7166d9

Diff:
Files /tmp/fromPlay_io.horizontalsystems.bankwallet_41/apktool.yml and /tmp/fromBuild_io.horizontalsystems.bankwallet_41/apktool.yml differ
Only in /tmp/fromPlay_io.horizontalsystems.bankwallet_41/original/META-INF: MANIFEST.MF
Only in /tmp/fromPlay_io.horizontalsystems.bankwallet_41/original/META-INF: RELEASEK.RSA
Only in /tmp/fromPlay_io.horizontalsystems.bankwallet_41/original/META-INF: RELEASEK.SF
Files /tmp/fromPlay_io.horizontalsystems.bankwallet_41/smali_classes2/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.smali and /tmp/fromBuild_io.horizontalsystems.bankwallet_41/smali_classes2/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.smali differ
```

Unfortunately that is one file too many. Upon closer inspection it looks totally benign though:

```
$ diff /tmp/from{Play,Build}_io.horizontalsystems.bankwallet_41/smali_classes2/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.smali
205c205
<     const-string v0, "unstoppable.support@protonmail.com"
---
>     const-string v0, "support.unstoppable@protonmail.com"
```

so while we do not ring the alarm over this, we unfortunately have to give it the verdict **not verifiable** until they produce a revision with the right email address.

Thank you to Horizontal Systems for repeat donations:

* [$200 2020-12-09](https://twitter.com/WalletScrutiny/status/1336651531442155522)
* [$200 2021-04-13](https://twitter.com/WalletScrutiny/status/1382161902399262720)

**Comment by Dianaaiym** [comment]
Hi Leo,

We have released a build with updated mail.  Please review our build in the market.

Best Regards,
HS Team

> It's a tiny detail but by the strict rules it's still a diff that makes the app "not reproducible". Apparently you changed the support email address between building the release and tagging the version. You will find the full review in some minutes [here](https://walletscrutiny.com/android/io.horizontalsystems.bankwallet/).
> 
> 
> 
> ----
> 
> 
> 
> The content of the linked page:
> 
> 
> 
> Here is the output using our [test script](https://gitlab.com/walletscrutiny/walletScrutinyCom/blob/master/test.sh) on the binary from Google Play:
> 
> 
> 
> ```
> 
> Results:
> 
> appId:          io.horizontalsystems.bankwallet
> 
> signer:         c1899493e440489178b8748851b72cbed50c282aaa8c03ae236a4652f8c4f27b
> 
> apkVersionName: 0.20.0
> 
> apkVersionCode: 41
> 
> apkHash:        1a98f8bec96d1e50b6aa6fe2cb9116b16ec1b48f71241c9081ac67dadc7166d9
> 
> 
> 
> Diff:
> 
> Files /tmp/fromPlay_io.horizontalsystems.bankwallet_41/apktool.yml and /tmp/fromBuild_io.horizontalsystems.bankwallet_41/apktool.yml differ
> 
> Only in /tmp/fromPlay_io.horizontalsystems.bankwallet_41/original/META-INF: MANIFEST.MF
> 
> Only in /tmp/fromPlay_io.horizontalsystems.bankwallet_41/original/META-INF: RELEASEK.RSA
> 
> Only in /tmp/fromPlay_io.horizontalsystems.bankwallet_41/original/META-INF: RELEASEK.SF
> 
> Files /tmp/fromPlay_io.horizontalsystems.bankwallet_41/smali_classes2/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.smali and /tmp/fromBuild_io.horizontalsystems.bankwallet_41/smali_classes2/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.smali differ
> 
> ```
> 
> 
> 
> Unfortunately that is one file too many. Upon closer inspection it looks totally benign though:
> 
> 
> 
> ```
> 
> $ diff /tmp/from{Play,Build}_io.horizontalsystems.bankwallet_41/smali_classes2/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.smali
> 
> 205c205
> 
> <     const-string v0, "unstoppable.support@protonmail.com"
> 
> ---
> 
> >     const-string v0, "support.unstoppable@protonmail.com"
> 
> ```
> 
> 
> 
> so while we do not ring the alarm over this, we unfortunately have to give it the verdict **not verifiable** until they produce a revision with the right email address.
> 
> 
> 
> Thank you to Horizontal Systems for repeat donations:
> 
> 
> 
> * [$200 2020-12-09](https://twitter.com/WalletScrutiny/status/1336651531442155522)
> 
> * [$200 2021-04-13](https://twitter.com/WalletScrutiny/status/1382161902399262720)
> 
>
