### ISSUE TITLE
[bug] Zcash and bitcoin sync issues

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#3548]
These appear to be separate things causing these issues but both sync related 

Zsync:
When reopening unstoppable from the backgroind, zync often gives the "failed to sync" error. Tapping the warning sign and then "retry" sometimes results in nothing happening but and close and reopen will fix it. This seems to be an app issue

Bitcoin: 
occasionally I will open unstoppable and bitcoin will stay stuck at "syncing 0%". This one sounds like a server problem. No issues with litecoin, bitcoin cash or ethereum 

I wasn't using zcash on the previous version so I cannot compare. I believe bitcoin had intermittent sync issues but they seem to be happening more often

Thank you

Android 10 
V 0.20.0 (apk that was on github)

**Comment by abdrasulov** [comment]
I couldn't reproduce the issue. Will check it later.

**Comment by nahuhh** [comment]
Zcash appears to run noticeably better on latest 2 releases. 

Closing. Will reopen if the issue persists
