### ISSUE TITLE
Balance Screen: Update UI

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#3555]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=31662%3A275447

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=29564%3A3594

**Comment by TalgatNurdinov** [comment]
@omurovch please fix the left margin of title (16px)
