### ISSUE TITLE
[Bug] occasionally unable to select transfer tab 

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#3564]
Occasionally (more than 2 times per day) I will open unstoppable and the transfer tab is greyed out (not selectable). Closing and reopening unstoppable corrects this until the next time it happens.

I didn't notice this issue (at all) on the previous version 

Currently running the Google play release of 0.20.0 on android 10

Update: running 0.21.1 now

Thank you

**Comment by abdrasulov** [comment]
Hi @nahuhh,

I've started working on this issue. As of now, I couldn't reproduce it. Based on the code, the transactions tab should be disabled (greyed out) only if there is no wallet created/restored. Do you have any thoughts about the steps to reproduce it?

**Comment by nahuhh** [comment]
It does seem to happen at random. I've been trying reproduce all night. 

I'm going to keep a close eye and hopefully I can catch it in action. 
Fwiw, I have multiple wallets and all show under the wallet tab. Just the transfer tab would be greyed out / nonselectable

**Comment by abdrasulov** [comment]
Thanks for your active participation!

We'll keep an eye on it, too.

**Comment by nahuhh** [comment]
![Screenshot_20210523_025735_1.jpg](https://user-images.githubusercontent.com/50635951/119251124-c45c9600-bb72-11eb-9dec-f9930282423d.jpg)

**Comment by nahuhh** [comment]
Has been harder to reproduce. Perhaps because I'm likely opening and closing less often. But it did just happen again.

**Comment by nahuhh** [comment]
Once more today. 

- app was not running in background (was not in recent apps and hadn't been used in hours)
- wallets are active 

![Screenshot_20210524_114353_io.horizontalsystems.bankwallet.jpg](https://user-images.githubusercontent.com/50635951/119372530-6c628400-bc85-11eb-9b8a-4de148a35a57.jpg)

**Comment by nahuhh** [comment]
> Thanks for your active participation!
> 
> We'll keep an eye on it, too. 

As I'm noticing this happen more and more often, it "feels" like a timing issue. 


I AM now about to reproduce 100% of the time. 

1. Open app
2. Send to background
3. Swipe remove from recent apps
4. As fast as possible, reopen unstoppable 

Transfer tab is greyed out everytime. 
While this isnt the typical use case for how I encounter it (happens randomly on a fresh start), closing the app and reopening as fast as possible has the same result.

**Comment by abdrasulov** [comment]
I couldn't reproduce the issue. The applied solution is based on the code. Used the number of accounts right from DB instead of cached one when setting the state of transactions tab selector.

**Comment by nahuhh** [comment]
> I couldn't reproduce the issue. The applied solution is based on the code. Used the number of accounts right from DB instead of cached one when setting the state of transactions tab selector.

This fix is not in 0.21.2, correct? Waiting for 0.22.x

**Comment by abdrasulov** [comment]
Yes, it's coming in version 0.22
