### ISSUE TITLE
Error parsing ERC-721 transactions

### ISSUE THREAD

**Issue by nk-the-crazy** [horizontalsystems/unstoppable-wallet-android#3598]
Address in  **Green** is  an Ethereum Account address (wallet)
Address in **Red** is  an ENS contract address
Transaction marked as outgoing

<img width="379" alt="Screen Shot 2021-04-26 at 5 55 57 PM" src="https://user-images.githubusercontent.com/11713346/116083543-8331ad00-a6be-11eb-9129-11730e3ac56c.png">

**Comment by esengulov** [comment]
Closing the issue as such behavior is expected at the time being. Unstoppable doesn't support parsing of ERC-721 transactions
