### ISSUE TITLE
markets: issues with TVL in DEFI charts

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#3600]
The charts for TVL do not look nice at the moment (see in the image below). 

This likely happens due to the way the TVL data being collected from Defilama by our remote worker as well as how the data being updated on Defilama itself.

- [x] The easiest fix would be to smoothen the chart on a client side.
- [ ] if the client side fix works, please create the issue for iOS client

**Comment by esengulov** [comment]
![IMG_3296](https://user-images.githubusercontent.com/8611762/116220789-d06d5780-a76e-11eb-8897-cbad3bd59dd0.jpg)

**Comment by nk-the-crazy** [comment]
Fix on on backend side (MarketsAPI)
