### ISSUE TITLE
btc and bsc no internet connection

### ISSUE THREAD

**Issue by bitcard** [horizontalsystems/unstoppable-wallet-android#3602]
the wallet btc and bsc no internet connection, so no sync tx data, the eth status is ok.

**Comment by Dianaaiym** [comment]
> the wallet btc and bsc no internet connection, so no sync tx data, the eth status is ok.

Hi,

Please send us your App Status (Settings - About App)

**Comment by bitcard** [comment]
![Screenshot_1619657882](https://user-images.githubusercontent.com/9978206/116490136-38d04c00-a8c9-11eb-9a7a-6d764d83c710.png)

App Status

**Comment by tmedetbekov** [comment]
Can't reproduced this issue, tested on Xiaomi note 6 pro and on Emulator with Android 11. Feel free to reopen and send more details if problem still reproduces on your device.
