### ISSUE TITLE
No TVL chart data for ALPHA Token

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#3634]
![photo_2021-04-30_13-36-45](https://user-images.githubusercontent.com/22589457/116685742-83ca8c00-a9bb-11eb-9125-22733c69e9b5.jpg)

**Comment by rafaelekol** [comment]
Tokens  like Alpha, MKR don't have value changes in TVL for latest periods. Because of that app can't draw chart for them in 1 day and 7 days periods. Both Android and IOs platforms are affected by this issue.
