### ISSUE TITLE
coin page enhancements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#3639]
markets tab >> overview boxes (BTC dominance, ...)

- [x] display source 'Powered By DefiLlama API' below the chart for BTC dominance, 24h volume, DeFi cap and TVL in DeFi

coin page >> Volume data

- [x] 1st cell 'Trading Volume (24h)' : display 24h volume data and on click should open chart. Similar to how it works for TVL data.
- [x] 2nd cell 'Markets': should open markets where the coin is traded.

coin page  >> Investor data

- [ ] 1st cell 'Major Holders' : opens a page
-- rename 'Top 10 Holders' to 'Top Wallets'
-- change the text below the % in chart to 'in top 10 wallets' 
-- bottom text: 'Chart above shows the % of all tokens in circulation held by top 10 wallets. The lower the % the more 
- [x] 2nd cell 'Funds Invested' : opens a page
- [ ] 3rd cell 'Treasuries' : opens a page
- [x] 4th cell 'Reports' : opens a page

coin page  >> also apply following items

- [x] display market cap rank label next Market Cap data
- [x] add Launch Date entry below the Dilluted M.Cap
- [x] make 'TVL Rank' cell clickable, it should open a page(visually similar to traceable markets list) that lists all protocols, sorted by TVL. @kansalt 

As a result the hierarchy below the ROI box should be as follows:

1. market cap and coin data
2. volume data
3. TVL data
4. Investor data

coin page >> bottom links

- [x] display actual site domain instead of 'website' text
- [x] display actual Twitter handle instead of 'twitter' text
- [x] if user has twitter app installed then open the link directly in the app

**Comment by TalgatNurdinov** [comment]
- [ ] Change the "Launch Date" title to "Inception Date"
- [ ] Add Security Parameters section
