### ISSUE TITLE
Coin search improvements

### ISSUE THREAD

**Issue by esen** [horizontalsystems/unstoppable-wallet-android#3641]
Coin search must sort coins by the following order:

Exact coin code match
Exact coin name match
Coin is categorized
Coin is in top 1000 of coinGecko provider
Others

**Comment by TalgatNurdinov** [comment]
coin format badge
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=29015%3A174525
