### ISSUE TITLE
transactions tab refactoring (UI and architecture)

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#3678]

**Comment by TalgatNurdinov** [comment]
- [ ] Add coin code for unlimited value in the approvals cells  (unlimited CRV)

- [ ] Remove “-“ from sent transactions 

- [ ] Add blockchain names for contract calls

- [ ] Disable revoke approval cell from transaction info

- [ ] Need to change the places of value and rate in transaction info, value in base currency should be main (ui was changed after testing)
