### ISSUE TITLE
Coin Page Enhancements

### ISSUE THREAD

**Issue by Dadybayo** [horizontalsystems/unstoppable-wallet-android#3688]
- Apply the new design to the ROI table 

 - Add "vs BNB"

**Comment by nahuhh** [comment]
![Screenshot_20210525_163823.jpg](https://user-images.githubusercontent.com/50635951/119565205-b035b600-bd77-11eb-9a3d-785aa161e46f.jpg)

Hi. I noticed the "vs bnb" in the latest version. 

I do not trade in binance or use bnb, nor do I consider bnb to be a obvious choice (like eth and btc)

I was going to open a feature request but I will ask here. 


Can we
1. Add back vs 1 year
2. Add an option to choose another coin (to replace bnb). 

To be honest, it would be nice to have each of them be custom. 

Personally, I'd have mine set something like 

1 - a stablecoin (usdt or usdc. Some may use their chosen trading pair or one representing their native currency)
2 - bitcoin 
3 - eth
4 - either my exchange token or another coin I'm holding. 

Thanks
