### ISSUE TITLE
Coin page does not display blockchain/protocol icons

### ISSUE THREAD

**Issue by Dadybayo** [horizontalsystems/unstoppable-wallet-android#3693]

**Comment by Dadybayo** [comment]
![photo_2021-05-08 19 10 14](https://user-images.githubusercontent.com/33674013/117540395-0b09a680-b031-11eb-8948-084edd953828.jpeg)

**Comment by Dianaaiym** [comment]
fix margins
![IMG_20210509_221855_056](https://user-images.githubusercontent.com/22589457/117656496-3d92db00-b1ba-11eb-9f25-1bb74cb61789.jpg)
