### ISSUE TITLE
app welcome screen : text changes

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#3712]
- main screen: should show icon at the top and 'Be Unstoppable' text below
- 2nd screen
-- title >> Unchain Assets
-- text >> Don't lock yourself in and don't let others do that to you.
- 3rd screen
-- title >> Go Borderless
-- text >> Bypass conditional barriers and access markets globally.
- 4th screen
-- title >> Stay Private
-- text >> Do not leak your private and financial data to the world.

**Comment by kansalt** [comment]
Layouts
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=34877%3A323175
