### ISSUE TITLE
Latest Release 0.21 on github missing apk file

### ISSUE THREAD

**Issue by emanuelb** [horizontalsystems/unstoppable-wallet-android#3726]
There is no apk file as asset in latest release 0.21 in github:
https://github.com/horizontalsystems/unstoppable-wallet-android/releases/tag/0.21.0

There are apk files in previous releases:
https://github.com/horizontalsystems/unstoppable-wallet-android/releases

Please continue to publish apk in github releases.

**Comment by Dianaaiym** [comment]
> There is no apk file as asset in latest release 0.21 in github:
> https://github.com/horizontalsystems/unstoppable-wallet-android/releases/tag/0.21.0
> 
> There are apk files in previous releases:
> https://github.com/horizontalsystems/unstoppable-wallet-android/releases
> 
> Please continue to publish apk in github releases.

Uploaded!
