### ISSUE TITLE
show user a custom alert when s/he tries to send entire ETH/BNB balance while having active ERC20/BEP20 tokens

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#3730]

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=34977%3A218

https://user-images.githubusercontent.com/42367908/118601029-932b4100-b7d3-11eb-81f9-95d60c57f368.mov

**Comment by esengulov** [comment]
implemented!
