### ISSUE TITLE
Show PIN unlock for screens with sensitive informations

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#374]
Screens that should be locked with PIN code

- [ ] sync with iOS team before implementing and if missing on iOS then create respective issues on  iOS
- [ ] Backup screen. This shouldn't accept FaceID/TouchID/Fingerprint, even if it's activated the PIN should be requested. The same lockout logic as for app unlock should be applied here
- [ ] Unlink from this device. This shouldn't accept FaceID/TouchID/Fingerprint, even if it's activated the PIN should be requested. The same lockout logic as for app unlock should be applied here
- [ ] on Face ID activation
- [ ] on send

**Comment by esengulov** [comment]
The issue is already implemented and no longer relevant
