### ISSUE TITLE
Coin card became collapsed when users return back to Balance page

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#3747]
Reproduce:
Expand coin card in Balance tab, open Send, then return back to Balance tab. Coin card became collapsed.

**Comment by nahuhh** [comment]
https://user-images.githubusercontent.com/50635951/119567862-d27d0300-bd7a-11eb-87d7-a589c5cdf688.mp4

Latest v on android

**Comment by nahuhh** [comment]
Latest version on android. 
Are you using iOS?

https://user-images.githubusercontent.com/50635951/119568126-2687e780-bd7b-11eb-92a0-e9400c6022ab.mp4

**Comment by rafaelekol** [comment]
Try Ethereum wallet

**Comment by nahuhh** [comment]
> Try Ethereum wallet

Reproducible 

ETH = reverts
BCH, LTC, BCH, ZEC = remains
