### ISSUE TITLE
BitcoinCashCoinType is null after updating to 0.21

### ISSUE THREAD

**Issue by russellbanks** [horizontalsystems/unstoppable-wallet-android#3758]
I updated to version 0.21 from Google Play this morning and now the app crashes every time I open it. I have attached the stack trace I get.

It seems to point to [Line 76 in BitcoinCashAdapter.kt](https://github.com/horizontalsystems/unstoppable-wallet-android/blob/d16bd719d8a8b6dc5fb9d4af356be014936c0b69/app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt#L76) which throws an error. Bitcoin Cash was the only currency that I had any money so I imagine this is down to the migration to one wallet for every currency. Any help would be appreciated on a fix, both temporarily and permanently. If you need any other information provided about the crash, I can do my best to give it.

<img src="https://user-images.githubusercontent.com/74878137/119206053-fc3fdc80-ba91-11eb-95c8-793fc24a9016.jpg" alt="Stack trace" width="300"/>

**Comment by abdrasulov** [comment]
Hello @russellbanks,

Thanks for your detailed explanation. We've made a research on this issue on the weekend. As you've mentioned, it is related to the migration. There are cases when the migration doesn't work properly. We've couldn't reproduce the issue on our devices so far. Could you please share the info about android version and what the device you've faced this issue?

As of now, reinstalling app fixes it.

**Comment by abdrasulov** [comment]
Hello @russellbanks,

We've fixed this issue and released a new version. It's being reviewed in Play Store. It should be available soon. 

We also published it here in github. You can download it via this link https://github.com/horizontalsystems/unstoppable-wallet-android/releases/download/0.21.0/unstoppable-wallet-0.21.0.apk
