### ISSUE TITLE
Unable to send BCH

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#3760]
@esengulov 

I'm still unable to send bch. 
The tx never gets broadcast.

Ongoing for over a month. Am I the only one?

Can you reproduce? 
Using
- "New" address format

_Originally posted by @nahuhh in https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3490#issuecomment-834102700_

Initially, they remained pending and 100% of them would fail. Now it is working unreliably? 

![Screenshot_20210523_070242.jpg](https://user-images.githubusercontent.com/50635951/119257921-7c029f80-bb95-11eb-8a8b-345f4d21c149.jpg)

**Comment by nahuhh** [comment]
On the prior version, I was unable to send at all. 

At the time of writing the issue, on the current version, some transactions did work after retrying.

Never had any issues sending litecoin or zcash. (Aside from litecoin fees sometimes being set too low to get processed in a timely manner)

**Comment by esengulov** [comment]
> On the prior version, I was unable to send at all.
> 
> At the time of writing the issue, on the current version, some transactions did work after retrying.
> 
> Never had any issues sending litecoin or zcash. (Aside from litecoin fees sometimes being set too low to get processed in a timely manner)

thanks for the followup

1) re: bch not sending
problem still there? I mean did you experience transaction not sending in the new version. We have fixed the bugs in the latest version and it should work. 

2) re: fees being set low
you mean Zcash transaction fees? if I am not mistaken fees for ZEC/ LTC / DASH / BCH are hardcoded to some minimum values. At the time when this was put in place the blocks for these blockchains nearly always had some empty space. Let us know which one you experienced issues with and we'll revisit.

**Comment by nahuhh** [comment]
> > On the prior version, I was unable to send at all.
> > 
> > At the time of writing the issue, on the current version, some transactions did work after retrying.
> > 
> > Never had any issues sending litecoin or zcash. (Aside from litecoin fees sometimes being set too low to get processed in a timely manner)
> 
> thanks for the followup
> 
> 1) re: bch not sending
> problem still there? I mean did you experience transaction not sending in the new version. We have fixed the bugs in the latest version and it should work. 
> 

1a) yes. Latest version is much improved but issue still present. 
In this screenshot, the sent transactions are after updating. 

It was completely broken before, still not working reliably 
![Screenshot_20210525_093215.jpg](https://user-images.githubusercontent.com/50635951/119506778-3cc28300-bd3c-11eb-8c4d-2f91a9aff54d.jpg)

> 2) re: fees being set low
> you mean Zcash transaction fees? if I am not mistaken fees for ZEC/ LTC / DASH / BCH are hardcoded to some minimum values. At the time when this was put in place the blocks for these blockchains nearly always had some empty space. Let us know which one you experienced issues with and we'll revisit.

2a) yes, zcash is hardcoded. No issues there. 
Not sure about DASH

LTC and BCH are not though. 
Unstoppable appears to set these dynamically (changing depending on how much you are sending) and in all cases but one I've had no issues. 

The one time I did, the transaction took a few hours because the avg fee on blockchain was like around 25c but my fee was set somewhere between 1-3c . (Which is the average in most cases, but this day it was far out of range)

 Here's some litecoin fees from most recent transactions in the current block:
![Screenshot_20210525_094932.jpg](https://user-images.githubusercontent.com/50635951/119509529-b6f40700-bd3e-11eb-83d6-0e1a540555f4.jpg)

May need to have the option to set bch, ltc and other btc forks with custom fees (like bitcoin). Default being "recommended".

**Comment by abdrasulov** [comment]
Hello @nahuhh,

We've found the potential reason why the BCH transaction fails. It depends on the speed of remote peers responses. We are in the process of releasing the hotfix version. We'll let you know when it's available.

**Comment by nahuhh** [comment]
Appears to be working 100% on 21.1 pre-release 

🍻

**Comment by nahuhh** [comment]
While we're here:

In #3490 I had experienced the same issue for bitcoin. 

I have since stopped moving my bitcoin around due to high fees, so I have not tested whether the issue is still present for BTC.

Initial faulty behavior of both btc and bch: 
- both would never send. Unstoppable would show pending but tx never appeared on blockchain.

In v 0.21.0:
- bch became intermittent. I did not test btc.

In v 0.21.1 pre-release
- bch appears to be 100% working. I did not test btc. 

Perhaps bitcoin needs the same tweak as bch?
I'm not sure though (haven't tested btc). Just thought I should bring it up.

**Comment by abdrasulov** [comment]
Great to hear that!

The modified code is common for all bitcoin based blockchains like btc, bch, ltc and dash. So sending btc should become more stable now.

By the way, the updated version has been published in Play Market.

@nahuhh, thank you for all your feedback! It helps us to make our app better.
