### ISSUE TITLE
BEP2 XRP incorrect identified (noticing a few others as well)

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#3765]
XRP is listed in app as "Ripple"
![Screenshot_20210524_190315.jpg](https://user-images.githubusercontent.com/50635951/119417478-e31e7200-bcc3-11eb-884f-377809585fa8.jpg)

As this is not the Ripple / XRP address, it should be listed as

"Ripple BEP2"

Like this

![Screenshot_20210524_190359_io.horizontalsystems.bankwallet.jpg](https://user-images.githubusercontent.com/50635951/119416985-dcdbc600-bcc2-11eb-858b-169b23f3871b.jpg)
Also. 
"ETH BEP2"
 should be 
"Ether BEP2"

More on Ripple listing: 

1. Both "xrp bep 2" and "xrp" charts/data are available
![Screenshot_20210524_191047.jpg](https://user-images.githubusercontent.com/50635951/119417406-c1bd8600-bcc3-11eb-99cc-095dd7222749.jpg)
2. The "Ripple" listing in the "add coin" (actually bep2), clicking the chart brings you to "xrp" chart instead of "xrp bep2" chart. 

I think this should be fixed before adding mainnet xrp, to avoid conflicts

**Comment by Dadybayo** [comment]
1. Replace the name XRP (BEP2) with XRP BEP2
2. When you clicking to chart XRP (BEP2), coin page XRP BEP2 should open

**Comment by Dianaaiym** [comment]
not relevant
