### ISSUE TITLE
update recommended coins list

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#3781]
Update recommended coins list. The tokens which are to be added to the list are marked as recommended in the document (Notion document)

**Comment by Dadybayo** [comment]
- Uniswap 
- Chainlink 
- Polygon 
- Aave 
- Maker 
- PancakeSwap 
- Compound 
- Sushi
- Synthetix 
- yearn.finance
- Curve
- 1inch 
- Balancer
