### ISSUE TITLE
Navigation >> swipe between screens

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#3815]
I noticed on the "show phrase" screen, you are able to swipe to navigate between the seed page and the key page. 

I'd like to request swipe navigation on: 
1. Transfer tab (switch currencies)
2. Wallet tab (switch wallets) 
3. Markets tab (overview, discovery, watchlist) 

Not related ti swipe, but ui on relevant pages:

0a: spacing of "recovery phrase | private key" (should be centered life/right).
0b: "private key" renamed > "private keys"
0c: copy button for private key (with warning that apps can read clipboard without asking permission) 
3a. Equal spacing of "overview, discovery, watchlist" headers. Discovery centered.

**Comment by TalgatNurdinov** [comment]
We are already working on this, you will get this feature in the next updates, thanks for the request

<img width="865" alt="Screen Shot 2021-06-04 at 12 28 50" src="https://user-images.githubusercontent.com/42367908/120756557-3482f880-c531-11eb-972a-a26414143a1f.png">

**Comment by nahuhh** [comment]
Must be my psychic 😋

**Comment by esengulov** [comment]
Issue Merged Into https://github.com/horizontalsystems/unstoppable-wallet-android/issues/4543
