### ISSUE TITLE
Feature request: more coins to show under privacy coin filter

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#3816]
![Screenshot_20210603_175601.jpg](https://user-images.githubusercontent.com/50635951/120717090-ffc16380-c494-11eb-8c7d-a1d3e32e00c2.jpg)

- ARRR
- OXEN

**Comment by Dadybayo** [comment]
We have a guideline for adding new protocols to categories, volume per day must be over $1M

We will add Pirate Chain (ARRR) to the "Privacy" category, but OXEN will not be added
