### ISSUE TITLE
Add TestNet support for EVM blockchains

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#3819]
https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/3137

**Comment by TalgatNurdinov** [comment]
need to add disclaimer on switching network
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=36722%3A436363
