### ISSUE TITLE
Add missing icons

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#3822]
- [x] Internet Computer (ICP) 
- [x] TON Crystal (TON) 
- [x] Theta Fuel (TFUEL)
- [x] Persistence (XPRT)
- [x] GivingToServices (SVCS) 0x9cec686ba6f07d6135b2091140c795166ef5b761 (erc20)
- [x] Klaytn (KLAY)
- [x] Tenset (10SET) 0x7ff4169a6b5122b664c51c95727d87750ec07c84 (erc20)
- [x] Ampleforth Governance Token (FORTH) 0x77fba179c79de5b7653f68b5039af940ada60ce0 (erc20)
- [x] Shiba Inu (SHIB) 0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce (erc20)
- [x] FEG Token (FEG) 0x389999216860ab8e0175387a0c90e5c52522c945  (erc20)
- [x] Mina Protocol (MINA)
- [x] CumRocket (CUMMIES) 0x27ae27110350b98d564b9a3eed31baebc82d878d (bep20)
- [x] Alchemix USD (ALUSD) 0xbc6da0fe9ad5f3b0d58160288917aa56653660e9 (erc20)
- [x] LockTrip (LOC) 0x5e3346444010135322268a4630d2ed5f8d09446c (erc20)
- [x] Sapphire (SAPP) 
- [x] Unit Protocol (COL)
- [x] GNY (GNY) 0xb1f871ae9462f1b2c6826e88a7827e76f86751d4 (erc20) 0xe4a4ad6e0b773f47d28f548742a23efd73798332 (bep20)
- [x] Unit Protocol New (DUCK) 0x92e187a03b6cd19cb6af293ba17f2745fd2357d5 (erc20)
- [x] Alchemist (MIST)  0x88acdd2a6425c3faae4bc9650fd7e27e0bebb7ab (erc20)
- [x] QuickSwap (QUICK)  0x6c28aef8977c9b773996d0e8376d2ee379446f2f (erc20)
- [x] Function X (FX)  0x8c15ef5b4b21951d50e53e4fbda8298ffad25057 (erc20)
- [x]  SONM (SNM)  0x983f6d60db79ea8ca4eb9968c6aff8cfa04b3c63 (erc20)
- [x] ApeSwap (BANANA)  0x603c7f932ed1fc6575303d8fb018fdcbb0f39a95 (bep20)
- [x] WaultSwap (WEX)  0xa9c41a46a6b3531d28d5c32f6633dd2ff05dfb90 (bep20)
- [x] Hoge Finance  0xfad45e47083e4607302aa43c65fb3106f1cd7607 (erc20)
- [x] SERO (SERO)
- [x] EcoFi (ECO)  0xc242eb8e4e27eae6a2a728a41201152f19595c83 (erc20)
- [x] PAID Network  0x1614f18fc94f47967a3fbe5ffcd46d4e7da3d787 (erc20)
- [x] Privateum (PVM) 0x71aff23750db1f4edbe32c942157a478349035b2 (bep20) 
- [x] PEAKDEFI (PEAK) 0x630d98424efe0ea27fb1b3ab7741907dffeaad78 (erc20)
- [x] Refinable (FINE) 0x4e6415a5727ea08aae4580057187923aec331227(bep20)
- [x] Apollo (APL) 
- [x] Cobak Token (CBK) 0xd85a6ae55a7f33b0ee113c234d2ee308edeaf7fd (erc20)
- [x] Smooth Love Potion (SLP) 0xcc8fa225d80b9c7d42f96e9570156c65d6caaa25 (erc20) 
- [x] RAMP (RAMP) 0x33d0568941c0c64ff7e0fb4fba0b11bd37deed9f (erc20)
        0x8519ea49c997f50ceffa444d240fb655e89248aa (bep20)
- [x] Nominex (NMX) 0xd32d01a43c869edcd1117c640fbdcfcfd97d9d65 (bep20)

- [x] Hydra (HYDRA) 
- [x] sEUR (SEUR) 0xd71ecff9342a5ced620049e616c5035f1db98620 (erc20)
- [x] Kirobo (KIRO) 0xb1191f691a355b43542bea9b8847bc73e7abb137 (erc20)
- [x] Evolution Finance (EVN) 0x9af15d7b8776fa296019979e70a5be53c714a7ec (erc20)

**Comment by nahuhh** [comment]
Nominex (NMX)

If possible

**Comment by Dianaaiym** [comment]
> Nominex (NMX)
> 
> If possible

ok, added to the list
