### ISSUE TITLE
Blockhain connectivity settings and Sync error enhancements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#3834]
- [x] Sync error alert on balance tab should always open bottom menu. It currently doesn't open for ETH, ZEC, BSC as there is no option to change the sync source there. Let's still open the menu but without 'change source' button, until we add the ability for the user to interact with the blockchain via personal node.

- [x] Noticed cases when clicking on alert it shows 'no internet' alert. Feels like a big, better to either indicate it on the balance tab or on retry click.

- [x] clicking on 'change source' button should take user to settings for the given wallet (in Manage Wallets).

- [x] remove connectivity/restore related blockchain settings from Privacy section in settings. The privacy controller should only have text about 'no data collected' and Tor/VPN settings. All blockchain related settings should be placed in the settings for the individual wallet, accessible from Manage Wallets section.

- [ ] Manage Wallet screen minor changes
- rename 'Show Phrase' to 'Private Key'
- add 'Transaction settings' and move there privacy related settings (as well as the info text for it) for bitcoin UTXO shuffling. The 'Transaction settings' cell can only appear when the wallet has Bitcoin active. 
- move text from Privacy Info (Blockchain transactions) to 'Transaction settings' page. It can be placed in the same info controller.

- [ ] Wallet >> Network Settings
- this page needs two sections: blockchain sync and blockchain restore.
- 'blockchain sync' section should list sync source for ETH/BSC
- 'blockchain restore' section should list settings for API/blockchain restore
- move texts from Privacy Info (Blockchain Sync, Blockchain Restore) to 'Network Settings' page. It can be placed in the same info controller.

- [ ] Privacy info texts
- 'Select data source for past wallet transactions' text should be placed below 'blockchain restore'

**Comment by TalgatNurdinov** [comment]
updated and new layouts
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=35399%3A359342
