### ISSUE TITLE
Is there a documentation for this wallet?

### ISSUE THREAD

**Issue by talhadar90** [horizontalsystems/unstoppable-wallet-android#3862]
I am working on a wallet for my company and unstoppable seems like a nice option but I wanted to ask if there is any documentation for the wallet to customize like which api keys to change?

1) Infura
2) ETHScan
3) BSCScan
4) Cryptocompare

If I have missed any, please let me know.

**Comment by nk-the-crazy** [comment]
> I am working on a wallet for my company and unstoppable seems like a nice option but I wanted to ask if there is any documentation for the wallet to customize like which api keys to change?
> 
> 1. Infura
> 2. ETHScan
> 3. BSCScan
> 4. Cryptocompare
> 
> If I have missed any, please let me know.

Hi, 

Use app/build.gradle to customize api keys.

On latest version, CryptoCompare is not used. Customize keys for only below items. 
```
resValue "string", "infuraProjectId", "2a..."
resValue "string", "infuraSecretKey", "fc..."
resValue "string", "etherscanKey", "G..."
resValue "string", "bscscanKey", "5...
```
