### ISSUE TITLE
Balance Screen: Disable coin on swipe

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#3864]

**Comment by nahuhh** [comment]
Hi. A couple suggestions.

1. Can we add a setting to change this behavior? 

Swipe right > left  = x/y/nothing
Swipe left > right  = x/y/nothing

2. It's also too sensitive. 

3. The undo button appears at the bottom of the screen, and disappears after a few seconds. 
Should be a confirm/revert prompt. 


Ultimately, I think the feature could be removed entirely and I wouldn't miss it. 

I'd prefer to swipe between screens. Not often do I disable my coins.

I can always very easily disable coins from the "add coins" page. 

Thanks
