### ISSUE TITLE
Security concern.

### ISSUE THREAD

**Issue by Originalimoc** [horizontalsystems/unstoppable-wallet-android#3902]
Is private key properly stored on TEE/SE of an Android device and sign transaction with KeyStore(Bio/Pwd/Bio+Pwd) so privilege escalation attack/executable hijack/root is not a problem.

**Comment by abdrasulov** [comment]
Hello @Originalimoc,

We use the Android Keystore System to store sensitive data. We store them encrypted with the key provided by the Android OS. This key is related to the current unlock pin/pattern of the device. If the unlock pin/pattern is removed somehow then the key will be invalidated. So the encrypted data cannot be decrypted anymore. It is supposed to protect if the attacker tries to get access to the app by resetting the device unlock pin/pattern.

**Comment by Originalimoc** [comment]
Coinomi is doing this ideally, you can choose Bio(so the one you're using? problem is it is an option BESIDES 6 digits PIN)/Pwd(KeyStore option)/Bio+Pwd double encryption and extra screen lock(which no relate to encryption). Ideally private key should never leave security hardware, and is protected even against root access, meaning a key that different than the one used to encrypt /data/data folder and is generated by user entered password plus Biometric related key(the one you're using) will given best result. Stop using 6 digits PIN as only option, use proper KeyStore password Intent to do authentication.

**Comment by abdrasulov** [comment]
As I mentioned before, we do use the Android Keystore System. All of the sensitive data are encrypted with the keys stored in Android OS itself. So if there is any attempt to hack the device's pin/bio (note device pin, not app pin) the sensitive data becomes encrypted forever. We don't use the app pin for encryption anyhow. It's the pin that allows using the app if the user sets it.

Please check the https://developer.android.com/training/articles/keystore for more details

**Comment by Originalimoc** [comment]
I know how KeyStore works and what's the purpose of your app PIN. There's still one potential attack surface. Which is the transaction is not signing INSIDE the secure hardware. pKey entered main memory if you just used KeyStore to decrypt the private key.
