### ISSUE TITLE
Manual Derivation key support/multi address support.

### ISSUE THREAD

**Issue by Originalimoc** [horizontalsystems/unstoppable-wallet-android#3907]
For example, need a way to add multiple ETH addresses.

**Comment by esengulov** [comment]
> For example, need a way to add multiple ETH addresses.

Do you mean having an ability to use multiple ETH addresses within single wallet?

The ETH typically works with a single address. Applying Bitcoin-like multiple address support to Ethereum would make Ethereum unusable for anything other then sending / receiving tokens. 

One way to realize this would be to let the app create multiple Ethereum instances within a single wallet where each instance uses its own address, but derived from the same seed. 

Do you have any examples where such multi address support is implemented?

**Comment by Originalimoc** [comment]
It's more of a compatibility thing. Coinomi supports this pretty well.

**Comment by nailkhaf** [comment]
Almost all reliable ethereum wallets can derive multiple addresses for one account: trezor, metamask, status wallet, myetherwallet. It needs for additional security for separation like first address for hodl, second for dex, third for staking, fourth for product specific. In this way all assets are stored indendenable and secure, if someone hack contract that used in one address it doesn't affect assets on other addresses.

**Comment by esengulov** [comment]
> trezor

true, good point

is it too much of a hassle creating a sepaarte wallet for each address?

The reason we are not on keen on giving this ability within a single wallet as it's not a standart implementation depsite wallets like Metamask providing such capability. Non standard implementation locks user tot bat specific wallet. Plus this requires significant UI changes in varios screens.
