### ISSUE TITLE
Buttons and tabs refactoring

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#3916]
- [x] Primary Buttons redesign 

- [x] Secondary Buttons redesign 

- [x] Remove tertiary buttons style (replace with secondary)

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=36539%3A304

- [x] Tabs redesign 
Coins / Guides - Top
Market / Keys - Top - Fitted

- [x] Period Tabs

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=38281%3A303601

- [x] Sorting headers redesign

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=24048%3A105903

- [x] sorting buttons on balance tab. change ' 24h Price(%) ' to ' Price Change'

- [x] change 'Add coin' button/text to icon

**Comment by kansalt** [comment]
Update the button icons on the balance card
- [ ] Replace the "receive" button icon with "icon / 24 / arrow / medium-3 / down-left"
- [ ] Update the "icon / 24 / arrow / swap-2" on "swap" button
