### ISSUE TITLE
Coin info >> funds invested: add funds data for protocols

### ISSUE THREAD

**Issue by Dadybayo** [horizontalsystems/unstoppable-wallet-android#3921]
Need to parse the data for this feature

If a fund does not have a website link, Dan will add the missing data

[Final Version-Grid view.csv](https://github.com/horizontalsystems/unstoppable-wallet-android/files/6795260/Final.Version-Grid.view.csv)
[Summary-Unstoppable Wallet Feauture (1).csv](https://github.com/horizontalsystems/unstoppable-wallet-android/files/6795261/Summary-Unstoppable.Wallet.Feauture.1.csv)

**Comment by esengulov** [comment]
Issue Merged Into https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3922
