### ISSUE TITLE
Coin Page : Add PRO features

### ISSUE THREAD

**Issue by Dadybayo** [horizontalsystems/unstoppable-wallet-android#3922]
In this sprint we intent to expand the details tab of the coin page with premium analytics data. That data would only be available to users holding Unstoppable token.

- [ ] integrate PRO feature capability. The items which are listed below AND market as PRO should only be available to users holding Unstoppable Wallet token and/or any other token we decided to add in the future i.e making PRO features available to BAYC holders.

- [ ] add advanced coin analytics 
- add 'DEX Volume'  (+ historical chart) PRO
- add 'DEX Liquidity' (+ historical chart) PRO
- add 'Active Adresses' (+ historical chart) PRO
- add 'Transaction Count' (+ historical chart) PRO
- add 'Transaction Volume' (+ rank list) PRO

**Comment by esengulov** [comment]
Duplicate of # https://github.com/horizontalsystems/unstoppable-wallet-android/issues/4443
