### ISSUE TITLE
Feature request (IMPORTANT): Custom nonce while sending eth.

### ISSUE THREAD

**Issue by golompiki** [horizontalsystems/unstoppable-wallet-android#3993]
Please, add support for creating ETH transactions with custom nonce, or any other way to unstuck stucked transactions. Please, please.

**Comment by esengulov** [comment]
> Please, add support for creating ETH transactions with custom nonce, or any other way to unstuck stucked transactions. Please, please.

hi, already in the development version and currently being tested. hopefully will be out in the next updated. There will be a way to speedup or cancel transaction
