### ISSUE TITLE
When restoring Zcash wallet, transactions are not displayed

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4008]
if you kill the application and open, then transactions are displayed

**Comment by rafaelekol** [comment]
This issue in ZCash repository
https://github.com/zcash/zcash-android-wallet-sdk/issues/281

**Comment by abdrasulov** [comment]
We've recently updated the SDK. Need to check if the issue is fixed

**Comment by rafaelekol** [comment]
I tested app with latest snapshot of ZCashSDK `1.4.0-beta01-SNAPSHOT`. Issue is not reproduced on this snapshot. Transactions are shown after initial sync is completed.
Now we need to wait when ZCash team will release stable SDK version.
