### ISSUE TITLE
markets tab UI improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#4019]

**Comment by TalgatNurdinov** [comment]
**Main Page**
1. Cards on overview should open a page with a chart and a list of coins with ability to sorting
  1.2. Total M.Cap as card on overview 
  1.3. Bitcoin Dominance moves in Total.M.Cap page
  
2. Add to the Top Gainers / Losers sections the ability to change to Top(250/500/1000), the "See All" button moves to the bottom of the section.

3. News is placed in the third tab

**Search Page**
1. Categories moved to the search page, their shown as cards in 2 columns
2. Advanced Search moved to the top, and renamed "Filters"

**Con list Page**
Clicking on "See All" of Top G/L sections, clicking on Categories cards (in search page) should open page with a list of coins (+sorting) with the Title/description/image at the top
