### ISSUE TITLE
TX tab: swap cell doesn't display correctly when  the amount of tokens in/out has a lot of digits.

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#4058]

**Comment by esengulov** [comment]
![IMG_3674](https://user-images.githubusercontent.com/8611762/130432891-e555b470-aed8-43cc-9834-194949bdf00c.jpg)

**Comment by abdrasulov** [comment]
How should we display amount in this case?

@esengulov @TalgatNurdinov @kansalt

**Comment by abdrasulov** [comment]
Discussed with design team. Decided to limit the amount text width. So in this case the "Swap" title and "from ..." string should shows up as is, then the amount is shown in remaining space.
