### ISSUE TITLE
apply layout enhancements to coin manager

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#4071]

**Comment by kansalt** [comment]
- [ ] On the "coin manager" page, arrange the list of coins in order 
       1. included coins 
       2. in order with the highest capitalization
       
- [ ] In the search state, hide those coins that the wallet does not support
- [ ] Add the text "No results, you may try to add token manually." for the "not found" state when searching

- [ ] Replace the check marks on the "bottom" components with the switch buttons

For coins on two or more chains 
- [ ] Add the coin type ''bottom" component 
- [ ] Add the "edit" button in the"cell" components
- [ ] Add new states on the "add token" pages, states with "switch" buttons to select a chain

layouts
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=40626%3A373127
