### ISSUE TITLE
It is not fully supported to define distributionSha256Sum

### ISSUE THREAD

**Issue by trustwalletvn** [horizontalsystems/unstoppable-wallet-android#4112]
It is not fully supported to define distributionSha256Sum in gradle\wrapper\gradle-wrapper.properties.
Using an incorrect value may freeze or crash Android Studio.
Please manually verify or remove this property from all of included projects if applicable.
For more details, see https://github.com/gradle/gradle/issues/9361.
Use "2debee192..." as checksum for https://services.gradle.org/distributions/gradle-7.1-bin.zip and sync project
Remove distributionSha256Sum and sync project
Open Gradle wrapper properties

**Comment by trustwalletvn** [comment]
gradle/wrapper/gradle-wrapper.properties

#distributionSha256Sum=2debee19271e1b82c6e41137d78e44e6e841035230a1a169ca47fd3fb09ed87b

**Comment by abdrasulov** [comment]
We add it to increases security as it said in here https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification.

Choosing option `Use "2debee192..." as checksum for ...` in this case should help.
