### ISSUE TITLE
Add our wallet to the site Blockchair

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4116]
https://blockchair.com/zcash/wallets

**Comment by nahuhh** [comment]
Looks like this can be closed

![Image_44.jpg](https://user-images.githubusercontent.com/50635951/153745049-bfef3e40-583f-4757-a51c-543411a9f9be.jpg)

**Comment by esengulov** [comment]
> Looks like this can be closed
> 
> ![Image_44.jpg](https://user-images.githubusercontent.com/50635951/153745049-bfef3e40-583f-4757-a51c-543411a9f9be.jpg)

thanks for heads up my friend!
