### ISSUE TITLE
Integrate EIP-1559

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4124]
- [ ] apply new UI for fee setting
- [ ] Research/Apply the tool to prevent overpayment of transaction fees as fallback/addition for the integration EIP-1559 https://decrypt.co/80930/ethereums-infura-releases-tool-prevent-overpayment-transaction-fees

**Comment by Dianaaiym** [comment]
https://twitter.com/lefterisjp/status/1443143599235944451?s=28

**Comment by Dianaaiym** [comment]
https://twitter.com/lefterisjp/status/1443143599235944451?s=28

**Comment by LukeWheeldon** [comment]
Is there an ETA for the implementation of EIP-1559? Using Unstoppable on Ethereum is prohibitively expensive.

**Comment by esengulov** [comment]
> Is there an ETA for the implementation of EIP-1559? Using Unstoppable on Ethereum is prohibitively expensive.

@LukeWheeldon  coming in version 0.24 which is due early January 2022

**Comment by esengulov** [comment]
when base fee is normal

https://user-images.githubusercontent.com/8611762/146021286-d97d0cb4-cb6c-4ac2-ac2f-b2c19db9f99b.mp4


when base fee is high

https://user-images.githubusercontent.com/8611762/146021178-8e37ffad-981d-48d5-8da6-6d82e5dfd116.mp4


@Dianaaiym note texts below

- [ ] alert for when base fee is high

- title : Base Fee is High!
- text : At the moment the base fee for transacting is high. It may go down when the network becomes less congested.
    
- [ ] texts for info alerts
    
- Tx Speed : description already available

- Max. Base Fee : A base fee is the algorithmically determined price users need to pay for a transaction on Ethereum blockchain. The base fee automatically set by Ethereum network and is not controlled by a specific entity.

- Miner Tip : Miner tips are defined as optional fees that users may include to incentivize network participants to prioritize user's transaction.

**Comment by TalgatNurdinov** [comment]
Layouts
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=47269%3A448534
