### ISSUE TITLE
Add text for Coin page > details

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4143]
- [x] Add INFO icons on the header of the section (Token TVL, Investor Data)
 - [x] Add Info Pages
 - [x] Remove Info icons from a cell in the Security Parameters section
 - [x] Remove info from Major Holders Page

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/?node-id=54710%3A298028

Token Liquidity

> The state of liquidity for the given asset on decentralized exchange markets.

DEX Volume

>The trading volume for the token on decentralized exchanges.

 DEX Liquidity

>The total amount of available liquidity for the token on decentralized exchanges.

 Token Distribution

>Onchain token parameters. Typically, healthy projects have an active on-chain user base and well-distributed token.

Tx Count

> The number of token transactions recorded on-chain over various periods.

 Tx Volume

>The aggregate token transaction volume is recorded on-chain. The volume is measured in the actual tokens (not USD).

 Active Addresses

>The number of unique wallet addresses involved in transactions over various periods.

Major Holders

> The number of tokens held by the top 10 wallets. Quality projects typically have a widely distributed token.

Token TVL

> Total Value Locked (TVL) is a metric that shows the total value of crypto assets under automated management by the smart contracts powering the given protocol.

TVL Rank

>The ranking among other protocols is based on the TVL value in USD terms.

 M.Cap / TVL

>The ratio of the project token's market cap over its TVL.

 Treasuries:

 Security Parameters

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/?node-id=54710%3A298028

**Comment by Dianaaiym** [comment]
Remove info button for Investor Data
