### ISSUE TITLE
Wallet connect Opensea sign fail

### ISSUE THREAD

**Issue by xxxcrow** [horizontalsystems/unstoppable-wallet-android#4144]
When i try to put an item for sale with Wallet Connect on opensea
It opens Unstoppable wallet and says "Invalid URL Address"

**Comment by abdrasulov** [comment]
Hello @xxxcrow,

We couldn't reproduce the issue. We tried it with both desktop (Chrome and Safari) and mobile (Chrome) browsers. It worked fine.

Can you please share the model of your device, android version and the steps to reproduce it?

**Comment by xxxcrow** [comment]
@abdrasulov 
Oh, the issue is gone!
Before it didn't work, but i installed chrome just to check my device
And it worked! But then i checked my main browser, and it started to work there too
Sorry for creating the issue
Here's my device just in case
Xiaomi Mi 9
Android 11 (AOSP)
Fennec browser

**Comment by abdrasulov** [comment]
@xxxcrow 

Great to hear that! Thanks for informing us
