### ISSUE TITLE
Major bug: same receive address across wallets

### ISSUE THREAD

**Issue by martinoshub** [horizontalsystems/unstoppable-wallet-android#4157]
It's hard to believe that this mobile wallet software has such a basic and catastrophic bug. But I'm looking right at it. 100% confirmed.

I created 3 different wallets. I set all 3 to have only a BTC account with only native segwit (bech32) addresses.

I switch between the wallets (tapping the top left hand corner, then selecting different wallets, then confirming that the right wallet is shown in the top left hand corner). Whenever I click the button under BTC to receive (and generate an address), I get the same deposit address. All three wallets have a different 24-word mnemonic. But apparently they all show the exact same BTC wallet when I open them, because the receive address is the same.

I don't know if it's a caching or display bug or whatever, but it ruins the whole thing for me. I was just looking for a wallet that supported creating different accounts (MyCelium does that, but it's buggy, it doesn't allow you to create a new one after you've moved coins out of an account). It was disappointing that Unstoppable Wallet didn't support different accounts under one coin, but I figured I could just create and write down many mnemonics and get the same result. It turns out your software is even buggier than MyCelium. :(

I would take screenshots to prove this but the "Receive BTC" screen is separate from everything else, so it would be the same screenshot 3 times - even though I arrive to them from different wallets.

If you ever get around to fixing this bug and adding the ability to have multiple accounts under one coin, let me know. I have to move on for now and keep looking for a reliable wallet with the ability to set TX fees, have accounts and other important features like that.

**Comment by LinksPB** [comment]
I have not been able to replicate. If a dev could, please share some insight on what might be happening with OP's install.

**Comment by rafaelekol** [comment]
@martinoshub Can you give more information on your setup; 
phone Android version, 
installed app version or from which branch?

**Comment by martinoshub** [comment]
Android 8 on a Galaxy note 8, whatever version was available from Google Play at the time of posting this. I couldn't "not reproduce it" - No matter how many new wallets I created with a new mnemonic (and selecting bech32), I got the same receive address.

**Comment by abdrasulov** [comment]
Hello @martinoshub,

Thanks for clarifications. As of now, we couldn't reproduce this issue on any of our devices. We'll check it further.
