### ISSUE TITLE
Navigation >> Add Swipe to dismiss action to list items

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#4172]
https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/3457

https://github.com/MakeItEasyDev/Jetpack-Compose-Swipe-to-Reveal

**Comment by esengulov** [comment]
@TalgatNurdinov please provide a list of all places where such dismiss actions can be applied. Once done reassign the issue for implementation.

  - [ ] Balance >> coin item
 ...

**Comment by abdrasulov** [comment]
Need to disable swiping in balance for watch accounts
