### ISSUE TITLE
Wallet Connect v2 integration

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4199]
https://twitter.com/walletconnect/status/1450398265699192835

**Comment by trymeouteh** [comment]
Please also allow for pasting the wallet connect URL as an alternative to scanning a QR code if your using a web3 app on the same devices your unstoppable wallet is on.

**Comment by rafaelekol** [comment]
There is bug with WalletConnect SDK, https://github.com/WalletConnect/WalletConnectKotlinV2/issues/99
They promised to fix it with the next release.

**Comment by rafaelekol** [comment]
Bug with connection created as new issue https://github.com/horizontalsystems/unstoppable-wallet-android/issues/4684
