### ISSUE TITLE
Market Overview -> Globals Chart Subpage Issues

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#4208]
Total Market Cap
* Title
* BTC Dominance
* Selected field

Volume
* Selected field

Defi Cap
* Selected field

TVL in Defi
* Chains Selectors
* Field Selector

All
* For all 24H type of charts x axis should show time in HH:mm format
* Check overall UI with design in figma

**Comment by Dianaaiym** [comment]
on the "TVL in Defi", "Total Mcap" charts with negative price changes, 2 minuses are shown
![2021-11-10 14 57 09](https://user-images.githubusercontent.com/22589457/141081880-f4f45f98-4caf-4d8b-a7e6-f0b548c7b6e9.jpg)
