### ISSUE TITLE
Add a “retry” button for all “sync error” screens

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-android#4229]

**Comment by Dianaaiym** [comment]
Coin Chart: "retry" button is not shown when sync error

**Comment by Dianaaiym** [comment]
![2021-11-10 14 31 59](https://user-images.githubusercontent.com/22589457/141077989-9bb8a544-9bba-41f1-990e-917c23d906c2.jpg)
