### ISSUE TITLE
Settings: Add launch screen settings

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-android#4237]
- [x] Add launch screen settings 
"Auto" mode - opens the last page where the session was closed 
- market (+news, watchlist)
- wallet
- transactions 

<img width="800" alt="Screen Shot 2021-10-28 at 4 42 10 PM" src="https://user-images.githubusercontent.com/58926737/139240861-3881bc19-3a61-4d42-9f8d-7f8a931da1b5.png">

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=44279%3A438702

**Comment by Dianaaiym** [comment]
Auto mode does not work correctly, when the app is opened, the market page is shown, then it transfers to the balance tab (always)
