### ISSUE TITLE
Market metrics on chart press not keeping crosshair

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#4289]

**Comment by abdrasulov** [comment]
In compose version `1.2.0-alpha08` there is a new parameter `userScrollEnabled` of `LazyColumn`. We need it for fixing the issue. Waiting for the stable version of 1.2.0.

https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.2.0-alpha08
