### ISSUE TITLE
Hardware wallet support

### ISSUE THREAD

**Issue by DevJackSmith** [horizontalsystems/unstoppable-wallet-android#4298]
Humbly requesting to support hardware wallets like ledger and trezor

**Comment by trymeouteh** [comment]
Would like to see Trezor support over Ledger since Trezor wallets are open source.

**Comment by esengulov** [comment]
soon! @DevJackSmith @trymeouteh

**Comment by nahuhh** [comment]
> Would like to see Trezor support over Ledger since Trezor wallets are open source.

I agree 🤷‍♂️

**Comment by esengulov** [comment]
@nahuhh @DevJackSmith @trymeouteh since version 0.29/0.30 the app supports watching wallets in read only mode. This means that both Ledger and trezor users are now able to watch their wallets within Unstoppable
