### ISSUE TITLE
Tor issue

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4310]
I downloaded an unstoppable wallet to test it and I am satisfied with it thus far, the interface, usability, etc. thank you.
one issue I have that I desire to receive some support in please:
I use Tor with it, and I have now constantly a Tor service being connected, also if the unstoppable wallet is exited. it pops back up on me and persists there, the Tor notification, it is connected. I figured that eventually the unstoppable wallet push notifications (in settings) are the reason for this but I disabled that entirely now and Tor still persists on me.
I desire to not have it connected all the time. I roam with my phone and as it stands any network I am connected to has a standing Tor connection through it. that's undesirable. I can't figure out how to get rid of this. I desire to be able to open an unstoppable wallet, have it connect to Tor (if then desired) and when I close it I desire it not to push a running Tor on me, all day. how do I achieve this, please?
thank you.

**Comment by esengulov** [comment]
@Dianaaiym do we have any info on user's device?

**Comment by Dianaaiym** [comment]
> @Dianaaiym do we have any info on user's device?

no specific characteristics

**Comment by kdejaeger** [comment]
On Android closing the app also closes the tor process + notification. Closing = go to list of running apps and swipe the app away.

Let's say you swap coins and minimize the app, you still want the app and tor running for a while. At least until it's done with some important background operations.

**Comment by TalgatNurdinov** [comment]
design of tor connection status on main pages
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=57277%3A242272&viewport=-533%2C1164%2C1


also need to redesign connecting pages
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=62870%3A402147&viewport=-15948%2C-222%2C1
