### ISSUE TITLE
Add Dogecoin to wallet

### ISSUE THREAD

**Issue by GiyoMoon** [horizontalsystems/unstoppable-wallet-android#4311]
Hey! I tried adding Dogecoin (DOGE) to my wallet over its BSC Contract address and it didn't work. I now have DOGE displayed there but it's not a valid Dogecoin address, rather it looks like an ethereum address.
Did I misunderstand something? Or how can I add the Dogecoin crypto currency to my wallet?

**Comment by abdrasulov** [comment]
Hey @GiyoMoon. The Dogecoin is going to be added in the upcoming version

**Comment by GiyoMoon** [comment]
Awesome to hear, thanks!

**Comment by GiyoMoon** [comment]
Hey @abdrasulov ! I just installed the preview version for 0.23, but it seems that Dogecoin is still missing. Only the BEP20 token for Dogecoin is there :/ Am I missing something?😓

**Comment by abdrasulov** [comment]
Hey @GiyoMoon. We've added support for Dogecoin in BEP20 format. I thought that you need this format of Dogecoin when you wrote that you tried adding it via its BSC contract address. Now it seems like I misunderstood.

So to be clear, as of now, we support Dogecoin in BEP20 format. We don't support the native format. At least for now.

**Comment by GiyoMoon** [comment]
Oh my bad. I'm very new to crypto and the BSC Contract Address got me confused.
Unfortunate to hear that you don't support the native support yet but thanks for the all the answers! Looking forward to future updates :).
