### ISSUE TITLE
Mobilecoin support

### ISSUE THREAD

**Issue by kdejaeger** [horizontalsystems/unstoppable-wallet-android#4343]
Another privacy coin, currently integrated on FTX, Signal app (as a beta payments feature) and mixin messenger.

https://mobilecoin.foundation/

https://github.com/mobilecoinofficial/android-sdk

https://github.com/dinchamion/mobilecoin-android-sdk-gitbook/commit/79262accd0e11fc7bbdab514458fb9e520f5775b

**Comment by esengulov** [comment]
we will review it in the future. no plans for it just yet due to large backlog
