### ISSUE TITLE
Support for sending to unstoppable domains minted on polygon L2

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#4361]
Hi, unstoppable domains has rolled out l2 polygon minting.

It seems the wallet is unable to find domains minted on polygon 

Tested and working on Trust Wallet.

Update coming?
Thanks

![Screenshot_20211129_132641.jpg](https://user-images.githubusercontent.com/50635951/143922692-fa09b41f-cdc4-4278-a663-e32ee71b9a16.jpg)

**Comment by nahuhh** [comment]
#2913

**Comment by nahuhh** [comment]
Seems to be working.

Closing 
Thanks

**Comment by esengulov** [comment]
> Seems to be working.
> 
> Closing Thanks

thanks!
