### ISSUE TITLE
Ethereum NFT token support

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#4386]
- [ ] balance
- [ ] send/receive
- [ ] display floor prices for collections
- [ ] display OpenSea offers

**Comment by nahuhh** [comment]
> - [ ] balance
> - [ ] send/receive
> - [ ] display floor prices for collections
> - [ ] display OpenSea offers 

Polygon as well? #4361

**Comment by trymeouteh** [comment]
Would be handy to support the storage and management of Unstoppable Domains with NFT support.
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3297

**Comment by nahuhh** [comment]
> Would be handy to support the storage and management of Unstoppable Domains with NFT support.
> https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3297

Also support for sending to domains minted on polygon 
#4361

**Comment by TalgatNurdinov** [comment]
Layouts:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=45885%3A420321

Prototype:
https://www.figma.com/proto/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?page-id=22050%3A2377&node-id=45885%3A420321&viewport=241%2C48%2C0.29&scaling=scale-down&starting-point-node-id=45885%3A420321&show-proto-sidebar=1
