### ISSUE TITLE
Add BTC as a main currencie

### ISSUE THREAD

**Issue by mlovizio** [horizontalsystems/unstoppable-wallet-android#4401]
Although there is plenty of options to select as main currencies, so far there is only fiat options to select.

I think there will be useful to have the option to see the prices of crypto denominated in BTC, mBTC or SATs.

**Comment by nahuhh** [comment]
Btc, eth, xmr, ltc, bnb

Should be choices

**Comment by mlovizio** [comment]
> Btc, eth, xmr, ltc, bnb
> 
> Should be choices

Agree

**Comment by esengulov** [comment]
Done in version 0.25 which is about to be released. The main balance amount now shows equivalent in BTC or ETH. Clicking on crypto equivalent of balance switches between options. Version 0.26, would expand on feature by adding additional related settings to Settings tab
