### ISSUE TITLE
Sometimes app opens main screen despite the screen the user was before switching

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#4408]
It starts as if it's cold start

**Comment by abdrasulov** [comment]
@esengulov yes, we've thoughts that resolving this issue may potentially decrease the battery usage. We'll check it :)

**Comment by omurovch** [comment]
The reasons of this behavior are:
- android system killing app due to low memory
- app not being restored to the last state after subsequent restart

Following tasks need to be done to solve above problems:
- [ ] #4441
- [ ] #4440
- [ ] #4439
