### ISSUE TITLE
Fix tab paddings in Coin Market

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4413]
![2021-12-07 14 30 14](https://user-images.githubusercontent.com/22589457/144993962-af828cb7-ec32-4270-a3b8-59d8909e974f.jpg)

**Comment by abdrasulov** [comment]
@TalgatNurdinov @kansalt 

There is a min-width of tabs that equals 90dp. We need a decision for this case. Leave as is or redesign tabs.

**Comment by TalgatNurdinov** [comment]
> is
Let's remove the minWidth
