### ISSUE TITLE
Debug Section in Settings: Display (1)current network tx fee rates for each supported blockchain, (2) display current exchange rate

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#442]
- [ ] Show build number for dev build
- [ ] network logs
- [ ] any other logs that may be relevant for debugging
- [ ] display current network tx fee rates for each supported blockchain
- [ ] display current exchange rates for base_currency and supported crypto

more details to be provided

**Comment by rafaelekol** [comment]
This issue needs discussion.

**Comment by esengulov** [comment]
The issue is already implemented and no longer relevant
