### ISSUE TITLE
Same contract on ERC20 and BEP20, can only add ERC20

### ISSUE THREAD

**Issue by WedgeSama** [horizontalsystems/unstoppable-wallet-android#4431]
When I added a contract that is on both ERC20 and BEP20 with the same contract address, it take only the ERC20 address, impossible to get the BEP20.

If needed, I can put here the contract address.

**Comment by abdrasulov** [comment]
Hello @WedgeSama. Please share the contract address with us. We'll check it.

**Comment by WedgeSama** [comment]
This one:
0x6b23C89196DeB721e6Fd9726E6C76E4810a464bc

**Comment by abdrasulov** [comment]
@WedgeSama thanks for details. We'll work on this issue soon.

**Comment by esengulov** [comment]
hi @WedgeSama Are you sure the token has official ERC20 contract? Coingecko API shows only one contact and that is on BSC.

I did look it up on Ethereum and there is one contract with same address but it has only 3 transactions in total.

**Comment by WedgeSama** [comment]
Yes, the official contract is on BEP20.
But unstoppable only select the ERC20 contract, it never show me the BEP20 or allow me to tell to only look on BEP20.
