### ISSUE TITLE
0.23 - Enabling tor breaks the app

### ISSUE THREAD

**Issue by RebelCoderRU** [horizontalsystems/unstoppable-wallet-android#4435]
App version: 0.23.0 (from F-Droid)
Device: Samsung Galaxy S21 Ultra - App is running in a Knox secure folder.

Action: Enabling tor in `Security -> Privacy`

Result: app restarts and stays on the black screen. Killing the app, restarting the phone does not help. Every time app is started, it stays on the black screen. Requires cache cleaning and restoring the wallet. 

Additional notes: Enabling tor worked correctly in the previous version from F-Droid (0.22)

**Comment by rafaelekol** [comment]
Fixed by
https://github.com/horizontalsystems/unstoppable-wallet-android/pull/4432
