### ISSUE TITLE
Knox secure folder: "Encrypted data" gets randomly corrupted 

### ISSUE THREAD

**Issue by RebelCoderRU** [horizontalsystems/unstoppable-wallet-android#4447]
App version: 0.23.0 (from F-Droid)
Device: Samsung Galaxy S21 Ultra - App is running in a Knox secure folder.

Issue: wallet says that some encrypted data was invalidated. This happens randomly with no changes on the device. After the error message is shown, users needs to restore the wallet with the seed phrase. After a fresh restore, wallet might work fine for 20-30 app openings, but randomly will show the error and will need to be restored.

Screenshot: 
![SmartSelect_20211217-005519_Unstoppable](https://user-images.githubusercontent.com/20476773/146479989-217ec2b8-92df-4306-a017-bdef12d7f8d5.jpg)

**Comment by abdrasulov** [comment]
Hello @RebelCoderRU. Thanks for report. We face this issue from time to time. The Android OS supposed to invalidate secret keys only when the phone PIN is changed. But sometimes it does it for no reason. We've been searching for the solution. Can you please check it outside of knox and let us know if the issue persists?

**Comment by RebelCoderRU** [comment]
A quick update: Wallet seems to be working correctly outside the Knox secure folder. No keystore corruption error for 3 days, including a few device reboots.

I hope the team can figure this out as I have all of my Crypto related stuff in Knox folder.

**Comment by abdrasulov** [comment]
@RebelCoderRU Thanks for details. When we work on the issue we'll check the Knox too

**Comment by abdrasulov** [comment]
See #4163
