### ISSUE TITLE
As a defi wallet user, I want token contacts to be visible in the Coin Manager to improve security

### ISSUE THREAD

**Issue by BitBistro-code** [horizontalsystems/unstoppable-wallet-android#4448]
As a defi wallet user, I want token contract and standard to be visible in the Coin Manager to improve security

Success Criteria
* I want the token standard (i.e. erc20) displayed as part token in the Coin Manager. Suggested implementation, in small caps to the right of the token name in the Coin Manager first line of item; similar to how it shows when viewing the wallet.
* I want the hex contract ID to be displayed as part of the token in the Coin Manager. Suggested implementation, perhaps on the second line next to the symbol, but space could be a problem. This is particularly important for security so that a user knows they are adding the correct token.

**Comment by abdrasulov** [comment]
Resolved in #5140
