### ISSUE TITLE
Transaction tab: Disable the filter by coin if only one coin is enabled

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#4466]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=43856%3A493813

**Comment by abdrasulov** [comment]
@TalgatNurdinov 

When ETH is the single enabled coin then it shows also erc20 token transactions. In this case filtering by ETH shows only ETH. If we remove coin then user won't be able to view only ETH transactions. The same for BSC.
