### ISSUE TITLE
Unable to Add (WRX) BEP-2 Token 

### ISSUE THREAD

**Issue by ynsnf** [horizontalsystems/unstoppable-wallet-android#4473]
It just doesn't seem to work. It says "Invalid Contract Address". Tried all the possible ways.

**Comment by esengulov** [comment]
> It just doesn't seem to work. It says "Invalid Contract Address". Tried all the possible ways.

Just tried with BEP2 and noticed the issue. Not possible to add 'WRX-ED1' as coin while it being a valid asset name. Will look into it soon.

Having no issues adding its BEP20 token though.

**Comment by ynsnf** [comment]
@esengulov me too. This issue occured since the last update, just so you know.

**Comment by rafaelekol** [comment]
I can't reproduce  this issue.
