### ISSUE TITLE
Transactions >> Show in/out values on Swaps and ETH Contract Calls

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4507]
![2022-01-10 17 16 13](https://user-images.githubusercontent.com/22589457/148757546-fcf854df-01ad-4abd-b491-85e8eb0ee37d.jpg)

**Comment by esengulov** [comment]
Display in/out values on all transactions where such information can be extracted.

- [ ] display in/out values on all SWAP transactions, currently it's shown only for a fraction of transactions.
- [ ] rename 'Ethereum Contract Call' to 'Contract Call'
- [ ] display in/out values on all 'Contract Call' transactions. 

@TalgatNurdinov 
- [ ] provide a mockup for cases when there are multiple IN or OUT values on 'Contract Call' transaction type i.e. during deposit to a liquidity pool

**Comment by esengulov** [comment]
The issue is already implemented and no longer relevant
