### ISSUE TITLE
Watch Address: Handle the case if there is no balance at all

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4512]
- [ ] Text "This wallet address doesn’t have any balance."

- [ ] Remove button "Add Coins

![2022-01-12 17 58 04](https://user-images.githubusercontent.com/22589457/149136263-47ce5cc3-021a-4176-a462-0156e059c92e.jpg)
"

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=48534%3A308444

**Comment by Dianaaiym** [comment]
Need to remove sorting, displaying the address and the balance amount
![2022-01-21 16 41 31](https://user-images.githubusercontent.com/22589457/150513365-35e6af53-dbc5-4293-8336-6419f69a9fba.jpg)
