### ISSUE TITLE
Zcash Sync 0%

### ISSUE THREAD

**Issue by Egra333** [horizontalsystems/unstoppable-wallet-android#4540]
Zcash sync freezes at 0%

App version 0.23.3

**Comment by Egra333** [comment]
in the meantime how to recover the coins?

**Comment by lukas-conlance** [comment]
Same for Dash. @Egra333 you can restore your keys with your 12 word phrase in another wallet.

**Comment by Egra333** [comment]
For me Dash sync, Zach nothing.
Which wallet you suggest for the moment?

**Comment by Egra333** [comment]
> Same for Dash. @Egra333 you can restore your keys with your 12 word phrase in another wallet.

But it seems not possible to recover in another wallet. How is it possible?

**Comment by Egra333** [comment]
Now it seems syncing correctly
