### ISSUE TITLE
Navigation >> swipe between onpage tabs

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#4543]
- [ ] Market tab >> allow swipe to transition between on-page tabs 
- [ ] Coin page >> allow swipe to transition between on-page tabs 
- [ ] TX page >>  allow swipe to transition between on-page tabs (all, incoming, outgoing etc)
- [ ] FAQ page >> allow switching between question categories. Related to  https://github.com/horizontalsystems/unstoppable-wallet-android/issues/4044
.... 

@TalgatNurdinov please review

**Comment by abdrasulov** [comment]
To show pages with a slider there should be 3 pages loaded at a time, the current and its neighbors. It will affect the app's performance. We decided not to implement it
