### ISSUE TITLE
Is it possible to add a celo network

### ISSUE THREAD

**Issue by dinarpay** [horizontalsystems/unstoppable-wallet-android#4551]
Hello
We desperately need the support of the Blockchain Celo network
is that possible

**Comment by esengulov** [comment]
> Hello
> We desperately need the support of the Blockchain Celo network
> is that possible

Hi @dinarpay 

We will look into it shortly. We haven't had a chance to explore CELO yet. Do you know any wallets that have already them integrated? If there are any please let us know it will make the process easier on our end.

**Comment by esengulov** [comment]
@dinarpay 

OK, just did a quick search and seems like its and EVM compatible blockchain so can be integrated fairly quickly. We will try to get it in place in the next sprint 0.25. Currently working on 0.24

regards

**Comment by esengulov** [comment]
Issue Merged Into https://github.com/horizontalsystems/unstoppable-wallet-android/issues/4555
