### ISSUE TITLE
Coin price >> Historical data should be fetched from HS instead of Coingecko

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#4557]
- [x] coin price charts >> get data from HS, instead of Coingecko
- [x] tx info >> historical rate for the tokens in TX should be obtained from HS
- [x] make sure volume appears on all chart periods, except today. If there are issues with getting volume data for 24 hour period then feel free to exclude it as well

**Comment by TalgatNurdinov** [comment]
layouts displaying volume and MACD RSI charts in a separate section
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=30890%3A959
