### ISSUE TITLE
NFT >> Improvements to balance page

### ISSUE THREAD

**Issue by horsys** [horizontalsystems/unstoppable-wallet-android#4591]
- [ ] display ETH value next to total balance for NFTs (like for coins)

**Comment by esengulov** [comment]
@nk-the-crazy @tmedetbekov the API endpoint which returns user's NFT balances should also return floor prices for each collection where user has a token

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=46469%3A426672
