### ISSUE TITLE
Send "max" fails (zcash zec)

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#4594]
Zcash tx fees are static.
TX failed due to insufficient balance due to unstoppable rounding the tx up to the 6th digit.

Using "send max" for any coin should use all available digits, sending everything. 

Note: litecoin uses all 8 digits, so the rounding might only be an issue with zcash.

**Comment by esengulov** [comment]
@nahuhh thanks, good catch)
