### ISSUE TITLE
On the fly convert crypto to normal cash.

### ISSUE THREAD

**Issue by Raj2032** [horizontalsystems/unstoppable-wallet-android#4597]
Hey guys I wanted to suggest a feature request, say I have bitcoin and I wanted to buy something from the store but the store owner does not support crypto, let alone bitcoin.

I was wondering if there it was possible to have a feature which "converts on the fly" from bitcoin to USD/AUD/NZD as soon as I do an NFC scan on the eftpos machine? As most stores don't even support crypto currencies and this would be a great way to encourage more people to use cryptocurrencies and doing this sort of "on the fly" transaction would greatly improve privacy instead of using your normal debit/credit card?

**Comment by nahuhh** [comment]
> Hey guys I wanted to suggest a feature request, say I have bitcoin and I wanted to buy something from the store but the store owner does not support crypto, let alone bitcoin.
> 
Accepting bitcoin is a privacy nightmare.
No matter if receiving for a sale, donation, etc. Always at risk of getting some dirty coins + exposing your tx and balance.

> I was wondering if there it was possible to have a feature which "converts on the fly" from bitcoin to USD/AUD/NZD
Without KYC? And s regulated deposit place, like a bank account linked to Google play? 

> as soon as I do an NFC scan on the eftpos machine? 
NFC POS from a phone, without using a regulated card via Google pay etc? 
Is there anywhere in the world that you can pay a retailer using NFC, without the correct payment method authenticated via Google pay etc?
Or you want the money deposited into your bank account? 

> As most stores don't even support crypto currencies 
The right tool for the right job.
Most cryptocurrencies excel at something. 
Staking, dividends, governance etc.
But for transactional crypto, you need privacy coins for that.

Nobody normal retailer should accept payment in dydx, bch, ETH etc..

> and this would be a great way to encourage more people to use cryptocurrencies and doing this sort of "on the fly" transaction would greatly improve privacy instead of using your normal debit/credit card?
Where would the Fiat be stored?

I dont see how it would improve privacy at all.
If you want privacy, you shouldnt be using bitcoin, litecoin, etc.

What youre looking for sounds like something along the line of coincards. 
Selling crypto into fiat triggers kyc is most cases.

This is a problem in search of a solution.
There is nothing wrong on the wallets end. 
If I was a vendor, it makes 0 sense to accept public-ledger cryptocurrencies for any reason other than convenience for my customers.
Even with "cash" in the name BCH isnt meant to be used in the real world.

The only real alternative to cash, is a privacy coin like Monero, or.. cash /efiat itself.


Alternatively, something like this might work.. assuming they arent killed with regulations
https://havencard.io

**Comment by Raj2032** [comment]
Hey mate thanks for your help then mate =D
