### ISSUE TITLE
Error on sending coins

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#460]
Need to handle the error when sending coins:
1. Show more informative message instead of just "Error"
2. Make sure that user won't send funds twice

**Comment by esengulov** [comment]
> Need to handle the error when sending coins:
> 
> 1. Show more informative message instead of just "Error"
> 2. Make sure that user won't send funds twice

@abdrasulov 
Is this still relevant? More details needed

**Comment by esengulov** [comment]
@abdrasulov in the last release we started blocking GUI after send action to avoid duplicate payments. With this I think we have needed measures in place. 

If this issue is still relevant please reopen it.
