### ISSUE TITLE
NFT: Amount badge and Cell

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4601]
Show the amount badge on the balance tab and the amount cell on item page if the amount of erc1155 token is more than 1

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/?node-id=49343%3A316745

**Comment by abdrasulov** [comment]
As of now, we can not show the owned count, since the NFT Data source doesn't provide this info.

**Comment by esengulov** [comment]
merged into another ticket https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5207
