### ISSUE TITLE
EIP-1559: UI Improvements

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4605]
- [x] Change Text : Send - Confirm Page

Max Fee ->Fee

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System

- [x] Add info for Max Fee on Fee Settings Page

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=47558%3A463127

**Comment by TalgatNurdinov** [comment]
Need to fix

- [ ] Wrong side margins of cells sections in swap confirmation page
- [ ] Send and Swap buttons on the confirm pages should be the bottom buttons
- [ ] Add gradient to the background of the "DONE" bottom button in the fee settings page 
- [ ] Fix the top margin of warning messages on confirm screens
- [ ] Fix the margins between warning messages to 12
