### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [horizontalsystems/unstoppable-wallet-android#4614]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 93 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on unstoppable-wallet-android (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve unstoppable-wallet-android's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by esengulov** [comment]
> I'm a PhD student interested in finding security vulnerabilities in open source projects.
> 
> We found a total of 93 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on unstoppable-wallet-android (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).
> 
> Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve unstoppable-wallet-android's security, and the quality of the reports of static analysis tools. (*) https://github.com/CROSSINGTUD/CryptoAnalysis

hi @misterAnderson90 thanks for reaching out, please share your findings with us @ hsdao@protonmail.com.

We will review them right after.
