### ISSUE TITLE
Add Eip1559 support to WalletConnect V2

### ISSUE THREAD

**Issue by omurovch** [horizontalsystems/unstoppable-wallet-android#4615]

**Comment by Dianaaiym** [comment]
![2022-03-16 17 37 18](https://user-images.githubusercontent.com/22589457/158581666-dfc9b8f1-1c37-488b-b94f-b4f62464a4f0.jpg)
![2022-03-16 17 37 21](https://user-images.githubusercontent.com/22589457/158581672-c447b90f-d93e-4b5b-9c9b-995b2e438b05.jpg)

Screen Fee Settings  is incomplete
