### ISSUE TITLE
Markets >> Top Collections page

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#4620]
- [ ] accessible from the the last section on Markets tab
-- resulting page displays top NFT collections sorted by volume (highest/lowest volume sorting options)
-- top right menu to change time period (24H / 7D / 1M), with 7D being default
-- each collection item in the list should display volume, diff for the selected period and current floor price for the collection.
-- in its first implementation the items in top collection list should not be clickable.

**Comment by Dianaaiym** [comment]
Sorting for Top NFT Collections: with 24h being the default
