### ISSUE TITLE
Change text in placeholder

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4630]
- [x] Add token: Change text "ERC20 / BEP20 / BEP2" -> "address or symbol..."
![2022-02-28 15 06 38](https://user-images.githubusercontent.com/22589457/155955177-65c883d6-ae64-4539-9dd2-b03f1a322e4e.jpg)

- [x]  Coin Manager - Search: Change "Search" -> "token name"
![2022-02-28 15 06 42](https://user-images.githubusercontent.com/22589457/155955215-8606dcf3-5e6f-4f81-bc15-b9201a8c78d4.jpg)

**Comment by esen** [comment]
"ERC20 / BEP20 / BEP2" -> "Address or BEP2 symbol"
"Search" -> "Token Name"
