### ISSUE TITLE
Private key wrong length

### ISSUE THREAD

**Issue by Zep-Maxim-Malikov** [horizontalsystems/unstoppable-wallet-android#4642]
Hi! I'm a user of Unstoppable android app (version 0.23.3) and I faced with bug. When I copy private wallet key (Ethereum or Binance Smart Chain) the value length is 66 instead of 64 and I can't to use it for import to another wallet.

**Comment by omurovch** [comment]
Hi @Zep-Maxim-Malikov,
Sorry for late response. This bug was fixed. Can you please update the wallet to the latest version 0.25.3 and check?

**Comment by omurovch** [comment]
Closing the issue for now, please feel free to reopen it in case you encounter the bug again.
