### ISSUE TITLE
Kotlin Extension Deprecated, Plz help!!!

### ISSUE THREAD

**Issue by wolfenix** [horizontalsystems/unstoppable-wallet-android#4644]
Getting these errors just after opening the project, tried everything, kindly help.

*Check the attached screenshot.

![11](https://user-images.githubusercontent.com/55916268/157294277-40402ed9-5503-45de-85d9-86a935ae0c82.PNG)

**Comment by wolfenix** [comment]
@rafaelekol kindly help me, it's urgent, I'm really stuck.

**Comment by rafaelekol** [comment]
You Gradle file not same as our Gradle file. Check errors and try to Google them to find the cause of errors.
