### ISSUE TITLE
Unable to send USDT bep20. Rpc Error

### ISSUE THREAD

**Issue by app** [horizontalsystems/unstoppable-wallet-android#4694]
unstoppable-wallet version 0.23.3

BTC transactions - Ok.
USDT bep20 receive - Ok.
USDT bep20 send - Fail. Button "Send" not enabled due to Error while Estimating Fee.
Trying to send several times within couple of hours. With and without VPN.

![image](https://user-images.githubusercontent.com/9341/159138583-7bc49d08-a725-4ea9-98a8-56593b22a320.png)

**Comment by hazge** [comment]
Have same problem on same version

**Comment by hazge** [comment]
Haven't got any BNB in my wallet for fee payment. 
Some meaningful message would be great

**Comment by omurovch** [comment]
Hey @app, @hazge 
It has been fixed in 0.24 already and will be released soon. It will show meaningful message.
Thanks for feedback!
