### ISSUE TITLE
Urus migrated

### ISSUE THREAD

**Issue by kdejaeger** [horizontalsystems/unstoppable-wallet-android#4727]
Urus token migrated to a new address. On the new token, the current price is missing.

New address:

https://etherscan.io/token/0xc6dddb5bc6e61e0841c54f3e723ae1f3a807260b

**Comment by Dianaaiym** [comment]
> Urus token migrated to a new address. On the new token, the current price is missing.
> 
> New address:
> 
> https://etherscan.io/token/0xc6dddb5bc6e61e0841c54f3e723ae1f3a807260b

Thanks for the information! Updated, during the day updated data will be available in the app

**Comment by kdejaeger** [comment]
I just looked and it's not ok yet.

**Comment by Dianaaiym** [comment]
> I just looked and it's not ok yet.

data has been updated

![2022-03-30 14 05 02](https://user-images.githubusercontent.com/22589457/160782708-a1e5a951-693b-4e5e-9ac1-1f20f8bcdeb2.jpg)
d

**Comment by kdejaeger** [comment]
![IMG_20220330_103916](https://user-images.githubusercontent.com/279268/160789826-0e57af0c-794d-4045-9be9-b8e9464fa219.jpg)
My issue is not about that view but about the wallet view.

**Comment by Dianaaiym** [comment]
> ![IMG_20220330_103916](https://user-images.githubusercontent.com/279268/160789826-0e57af0c-794d-4045-9be9-b8e9464fa219.jpg) My issue is not about that view but about the wallet view.

Is your current balance still at the old address?

**Comment by Dianaaiym** [comment]
> ![IMG_20220330_103916](https://user-images.githubusercontent.com/279268/160789826-0e57af0c-794d-4045-9be9-b8e9464fa219.jpg) My issue is not about that view but about the wallet view.
![2022-03-30 15 19 12](https://user-images.githubusercontent.com/22589457/160797491-f0e12850-6c29-4b97-a878-5140bbd8183a.jpg)

**Comment by kdejaeger** [comment]
No, the first entry is in fact the latest contract. I'm sure because I have just send 7 urus coins from the first entry to kucoin. And it went from 33.331 to 26.331.

I'm using the android app.

**Comment by kdejaeger** [comment]
I think, in an earlier version of the wallet, maybe 0.23, before it was available in the coin manager, I may have added the URUS token manually.

**Comment by Dianaaiym** [comment]
> I think, in an earlier version of the wallet, maybe 0.23, before it was available in the coin manager, I may have added the (old) URUS token manually.

Because you added the coin manually, URUS rate is not displayed now. To fix the problem, you need to reinstall the application, restore the wallet and add the URUS token.

**Comment by kdejaeger** [comment]
I reinstalled and now I have the right entry with the money displayed.
2 things however during this process:
- upon restoring wallet, I first forgot the passphrase and ended up with an 'empty' wallet. -> if possible to detect a passphrase was set on a wallet, please then also do some error handling there
- by default the old 'aurox' token was selected. I had to switch in this dialog:
![Screenshot_2022-03-30-17-28-18-188_io horizontalsystems bankwallet](https://user-images.githubusercontent.com/279268/160873879-caa512c4-2933-4457-ad05-26486012e919.jpg)
I guess this is a side-effect of a coin name having multiple entries on the same blockchain.

**Comment by Dianaaiym** [comment]
> I reinstalled and now I have the right entry with the money displayed. 2 things however during this process:
> 
> * upon restoring wallet, I first forgot the passphrase and ended up with an 'empty' wallet. -> if possible to detect a passphrase was set on a wallet, please then also do some error handling there
> * by default the old 'aurox' token was selected. I had to switch in this dialog:
>   ![Screenshot_2022-03-30-17-28-18-188_io horizontalsystems bankwallet](https://user-images.githubusercontent.com/279268/160873879-caa512c4-2933-4457-ad05-26486012e919.jpg)
>   I had to select the last option. I guess this is a side-effect of a coin name having multiple entries on the same blockchain.

This has already been fixed, the changes will be available in the new 0.25 version.
