### ISSUE TITLE
Different binaries on different channels. Why?

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4785]
I got the .apk file from the Unstoppable Wallet v0.24.1 here on GitHub, using [this link.](https://github.com/horizontalsystems/unstoppable-wallet-android/releases/tag/0.24.1)

On F-Droid (redirected from the [Unstoppable Wallet website]( htttps://unstoppable.money/)), I also downloaded[ v0.24.1](https://f-droid.org/en/packages/io.horizontalsystems.bankwallet/)

Then I copied the apk I from my phone, downloaded directly via Play Store.

```
I hashed all of them and that's what I got:
File: unstoppable-wallet-0.24.1 fdroid.apk
SHA-1: c2b935ae6bcfbaa696b3067ee2747eac3f008df1
SHA-256: e44725e11b1d0665331e29ec58b5084034050568bed353699f13a7efa3c8fd37

File: unstoppable-wallet-0.24.1 github.apk
SHA-1: c14e86bde01d1916b33da1e0c02222487bc2060f
SHA-256: b698efd06fd2c1f0346146ed5ecbd7c88330ef437bcdf4cbc1d3f39124143478

File: unstoppable-wallet-0.24.1 PS.apk
SHA-1: fdffc44e4a2396bed5389c11d0d8a59247ac9718
SHA-256: ecff4a80f259ea4d7dc4f701c87000c5a6f1c93b3fc5f4235aa038cab41ff528

```

links were provided above (except for Play Store version, you need to get it some other way, I suppose)

**Comment by rafaelekol** [comment]
Latest version in PlayStore must be 0.24.2. Can you check it by opening Settings page in Unstoppable App, it should be at the bottom. 
We forgot to publish 0.24.2  release in Github. Can you try run you compare with Github version 0.24.2  and latest on from PS.
As for F-Droid version. It should be anyway different since they build and sign app with their own key.

**Comment by ezxpro** [comment]
> Latest version in PlayStore must be 0.24.2. Can you check it by opening Settings page in Unstoppable App, it should be at the bottom. We forgot to publish 0.24.2 release in Github. Can you try run you compare with Github version 0.24.2 and latest one from PS. As for F-Droid version. It should be different anyway since they build and sign app with their own key.

I just checked it, it indeed is 0.24.1, no update available in Play Store.
![Screenshot_20220420-081339](https://user-images.githubusercontent.com/15344931/164220444-4d54ca61-f02e-4595-9d14-163a49f3c551.png)
![Screenshot_20220420-081403](https://user-images.githubusercontent.com/15344931/164220448-e4b9bb5c-1682-4403-bff3-eedb45d4616b.png)
![Screenshot_20220420-081414](https://user-images.githubusercontent.com/15344931/164220452-cafd5632-5a92-415d-98df-f980eb8a1c35.png)
![Screenshot_20220420-082609](https://user-images.githubusercontent.com/15344931/164220604-55887324-28f8-404e-8970-9d9723004ec1.png)

**Comment by ezxpro** [comment]
just tested again, uninstalling the app and installing it again from play store results in version 0.24.1 being installed.

**Comment by rafaelekol** [comment]
I just checked PlayStore dashboard. You was correct PS has 0.24.1 version as latest. 0.24.2 version was is Draft mode. Our manager forgot to move it to release mode. 
We fixed this issue, now app is in review. I think it will be available in few hours.
Sorry for our mistake.

**Comment by rafaelekol** [comment]
@ezxpro did you try it again?

**Comment by ezxpro** [comment]
> @ezxpro did you try it again?

I didn't have the time yet, but I'll do it asap

**Comment by ezxpro** [comment]
> @ezxpro did you try it again?

Hashes still differ:

```
File: unstoppable-wallet-0.24.2 PS.apk
SHA-1: 9baa5c8a99b6594377f53585601f1c59a1fbaa9a
SHA-256: 50becb19846c2cd2f686a0ad40f2889f99793558f58941ab9a492f8fb817a899

File: unstoppable-wallet-0.24.2 github.apk
SHA-1: 6f4d79daab61e2a141e7b0fedf3feb52881f624c
SHA-256: a4de14fa79b237923dd19773cd69bd60b0cae3fc5fdb6c0b320a82babe252568
```

Same for version 0.24.1

**Comment by rafaelekol** [comment]
The difference of APK from PlayStore can be caused by "frosting", check the link
https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1

**Comment by ezxpro** [comment]
@rafaelekol 

Ok, I'm closing this, because in following your insight, I was able to check the files do match.

To that effect and for anyone interested, I extracted both apks and created a checksum of the extracted content, 1685 files, all checksums matched.
