### ISSUE TITLE
Custom keyboard for seed phrase input

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4791]
First of all, I have to congratulate you guys on a nice feature, which is, when I go to settings and request the app to show me my seedphrase, I can set a pin or ask for biometric authentication there, and I can't take a screenshot,that's great, that's all very useful. 

On the  backup restore option though, there are several problems:
- I can take a screenshot/record the screen while typing my seedphrase
- keyboard is not in incognito mode. We know these keyboards actively send data we type to cloud servers 
- actually, I don't think we should use Android input methods at all. How can I trust google, Microsoft or whoever made the keyboard wont be sending what we type anyway, even when they're not supposed to?

To that effect, see the Mycelium wallet or AirGap vault. Both implement an internal keyboard very similar to that of some hardware wallets, where you type the first letters of a word in an internal keyboard, it suggests words from the known word lists, you can tap them not to have to type the full word.

So, the way I see it, we currently can have our seedphrase leaked by:
- malware that takes screenshots
- screen recorders
- keyboard sends away my seedphrase

Plus, there's the fact that using the current implementation, it's cumbersome to type long seed phrases.

Btw, Idk of I'm supposed to, but I put the label priority on this, because I think this is a pretty critical thing. Correct me if I'm wrong.

**Comment by abdrasulov** [comment]
Hello @ezxpro. Good points.

**Comment by ezxpro** [comment]
Hi, what's the progress status on this?

I still feel quite wary of typing seedphrases on Gboard, and i dont trust any of the keyboards out there not to be phoning home...


Anyways, just curious, i know you guys must have a lot on your plates already

**Comment by abdrasulov** [comment]
@ezxpro

We had multiple discussions regarding this issue. There are both pros and cons to implementing a custom keyboard. Implementing our custom keyboard requires additional resources to support it. There might be support for remaining bip-39 languages. So it may need many resources for support.

There are 3rd party keyboards in the app market that were implemented for privacy. It can be used instead of the standard keyboard as an option.

Summarizing all the above, we decided not to implement the custom keyboard as of now.

**Comment by ezxpro** [comment]
> @ezxpro
> 
> We had multiple discussions regarding this issue. There are both pros and cons to implementing a custom keyboard. Implementing our custom keyboard requires additional resources to support it. There might be support for remaining bip-39 languages. So it may need many resources for support.
> 
> There are 3rd party keyboards in the app market that were implemented for privacy. It can be used instead of the standard keyboard as an option.
> 
> Summarizing all the above, we decided not to implement the custom keyboard as of now.

Hmm, i see.
It's good to see you guys at least considered the suggestion.

After all, you've been doing a great job, the app is amazing 😍
