### ISSUE TITLE
How can I help translating the app?

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4792]
I'm interested in translating the app into Portuguese, however, I'd like to know how I'd go about doing that.

**Comment by Dianaaiym** [comment]
> I'm interested in translating the app into Portuguese, however, I'd like to know how I'd go about doing that.

Hi, 

We would be very grateful if you could help us with translations into Portuguese. We work through Crowdin Platform https://crowdin.com/project/bank-wallet-android You can ask questions about translations there.

**Comment by ezxpro** [comment]
@Dianaaiym Please, check this: https://crowdin.com/project/bank-wallet-android/discussions/6

Basically, there's only one "Portuguese" language in the project. I'm Brazilian and I started translating it in Brazilian Portuguese. European Portuguese and Brazilian Portuguese are the same language, but there are idiosyncrasies on both sides, and I sure as hell find it uncomfortable to use an app in European Portuguese, and I am sure the converse is true as well.

**Comment by Dianaaiym** [comment]
> @Dianaaiym Please, check this: https://crowdin.com/project/bank-wallet-android/discussions/6
> 
> Basically, there's only one "Portuguese" language in the project. I'm Brazilian and I started translating it in Brazilian Portuguese. European Portuguese and Brazilian Portuguese are the same language, but there are idiosyncrasies on both sides, and I sure as hell find it uncomfortable to use an app in European Portuguese, and I am sure the converse is true as well.
> 
> That's why I suggest splitting the projects. If you guys do decide to split, I suggest the existing project be renamed to "Brazilian Portuguese" and another be created with the name "Portuguese" only for the Europeans..

ok, I added Portuguese (Brazilian)
