### ISSUE TITLE
Refactor reading from SecureStorage

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#480]
The current implementation is too complicated

**Comment by abdrasulov** [comment]
There is one solution to simplify it. It is to cache sensitive data in memory in the very first activity start. But it doesn't work for saving values into the secure storage. Need to find a better solution.

**Comment by esengulov** [comment]
This issues was dropped from the list due to lack of team consensus on the importance/need of the described feature
