### ISSUE TITLE
App should make it clearer for user that private keys will be lost if screen lock is removed.

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4807]
I this screen could be improved.  Maybe you could just force the user to set a screen lock again? 
Perhaps I'm talking shit, because I don't know what the rationale was for this being implemented the way it is.

Thing is, the first time I went into the settings and accepted the terms, and saw one saying the private keys will be deleted if I mess with the lock screen, first thing I thought was: "Damn, this is terrible design, no way in the world people are gonna read this".

It should be the first thing that pops in your face once you open the app.

To that effect, I just checked Play Store's review section and found at least three complaints about people who didn't know it and lost access to their wallets, one of them had no idea why when he changed his lock screen he could no longer access his wallet.

Other one allegedly lost funds.

I mean, I think you guys must've thought this is a good idea, and I agree you shouldn't access the wallet if the phone has no lock screen, but the way this is implemented I think it's worse than if the user could access it without a lock screen. At least that way, if they get stolen, it's their fault, not the app's.

**Comment by abdrasulov** [comment]
Hi @ezxpro. Thanks for the feedback.

The main usage of the screen lock is the protection of sensitive data. We encrypt data with the key provided by the Android OS. This key is locked with the screen lock of the device. So if the screen lock is turned off the key gets expired. And the encrypted data cannot be decrypted anymore. It is the case when, for ex., the user's device has been lost or stolen. It is intended to protect user funds from being stolen. 

There are rare cases when the key gets expired by Android OS for no reason. That may be a reason why some users facing that issue.

As for the one who allegedly lost funds, this is not possible. The app requires the user to back up his 12/24 words before showing his recipient address for any blockchain. The user has to back up his words.

I agree that the message should be more noticeable. I'll discuss it with a team.

**Comment by ezxpro** [comment]
@abdrasulov ok, now I understand the rationale, esp. the part about the keys sometimes expiring for no reason, and the part about the impossibility of losing the funds.

Any way, I was a bit verbose on this issue. The whole point I wanted to make is that the message should be more visible.

**Comment by TalgatNurdinov** [comment]
@ezxpro We are currently working on it
![image](https://user-images.githubusercontent.com/42367908/179502938-cff8e66c-f1b9-475d-8296-212ef44930ab.png)

**Comment by TalgatNurdinov** [comment]
Terms Redesign: https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5246

**Comment by abdrasulov** [comment]
See #5246
