### ISSUE TITLE
WalletConnect doesn't work with AppoloX DEX

### ISSUE THREAD

**Issue by AbakumovAlexandr** [horizontalsystems/unstoppable-wallet-android#4809]
When going to [AppoloX DEX](https://www.appolox.finance/en) and trying to establish a connection with Unstoppable 0.24.2 using the 'Connect Wallet' button, Unstoppable shows 'You can go to the browser' screen. However, in a few seconds this screen gets replaced with the 'WalletConnect' (the one with connections list) screen and there's no AppoloX in the connections list. 

If navigated back to the AppoloX website, it shows an error:
![Screenshot_20220420-194921_Brave](https://user-images.githubusercontent.com/6968009/165018605-4fa60cfd-87be-4597-87a0-278c2b26febb.png)

**Comment by rafaelekol** [comment]
From https://coinmarketcap.com/currencies/apollox/ website address is https://www.apollox.finance/ and not `https://www.appolox.finance/en` that you indicated. 
I tested WalletConnection to apollox.finance. It connects to site, but then connection drops. Then I tried to connect with MetaMask app. It seems to connect, but interface in website not updated. I guess something is broken with WalletConnect on `apollox.finance` side.

**Comment by AbakumovAlexandr** [comment]
@rafaelekol Oh, I'm sorry. I've messed with the URL address and provided the incorrect one.

Thank you for looking into it. I've contacted ApolloX customer support with the issue of returning an incorrect chain id. So, I'm going close this one as it's not an Unstoppable issue,
