### ISSUE TITLE
Where is the biometric authentication gone?

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4814]
After updating the app to version 0.24.2, it stopped prompting me for my fingerprint (unless I'm confusing something and the app never had it in the first place).

I also don't see the option to enable it anywhere. Am I missing something here?

**Comment by abdrasulov** [comment]
That is strange. Did you have it set before the update? The app should not reset it if you had.

Well, you can set it in Settings -> Security -> Enable Passcode. Then enable Biometric Authentication

**Comment by ezxpro** [comment]
> That is strange. Did you have it set before the update? The app should not reset it if you had.
> 


Yeah, I had it set up before. I was starting to doubt myself

> Well, you can set it in Settings -> Security -> Enable Passcode. Then enable Biometric Authentication

Biometric authentication option is gone, nowhere to be found, here at least.

**Comment by abdrasulov** [comment]
I got it. Biometric authentication can be enabled only when it is set in the device. Most likely it is unset in the device.
