### ISSUE TITLE
Paste button in Add Token page not working

### ISSUE THREAD

**Issue by HenryWu01** [horizontalsystems/unstoppable-wallet-android#4835]
The paste button in Add Token page does not check and request read clipboard permission if necessary, so the paste button will have no action since the app did not have access to read data from it. Unstoppable Wallet did not throw any error about this. However when I enter Send coin page, Unstoppable Wallet request for that permission and now the paste button in Add Token page finally works.

**Comment by rafaelekol** [comment]
On what version of Android you experience this behavior? Do you use default keyboard(GBoard)?

**Comment by HenryWu01** [comment]
I have seen this on the newest release, I think it's 0.24. I'm using Xiaomi's device (Chinese keyboard)

**Comment by rafaelekol** [comment]
I can't reproduce the problem on my phones. Can you tell me Android version of your phone? Also can you make video or screenshot of the problem you are experiencing.

**Comment by HenryWu01** [comment]
I'm using Android 12 MIUI 13.0.4.0 (SKMCNXM)

**Comment by HenryWu01** [comment]
I reinstall Unstoppable Wallet and saw the permission request now. I think Unstoppable Wallet should handle when read clipboard permission is rejected?

**Comment by rafaelekol** [comment]
Can you screenshot the permission part. We have Samsung phone with Android 12, but we don't see any permission requests.

**Comment by HenryWu01** [comment]
I believe it's some modification to the Android System that Xiaomi make. I will change my phone to English and take a screenshot.

**Comment by HenryWu01** [comment]
Here is a short video to demonstrate what is happening:

https://user-images.githubusercontent.com/99880210/166652904-fb8cd767-0d1f-49c0-9706-c8766c482cdc.mp4

**Comment by rafaelekol** [comment]
We need to research this issue in order to fix it. Thank you for detailed information.

**Comment by rafaelekol** [comment]
@HenryWu01 Can you test this case.  We fixed paste buttons logic, and your case should be already fixed.
