### ISSUE TITLE
Add OKX Chain (OKC) to EVM networks

### ISSUE THREAD

**Issue by HenryWu01** [horizontalsystems/unstoppable-wallet-android#4836]
OKC is known as OKX Chain, 100% EVM compatibility. It was launched by OKX exchange, it have it's own token called OKB.

Here are some links:
- [Official Website](https://www.okx.com/okc)
- [Coinmarket Cap](https://coinmarketcap.com/currencies/okb/)

**Comment by esengulov** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/4716
