### ISSUE TITLE
Coin Page: Move ERC20 token to a page in ETH token and BEP20 token to page in BNB token

### ISSUE THREAD

**Issue by HenryWu01** [horizontalsystems/unstoppable-wallet-android#4840]
Instead of displaying all token on the home page, maybe display erc20 token in ETH token's page (a button when click ETH token, you will get like Send, Receive, Transfer, Stats. We may add another button let's say token button). In that page, all ERC20 token will be displayed. BEP20 will be display in BNB's token page. This makes home page cleaner and make it more user friendly for the incoming more EVM network integrations. Also for some altcoin like TRX(TRC20 protocol).

Here is some screenshots from other wallet product to demonstrate what I'am talking about:
![image](https://user-images.githubusercontent.com/99880210/166735349-79910448-fee4-4c77-a3ca-9fe5e60d1e59.png)

![image](https://user-images.githubusercontent.com/99880210/166736167-89907149-e44e-4791-8eba-d7ec77ba2d4d.png)

**Comment by HenryWu01** [comment]
Could we add this to consideration list? This is a pretty decent feature and keep home page cleaner and easy to track portfolio. @Dianaaiym

**Comment by HenryWu01** [comment]
@esengulov Could we add this to consideration list?

**Comment by esengulov** [comment]
@HenryWu01 hi Henry, we will consider this with UX guys and see if it's viable. Thanks

**Comment by esengulov** [comment]
meanwhile will keep the issue open

**Comment by esengulov** [comment]
we decided not to separate the tokens per chains at this point
