### ISSUE TITLE
Pro Feature > integrate decentralized RPC API protocol for EVM chains

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#4843]

**Comment by esen** [comment]
UX design needed first, considering:

- Off-chain orders list. Management of orders (replace, cancel(off-chain), invalidate(on-chain))
- Reflection of pending order amounts on the balance. Ability(or disability) to spend balance which takes part in pending orders. 

see [cowswap](https://cowswap.exchange/)
