### ISSUE TITLE
Markets: add a platform page with a list of protocols

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#4854]
![2022-05-06 18 10 24](https://user-images.githubusercontent.com/22589457/167128997-808e18bc-e617-4f7a-933d-acf7c7cdcaf2.jpg)

**Comment by kansalt** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=55269%3A274356
