### ISSUE TITLE
WalletConnect errors are useless

### ISSUE THREAD

**Issue by sirikid** [horizontalsystems/unstoppable-wallet-android#4855]
How tf I should know that you chose not to support WalletConnect v1 from just "Invalid address"? If I wasn't a software engineer myself I wouldn't understand it ever.

**Comment by rafaelekol** [comment]
We support both versions of WalletConnect. Can you provide the link(dApp) that gives this error.

**Comment by sirikid** [comment]
> Can you provide the link(dApp) that gives this error.

I'm trying to pay for Vultr hosting, they use BitPay. Is BitPay a dApp in this case?

**Comment by rafaelekol** [comment]
I tried BitPay with WalletConnect and Unstoppable Wallet. It connected and showed payment request without problem. I also needed to enable VPN, because BitPay is blocking IP from our country.
Also make sure that you have enough Ethereum in your wallet.
