### ISSUE TITLE
Deep research for Solana implementation. if all good implementation.

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4890]
Currently, I have 30% of my portfolio in the Solana network.  It would be nice to manage them with Unstoppable Wallet, but currently, Solana network is not supported.i also think this deserves some attention because Solana is one of the top 10 cryptos out there.

**Comment by esengulov** [comment]
- [ ] standard wallet feature for Solana SOL nd tokens on Solana chain
- [ ] support for solana DEX
- [ ] look into NFT support. implementation can be postponed if differs from standard token support.
