### ISSUE TITLE
Market Cap view

### ISSUE THREAD

**Issue by Irvise** [horizontalsystems/unstoppable-wallet-android#4892]
When looking at a token/coin in the "Price" tab there is an entry for the current Market Cap. However, there is no chart showing the historical evolution of such.

Under the "Analytics" tab for a coin, the Total Volume is shown in a chart and can be navigated as such (clicking on it and then being able to change the period in the  pop-up window).

Would it be possible to add such chart view of the Market Cap just like for Total Volume under the "Analytics" tab of a coin? The [backend used by the application (afaik Coingecko)](https://www.coingecko.com/en/coins/bitcoin) supports historical Market Cap data. In the link provided, click on the Market Cap tab (next to price) to view such information.

Regards,
Fer

**Comment by esengulov** [comment]
> When looking at a token/coin in the "Price" tab there is an entry for the current Market Cap. However, there is no chart showing the historical evolution of such.
> 
> Under the "Analytics" tab for a coin, the Total Volume is shown in a chart and can be navigated as such (clicking on it and then being able to change the period in the pop-up window).
> 
> Would it be possible to add such chart view of the Market Cap just like for Total Volume under the "Analytics" tab of a coin? The [backend used by the application (afaik Coingecko)](https://www.coingecko.com/en/coins/bitcoin) supports historical Market Cap data. In the link provided, click on the Market Cap tab (next to price) to view such information.
> 
> Regards, Fer

Hi Fer,
 
Thanks for the input! We will look into adding it. @kansalt

iBk

**Comment by esengulov** [comment]
@Irvise thanks for the input. Question, wondering what;s th use case for this considering that Map chart is likely to be same or closely similar to the price chart of the coin

**Comment by Irvise** [comment]
Hi @esengulov I believe that by Map Chart you are referring to the market value chart. Correct me if I am wrong.

Market Cap refers to the total value (in $) of the coin. It generally is Current Price x Number of Coins. For example, Bitcoin is right now at 463B$. However, it used to have a greater market cap (>1T$) a few months ago.

The reason I would like such a chart is to see the evolution of the total value of the Token/Chain. For example, such chart would have allowed to see the rapid decline of total market value of Tether that took place in spring/summer. The market cap view helps visualise the changes in value of a chain/token.

Thank you for your time,
Fer
