### ISSUE TITLE
Allow users to import any custom tokens like in metamask

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4915]
There's a whole lot of tokens that are in BSC or Ethereum that we could manage using unstoppable, but they're not supported and we can't import them ourselves.

What prevents us from adding just any token based on the protocol they use (ERC20/BEP20/TRC20)?

Anyways, I think this is a good idea, that way users have more freedom and autonomy, and devs won't have to bother adding every other token out there. In fact, new tokens are added practically everyday on the most popular networks, so I don't think devs can keep up anyway, so the best would be to delegate that to the users IMO.

**Comment by abdrasulov** [comment]
Hey @ezxpro. We have it already. On the Manage Coins screen clicking on the plus icon opens the screen Add Token. Here you can add a token by its contract address.
