### ISSUE TITLE
[BUG] Signing operations when connected to Orion Protocol doesn't work

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4916]
I used WalletConnect to access Orion Protocal(https://trade.orionprotocol.io/swap) the other day. 
I wanted to trade some BEP20 tokens from my BSC wallet.

Approving transactions worked fine, but signing contracts didn't, I click the Sign button and nothing happens. 
I don't know if it's a problem on their end or with unstoppable, so I reported it here and there.

**Comment by ezxpro** [comment]
@rafaelekol i was not willing to say this to avoid looking to be bad mouthing another project, but the truth is I found Orion Protocol to be extremely buggy, seems like it isn't even out of alpha stage yet. 

I talked about this and people slammed me, said they dont see bugs anywhere, but the fact is that the first time I used it I confirmed 5 reproducible bugs and reported it to them. 

So be advised this might not have anything to do with Unstoppable

**Comment by rafaelekol** [comment]
@[ezxpro](https://github.com/ezxpro) Thank you for detailed information. We decided to postpone this issue.

**Comment by MODSILVA1730** [comment]
Hello @ezxpro, I'm the Dev support assigned to attend to you, kindly proceed with a response regarding your current issue so we ca look into it or send an email to Silvayepes95@gmail.com
