### ISSUE TITLE
Add Polygon support for Android

### ISSUE THREAD

**Issue by HenryWu01** [horizontalsystems/unstoppable-wallet-android#4924]
When can Android have polygon (MATIC) support?

**Comment by ezxpro** [comment]
I can access MATIC tokens just fine around here.

**Comment by HenryWu01** [comment]
I mean polygon network, not MATIC token on ERC20, BEP20

**Comment by ezxpro** [comment]
Oh, I see

Em seg., 23 de mai. de 2022 2:15 PM, Henry Wu ***@***.***>
escreveu:

**Comment by abdrasulov** [comment]
Done in #4555
