### ISSUE TITLE
Periodically I see alert that warns that app drains battery

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#494]
App should be optimized.

[https://developer.android.com/topic/performance/power/](https://developer.android.com/topic/performance/power/)
[https://developer.android.com/topic/performance/background-optimization](https://developer.android.com/topic/performance/background-optimization)
We also should try to use [WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager/)

**Comment by esengulov** [comment]
This issues was dropped from the list due to lack of team consensus on the importance/need of the described feature
