### ISSUE TITLE
Update confirmation UI component style

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#4947]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=56059%3A234672

**Comment by kansalt** [comment]
- [ ] Change the color from Lucian to Leah
- [ ] Remove the "-", "+" signs 

<img width="855" alt="Screen Shot 2022-05-31 at 12 46 55 PM" src="https://user-images.githubusercontent.com/58926737/171110100-1fce8dd1-62b0-471e-be74-24c26939d488.png">
