### ISSUE TITLE
WalletConnect bugs

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4953]
Earlier today I experienced 2 bugs when using WalletConnect to connect to Biswap and Pancake Swap, respectively.

**Issue 1 - Biswap**
First, I was connected to Biswap's Swap interface, when google chrome crashed.
After the crash, I returned to the page and it showed my wallet as disconnected. Inside unstoppable, all I could see was this:
![image](https://user-images.githubusercontent.com/15344931/170722184-61c85155-f57b-4110-9c89-b9fc9d4be215.png)

I tried connecting again, once I scanned the QR code, I saw the same image as the one above.
Eventually, I found out that in Biswap, your wallet won't stay connected across the whole site. Say, if you connect your wallet in the "Liquidity" tab, it's only connected there, so in my case, I went to the "Swap tab" and could operate normally again.

**Issue 2 - Pancake Swap not connecting**
The second issue regards pancake swap, I can't connect to it at all. I disconnected my wallet from biswap both from the app and in the DEX website, but now when I scan Pancake Swaps QR code or input the code, all I see is this:
![image](https://user-images.githubusercontent.com/15344931/170722799-59075ddc-547a-4530-9318-f683d09dae90.png)

EDIT:
actually, this error is gone after restarting the phone

**Comment by abdrasulov** [comment]
As for the Biswap:

1. I could not reproduce the issue with "Invalid URL address". We have faced issues with the wallet connect bridge servers before. I think it may be the same reason. We'll periodically recheck it.
2. Regarding the wallet not staying connected across the whole site, I could reproduce it when I connect to biswap on the main page. Then when I went to the "Trade -> Exchange" page it showed me that the wallet is not connected. But with the Swap and Liquidity tabs, it works fine. Switching between tabs preserves the connection to the wallet. Could you please check it once again? I suppose that the biswap creates separate wallet connect sessions based on their domains. So the main page is hosted on the https://biswap.org/, and the Swap page is on https://exchange.biswap.org/. That may be a reason.

As for Pancake Swap, I could not reproduce it. Let's check it after some time.

**Comment by ezxpro** [comment]
> As for the Biswap:
> 
> 1. I could not reproduce the issue with "Invalid URL address". We have faced issues with the wallet connect bridge servers before. I think it may be the same reason. We'll periodically recheck it

I think this was a one time thing 

> 2. Regarding the wallet not staying connected across the whole site, I could reproduce it when I connect to biswap on the main page. Then when I went to the "Trade -> Exchange" page it showed me that the wallet is not connected. But with the Swap and Liquidity tabs, it works fine. Switching between tabs preserves the connection to the wallet. Could you please check it once again? I suppose that the biswap creates separate wallet connect sessions based on their domains. So the main page is hosted on the https://biswap.org/, and the Swap page is on https://exchange.biswap.org/. That may be a reason.

I am having no issies using biswap today and yeah, you're right, one has to establish separate connections in that DEX, but it works fine, i can connect to more than one tab simultaneously 


> 
> As for Pancake Swap, I could not reproduce it. Let's check it after some time.

Its okay, you can close this issue if you want, i think these bugs will be hard to reproduce, they're not taking place today, for example
