### ISSUE TITLE
All BSC transaction fees are showing up as "0BNB | $0.00"

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4954]
I've made a couple dozen payments and swaps from my BEP20 wallet today, all of them show the fees as "0BNB | $0.00". 

See
![image](https://user-images.githubusercontent.com/15344931/170731661-1ce707aa-05ac-4f61-9077-e539f0180c17.png)
![image](https://user-images.githubusercontent.com/15344931/170731734-b532f8c6-4bd2-4fb5-abce-5b9ac1d9d00d.png)

This is happening for payments as well as swaps made on dexes.

**Comment by abdrasulov** [comment]
@ezxpro, 

We could not reproduce the issue on both production and dev versions. Could you please check the fees for those transactions on bscscan.com?

**Comment by ezxpro** [comment]
> @ezxpro, 
> 
> We could not reproduce the issue on both production and dev versions. Could you please check the fees for those transactions on bscscan.com?

Ok, I'll do that

**Comment by ezxpro** [comment]
@abdrasulov Same transaction:
bscscan:
![image](https://user-images.githubusercontent.com/15344931/171429826-8bfe4f27-26b7-4149-957a-857ebe08f640.png)

unstoppable
![image](https://user-images.githubusercontent.com/15344931/171430222-75b7f0d8-7fcb-4acd-ba0e-ea74f0c7ddb5.png)

I checked every single BSC transaction I did across several wallets, all like this.

BTC transactions show the fee just fine.

**Comment by abdrasulov** [comment]
Hey @ezxpro. We've released the new version 0.25. Could you please check it in the updated version?

**Comment by ezxpro** [comment]
> Hey @ezxpro. We've released the new version 0.25. Could you please check it in the updated version?

Working fine now !
