### ISSUE TITLE
When on the "settings" screen, back button closes the app instead of going back.

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4956]
Hi guys, I do this all the time: I'm in the Balance/Transaction/Overview screen, enter settings, then I press the back button, the app closes.

That conjugates with the app locking itself every time it's minimized, as I mentioned [here](https://github.com/horizontalsystems/unstoppable-wallet-android/issues/4955), and thus it often becomes irritating.

I think it should go back to whatever tab was opened before, and then if I press it again, it closes.

**Comment by abdrasulov** [comment]
After #5009 and some testing, we came to that the back button on the Settings tab should act as in all other tabs. So we decided to leave it as is.
