### ISSUE TITLE
Create new `Appearance` screen in app settings

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-android#4974]
This page should contain

-theme setting
-launch screen setting
-balance conversion setting
-balance value setting

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=55693%3A282291

**Comment by abdrasulov** [comment]
Add ticket #5001 for app icon related tasks
