### ISSUE TITLE
Add float action buttons

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#4988]
- [x] Watch Address
- [x] Swap Settings (instead Apply button)
- [x] Create
- The button should be inactive if the necessary data are not filled in
- Keyboard should push float active button upward

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=59686%3A316213
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=59686%3A316055
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=59686%3A315824

**Comment by abdrasulov** [comment]
Check documentation for the "Extended FAB" and "`Modifier.imePadding()`"
