### ISSUE TITLE
[BUG] Properly fill in fields when scanning QR code in "bitcoin:..."

### ISSUE THREAD

**Issue by digisus** [horizontalsystems/unstoppable-wallet-android#4989]
Hi, if the user scans a QR code that delivers information in the format 

```
bitcoin:<address>?amount=<number>
```
the wallet copies the entire string into the address field. Then the user needs to manually copy/paste [number] to amount field and sanitize the address field. That is very error-prone on a phone.

_Expected behavior_

When receiving a QR in above format, the wallet automatically and correctly fills in the [amount] and [address] fields.

Thanks for providing UW and for looking into this small but effective improvement.

**Comment by abdrasulov** [comment]
Hello @digisus. Thanks for your feedback and kind words. We have this task in the next sprint #4653
