### ISSUE TITLE
Bep20 eth: Destination address changes to another one when there's no gas 

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#4995]
Idk exactly what triggers this but seemd like it's lack of gas.

![Screenshot_20220607-011646.png](https://user-images.githubusercontent.com/15344931/172294959-e2af657d-7c5f-4056-8d86-65aacbb284b0.png)

If i try to send binance peg eth and there's not enough gas, i see this address:
0x2170Ed0880ac9A755fd29B2688956BD959F933F8

In the destination field, instead of the one i typed.

**Comment by abdrasulov** [comment]
Hi @ezxpro. Could you please clarify, did you try to send via wallet connect?

**Comment by ezxpro** [comment]
@ezxpro no, that's a regular "send" transaction. See:

1.Start Binance Peg Eth send transaction, there's no gas:
![image](https://user-images.githubusercontent.com/15344931/172377112-1f5ff002-8724-481b-83e2-9e43fd8cfc85.png)

2. Enter valid address and amount of ETH
![image](https://user-images.githubusercontent.com/15344931/172377441-0391f737-df7f-4a1f-943b-89bff0f515bf.png)


3. address displayed different than what I typed in 
![image](https://user-images.githubusercontent.com/15344931/172377476-2d7e978a-9877-4abc-accf-609417d1ac8a.png)

Not sure if this is important, just thought it was confusing. If gas is there this appears not to happens ,as I sent multiple payments before, including this token.

**Comment by abdrasulov** [comment]
@ezxpro, we've fixed this issue. Could you please check it?

**Comment by ezxpro** [comment]
> @ezxpro, we've fixed this issue. Could you please check it?

Well, i just moved all my ether to Ethereum, so no, i cant really test it, but I think it

Well, i just moved all my ether from bsc to Ethereum, so i cant test it right now

I think you can close this issue, I mived all my binance peg coins to their respective networks yesterday's
