### ISSUE TITLE
Implementation of the Medium TopAppBar

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#5014]
Component:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=56923%3A235048

The pages where the MTAB should be:
- [ ] Restore
- [ ] Create
- [ ] Watch Address
- [ ] Transaction Info
- [ ] Fee Settings

- [ ] All Settings Pages

Layout Ex:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=56923%3A232238

**Comment by abdrasulov** [comment]
Tried Meidum Top App Bar on several screens with a parallax effect. It looks not that good. In addition, it takes much place in small screen devices.

So we decided to leave it as is for now. In the next version of the design, the Top App Bar should be totally reviewed.
