### ISSUE TITLE
Myst

### ISSUE THREAD

**Issue by PlayTim** [horizontalsystems/unstoppable-wallet-android#5015]
I have transvered 0.2 myst erc-20 to my wallet on the Block chain ist the Transaktion sucessful and the wallet Adresse is right but on unstoppable is no myst get in. Why?

**Comment by PlayTim** [comment]
I aktivate the other blockchains from myst and the myst is on poligon chain. But I would IT on erc-20 chain how can I change that? The Adresses are the same

**Comment by Dianaaiym** [comment]
> I have transvered 0.2 myst erc-20 to my wallet on the Block chain ist the Transaktion sucessful and the wallet Adresse is right but on unstoppable is no myst get in. Why?

Hallo,

Thanks for the feedback! Can you please provide more information about the token (name, coin code, and smart contract), and indicate where the transaction came from (from another wallet or exchange).

**Comment by ezxpro** [comment]
> I have transvered 0.2 myst erc-20 to my wallet on the Block chain ist the Transaktion sucessful and the wallet Adresse is right but on unstoppable is no myst get in. Why? 

Maybe you just need to add the token's smart contract
See
 
![Screenshot_20220622-081719.png](https://user-images.githubusercontent.com/15344931/175017055-dc022e07-c14f-41cd-a112-4e2e0cf458ec.png)
![Screenshot_20220622-081719.png](https://user-images.githubusercontent.com/15344931/175017096-5cdc695c-474f-49f6-99c0-5b046bd1a47b.png)
