### ISSUE TITLE
Accept donations using GitHub Sponsorship 

### ISSUE THREAD

**Issue by jasongodev** [horizontalsystems/unstoppable-wallet-android#5021]
You need more streams of income.

Ethically capitalize the strengths of Unstoppable Wallet as one of the most secure and verifiable wallet builds out there.

People are willing to give money for this.

**Comment by esengulov** [comment]
> You need more streams of income.
> 
> Ethically capitalize the strengths of Unstoppable Wallet as one of the most secure and verifiable wallet builds out there.
> 
> People are willing to give money for this.

Sorry for not following up here. We plan on adding a premium feature that would unlock certain features within the app as well as allow anyone to support our work.
