### ISSUE TITLE
Add Secondary currencies 

### ISSUE THREAD

**Issue by nahuhh** [horizontalsystems/unstoppable-wallet-android#5028]
This is a follow up to #4401, which requested the the ability to view your wallet balance in BTC or ETH.

This request is an enhancement / expansion

1. Add setting for "Alternate Currencies"
![Image_173.jpg](https://user-images.githubusercontent.com/50635951/173924256-c35431ec-9f6f-4596-9d28-7eafdce89917.jpg)
2. Option to disable "Alternate Currencies"
3. Allow selecting either Fiat or Crypto for "Base Currencies"
4. Only allow one alternate currency. Tapping on the currecy on the wallet screen swaps between which is the "Base Currency".

^ this improves the current implamentation

Further features: 
5. Calculate market tab in base currency
6. ![Image_174.jpg](https://user-images.githubusercontent.com/50635951/173929488-9bb388b8-5dfa-48dc-8f45-5464552a7699.jpg)
This button could also show here 
![Image_175.jpg](https://user-images.githubusercontent.com/50635951/173929788-87375755-d4a9-4a5a-8733-d91f07cafeb3.jpg)

The selection should not be global if changed on coin page
7. Per coin values (wallet entries) should also show in the selected "base"

**Comment by ezxpro** [comment]
Just out of curiosity, according to your suggestion, base currency could be a crypto currency?
Why?

**Comment by esengulov** [comment]
This has been implemented since version 0.25. Thanks for the input @ezxpro @nahuhh
