### ISSUE TITLE
BTC not syncing with APi:

### ISSUE THREAD

**Issue by ezxpro** [horizontalsystems/unstoppable-wallet-android#5039]
Today i noticed that if its syncing with the API it will either stay greyed out and never sync, or give me this error

![Screenshot_20220619-002623.png](https://user-images.githubusercontent.com/15344931/174464600-ba637578-9048-4be7-8fc9-895260cf0f4b.png)

Syncing from the blockchain works, but it takes forever.

**Comment by abdrasulov** [comment]
We've just released hotfix v0.25.2. It was the hotfix exactly for this issue. Could you please update the app and check it once again?

**Comment by ezxpro** [comment]
@abdrasulov oh, thanks, i did but see there was an update. Ot works fine now, you can close this issue
