### ISSUE TITLE
Connection 

### ISSUE THREAD

**Issue by Mikec90** [horizontalsystems/unstoppable-wallet-android#5069]
I wanted to trade some Matic tokens from my wallet.
Transactions worked fine, but signing contracts didn't, I click the Sign button and nothing happens.
I don't know if it's a problem on their end or with unstoppable, so I reported it here and there. https://github.com/horizontalsystemshttps://unstoppablewallet.com

**Comment by abdrasulov** [comment]
@Mikec90, could you please share the details?
