### ISSUE TITLE
Market Search: Make Filter by Blockchain UI as in design

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#5086]

**Comment by TalgatNurdinov** [comment]
@rafaelekol  this page has been redesigned a bit, decided to close with a back button.
also please add the icons.
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=48905%3A305280
