### ISSUE TITLE
Issue with btc sync

### ISSUE THREAD

**Issue by AntonBespalov** [horizontalsystems/unstoppable-wallet-android#5125]
There was a synchorinized BTC BIP49 in my wallet. I chose BIP84 also and it started to synchronize too. During the sync process of BIP84, I send BTC to BIP49 address. According to blockchair.com, the transacrion was confirmed, but I didn't see BTC in my wallet.
Only after I close and restart the app, BIP49 were also synchronized and I saw received BTC.

**Comment by abdrasulov** [comment]
Hi @AntonBespalov,

We checked the issue. We could reproduce it. Most likely, there was a bitcoin network syncing issue. If you face this issue again can you please send us app logs (Settings -> About App -> App Status)?  From our side, we'll check it periodically and inform you if we have any updates.

**Comment by esengulov** [comment]
@AntonBespalov any updates on the issue?

**Comment by AntonBespalov** [comment]
Hi, I didn't run into this problem again.
