### ISSUE TITLE
Cannot build the app

### ISSUE THREAD

**Issue by laisuki1109** [horizontalsystems/unstoppable-wallet-android#5163]
After I downloaded the release `0.25.3`
The app cannot be build cause it cannot find the bitcoin kit and add into the project.

```
FAILURE: Build completed with 9 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.horizontalsystems:bitcoin-kit-android:a070562.
     Required by:
         project :app

```

how to solve it?

**Comment by abdrasulov** [comment]
Try to "Sync project with gradle files" and then build the app.

**Comment by laisuki1109** [comment]
> Try to "Sync project with gradle files" and then build the app.

The above error is appeared, after I sync and build

**Comment by abdrasulov** [comment]
We checked it once again. It works fine. It seems that the https://jitpack.io/ where bitcoin-kit artifacts are located is not accessible. Try to check it later.

**Comment by laisuki1109** [comment]
I waited for 7 days, but the library of bitcoin kit is also not found

**Comment by rafaelekol** [comment]
Try in Android Studio : Build -> Clean Build
then press Rebuild Project in same place

**Comment by laisuki1109** [comment]
![image](https://user-images.githubusercontent.com/43807081/182811649-3e2f860b-a023-46dd-9b8b-c27709c8f580.png)
The problem is still occured

**Comment by tkterris** [comment]
I changed it to use the "a070562cc6", which worked as well.

https://jitpack.io/com/github/horizontalsystems/bitcoin-kit-android/a070562cc6/

**Comment by laisuki1109** [comment]
> a070562cc6

Worked. Thank you
