### ISSUE TITLE
BTC Recommended Fees is too low

### ISSUE THREAD

**Issue by AbuGosok** [horizontalsystems/unstoppable-wallet-android#5171]
Since last few weeks until today, I tried to send BTC from unstoppable wallet several times (BIP49, haven't tried other yet).

Most of the times, I got recommended a fee of 2-4 sat/vBytes. It results often in several hours up to 2 days of confirmation.

When I check mempool.space, recommended fees should be around 10-12 sat/vBytes. Any idea why is this happening?

**Comment by abdrasulov** [comment]
Hello @AbuGosok. Thanks for your report.

The fee rates configured in the app became low. We will update them.

**Comment by abdrasulov** [comment]
Set the following fee rates for BTC

- high priority: 1 block
- medium: 2 blocks
- low: 6 blocks
