### ISSUE TITLE
make sure client is prepared for ETH merge and fork event

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#5241]
- [ ] The app should be able to identify balance on both POW and POS chains and display correctly. 

- [ ] if the Uniswap or 1inch supports new POW chain then swap feature should be available for the fork. Please followup with respective protocols and see what's theis stance on it.

- [ ] the old ETH should renamed to Ethereum POW and old ETH coin code should be ETHP. The chain name should be renamed to Ethereal POW. The post merge Ethereum should retain current (default) naming i.e. Ethereum for chain name and ETH for coin code. Also followup with @Dadybayo to see what the naming will be adopted by coingecko, uniswap, binance and 1inch and proceed accordingly to avoid confusion on the users' end

- [ ] @Dadybayo depending on the namiing of the new chains post merge labels for methoIDs might need to be edited

**Comment by abdrasulov** [comment]
We tested the app on the Goerli network which is PoS. It works fine. No changes are needed. 

As for the PoW forks, let's get back to it when the Mainnet switches to PoS.

**Comment by esengulov** [comment]
Upon firther consideration it was decided that Unstoppable won't be supporting Ethereum POW chain to avoid confusion on client side. There is a wide consensus among leading projects not to support Ethereum POW chain.
