### ISSUE TITLE
Backup Recovery Phrase: improvements

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-android#5264]
- [x] After creating a new wallet, open the bottom "backup recovery phrases" sheet

- [x] Update the design, text

- [x] Update the steps of the phrase verifying 

Layouts:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=59915%3A339007

**Comment by 3point14159** [comment]
Will these improvements allow for importing BIP39 Seed, BIP32 Root Key, Account Extended Private Key, and/or BIP32 Extended Private Key? Also, will it allow for watch only via Account Extended Public Key and/or BIP32 Extended Public Key? Importing inputs from [these outputs](https://iancoleman.io/bip39/) could be helpful for users.

**Comment by abdrasulov** [comment]
Hello @3point14159. Could you please add a separate issue for that?

**Comment by 3point14159** [comment]
Let's wait until .27 releases. Perhaps this is addressed and implemented in the build. Many issues seem to reference this in other terms, but I was looking for confirmation.

**Comment by abdrasulov** [comment]
OK good.

As of now, watching account is supported for EVM-based blockchains. Ethereum, Binance Smart Chain, Avalanche (C chain), Optimism, Polygon, and Arbitrum. Restoring an account from its seed phrase is already in the app.

**Comment by 3point14159** [comment]
The circumstance may be that you don't want to enter private keys or seed phrases to make transactions, but may want to simply watch assets or whale-watching. I seen the option to do so on the VM chains, but it should be just as simple to allow for that with any blockchain using xpubs.
