### ISSUE TITLE
Derivation issues?  I restored my coinomi wallet words into unstoppable ... it found jack.

### ISSUE THREAD

**Issue by PopeNobody** [horizontalsystems/unstoppable-wallet-android#5301]
Hey, y'all.  I'm looking for a new home now that coinomi, which I have been using forever, is going to be discontinued.

It's probably for the best, I hate using software I can't see the source for.

But unstoppable showed errors on the two chains where I had anything to speak of ... BCH and BTC.

And failed to locate any balances.  I've seen such things before, usually having to do with the derivation of the keys ... but I don't see a way to adjust the derivatives used through your interface.

I'm planning to fire it up under Android Studio, and that will probably answer the question, but it might not be a bad plan to add a step to the restore where you ask what wallet the user formerly used.  If I was a newbie, and could not look at a blockchain explorer, I'd be rattled.

**Comment by heno72** [comment]
Have you tried changing the address types of your asset? It can be done from the wallet interface by:

**Select this icon on the wallet interface**
![WhatsApp Image 2022-08-20 at 8 55 39 PM](https://user-images.githubusercontent.com/100990936/185747259-d8328534-dbb2-443b-9df0-5ff0ed26a761.jpeg)

**Select the pencil icon on your selected asset.** As far as I know there are 3 options for BTC, and 2 options for BCH.
![WhatsApp Image 2022-08-20 at 8 55 40 PM](https://user-images.githubusercontent.com/100990936/185747321-ff90328a-92d8-483e-9375-709900363687.jpeg)

**For example in BTC,** there are three commonly used derivation paths:
![WhatsApp Image 2022-08-20 at 8 55 40 PM (1)](https://user-images.githubusercontent.com/100990936/185747341-a3b24970-5201-4668-8edc-4ad25392d94c.jpeg)

Can you find your balance on any of those derivation paths?

**Comment by abdrasulov** [comment]
Hello, @PopeNobody. Could you please let us know if the issue still persists?

**Comment by PopeNobody** [comment]
Sorry for the delay.  I found one problem, apparently the wallet was looking at TestNet.  However, I'm still not seeing my balance ... it looks like network/connection problems.  I'll check back in when I have time.
