### ISSUE TITLE
Incorrect AWBTC values on deposit to Aave V3 Polygon

### ISSUE THREAD

**Issue by heno72** [horizontalsystems/unstoppable-wallet-android#5302]
![WhatsApp Image 2022-08-20 at 8 34 36 PM](https://user-images.githubusercontent.com/100990936/185746450-29e40e6d-f731-448b-97ee-25bbc8306f99.jpeg)

**Expected behavior:**
On depositing WBTC to Aave V3 Polygon, the wallet should deduce WBTC and obtain a similar amount of AWBTC.

**Actual behavior:**
The wallet instead detected that AWBTC received is 10^8 times the deposited WBTC. The value of each AWBTC is apparently set equal to WBTC, therefore it shows that I received 10^8 times the worth I receive.

Upon inspection, the token contract address is correct:
`0x078f358208685046a11C85e8ad32895DED33A249`

However said contract address is not present in the wallet's Polygon chain coin list by default:
![WhatsApp Image 2022-08-20 at 8 39 13 PM](https://user-images.githubusercontent.com/100990936/185746611-cfedae11-1f99-476d-a606-4f49a64dfec5.jpeg)

Is there any other info that I can provide to help the developers to fix it? Thank you.

**Comment by abdrasulov** [comment]
@heno72, there were some issues with the data. Now it should show correct values. Can you please check?
