### ISSUE TITLE
transfer Zyn to my wallet which does not appear

### ISSUE THREAD

**Issue by MX10-AC2N** [horizontalsystems/unstoppable-wallet-android#5303]
Hello to all.
I installed your application and created a wallet with the few cryptos I may have already elsewhere.
Then I tried a first upload in ZYN, I transferred a little more than 10 ZYN but nothing appears in my Unstoppable wallet.
What's going on? It's been more than 2 hours and still nothing in my unstoppable wallet.

here is the TxHash of my transfer
https://explorer.wethio.io/txs/0x8d6380832e2270dd3b72477d2640b0ce996eac92712404d57e948351094019b6

**Comment by abdrasulov** [comment]
Hello,

There is no support for the Wethio blockchain in the Unstoppable wallet. ZYN token you've enabled in the Unstoppable wallet is the token in the Ethereum blockchain.

**Comment by MX10-AC2N** [comment]
Pff, so I loose my transfert ?

**Comment by abdrasulov** [comment]
Try to restore your account in the wallet that supports that blockchain.

**Comment by MX10-AC2N** [comment]
Thank @abdrasulov 
I don't quite understand your answer.
Do I have to restore my wallet under Unstoppable? Anyway, my wallet is empty at the moment, so I don't risk anything, that's for sure.
Or should I restore my wallet somewhere else?
And are we talking about the restoration of the wallet created in unstoppbale?
Sorry I'm still a beginner in the crypto world, thanks for your advice..

**Comment by MX10-AC2N** [comment]
Hi,
I was finally able to recover my Zyn by importing my wallet created in Unstoppable, I imported it into wethio wallet with the private key and I found the zyn that I had sent to my Unstoppable wallet.
Thanks again.
