### ISSUE TITLE
Zcash (ZEC) Sync Error

### ISSUE THREAD

**Issue by espdev** [horizontalsystems/unstoppable-wallet-android#5340]
Hello,

Zcash (ZEC) does not synchronize for several days in a row. "Sync Error" is occurred, "Retry" does not help. There are no any settings for a lightwallet server or something like this for ZEC wallet. I have checked network, reinstalled the app. ZEC wallet just does not work now.

<img src="https://user-images.githubusercontent.com/1299189/187227689-64bab116-2770-4b44-b49f-7f41115d5a38.jpg" width="300" />

**Comment by rafaelekol** [comment]
What type of network are you using: Wifi or Mobile internet?

**Comment by espdev** [comment]
I tried both and even turned the VPN on/off. Tor is not used.

I just launched the app again and ZEC started syncing. Blocks are downloaded.

**Comment by espdev** [comment]
Sync doesn't work again

**Comment by espdev** [comment]
BTC synchronizes, ZEC does not.

<img src="https://user-images.githubusercontent.com/1299189/187885226-cf5fed94-93bf-43ea-b497-b073f31fcbf3.jpg" width="300" />

I cannot access my funds on ZEC wallet. I have created a wallet with a passphrase and cannot restore the ZEC wallet in another wallet program by seed phrase only.

**Comment by Dianaaiym** [comment]
> BTC synchronizes, ZEC does not.
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/1299189/187885226-cf5fed94-93bf-43ea-b497-b073f31fcbf3.jpg">
> 
> I cannot access my funds on ZEC wallet. I have created a wallet with a passphrase and cannot restore my ZEC wallet in another wallet program by seed phrase only.

Hi,

We are already working on fixing the bug  🙏

**Comment by espdev** [comment]
@abdrasulov 

It didn't work on weekends. Now I have launched the application, sync is in progress.

**Comment by espdev** [comment]
The only thing is very slow "scanning blocks".

**Comment by abdrasulov** [comment]
Yes, it is. We've been looking for a solution to make it faster.
