### ISSUE TITLE
Add USDT (TRC20) to Unstoppable wallet

### ISSUE THREAD

**Issue by TheFuzzStone** [horizontalsystems/unstoppable-wallet-android#5355]
Most activity on the OTC/p2p market has USDT (TRC20).

Many people complain about proprietary wallets such as Exodus, which often have problems and you have to write to support to solve the problem.

Other users said that transaction history in Trust Wallet might have disappeared, which again, is very inconvenient when you need to keep track of your transactions at the end of the day/week/month. [I think they've already fixed that problem, but still - unpleasant memories remained].

By adding USDT (TRC20) to your wallet you can attract many new users.

**Comment by TheFuzzStone** [comment]
Any updates?

**Comment by esengulov** [comment]
> Any updates? 

Hi there, we are unsure about TRON yet as we didn't have a chance to research the integration.we will keep the issue open for the time being and will see if it can be integrated in the near future

**Comment by TheFuzzStone** [comment]
@esengulov, any updates?

**Comment by TheFuzzStone** [comment]
![image](https://user-images.githubusercontent.com/16173361/211484493-c81a46a4-cb2d-4d93-b68a-eed7c8ab99ce.png)

[[source]](https://discord.com/channels/884740851203448882/885107608057434122/1060798702136066058)

**Comment by esengulov** [comment]
@TheFuzzStone @trafficbenj so we spent some time evaluating TRON chain and it seems there are some specifics in regards to the chain that makes it incompatible with our current architecture. Although it's branded as EVM chain it's not really plug n play as other EVM chains. There are some unusual mechanisms regarding account creation, fee settings, staking etc. So with that in mind we decided to postpone the integration for the time being.

**Comment by ikigai-gh** [comment]
The lack of this feature is the only one thing that prevents me from using your app :(

**Comment by esengulov** [comment]
> The lack of this feature is the only one thing that prevents me from using your app :(
it's in the works and most likely will be added in the next update

**Comment by TheFuzzStone** [comment]
Just updated to version 0.33 and I see support for Tron (TRX) and USDT (TRC20). You guys are cool!

---

Only the "What's new" page didn't load for some reason...

![image](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/16173361/cec5f12e-9181-4a96-98e5-bca8a2c59a4e)

**Comment by TheFuzzStone** [comment]
@esengulov

**Comment by abdrasulov** [comment]
@TheFuzzStone, thanks for the kind words. We are still in the process of releasing v. 0.33. It seems like F-Droid built it once we created a tag. We'll publish the What's New for this version soon.

**Comment by TheFuzzStone** [comment]
@abdrasulov, so at this point it is better not to use version 0.33, because it has not yet been completed?
