### ISSUE TITLE
Add eCash (XEC), a Bitcoin Cash fork by the creator of BCH

### ISSUE THREAD

**Issue by 3point14159** [horizontalsystems/unstoppable-wallet-android#5363]
It would be great for Unstoppable to be the first non-custodial wallet to support eCash, especially when Avalanche activates on Sept 14!

Relevant links:

https://e.cash/wallets

https://avalanche.cash/

https://twitter.com/eCashOfficial/status/1565010900792360960

https://www.bitcoinabc.org/releases/

contact@e.cash

I am looking forward to [Amaury's improvements](https://www.youtube.com/watch?v=uJOQsQdp1Uc) and how much easier it will allow for users to [transact in a post-CBDC world](https://www.youtube.com/watch?v=3lUs-MUnwqA).

**Comment by esengulov** [comment]
merged into https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5962
