### ISSUE TITLE
[BUG] 1inch allowance approve

### ISSUE THREAD

**Issue by ioiouaua** [horizontalsystems/unstoppable-wallet-android#5388]
"The current ETH balance is below the amount required to process this transaction, including the transaction fee"
And in "Fee" line I see: "N/A"

I have enough ETH to make this transaction but time-by-time I see this error. Sometime this can make a big loss

**Comment by abdrasulov** [comment]
@ioiouaua,

The fee depends on the current transactions in the mempool. So sometimes it can be high. What was your approximate ETH balance when you faced that issue?

**Comment by ioiouaua** [comment]
> @ioiouaua,
> 
> The fee depends on the current transactions in the mempool. Sometimes it can be very expensive. What was your approximate ETH balance when you faced that issue?

>10 ETH I think this enough to cover any fee. And another bug with allowance until I spent all "allowed amount" it shows this error. I still have allowed ~3$ for spend and until I not spend this 3$ I can't allow use more funds.

**Comment by abdrasulov** [comment]
That is more than enough. Could you please share what token you tried to swap?

**Comment by ioiouaua** [comment]
> That is more than enough. Could you please share what token you tried to swap?

USDT->ETH.
Previous allowed amount: 10k
Used: 9.997$
Left for spend: 3$

For 3 days I see "N/A" and this error screen. But if I will buy something for this 3$ (with fee ~7$ :D) I will able to set new allowed  amount to spend.

**Comment by abdrasulov** [comment]
@ioiouaua

When the app tries to calculate the fee for updating the USDT allowance Ethereum node responds with an error. The error message says "execution reverted". After researching, we concluded that USDT token smart contract doesn't allow changing allowance to a value other than 0. So to update the allowance, you should first set it to 0. And then set it to the desired amount.
