### ISSUE TITLE
[BUG] Incorrect amount

### ISSUE THREAD

**Issue by ioiouaua** [horizontalsystems/unstoppable-wallet-android#5390]
I and another 5 users have troubles when incorrect amount show's in transaction. Example:
![image](https://user-images.githubusercontent.com/113476211/190105427-87cfcde6-99c3-42b4-ade6-2c2ccb6d4e1d.png)

Sent 11$ but it shows 2 transaction and shows it like 22$ in transaction history.

**Comment by Dianaaiym** [comment]
> I and another 5 users have troubles when incorrect amount show's in transaction. Example: ![image](https://user-images.githubusercontent.com/113476211/190105427-87cfcde6-99c3-42b4-ade6-2c2ccb6d4e1d.png)
> 
> Sent 11$ but it shows 2 transaction and shows it like 22$ in transaction history.

Hi, 

Could you send us a transaction ID? For privacy, you can send it to our support email (please find it in the app, Settings - About App - Contact).
