### ISSUE TITLE
Looking for documentation.

### ISSUE THREAD

**Issue by Pallvi-Rajput** [horizontalsystems/unstoppable-wallet-android#5414]
“Hi, this is a great project & looks very reliable. I have forked the repo & I am trying to deploy & make some changes, but I can’t seem to find my way around the code base. Can you share further documentation? Any guidance would be appreciated. Thanks so much for the great work & sharing with the community 🙏🏽”

**Comment by esengulov** [comment]
> “Hi, this is a great project & looks very reliable. I have forked the repo & I am trying to deploy & make some changes, but I can’t seem to find my way around the code base. Can you share further documentation? Any guidance would be appreciated. Thanks so much for the great work & sharing with the community 🙏🏽”

Documentation has been update recently
