### ISSUE TITLE
Add support for eCash (XEC), an improved BCH fork from some of its core devs

### ISSUE THREAD

**Issue by 3point14159** [horizontalsystems/unstoppable-wallet-android#5431]
Should be an easy integration into the next release of Unstoppable. Thanks in advance for the efforts to make it happen.

From the [latest Avalanche consensus protocol activation](https://www.youtube.com/watch?v=cbhXNfSznAI), confirmation times should register within just a few seconds, taking transacting and trading to a whole new level. It is going to be exciting to see what the next generation of blockchain tech will bring us, and thanks again for keeping us on the bleeding edge Unstoppable devs.

Links:

https://ecash.community/
https://www.bitcoinabc.org/
https://coinmarketcap.com/currencies/ecash/
https://teddit.net/r/ecash/new

*sorry for [the dual post](https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5363); delete away.

**Comment by esengulov** [comment]
being implemented https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5962
