### ISSUE TITLE
Bitcoin sub-units: bitcents and millibits

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#5446]
I really liked the Satoshi (sat) subunit so much that I use it in most of the apps that allow me to set up a Bitcoin subunit.

However, realistically, it is not suitable for conversion (convenient from the point of view of price readability) because it is too small unit to represent everyday expenses.

Could you implement bitcents and millibits in future updates?

**Comment by Dianaaiym** [comment]
Thank you for the feedback! But this task is currently not relevant
