### ISSUE TITLE
Can't See my own private keys

### ISSUE THREAD

**Issue by mitexleo** [horizontalsystems/unstoppable-wallet-android#5478]
Hi there 😊, From a user's review on play store I've come to know that Unstoppable Wallet doesn't allow users to see their Private Keys for Bitcoin or other currencies except EVM..

If I can't get my hands on my own wallets How am I supposed to Import the wallets to somewhere else?

Who is actually in control of my crypto while using this Wallet ?

**Comment by abdrasulov** [comment]
As of bip39, there is a recovery phrase that is also called a mnemonic or seed phrase. This phrase is used to generate all of the private keys. So you can import your account in any supported wallet using that phrase. To show the recovery phrase go to Manage Wallets -> Wallet -> Recovery Phrase. You can read more about bip39 here https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki.

As for private keys, we've recently released version 0.28.0 which includes the feature for showing private keys also for bitcoin-based blockchains too.

**Comment by mitexleo** [comment]
Thanks for your explanation 👍... 

BTW.. Could you please  add the Fdroid version in the Assets Section ?

**Comment by abdrasulov** [comment]
The Fdroid versions are built by the Fdroid itself automatically when there is a new release on GitHub. So the new version should be released there soon.

**Comment by mitexleo** [comment]
😊
