### ISSUE TITLE
can't send funds

### ISSUE THREAD

**Issue by mitexleo** [horizontalsystems/unstoppable-wallet-android#5491]
Hi ,
I'm unable to send my BTC to any address ! 
I'm getting following error while pressing "Send"

![Screenshot_20221106-125102_Unstoppable](https://user-images.githubusercontent.com/114842102/200158271-7fe3022b-c2c9-4bae-9406-d8aedfa78665.jpg)

**Comment by mitexleo** [comment]
After closing and reopening the app everything seems working fine ..

**Comment by abdrasulov** [comment]
Hello @mitexleo. Good to hear that everything working fine. Please let us know if it occurs again.
