### ISSUE TITLE
Dash not syncing

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#5507]

**Comment by abdrasulov** [comment]
The issue was in DNS seeds. All of the used dash DNS seeds stopped responding. After reporting it, the problem was solved by the Dash team.

**Comment by abdrasulov** [comment]
I could not reproduce it. Also, I checked DNS seeds. It works fine. Can you please check it once again?

**Comment by Dianaaiym** [comment]
> 0.31.0 Dash doesn't start sync. Never.
> 
> It doesn't even try to start.
> 
> ![1000005044](https://user-images.githubusercontent.com/113377431/230657444-c33a560c-5c25-41e8-92a7-4d8def983ddb.jpg)

Hi,

Please send your App Status (Settings-About App) to support.unstoppable@protonmail.com

**Comment by rafaelekol** [comment]
@serrq Did you try syncing on Wi-fi?
