### ISSUE TITLE
Transaction tab: update the design of a group of transaction cells

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-android#5512]
- [x] Add a stroke for the transaction group of the day 

![25a116b496](https://user-images.githubusercontent.com/58926737/201974489-9791a982-eb3d-4eb7-a808-24dedc98ca1e.jpg)

layouts: https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=63242%3A405595&t=Qyzu4bPll1O53MEp-4

**Comment by abdrasulov** [comment]
Wrong clickable area for first/last/single items
