### ISSUE TITLE
[Request] Adding ARRR (Pirate Chain) and BSV (Bitcoin SV)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#5523]
Both coins are based on a Bitcoin like blockchain. The first one is privacy oriented.

https://pirate.black/

The second one has some good features like transaction finality in just two seconds.

https://bitcoinsv.com/

**Comment by esengulov** [comment]
there are a number of other chains we would like to integrate before we can explore this. So, this may take a while. Not keen on BitcoinSV to be honest. Is it being used ?
