### ISSUE TITLE
[Request] Adding built-in swap between bitcoin like coins

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#5524]
I would like to swap between all bitcoin like coins (LTC, BTC, ARRR, ZEC, BSV, BCH, etc.) within the app.

**Comment by esengulov** [comment]
We are exploring recommended options. Considering Sideshift integration in the near future.

Closing the issue as it's same as https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5527
