### ISSUE TITLE
[Request] Adding a backup/restore all wallets method

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#5525]
The main method to restore a wallet is seed. Ok, but I have 20 wallets. So 20 seeds.

Can you add an encrypted file with all necessary inside to restore (and backup) all my twenty wallets with only one shot?

**Comment by esengulov** [comment]
@serrq @3point14159 thanks guys,

We are considering to add this but wondering how do you envision the backups steps. Backing an encrypted file to iCloud/GoogleCloud? or local storage?

**Comment by esengulov** [comment]
Upon further research we found some blackboxes in regards to this feature:

- if backup is to be made using native Google services than what to do with phones that do not support Google services i.e. Huawei

- there might be an issue in providing fdroid version of the app if it uses Google services.

Hence, we are postponing this for the time being.

**Comment by esengulov** [comment]
Thanks for the input @3point14159 @serrq we are keeping this in the pipeline. Backing up locally currently seems like a working option.
