### ISSUE TITLE
Duress PIN

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#5526]
Allows a person to enter a pin other than the real one that opens a wallet with little money. Useful if someone is threatened or under attack.

**Comment by esengulov** [comment]
in consideration. Looks like an easy feature on a first sight. Basically user activates this feature and indicates which wallets out of bunch would be visible when duress pin entered.

**Comment by esengulov** [comment]
moved to https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1064
