### ISSUE TITLE
[Request] Adding StealthEX and SideShift as built-in trading platforms

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#5527]
No sign-up crypto exchanges: this add a lot of possibilities for swapping more coins and tokens.
No account required. 

https://stealthex.io/

https://sideshift.ai/

**Comment by esengulov** [comment]
We don't have much info on StealthEx.io so not sure about it just yet. Sideshift on the other hand likely to be integrated at some point in the near future. The only thing that holds us back now is that its API is not reachable from sanctioned countries and asa result these users would be left out. We don't like that but perhaps something is better than nothing...

**Comment by esengulov** [comment]
After researching side shift we decided to postpone the feature indefinitely as it's currently not compatible with out architecture.

**Comment by d4f5409d** [comment]
> We don't have much info on StealthEx.io so not sure about it just yet. Sideshift on the other hand likely to be integrated at some point in the near future. The only thing that holds us back now is that its API is not reachable from sanctioned countries and asa result these users would be left out. We don't like that but perhaps something is better than nothing...

Tor mode should be able to fix this
