### ISSUE TITLE
Where can I find Master Extended Keys in version 0.0.28 ?

### ISSUE THREAD

**Issue by kineita** [horizontalsystems/unstoppable-wallet-android#5529]
Hi there 😊,
I have some curious about Master Extended Keys, I know Master Extended Keys which is generated by mnemonic or seed phrase.
Case 1: I dont wanna use seed phrase to recover all keys (BIP44, 48, 86 root keys). How can I recover that all keys in one instance intead of create seperate instance by bip root key ?
Case 2: When I recovery any BIP root key but I can see other root key. Ex: recover BIP 48 rootkey, you can see bip 44 and 86 root key. I searched it, but dont know it work for revert other root key.
Thank you so much <3

**Comment by omurovch** [comment]
Hi @kineita,

1. Ideally you should recover by root seed. But wallet doesn't support this at the moment. Each type xpriv, ypriv, zpriv should be used for recovering BIP 44, 48 and 84, respectively.

2. BIP root key is the same for all representations. You can think of bips as serialization format.

**Comment by kineita** [comment]
Thank you so much @omurovch, I hope we will have feature recovery by root seed in the future.

**Comment by omurovch** [comment]
You are welcome. Ok, we will discuss with the team the feasibility of this feature.
