### ISSUE TITLE
Adding chain Ethereum PoW (native)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#5540]
I really appreciated the Proof of Work so I would like the ETHW coin (and its native chain).

https://ethereumpow.org/

https://linktr.ee/ethw

https://medium.com/@ETHW/ethw-mainnet-info-released-d775865a05e6

**Comment by esengulov** [comment]
This coin doesn't seem to be supported by any exchange at this point. We think there is no value in adding it but should there be more users requesting it we'll reevaluate it. Keeping the issue open for the time being.
