### ISSUE TITLE
Restore a wallet by feeding a keyfile (seed)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#5548]
Since a keyfile is fully immune to clipboard record and keyloggers, the best way to provide a seed to Unstoppable (and passphrase if needed) is take a keyfile (a txt file turned in bin, so without any extension) and feeding it as seen in KeePassDX.

I mustn't type in any password to unlock database, just feeding a file.
The same thing can be done for the passphrase, if necessary.

**Comment by esengulov** [comment]
Good point. The way we see it this feature is part of the broader backup/restore mechanism that was mentioned here, https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5525

Closing this issue and adding a reference to it from (https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5525)
