### ISSUE TITLE
BIP39 restore not generating correct keys

### ISSUE THREAD

**Issue by 3point14159** [horizontalsystems/unstoppable-wallet-android#5558]
I have a non-english seed phrase with a bip39 passphrase over it. When I input it into the app, it does not generate the keys correctly.

To demonstrate this, interchange the same seed AND bip39 passphrase into your app and [here](https://github.com/iancoleman/bip39) to SEE the difference.

How did this pass the testing and review process? Watching your code flow, issues sometimes spend days and weeks in "progress" or "testing"... something tells me that no actual progress or testing is actually happening. This is the most non-functional wallet I've ever tried. Back to Coinomi again I guess, sad that abandonware works better than this wallet.

**Comment by rafaelekol** [comment]
Can you tell which languages produce wrong keys?

**Comment by esengulov** [comment]
@3point14159 thanks, there is indeed an issue when restoring certain French/Spanish cases. We are debugging it now.
