### ISSUE TITLE
Issues with BCH chain sync...

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#5589]
![Screenshot_2022-12-11-15-08-59-60_c871ba0c2328d2f949307d9493eb5319 (1)](https://user-images.githubusercontent.com/113377431/206909947-4d4870eb-2a78-4fbd-b9db-ac82e317888d.jpg)

It never begin sync. Other chains work fine.

**Comment by Dianaaiym** [comment]
> ![Screenshot_2022-12-11-15-08-59-60_c871ba0c2328d2f949307d9493eb5319 (1)](https://user-images.githubusercontent.com/113377431/206909947-4d4870eb-2a78-4fbd-b9db-ac82e317888d.jpg)
> 
> It never begin sync. Other chains work fine.

Hi,

It works, please try again. If the problem persists, please send us the App Status (Settings - About App).

**Comment by Dianaaiym** [comment]
> Yes, problem goes and return. So it persists. Where I can send my app log? Is it safe? Nothing personal info is sent? Thanks for your assistance.

support.unstoppable@protonmail.com
