### ISSUE TITLE
Add analytics data on the coin page

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#5646]
The analytics section of the COIN Page should provide access to the following analytical data
-- Onchain DEX volume (UniswapV2,V3, Sushiswap, PancakeswapV1/V2) for the token (+ historical chart)
-- Onchain DEX liquidity (UniswapV2,V3, Sushiswap, PancakeswapV1/V2) for the token (+ historical chart)
-- Active Addresses for the token (+ historical chart)
-- Onchain TX count for the token (+ historical chart)
-- Onchain TX volume for the token (+ historical chart)

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=65347%3A437552&t=oFzceK4vCoYnQLph-11
