### ISSUE TITLE
ZCASH (ZEC) blockchain not downloading all the blocks anymore

### ISSUE THREAD

**Issue by kralux** [horizontalsystems/unstoppable-wallet-android#5661]
The ZCash coin isn't working anymore because the app is unable to download all the needed blocks. It used to break and reset its downloaded block count after some time when it would reach a certain block number. Not sure whether this is caused by a change in the standard at some block height or something else but even with a phone with enough memory and storage space this keeps on occurring.

**Comment by abdrasulov** [comment]
Hello @kralux. Can you please check if the issue still persists?

**Comment by abdrasulov** [comment]
The sync is working now. As for the time required to sync it's related to how SDK works. When the Zcash team releases a new version we will update it in our app.

**Comment by kralux** [comment]
Thanks.
I am still syncing on my phone... I'll confirm it is working after the sync is done.
Thank you for all your great work. It is very much appreciated!

Alex

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by abdrasulov** [comment]
It took me about 1 day in sum to get it fully synced. And it took about 5GB of storage. Can you please check the free space on your device storage?

**Comment by kralux** [comment]
OK so after several days of wait time to get the sync complete, it resets after getting to block 1923000 roughly... (give or take 10000 blocks).
Then it restarts the download/sync from the beginning again and again and again... It never completes.
I have more than 40 GB left on my phone's memory.
This is the Android version of the app v 0.29.0
Let me know if you need more info.
Thank you.

------- Original Message -------
