### ISSUE TITLE
Adding a LOCAL backup/restore for all wallets via (a password protected) QR or .zip

### ISSUE THREAD

**Issue by 3point14159** [horizontalsystems/unstoppable-wallet-android#5677]
Not much to add, it's in the title. However, for context, here is a link to the issue from another closed request thread:

https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5525

If it were up to me, I would avoid using any cloud storage services for backup, that would make the wallet very "stoppable" in the case that cloud is disrupted -or- cloud is compromised by an attacker or nation state actor.

I think a QR code is probably the best way to backup for simplicity. A .zip file would be a good option to add as well. Both should be available to the user.

Almost forgot, this feature should backup ALL wallets in the Manage Wallets settings menu. So right now we have Create, Restore and Watch Addresses, added to those options should be "Backup All Wallets" and "Restore All Wallets". From there, options should be "QR code" or ".zip". This shouldn't be too difficult, but would multiply the utility of the app for even more new users and make the app more valuable for current users. From a security/privacy perspective, attracting more users to the app increases security and privacy for all users, so if we build a robust core app, then expand to trendy silliness of NFT's etc after we have core functions locked-in, we can market the app to all users of the competition. The time is right. Coinomi is abandonware at this point and there are going to be more and more refugees looking for a new wallet app, this is where we should have all the features that they're used to (and more) so they can find a new home here at Unstoppable.

**Comment by abdrasulov** [comment]
We are discussing this feature.

**Comment by esengulov** [comment]
@3point14159 @serrq @Wjxfi hi all, while working on this feature we decide to implement it in steps:

1 - ability to backup single wallet to local storage
2 - ability to backup/restore seed as QR code
3- ability to backup all wallets and app settings to local storage

Right now we are going to work on step 1, https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6101

**Comment by esengulov** [comment]
hey guys, as we approach the end of implementation for this feature please note that ultimately we decided to implement it in the manner where all wallets are backed up to a single file, encrypted by a user provided password. While this feature seemed fairly simple at start it turned out to be rather intensive as we had to account for many use case that were not obvious at start.

**Comment by esengulov** [comment]
> Since this function is still in writing, I express an improvement, which in my opinion is fundamental.
> 
> Instead of pasting the password in its intended field (in order to unlock the backup), making it visible in the copyboard to the other apps, it would be better the key file solution, which does not need to be typed on the keyboard and therefore not visible in the copyboard or to the key loggers.
> 
> This solution is used in the KeepassDX app for Android (if you set a key file of course).

For the time being this feature was implemented in a classical manner with a regular password field. That said we might improve it with a proposed recommendation in the future.
