### ISSUE TITLE
Сheck addresses for solana in wallets with mnemonic 15-24 words

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#5689]

**Comment by esen** [comment]
There are mainly 2 derivation paths that are used by the solana wallets:

1. **m/44'/501'/0'**
2. **m/44'/501'/0'/0'**

- Glow, Sollet, Nitrogen Solana Crypto Wallet and Phantom use **2** 
- Solflare uses **1**. (But you can change that in settings)
- TrustWallet uses **1** for 12/24 words and **2** for 15 words. (Seems like a bug)

We currently use **2**

**Comment by Helpcentera** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by CustomerTeam001** [comment]
@Dianaaiym
