### ISSUE TITLE
"Exit App" button

### ISSUE THREAD

**Issue by 3point14159** [horizontalsystems/unstoppable-wallet-android#5703]
Along with the proposed security feature of a duress PIN ( https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5526 ), it would also be useful to have an exit button that closes the app and wipes its memory footprint.

This may be a complicated feature, but at least starting with a button to (force) close the app manually. Some users may want to exit the app without it running in the background.

**Comment by omurovch** [comment]
Hi @3point14159,
How "an exit button that closes the app" would be useful, i.e how it is better than closing app from system menu (from recent apps)? Can you please explain your use cases.
