### ISSUE TITLE
Staggered transactions history 

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#5704]
Yesterday (2023-01-06) I sent some SOL (Solana) to another address and today (2023-01-07) it is reported in "Today" tab. This is incorrect.

The transaction date is correct within the transaction receipt but not in transactions overall list.

Could be the time zone?

**Comment by abdrasulov** [comment]
TransactionViewItem has a property named `formattedDate`. The value of this property is initialized with an instance of a class. So to update "Today" and "Yesterday", we need to make this property dynamic. It may affect performance depending on the transaction list items count.

Closing this issue as of now. We'll work on it when there is a good solution
