### ISSUE TITLE
Possibility to set base currency: crypto and commodities

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#5707]
I would like to experience a purist mode where I only have all balances expressed in cryptocurrency (BTC or something else) without any FIAT.

**Comment by esengulov** [comment]
At the moment it's already possible to see total balance in BTC but I am guessinng what you're after is the ability to see all token balances in BTC? or you mean all possible places where fiat is shown? The latter would not be possible as there are lots of places where fiat values are needed i.e. tx fees

**Comment by esengulov** [comment]
Thanks, I see your reasoning behind eliminating the fiat from the measurement of a counter value. It feels like that might be the biggest challenge for BTC in the long run. Ultimately, we should get there.
