### ISSUE TITLE
Settings to declutter UI by disabling some features

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#5721]
Some users want cleaner UI and the ability to turn ON/OFF specific app features. For starters, we can explore the option to enable/disable the Markets tab.

- [ ] The ability to hide the MARKETS tab
- [ ] by default open the balance tab

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=66047%3A304428&t=to1MfHXvhnuwnTAA-11

example
https://user-images.githubusercontent.com/42367908/211798393-fdb07151-1d7a-42ce-a439-366735e76abb.mov
