### ISSUE TITLE
Balance Tab-No Wallet: Apply minor changes

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#5732]
- remove description text
- change the text 'Watch Address' --> 'Watch Wallet'
![2023-01-12 12 40 47](https://user-images.githubusercontent.com/22589457/211996174-27fa7664-38f8-43b3-afc2-ae97d6df1e2b.jpg)

**Comment by rafaelekol** [comment]
Done by this pull request #5764
