### ISSUE TITLE
Add `Blockchain` selector to `Add Token` feature

### ISSUE THREAD

**Issue by omurovch** [horizontalsystems/unstoppable-wallet-android#5747]

**Comment by kansalt** [comment]
layouts:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=66241%3A310291&t=CkTU4JjOcVb1rS6B-4

**Comment by rafaelekol** [comment]
Blockchain selector should be similar to the in Market Filters

**Comment by Dianaaiym** [comment]
add gnosis chain
