### ISSUE TITLE
Watch Wallet: Add an input field for the name

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-android#5796]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=66554%3A284535&t=474t70uOyrLu66sF-4

**Comment by Dianaaiym** [comment]
change ordering for blockchain:

- Ethereum
- BNB Smart Chain
- Polygon
- Avalanche
- Gnosis
- Arbitrum
- Optimism
