### ISSUE TITLE
Cannot sending found over Solana wallet: error

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#5817]
I always receive this error while attempt to send SOL from a wallet to an other.

I don't know why.

![37537](https://user-images.githubusercontent.com/113377431/215271250-f65d77ae-b36c-4d26-8f19-beb6b1d9fc62.jpg)

**Comment by Dianaaiym** [comment]
> I always receive this error while attempt to send SOL from a wallet to an other.
> 
> I don't know why.
> 
> ![37537](https://user-images.githubusercontent.com/113377431/215271250-f65d77ae-b36c-4d26-8f19-beb6b1d9fc62.jpg)

Hi,

Not reproducible. Please give us more details to reproduce

**Comment by Dianaaiym** [comment]
> Might help I send your support team the app status file by email?

yes, please send your App Status to support.unstoppable@protonmail.com
