### ISSUE TITLE
BTC transactions failed

### ISSUE THREAD

**Issue by AlexandrAlexeev7119** [horizontalsystems/unstoppable-wallet-android#5818]
When I\`m trying to send BTC, each transaction was invalid and doesn\`t accepted by Bitcoin network

Fee was set up to preset "Recommend" (2 sat/byte at now), seems like API server doesn\`t broadcast transactions

Or app failed to send transaction data to API server

![image](https://user-images.githubusercontent.com/48525682/215323136-598efc7d-a489-427f-848e-d80fe89e8bb7.png)
![image](https://user-images.githubusercontent.com/48525682/215323141-ba967f75-e4b0-4cd3-98d1-f9c1a4ca3a21.png)

**Comment by Coskunkolay** [comment]
Does this problem still persist? Haven't you sent your bitcoins yet?

**Comment by Dianaaiym** [comment]
> When I`m trying to send BTC, each transaction was invalid and doesn`t accepted by Bitcoin network
> 
> Fee was set up to preset "Recommend" (2 sat/byte at now), seems like API server doesn`t broadcast transactions
> 
> Or app failed to send transaction data to API server
> 
> ![image](https://user-images.githubusercontent.com/48525682/215323136-598efc7d-a489-427f-848e-d80fe89e8bb7.png) ![image](https://user-images.githubusercontent.com/48525682/215323141-ba967f75-e4b0-4cd3-98d1-f9c1a4ca3a21.png)

Hi,

Please try again to restore your wallet and send bitcoins.

**Comment by AlexandrAlexeev7119** [comment]
I switched to restore from blockchain and BTC was sent successfully
But when I\`m switching back to API, wallet still show my previous balance
So, after restore wallet again from passphrase, problem disappeared, and now balance is correct

> > When I`m trying to send BTC, each transaction was invalid and doesn`t accepted by Bitcoin network
> > Fee was set up to preset "Recommend" (2 sat/byte at now), seems like API server doesn`t broadcast transactions
> > Or app failed to send transaction data to API server
> > ![image](https://user-images.githubusercontent.com/48525682/215323136-598efc7d-a489-427f-848e-d80fe89e8bb7.png) ![image](https://user-images.githubusercontent.com/48525682/215323141-ba967f75-e4b0-4cd3-98d1-f9c1a4ca3a21.png)
> 
> Hi,
> 
> Please try again to restore your wallet and send bitcoins.
