### ISSUE TITLE
[Feature request] Connect to own full Bitcoin node

### ISSUE THREAD

**Issue by AlexandrAlexeev7119** [horizontalsystems/unstoppable-wallet-android#5841]
Possibility to connect and use your own Bitcoin node (Bitcoin core)

**Comment by esengulov** [comment]
@abdrasulov please look into this. Suspecting this might be an easy feature if it only takes us to restrict client interaction with a single IP.

**Comment by abdrasulov** [comment]
Based on the current implementation, sending transactions requires at least 2 peers connected. So with one peer, we will need to implement another logic for sending transactions. Also, there is one more question - how should we handle it if the peer will be unavailable to connect? I don't have quick solutions for these points so far. So I guess this feature may take a long time. About weeks.

**Comment by esengulov** [comment]
> Based on the current implementation, sending transactions requires at least 2 peers connected. So with one peer, we will need to implement another logic for sending transactions. Also, there is one more question - how should we handle it if the peer will be unavailable to connect? I don't have quick solutions for these points so far. So I guess this feature may take a long time. About weeks.

let's postpone it then, not critical at this point

**Comment by Dianaaiym** [comment]
POSTPONED:

Issues with the current architecture.

**Comment by Pinipon88** [comment]
any news about this?

**Comment by jd1100** [comment]
+1
