### ISSUE TITLE
A way to withdraw?

### ISSUE THREAD

**Issue by SKOHscripts** [horizontalsystems/unstoppable-wallet-android#5842]
Hi
I'm using Unstoppable Wallet for a while now. I was wondering if you will add a buying and withdraw functionality one day. It would be perfect. For the moment, I have to switch between an app to another, to buy some coins. 
I really love your work and what you did. It would be a game changer. 
If you won't for the moment, do someone know a Defi and open source way to buy and withdraw crypto ?

**Comment by esengulov** [comment]
> Hi
> I'm using Unstoppable Wallet for a while now. I was wondering if you will add a buying and withdraw functionality one day. It would be perfect. For the moment, I have to switch between an app to another, to buy some coins.
> I really love your work and what you did. It would be a game changer.
> If you won't for the moment, do someone know a Defi and open source way to buy and withdraw crypto ?

Hi, we might add it one day but not just yet. The reason for that such feature currently requires us to work with a third party provider which has some pricey concerns and in general come rather limited in scope.
