### ISSUE TITLE
"Info" components and pages: Improvements

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-android#5862]
- [x] Replace the text and icon (info 20px) on the information cells

-- fee settings
<img width="482" alt="Screen Shot 2023-02-06 at 5 48 53 PM" src="https://user-images.githubusercontent.com/58926737/216963933-81349c78-68f5-4793-877d-a4c864b8f8e7.png">

-- swap
<img width="564" alt="Screen Shot 2023-02-09 at 17 15 15" src="https://user-images.githubusercontent.com/58926737/217798021-1dbe03f9-5b0a-4373-a385-7349543d0791.png">

- [x] Add an information button to the WalletConnect page. The Info button opens the FAQ page 'What are risks when using WalletConnect?'
<img width="422" alt="Screen Shot 2023-02-07 at 12 20 24 PM" src="https://user-images.githubusercontent.com/58926737/217165330-7f8e2847-6ea3-4775-a39a-8648dbba7253.png">

- [x] Add an information button to the 'Recovery Phrase' page on 'Backup' mode.The Info button opens the FAQ page 'What are private keys?'

<img width="451" alt="Screen Shot 2023-02-07 at 12 37 40 PM" src="https://user-images.githubusercontent.com/58926737/217167118-d7bbf176-46a0-47c8-9f55-67a82de7916e.png">

- [x] Add an information button to the pages:
-- 'Recovery Phrase' > The Info button opens the FAQ page 'What are private keys?'
-- 'EVM Private Key'
-- 'BIP32 Root Key'
-- 'Account Extended Private Key'
-- 'Account Extended Public Key' 

Layouts:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=67886%3A323336&t=PftowUt8TlC51pDY-4

**Comment by Dianaaiym** [comment]
Texts info

- [ ] Transaction Fee 
>The maximum fee a user is expected to pay for the given transaction. Typically, the actual fee for the transaction is going to be lower.

- [ ] Gas Limit 
>Transactions vary in complexity and measured in so-called gas units. This setting shows the expected maximum amount of gas units to spend on a given transaction. The gas limit is estimated and set automatically for each transaction. 


- [ ] Base Fee 
>The price of a single gas unit at any given time is known as the current base fee (or gas price). It changes in real time with network conditions and is not controlled by any single entity. 

- [ ] Max Fee Rate (Gwei)
>The max. fee rate is the maximum price for a gas unit a user is willing to pay when sending the given transaction. 

- [ ] Max Miner Tip (Gwei)
>The miner tip is essentially a small tip to blockchain nodes (aka miners) in order to incentivize the faster processing of the given transaction.


- [ ] TX nonce
>The nonce is the number of transactions sent from a given address. Each time user sends a transaction, the nonce value increases by 1. Changing the nonce might be needed when a user tries to invalidate the currently pending transaction (that might have been sent in error etc) by sending another transaction with the same nonce but a higher fee. If there are two pending transactions with the same nonce only one will be accepted.
