### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by d4f5409d** [horizontalsystems/unstoppable-wallet-android#5874]
![410655d1-3230-4e3c-bc8e-ff17549cbc2d.png](https://user-images.githubusercontent.com/76624594/218263702-6aa759da-e89b-4592-9968-64661d32af65.png)

![9482c481-641f-4729-a896-d64f0e7035fb.png](https://user-images.githubusercontent.com/76624594/218263704-24bc1cfd-f9d8-4830-9da5-adcc4009fa5f.png)

![da788226-d379-484a-a90a-2a7ad5eb28d6.png](https://user-images.githubusercontent.com/76624594/218263703-d37cbe53-c4ed-4392-b008-eb45906d40ee.png)

This happens only when checking prices
Android 13

**Comment by rafaelekol** [comment]
What currency do you use in App(Settings -> Base Currency)?

**Comment by d4f5409d** [comment]
> What currency do you use in App(Settings -> Base Currency)?

USD

**Comment by rafaelekol** [comment]
I tried to reproduce your issue with VPN(via Orbot app). I tried countries like Germany and USA. App still showed me price Tab with data.

**Comment by d4f5409d** [comment]
Should I send logcat data? If so, could you send me your public key? You could choose where should I upload the file ( I don't want to force on you anything to make you feel uncomfortable)

**Comment by rafaelekol** [comment]
At the moment I don't need logcat. Can you check if Unstoppable Wallet app works without VPN?

**Comment by d4f5409d** [comment]
> At the moment I don't need logcat. Can you check if Unstoppable Wallet app works without VPN?

I would rather not disable my VPN. I do not want my ISP to know I am involved in crypto.

**Comment by rafaelekol** [comment]
In order to reproduce your issue, can you at least tell us, what VPN app you use and what country you set as the router?

**Comment by krolik92** [comment]
Yeah I can confirm, that this bug exist. I changed from Lineageos 18.1 to 20. Still present on Redmi Note 7. No matter I use VPN or not. No matter is it Wi-Fi or LTE. Even on my second phone Motorola Moto G7 Power without root, running official system on android 10 this bug is still present. My main country is Poland. Tried to connect through VPN to USA or Netherlands. Still the same.

**Comment by d4f5409d** [comment]
> Yeah I can confirm, that this bug exist. I changed from Lineageos 18.1 to 20. Still present on Redmi Note 7. No matter I use VPN or not. No matter is it Wi-Fi or LTE. Even on my second phone Motorola Moto G7 Power without root, running official system on android 10 this bug is still present. My main country is Poland. Tried to connect through VPN to USA or Netherlands. Still the same.

Maybe it is related to Google Play Services? I have the whole GMS disabled.

**Comment by krolik92** [comment]
s
> Maybe it is related to Google Play Services? I have the whole GMS disabled.

No, on both phones i have google play services

**Comment by d4f5409d** [comment]
I'll make a exported logcat file. If the devs attach a public key, I'll send them

**Comment by rafaelekol** [comment]
Can you try to enable Tor and check if it will help. 
Unstoppable Wallet settings: Security -> Tor
@d4f5409d  can you send your logcat to our support email: support.unstoppable@protonmail.com

**Comment by krolik92** [comment]
> Can you try to enable Tor and check if it will help. Unstoppable Wallet settings: Security -> Tor

I tried. Still the same
![Screenshot_20230220-081013_Unstoppable](https://user-images.githubusercontent.com/84180079/220036962-66a88b7e-f46e-4175-b34d-38fa4d31c00d.png)

**Comment by rafaelekol** [comment]
@krolik92 
can you try open this link in browser, this is one of the requests we do in Markets Tab
https://api.blocksdecoded.com/v1/markets/overview?currency=USD&simplified=true

**Comment by krolik92** [comment]
> @krolik92 can you try open this link in browser, this is one of the requests we do in Markets Tab https://api.blocksdecoded.com/v1/markets/overview?currency=USD&simplified=true

<details><summary>Website returned this</summary>
    <pre>
    {"global":[{"date":1676793600,"market_cap":"1171244125933.4153","defi_market_cap":"50361670532.427505","volume":"55231642126.17497","btc_dominance":"40.532586386925544","tvl":"76384157360.74002"},{"date":1676795400,"market_cap":"1171737482477.1567","defi_market_cap":"50372654243.03446","volume":"54701926584.0061","btc_dominance":"40.511260326088475","tvl":"76365803731.5638"},{"date":1676797200,"market_cap":"1171422033453.126","defi_market_cap":"50451924466.78024","volume":"54728083356.293335","btc_dominance":"40.51518191286518","tvl":"76365803731.5638"},{"date":1676799000,"market_cap":"1170791113363.1511","defi_market_cap":"50362357313.55841","volume":"54592242758.08748","btc_dominance":"40.520325678587774","tvl":"76355597160.40988"},{"date":1676800800,"market_cap":"1171761489951.4185","defi_market_cap":"50418920395.50312","volume":"54778932184.66276","btc_dominance":"40.506809165673985","tvl":"76355597160.40988"},{"date":1676802600,"market_cap":"1171051894630.5732","defi_market_cap":"50334249900.64777","volume":"54729452947.441986","btc_dominance":"40.52371784632254","tvl":"76369491118.10689"},{"date":1676804400,"market_cap":"1173843069203.72","defi_market_cap":"50486056015.35703","volume":"54990622531.59753","btc_dominance":"40.52126207383956","tvl":"76369491118.10689"},{"date":1676806200,"market_cap":"1174540291957.0059","defi_market_cap":"50487209520.59654","volume":"54845363216.859184","btc_dominance":"40.51371639134849","tvl":"76467378606.63962"},{"date":1676808000,"market_cap":"1176003289077.731","defi_market_cap":"50601170844.58316","volume":"55206695242.74009","btc_dominance":"40.48639133547259","tvl":"76467378606.63962"},{"date":1676809800,"market_cap":"1176229929016.5933","defi_market_cap":"50678556592.01962","volume":"54579045105.398735","btc_dominance":"40.496209354611445","tvl":"76556677220.00912"},{"date":1676811600,"market_cap":"1176994126791.056","defi_market_cap":"50771242643.61277","volume":"54636792561.03575","btc_dominance":"40.47743094040252","tvl":"76556677220.00912"},{"date":1676813400,"market_cap":"1177301305060.2588","defi_market_cap":"50808072553.5981","volume":"54801980050.78364","btc_dominance":"40.46984904941117","tvl":"76624879714.87434"},{"date":1676815200,"market_cap":"1176534099352.2205","defi_market_cap":"50713143160.94556","volume":"54913761853.276115","btc_dominance":"40.480146211231485","tvl":"76624879714.87434"},{"date":1676817000,"market_cap":"1177450647961.8584","defi_market_cap":"50995029893.67421","volume":"54781086236.04219","btc_dominance":"40.443444289977954","tvl":"76648933337.42027"},{"date":1676818800,"market_cap":"1179894620903.6257","defi_market_cap":"51167266360.198814","volume":"55590630427.627495","btc_dominance":"40.42085307377024","tvl":"76648933337.42027"},{"date":1676820600,"market_cap":"1182128066486.9504","defi_market_cap":"51196220999.24328","volume":"55827808528.3864","btc_dominance":"40.48248581680504","tvl":"76787587697.82298"},{"date":1676822400,"market_cap":"1185407591294.651","defi_market_cap":"51277182608.272736","volume":"58261172319.99019","btc_dominance":"40.53528362179094","tvl":"76787587697.82298"},{"date":1676824200,"market_cap":"1192943019348.699","defi_market_cap":"51570052896.72285","volume":"60388617952.710175","btc_dominance":"40.576176264487366","tvl":"77003261376.31473"},{"date":1676826000,"market_cap":"1176388128250.1438","defi_market_cap":"50737283253.053665","volume":"62316155730.98698","btc_dominance":"40.620407029174046","tvl":"77003144687.84099"},{"date":1676827800,"market_cap":"1172663875045.1152","defi_market_cap":"50525239182.06501","volume":"65768204099.39258","btc_dominance":"40.51735078399345","tvl":"76841649969.35638"},{"date":1676829600,"market_cap":"1169366376230.9534","defi_market_cap":"50333259898.19649","volume":"66577324876.769104","btc_dominance":"40.55661906123648","tvl":"76841649969.35638"},{"date":1676831400,"market_cap":"1167719677935.4243","defi_market_cap":"50398604647.87418","volume":"67495960507.612144","btc_dominance":"40.399459022704264","tvl":"76398613546.93535"},{"date":1676833200,"market_cap":"1167336222656.2368","defi_market_cap":"50333081502.26361","volume":"67676900814.27014","btc_dominance":"40.43784075575133","tvl":"76398613546.93535"},{"date":1676835000,"market_cap":"1169279448493.4792","defi_market_cap":"50348176533.483315","volume":"67876066479.745224","btc_dominance":"40.49442753343857","tvl":"76288892511.60728"},{"date":1676836800,"market_cap":"1168794395149.2976","defi_market_cap":"50210935053.68432","volume":"67929092002.415115","btc_dominance":"40.516863284862396","tvl":"76288892511.60728"},{"date":1676838600,"market_cap":"1163049074603.4844","defi_market_cap":"49867375187.99874","volume":"68924634278.89703","btc_dominance":"40.48739873298421","tvl":"76305521841.25305"},{"date":1676840400,"market_cap":"1161309224428.474","defi_market_cap":"50057693032.590096","volume":"69297408624.85785","btc_dominance":"40.49976883081861","tvl":"76305521841.25305"},{"date":1676842200,"market_cap":"1167245883216.7305","defi_market_cap":"50065822032.05718","volume":"70734405275.15408","btc_dominance":"40.52754463259961","tvl":"76229950480.87169"},{"date":1676844000,"market_cap":"1168132213088.5525","defi_market_cap":"50128303563.20208","volume":"71644795320.35696","btc_dominance":"40.50801277825412","tvl":"76229950480.87169"},{"date":1676845800,"market_cap":"1168692480564.8733","defi_market_cap":"50229842156.634735","volume":"72015831509.08134","btc_dominance":"40.488147663713335","tvl":"76225841935.48982"},{"date":1676847600,"market_cap":"1167614863184.424","defi_market_cap":"50063657028.688614","volume":"72259888239.56042","btc_dominance":"40.479473900132895","tvl":"76225841935.48982"},{"date":1676849400,"market_cap":"1164372016225.1748","defi_market_cap":"50009012369.64999","volume":"72750297185.50204","btc_dominance":"40.44647420339314","tvl":"76293427646.8242"},{"date":1676851200,"market_cap":"1166243679480.067","defi_market_cap":"49790569793.798225","volume":"73542932507.58093","btc_dominance":"40.37229357692152","tvl":"76293427646.8242"},{"date":1676853000,"market_cap":"1162349761353.8452","defi_market_cap":"50166811080.47471","volume":"74503878931.04492","btc_dominance":"40.33565410289931","tvl":"76096741902.92296"},{"date":1676854800,"market_cap":"1161168119637.7024","defi_market_cap":"49865248520.510925","volume":"75266310965.3426","btc_dominance":"40.33495611136099","tvl":"76096741902.92296"},{"date":1676856600,"market_cap":"1146120566484.4995","defi_market_cap":"49144269652.34605","volume":"76264682312.87318","btc_dominance":"40.2832619717289","tvl":"75924718353.18292"},{"date":1676858400,"market_cap":"1162815777457.9058","defi_market_cap":"49814375719.49761","volume":"78187914797.4155","btc_dominance":"40.260833074826984","tvl":"75924718353.18292"},{"date":1676860200,"market_cap":"1163184273598.014","defi_market_cap":"49903356452.39425","volume":"79781440126.44676","btc_dominance":"40.33031130714964","tvl":"75755156654.34348"},{"date":1676862000,"market_cap":"1162304491452.917","defi_market_cap":"50013163748.27923","volume":"80552824065.31242","btc_dominance":"40.32951178502669","tvl":"75755156654.34348"},{"date":1676863800,"market_cap":"1164157728764.3025","defi_market_cap":"50086039525.05447","volume":"81364148797.23976","btc_dominance":"40.33313184262811","tvl":"75987048034.13367"},{"date":1676865600,"market_cap":"1167684520744.2727","defi_market_cap":"50260041574.0568","volume":"82193194230.6716","btc_dominance":"40.33364632899935","tvl":"75987048034.13367"},{"date":1676867400,"market_cap":"1168661129994.0522","defi_market_cap":"50432434728.78907","volume":"82720487222.2836","btc_dominance":"40.330942738467115","tvl":"76382141167.48683"},{"date":1676869200,"market_cap":"1170808402392.738","defi_market_cap":"50522966493.77449","volume":"83631200145.67781","btc_dominance":"40.335408351884084","tvl":"76382141167.48683"},{"date":1676871000,"market_cap":"1171160709405.6638","defi_market_cap":"50492254000.20802","volume":"84024972496.8915","btc_dominance":"40.31095545674728","tvl":"76491383684.68243"},{"date":1676872800,"market_cap":"1170620242225.8887","defi_market_cap":"50454521062.85436","volume":"83668725277.35867","btc_dominance":"40.32885140325823","tvl":"76491383684.68243"},{"date":1676874600,"market_cap":"1172541241761.1345","defi_market_cap":"50504867202.928024","volume":"83237924134.52213","btc_dominance":"40.32652571533823","tvl":"76394474983.374"},{"date":1676876400,"market_cap":"1171208590367.3088","defi_market_cap":"50583677297.676","volume":"83375302259.69958","btc_dominance":"40.302119612205104","tvl":"76394474983.374"},{"date":1676878200,"market_cap":"1172099931724.0107","defi_market_cap":"50444890640.06224","volume":"83149163266.77348","btc_dominance":"40.31149912698474","tvl":"76567888453.76848"},{"date":1676880000,"market_cap":"1175222228100.2664","defi_market_cap":"50751942765.50122","volume":"83651959371.6822","btc_dominance":"40.24194343328959","tvl":"76567888453.76848"}],"sectors":[{"uid":"storage","name":"Storage","description":{"de":"Decentralized data-storage.","en":"Decentralized data-storage.","es":"Decentralized data-storage.","fa":"Decentralized data-storage.","fr":"Decentralized data-storage.","ko":"Decentralized data-storage.","ru":"Decentralized data-storage.","tr":"Decentralized data-storage.","zh":"Decentralized data-storage."},"market_cap":"5630518044","change_24h":"9.319996125046186","change_1w":"41.917831759370564","change_1m":"48.33399824845942"},{"uid":"identity","name":"Identity","description":{"de":"Decentralized identity.","en":"Decentralized identity.","es":"Decentralized identity.","fa":"Decentralized identity.","fr":"Decentralized identity.","ko":"Decentralized identity.","ru":"Decentralized identity.","tr":"Decentralized identity.","zh":"Decentralized identity."},"market_cap":"1140457495","change_24h":"9.01934792448753","change_1w":"22.191560039217826","change_1m":"23.467289715032656"},{"uid":"infrastructure","name":"Infrastructure","description":{"de":"Projects building infrastructure solutions.","en":"Projects building infrastructure solutions.","es":"Projects building infrastructure solutions.","fa":"Projects building infrastructure solutions.","fr":"Projects building infrastructure solutions.","ko":"Projects building infrastructure solutions.","ru":"Projects building infrastructure solutions.","tr":"Projects building infrastructure solutions.","zh":"Projects building infrastructure solutions."},"market_cap":"9776886804","change_24h":"4.370206257928138","change_1w":"16.45025930950151","change_1m":"49.45205984820087"},{"uid":"synthetics","name":"Synthetics","description":{"de":"Platforms for creating decentralized synthetic assets.","en":"Platforms for creating decentralized synthetic assets.","es":"Platforms for creating decentralized synthetic assets.","fa":"Platforms for creating decentralized synthetic assets.","fr":"Platforms for creating decentralized synthetic assets.","ko":"Platforms for creating decentralized synthetic assets.","ru":"Platforms for creating decentralized synthetic assets.","tr":"Platforms for creating decentralized synthetic assets.","zh":"Platforms for creating decentralized synthetic assets."},"market_cap":"915252844","change_24h":"3.6419336177612456","change_1w":"13.352052391830787","change_1m":"32.53802021766112"}],"platforms":[{"uid":"ethereum","name":"Ethereum","rank":1,"protocols":1979,"market_cap":"200232107320.65775","stats":{"rank_1d":"1","rank_1w":"1","rank_1m":"1","change_1d":"0.27965980353312964","change_1m":"9.113774596701854","change_1w":"5.702774907618662"}},{"uid":"binance-smart-chain","name":"BNB Smart Chain","rank":2,"protocols":985,"market_cap":"17781754240.856537","stats":{"rank_1d":"2","rank_1w":"2","rank_1m":"2","change_1d":"0.24687228274114856","change_1m":"7.950066207499596","change_1w":"1.7858723403256054"}},{"uid":"solana","name":"Solana","rank":3,"protocols":125,"market_cap":"6002277213.80748","stats":{"rank_1d":"3","rank_1w":"3","rank_1m":"3","change_1d":"0.5190439244088445","change_1m":"-1.4776367796117655","change_1w":"1.787558024403334"}},{"uid":"polygon-pos","name":"Polygon","rank":4,"protocols":370,"market_cap":"3926132584.73504","stats":{"rank_1d":"4","rank_1w":"4","rank_1m":"4","change_1d":"-0.6775057174209065","change_1m":"14.125514048777926","change_1w":"8.253036111813207"}},{"uid":"avalanche","name":"Avalanche","rank":5,"protocols":144,"market_cap":"2822398169.9392195","stats":{"rank_1d":"5","rank_1w":"5","rank_1m":"5","change_1d":"0.39479769064850656","change_1m":"4.9999951712924195","change_1w":"3.1720791509158817"}}],"nft":{"one_day":[{"name":"Art Blocks Curated","opensea_uid":"art-blocks","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/GwnosrkaneKGEkWySxvTSzZ5bEUjWkRuQzLSNfrpgy2-gxYjoR3m5PohLT9Fzy0p1tohajZ1g-LFfF_ZLnS1GqlPNHPUaKUbDhbf=s120","floor_price":null,"volume_1d":915.8455370000011,"change_1d":-0.03671559138900205,"volume_7d":5117.265470302105,"change_7d":0.5730223689941742,"volume_30d":13265.160798965475,"change_30d":1.2118551788758118},{"name":"Bored Ape Yacht Club","opensea_uid":"boredapeyachtclub","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/Ju9CkWtV-1Okvf45wo8UctR-M9He2PjILP0oOvxE89AyiPPGtrR3gysu1Zgy0hjd2xKIgjJJtWIc0ybj4Vd7wv8t3pxDGHoJBzDB=s120","floor_price":71.99,"volume_1d":335.29,"change_1d":0.08578367875647672,"volume_7d":1510.20069,"change_7d":-0.4168549575839597,"volume_30d":11225.801109999997,"change_30d":0.10647410083609887},{"name":"Otherdeed for Otherside","opensea_uid":"otherdeed","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/yIm-M5-BpSDdTEIJRt5D6xphizhIdozXjqSITgK4phWq7MmAU3qE7Nw7POGCiPGyhtJ3ZFP8iJ29TFl-RLcGBWX5qI4-ZcnCPcsY4zI=s120","floor_price":1.3,"volume_1d":197.3420599999991,"change_1d":-0.023513755100778275,"volume_7d":1497.065583797999,"change_7d":-0.03888939382498774,"volume_30d":6702.131896555147,"change_30d":-0.21484307033269823},{"name":"Mutant Ape Yacht Club","opensea_uid":"mutant-ape-yacht-club","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/lHexKRMpw-aoSyB1WdFBff5yfANLReFxHzt1DOj_sg7mS14yARpuvYcUtsyyx-Nkpk6WTcUPFoG53VnLJezYi8hAs0OxNZwlw6Y-dmI=s120","floor_price":11.4,"volume_1d":184.67099999999996,"change_1d":0.3181982033427672,"volume_7d":1889.1164585000001,"change_7d":-0.2593896410493922,"volume_30d":6774.251699888869,"change_30d":0.015333582449062473},{"name":"Peking Monsters Official","opensea_uid":"pekingmonsters","blockchain_uid":"ethereum","thumbnail_url":"https://i.seadn.io/gcs/files/9762ccecaf250c709f0dd79d3f3eaec7.gif?w=500&auto=format","floor_price":0.133,"volume_1d":156.24394287013197,"change_1d":0,"volume_7d":156.24394287013197,"change_7d":0,"volume_30d":156.24394287013197,"change_30d":0}],"seven_day":[{"name":"Art Blocks Curated","opensea_uid":"art-blocks","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/GwnosrkaneKGEkWySxvTSzZ5bEUjWkRuQzLSNfrpgy2-gxYjoR3m5PohLT9Fzy0p1tohajZ1g-LFfF_ZLnS1GqlPNHPUaKUbDhbf=s120","floor_price":null,"volume_1d":915.8455370000011,"change_1d":-0.03671559138900205,"volume_7d":5117.265470302105,"change_7d":0.5730223689941742,"volume_30d":13265.160798965475,"change_30d":1.2118551788758118},{"name":"CryptoPunks","opensea_uid":"cryptopunks","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/BdxvLseXcfl57BiuQcQYdJ64v-aI8din7WPk0Pgo3qQFhAUH-B6i-dCqqc_mCkRIzULmwzwecnohLhrcH8A9mpWIZqA7ygc52Sr81hE=s120","floor_price":null,"volume_1d":72,"change_1d":-0.8545895218849182,"volume_7d":3708.389999999999,"change_7d":-0.22392318685572946,"volume_30d":15923.847000000002,"change_30d":0.12977471689733214},{"name":"Mutant Ape Yacht Club","opensea_uid":"mutant-ape-yacht-club","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/lHexKRMpw-aoSyB1WdFBff5yfANLReFxHzt1DOj_sg7mS14yARpuvYcUtsyyx-Nkpk6WTcUPFoG53VnLJezYi8hAs0OxNZwlw6Y-dmI=s120","floor_price":11.4,"volume_1d":184.67099999999996,"change_1d":0.3181982033427672,"volume_7d":1889.1164585000001,"change_7d":-0.2593896410493922,"volume_30d":6774.251699888869,"change_30d":0.015333582449062473},{"name":"Bored Ape Yacht Club","opensea_uid":"boredapeyachtclub","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/Ju9CkWtV-1Okvf45wo8UctR-M9He2PjILP0oOvxE89AyiPPGtrR3gysu1Zgy0hjd2xKIgjJJtWIc0ybj4Vd7wv8t3pxDGHoJBzDB=s120","floor_price":71.99,"volume_1d":335.29,"change_1d":0.08578367875647672,"volume_7d":1510.20069,"change_7d":-0.4168549575839597,"volume_30d":11225.801109999997,"change_30d":0.10647410083609887},{"name":"Otherdeed for Otherside","opensea_uid":"otherdeed","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/yIm-M5-BpSDdTEIJRt5D6xphizhIdozXjqSITgK4phWq7MmAU3qE7Nw7POGCiPGyhtJ3ZFP8iJ29TFl-RLcGBWX5qI4-ZcnCPcsY4zI=s120","floor_price":1.3,"volume_1d":197.3420599999991,"change_1d":-0.023513755100778275,"volume_7d":1497.065583797999,"change_7d":-0.03888939382498774,"volume_30d":6702.131896555147,"change_30d":-0.21484307033269823}],"thirty_day":[{"name":"CryptoPunks","opensea_uid":"cryptopunks","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/BdxvLseXcfl57BiuQcQYdJ64v-aI8din7WPk0Pgo3qQFhAUH-B6i-dCqqc_mCkRIzULmwzwecnohLhrcH8A9mpWIZqA7ygc52Sr81hE=s120","floor_price":null,"volume_1d":72,"change_1d":-0.8545895218849182,"volume_7d":3708.389999999999,"change_7d":-0.22392318685572946,"volume_30d":15923.847000000002,"change_30d":0.12977471689733214},{"name":"Art Blocks Curated","opensea_uid":"art-blocks","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/GwnosrkaneKGEkWySxvTSzZ5bEUjWkRuQzLSNfrpgy2-gxYjoR3m5PohLT9Fzy0p1tohajZ1g-LFfF_ZLnS1GqlPNHPUaKUbDhbf=s120","floor_price":null,"volume_1d":915.8455370000011,"change_1d":-0.03671559138900205,"volume_7d":5117.265470302105,"change_7d":0.5730223689941742,"volume_30d":13265.160798965475,"change_30d":1.2118551788758118},{"name":"Bored Ape Yacht Club","opensea_uid":"boredapeyachtclub","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/Ju9CkWtV-1Okvf45wo8UctR-M9He2PjILP0oOvxE89AyiPPGtrR3gysu1Zgy0hjd2xKIgjJJtWIc0ybj4Vd7wv8t3pxDGHoJBzDB=s120","floor_price":71.99,"volume_1d":335.29,"change_1d":0.08578367875647672,"volume_7d":1510.20069,"change_7d":-0.4168549575839597,"volume_30d":11225.801109999997,"change_30d":0.10647410083609887},{"name":"Mutant Ape Yacht Club","opensea_uid":"mutant-ape-yacht-club","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/lHexKRMpw-aoSyB1WdFBff5yfANLReFxHzt1DOj_sg7mS14yARpuvYcUtsyyx-Nkpk6WTcUPFoG53VnLJezYi8hAs0OxNZwlw6Y-dmI=s120","floor_price":11.4,"volume_1d":184.67099999999996,"change_1d":0.3181982033427672,"volume_7d":1889.1164585000001,"change_7d":-0.2593896410493922,"volume_30d":6774.251699888869,"change_30d":0.015333582449062473},{"name":"Otherdeed for Otherside","opensea_uid":"otherdeed","blockchain_uid":"ethereum","thumbnail_url":"https://lh3.googleusercontent.com/yIm-M5-BpSDdTEIJRt5D6xphizhIdozXjqSITgK4phWq7MmAU3qE7Nw7POGCiPGyhtJ3ZFP8iJ29TFl-RLcGBWX5qI4-ZcnCPcsY4zI=s120","floor_price":1.3,"volume_1d":197.3420599999991,"change_1d":-0.023513755100778275,"volume_7d":1497.065583797999,"change_7d":-0.03888939382498774,"volume_30d":6702.131896555147,"change_30d":-0.21484307033269823}]}}
    </pre>
   </details>

**Comment by rafaelekol** [comment]
Also can you try second request: https://api.blocksdecoded.com/v1/coins/top-movers?currency=USD

**Comment by krolik92** [comment]
> Also can you try second request: https://api.blocksdecoded.com/v1/coins/top-movers?currency=USD

<details>
  <summary>Second site returned this</summary>
{"gainers_100":[{"uid":"blockstack","price":"0.637769","price_change_24h":"55.80903","market_cap_rank":60},{"uid":"oec-token","price":"31.12","price_change_24h":"21.77837","market_cap_rank":88},{"uid":"neo","price":"11.371633383882902","price_change_24h":"17.27298","market_cap_rank":68},{"uid":"solana","price":"26.585131032401833","price_change_24h":"12.41603","market_cap_rank":12},{"uid":"vechain","price":"0.030933367280935795","price_change_24h":"12.03456","market_cap_rank":35}],"losers_100":[{"uid":"the-graph","price":"0.17311623604795234","price_change_24h":"-4.88397","market_cap_rank":41},{"uid":"internet-computer","price":"7.3","price_change_24h":"-4.66094","market_cap_rank":37},{"uid":"render-token","price":"1.73","price_change_24h":"-4.32704","market_cap_rank":96},{"uid":"rocket-pool","price":"50.885622763144106","price_change_24h":"-4.30497","market_cap_rank":55},{"uid":"mina-protocol","price":"1.018","price_change_24h":"-3.33067","market_cap_rank":61}],"gainers_200":[{"uid":"blockstack","price":"0.637769","price_change_24h":"55.80903","market_cap_rank":60},{"uid":"iostoken","price":"0.01401126","price_change_24h":"29.02488","market_cap_rank":179},{"uid":"conflux-token","price":"0.2182513888489869","price_change_24h":"26.57107","market_cap_rank":110},{"uid":"oec-token","price":"31.12","price_change_24h":"21.77837","market_cap_rank":88},{"uid":"waves","price":"3.1268077949741","price_change_24h":"20.32468","market_cap_rank":149}],"losers_200":[{"uid":"gains-farm","price":"9223.28","price_change_24h":"-9.96962","market_cap_rank":145},{"uid":"gains-network","price":"9.23","price_change_24h":"-8.44754","market_cap_rank":162},{"uid":"magic","price":"1.85","price_change_24h":"-8.12378","market_cap_rank":129},{"uid":"floki","price":"0.00004649","price_change_24h":"-7.06804","market_cap_rank":108},{"uid":"alethea-artificial-liquid-intelligence-token","price":"0.059291","price_change_24h":"-5.75139","market_cap_rank":195}],"gainers_300":[{"uid":"blockstack","price":"0.637769","price_change_24h":"55.80903","market_cap_rank":60},{"uid":"platon-network","price":"0.03116262","price_change_24h":"50.57055","market_cap_rank":304},{"uid":"alchemy-pay","price":"0.03602368","price_change_24h":"49.11008","market_cap_rank":215},{"uid":"iostoken","price":"0.01401126","price_change_24h":"29.02488","market_cap_rank":179},{"uid":"conflux-token","price":"0.2182513888489869","price_change_24h":"26.57107","market_cap_rank":110}],"losers_300":[{"uid":"compound-usdt","price":"0.0210435","price_change_24h":null,"market_cap_rank":230},{"uid":"dejitaru-tsuka","price":"0.122811","price_change_24h":"-10.63709","market_cap_rank":268},{"uid":"gains-farm","price":"9223.28","price_change_24h":"-9.96962","market_cap_rank":145},{"uid":"gains-network","price":"9.23","price_change_24h":"-8.44754","market_cap_rank":162},{"uid":"magic","price":"1.85","price_change_24h":"-8.12378","market_cap_rank":129}]}
</details>

**Comment by krolik92** [comment]
> Did you test API requests on phone, do they work on the phone too?

What do you mean? How can I do that? 

I don't know it matters, but on both phones, all Google stuff is deleted or disabled, only Maps and Google Services. Not logged into Google Account, no Play Store. Browsers I use are Bromite and Fennec. On rooted Redmi Note 7 i use AdAway, on Motorola I don't. Disabling it on RN7 does not resolve problem.

**Comment by rafaelekol** [comment]
Try opening same link on your phone, phone browser.
https://api.blocksdecoded.com/v1/coins/top-movers?currency=USD

**Comment by krolik92** [comment]
Yeah, I tested all your links on my phones browser.

**Comment by rafaelekol** [comment]
We will try to replicate your case here, with Lineageos.

**Comment by d4f5409d** [comment]
I got the issue. It's clear there is a problem with the app rather than the server. I am sending the logcat file right now.

**Comment by krolik92** [comment]
I can confirm, that changing language from polish to english solved the problem. Thanks

**Comment by rafaelekol** [comment]
We will fix this issue, and release it with next update.

**Comment by d4f5409d** [comment]
> @d4f5409d your logs really helped to resolve source of issue. As a fast fix for you: Go to App Settings and change language to English. And you should see Coin Page without Sync Error.
> 

You are welcome, and thank you 😌
