### ISSUE TITLE
Request: Add fingerprint authentication to security

### ISSUE THREAD

**Issue by xcelente** [horizontalsystems/unstoppable-wallet-android#5924]
Title says it all really.

**Comment by abdrasulov** [comment]
Hello @xcelente. There is already a Biometric Authentication there. It will be accessible when you set the passcode.

**Comment by xcelente** [comment]
Just wondering, why does it need a password and a passcode?

**Comment by xcelente** [comment]
I think I'm missing something, why can't someone use their password instead?

**Comment by abdrasulov** [comment]
I'm afraid I don't get it. Can you please clarify, what you mean by password? Is it the passcode or something else?

**Comment by xcelente** [comment]
Oh, I think it's my mistake. I thought there was a password and a passcode, apparently not! :D
