### ISSUE TITLE
Implement ERC-4337 Account Abstraction

### ISSUE THREAD

**Issue by kineita** [horizontalsystems/unstoppable-wallet-android#5928]
Hi Unstoppable wallet team, thank for bring best app to Android. I have a request to bring best experience for our social by implement ERC-4337 Account Abstraction.
Can we do it ? I'm Android developer, if you need support please contact me.
Thank you so much <3 

Ref: https://eips.ethereum.org/EIPS/eip-4337

**Comment by esengulov** [comment]
hi @kineita 

We didn't have a chance to explore ERC-4337 Account Abstraction in detail. Are you aware of any wallets that support it?

**Comment by kineita** [comment]
Hi @esengulov, thank for your reply
I found Safe wallet had this feature https://github.com/safe-global/safe-android. But I think we need to implement a smart contract based on EIP-4337.

**Comment by kineita** [comment]
I see this address https://etherscan.io/address/0x0576a174d229e3cfa37253523e645a78a0c91b57 officially developed by the Ethereum Foundation, and audited by Open Zeppelin. It run on many EVM as ERC-20, Polygon, ...
