### ISSUE TITLE
Arbitrum USDT

### ISSUE THREAD

**Issue by arkadym** [horizontalsystems/unstoppable-wallet-android#5947]
Somehow app cannot see USDT in my arbitrum wallet
What i did
- Open my wallet
- Enable Arbitrum USDT
- Copy address
- Goto Bybit
- Withdraw 100 USDT to that address using Arbitrum One network
- Wait to see 100 USDT in my wallet
- Started to worry because Tx is done, can see it there https://arbiscan.io
- Goto Trust Wallet
- Import my wallet by using private key
- Trust wallet can see my USDT there.

**Comment by arkadym** [comment]
Somehow it can see USDT and ETH amount now, it took few hours to appear. Possibly it was need to add ETH amount ?
But yet cannot see transactions.

**Comment by Dianaaiym** [comment]
> Somehow it can see USDT and ETH amount now, it took few hours to appear. Possibly it was need to add ETH amount ? But yet cannot see transactions.

Cannot reproduce it. Are you still experiencing this problem?

**Comment by esengulov** [comment]
@arkadym do you still see this issue?

**Comment by arkadym** [comment]
@esengulov Cannot recreate issue. Somehow it works now. Let's put that issue on hold yet.
