### ISSUE TITLE
app crash when importing xPubKey from electrum

### ISSUE THREAD

**Issue by SiLiKhon** [horizontalsystems/unstoppable-wallet-android#5987]
The app crashes when trying to import a watch wallet with the master public key from an electrum wallet. I've tried XPUB and ZPUB keys to same effect. Here's a screenshot of stack trace (I sent the full report via Market Feedback Agent in Android earlier this week):

<img src="https://user-images.githubusercontent.com/13967024/227711071-52cc0bfa-55cc-48a8-8c6f-a27cf82f3463.png" alt="drawing" width="200"/>

**Comment by rafaelekol** [comment]
After investigation of this crash we found out that seed that is generated in Electrum wallet is not a Bip39 seed. It's a [custom seed](https://electrum.readthedocs.io/en/latest/seedphrase.html) that can only be used in Electrum wallet.
With the help of your report I fixed xpub key validation in Watch.
