### ISSUE TITLE
I cannot see zcash blockchain settings

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6027]
Is it normal?

I would know the birthday height of my zcash wallet.

Notes: 

• zcash wallet runs properly (send button is yellow)
• UW 0.31.0 (github)
• OnePlus CPH2399 
• Android 13

**Comment by Dianaaiym** [comment]
Hi,

![2023-04-07 11 48 45](https://user-images.githubusercontent.com/22589457/230549399-5d22e2ba-7251-4f79-9696-ed61d3f28b35.jpg)

![2023-04-07 11 48 49](https://user-images.githubusercontent.com/22589457/230549410-dbe20b17-8391-47a3-a6bf-de3d9e35ec5d.jpg)

**Comment by esengulov** [comment]
> Thanks awfully. Zcash doesn't have a blockchain setting tool like other Bitcoin-like chains?

we are using a library from Zcash for our implementation. Unfortunately the ;library doesn't have such capabilities i.e. changing sync source etc
