### ISSUE TITLE
Make touch vibration feedback optional

### ISSUE THREAD

**Issue by leonp5** [horizontalsystems/unstoppable-wallet-android#6029]
I couldn't find an option to disable the vibration feedback of the smartphone when I for example unlock Unstoppable or when I scroll to coin statistic chart.

If this option exists, can somebody tell me where I can find it?
Otherwise I would suggest to implement such an option.

Thanks for your work!
Leon

**Comment by esengulov** [comment]
hi, we have looked into that and for the time being would like to keep it as is. We try to avoid anything that's not in our opinion is essential. Do you find the vibration feedback feature annoying?
