### ISSUE TITLE
Implement Shamir backup

### ISSUE THREAD

**Issue by d4f5409d** [horizontalsystems/unstoppable-wallet-android#6036]
https://blog.trezor.io/shamir-backup-the-revolution-of-private-keys-backup-is-here-858687ed7fe7

**Comment by abdrasulov** [comment]
It said in https://github.com/satoshilabs/slips/blob/master/slip-0039.md

This SLIP is mainly intended as a replacement for BIP-0039 and for the most part the two are not compatible.

As of now, we are not planning to replace the support BIP-0039.
