### ISSUE TITLE
I cannot boost the fee amount when I send BCH

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6039]
Today I sent some BCH and the queue was very long because my fee was too much low.
But I cannot modify it because currently there isn't a way in GUI.

I can modify the fee value (sat/byte) in BTC, in BCH no.

**Comment by abdrasulov** [comment]
@serrq 

There was no need for fee rate adjustments for Bitcoin Cash. The current fee rate is 3 sat per byte. Based on the recent transactions on the Bitcoin Cash network it is more than enough. There are transactions with a fee rate of 1 sat/byte. That is strange that your transaction took a long time. Usually, there are not so many transactions in the queue.

Could you please share that transaction hash? We'll check it

**Comment by abdrasulov** [comment]
I checked it. Many other transactions with a lower fee rate than yours were included in the same block. The same is true for a fee rate for previous blocks. 

I guess there was an issue with the bitcoin cash network. The fee rate is not an issue.

If you face the same issue please send us the App Status (Settings -> About App -> App Status).
