### ISSUE TITLE
Add PHP (Philippine Pesos) and other fiat currencies

### ISSUE THREAD

**Issue by xcelente** [horizontalsystems/unstoppable-wallet-android#6040]
Please add other fiat currencies, including the Philippine Pesos.

You can get a very reliable and stable fx feed from the central european bank. Updated daily at 3pm:

http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

**Comment by esengulov** [comment]
@Dianaaiym please check if PHP rates are available to us through Coingeko

**Comment by xcelente** [comment]
I'm not sure what benefit there is fetching PHP rate from a third party when the ECB link is from the horses mouth.

**Comment by Dianaaiym** [comment]
merged into #6054
