### ISSUE TITLE
Integrate chart indicators to app charts

### ISSUE THREAD

**Issue by fusionneur** [horizontalsystems/unstoppable-wallet-android#6042]
on latest version 0.31, the indicators seem to have been removed: MACD, RSI, EMA
maybe accidentally or was it on purpose?

**Comment by Dianaaiym** [comment]
> on latest version 0.31, the indicators seem to have been removed: MACD, RSI, EMA maybe accidentally or was it on purpose?

We would like to return chart indicators, and we need feedback from users. Please email us (support.unstoppable@protonmail.com) if you have any suggestions.

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=72278-460595&t=uaYZtew3febSNKdd-11

**Comment by esengulov** [comment]
> thank you for the info. can you please describe a bit the process of getting free lifetime access ?

sure thing, basically we have a smart contract that's responsible for handling subscription payments. The contract went online few days ago and currently being tested. It mainly allows us to define various subscription plans. The wallet app checks with the smart contract whether the user's EVM address is present among those who bought subscription on the contract. If so, the app then able to retrieve analytics data from our backend server. 

Apart from that contract has two other essential features:

1- allows us to whitelist any address for unlimited access. That's what we offered to you and some other users.

2- allows someone (ex: influencers) to be our reseller and get a share (up to 50%) from each sale.

At the moment the premium data is mostly about getting free access to premium analytics but in the coming weeks we intend to expand that with more perks i.e.:

- price trend indicators

- premium tech support

- advanced security tools for DeFi users

- advanced privacy options (i.e. ability to use decentralized RPC providers)

- ability to export exchange wallets (ex: Binance) to Unstoppable in read-only mode

- ability to discover whale users and watch them

**Comment by esengulov** [comment]
> Thank you for the detailed info.
> 
> From my understanding, there will be a monthly subscription to unlock these features, and if I buy premium for the first month now during the beta stage, I will no longer have to pay the subscription but will have access to all features indefinitely.
> 
> What I did not understand is why/when/where should I provide the EVM address if I cannot purchase premium yet? What am I missing? Is this beta signup documented anywhere more in detail? Also which will be the price for the monthly subscription (if yet decided)?

premium feature is now live!

**Comment by esengulov** [comment]
> So is there any plan to return macd and rsi to free version? At this point, I won't update the app anymore until these basic features are added.

yes, free version will have stuff you had access to before
