### ISSUE TITLE
put Oxen in the private sector. It is not there now. 

### ISSUE THREAD

**Issue by Wjxfi** [horizontalsystems/unstoppable-wallet-android#6050]
This is an improved version of monero (seemingly). Apart from that, I am waiting for its support in unstoppable.

**Comment by esengulov** [comment]
@Dianaaiym please add this project to privacy category

**Comment by Dianaaiym** [comment]
> @Dianaaiym please add this project to privacy category
![2023-05-02 15 05 18](https://user-images.githubusercontent.com/22589457/235625670-640328fe-d71a-4de1-b1a4-05868baff3a1.jpg)

Done
