### ISSUE TITLE
Add more fiat currencies to base currency list

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6054]
- [x] Norwegian Krone NOK
- [x] Philippine Pesos PHP
- [x] Argentine Pesos ARS

**Comment by kansalt** [comment]
flag icons:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=70655-464525&t=rFIoHLXw4Ai9tdHh-4

**Comment by d4f5409d** [comment]
HUF?
