### ISSUE TITLE
Button to remove from added tokens.

### ISSUE THREAD

**Issue by Wjxfi** [horizontalsystems/unstoppable-wallet-android#6055]
I'm asking because I've suddenly changed my mind, but removing tokens is so far away...

somewhere in here. Next to the former add button
![ca46ca2c-0a9b-4ff7-bd39-29e912b2601c.jpg](https://user-images.githubusercontent.com/113500363/234018662-bf84f2b4-c0b4-493c-9eae-675b83206773.jpg)

**Comment by esengulov** [comment]
@kansalt thoughts?
