### ISSUE TITLE
Return the ability to display MACD, RIS in analytics

### ISSUE THREAD

**Issue by Wjxfi** [horizontalsystems/unstoppable-wallet-android#6056]

**Comment by Dianaaiym** [comment]
> _No description provided._

We would like to return chart indicators, and we need feedback from users. Please email us ([support.unstoppable@protonmail.com](mailto:support.unstoppable@protonmail.com)) if you have any suggestions.

**Comment by Dianaaiym** [comment]
merged into #6042
