### ISSUE TITLE
ZCash: it works fine but syncing always remain behind

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6057]
All Bitcoin like chains sync with UW in standby. I launch the app and in less than thirty seconds I have the "Send" button operative. Zcash no. It needs two hours because if I don’t launch UW for one or two days zcash stops syncing and leaves behind many blocks it then has to recover once the app launches.

Can anything be done to shorten syncing time?

![1000011994](https://user-images.githubusercontent.com/113377431/234067923-514a0f88-5882-4fb3-82ec-774bf3b0fdf7.jpg)

**Comment by d4f5409d** [comment]
I guess it's because the privacy implemantation. This is fine imo. Nighthawk wallet has slower sync so Unstoppable is better.

**Comment by esengulov** [comment]
@serrq @d4f5409d when it comes to Zcash our hands are tight as we mainly work with SDK provided for us without the ability to change how it works under the hood. that said we are in constant communication with Zcash core devs and constantly pass our feedback to them. They are aware of relatively slow sync times and work on improving that. 

To our knowledge Unstoppable is the only wallet that currently implements Zcash latest protocol updates. At least when releasing version 0.33 there was no other mobile wallet app that supported latest updates. If there are any other wallets that does it faster please do let us know and we will look into it :)
