### ISSUE TITLE
Fetch the icons of custom erc20 tokens from Coingecko

### ISSUE THREAD

**Issue by d4f5409d** [horizontalsystems/unstoppable-wallet-android#6059]

**Comment by esengulov** [comment]
could you provide some example tokens for us to evaluate this in detail

**Comment by d4f5409d** [comment]
Pepe for example

**Comment by esengulov** [comment]
> Pepe for example

ok, it will be added shortly 

@Dianaaiym @tmedetbekov

**Comment by Dianaaiym** [comment]
> Pepe for example

![2023-05-02 14 52 19](https://user-images.githubusercontent.com/22589457/235622582-6040747c-2c9b-4649-b516-8fb84a2088c5.jpg)
 done
