### ISSUE TITLE
UW isn't compatible with eCash web wallet seed

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6060]
I have an eCash web wallet on https://cashtab.com/ but its seed cannot be imported directly in UW because (maybe) it uses a different derivation path.

Can I do something or should I leave and send all XEC to the new wallet in UW?

Thanks for this amazing job!

**Comment by Dianaaiym** [comment]
> I have an eCash web wallet on https://cashtab.com/ but its seed cannot be imported directly in UW because (maybe) it uses a different derivation path.
> 
> Can I do something or should I leave and send all XEC to the new wallet in UW?
> 
> Thanks for this amazing job!

That's correct. Currently, we use different derivation paths, with Cashtab probably using path 1899 and Unstoppable using path 899. In the upcoming sprints, we will add the ability to support all derivation paths.

Thanks for your feedback.
