### ISSUE TITLE
The application closes as soon as you set the Bitcoin shipping fee

### ISSUE THREAD

**Issue by Coskunkolay** [horizontalsystems/unstoppable-wallet-android#6061]
I'm trying to set up a bitcoin shipping fee.  When I set and go back, the application closes, help please

![Screenshot_20230425_220510](https://user-images.githubusercontent.com/106901607/234377679-dc6d9ae9-5fce-474a-91a6-bea04ce08d68.jpg)
![Screenshot_20230425_213656_io horizontalsystems bankwallet](https://user-images.githubusercontent.com/106901607/234377691-765f8fd9-2385-4f47-bb42-d25d08bf08fa.jpg)

**Comment by rafaelekol** [comment]
We can 't reproduce this issue. 
We need crash logs. Actually after several similar crashes phone should show you popup to send Crash logs. Can you send us this logs.
Can you retry your steps 3-4 times to get crash logs popup.

**Comment by Coskunkolay** [comment]
I am Turkish. My English is weak. I don't understand what are the crash logs, how do I send them? Nothing appears on the screen, the application closes directly

**Comment by Coskunkolay** [comment]
I tried at least 10 times, there was no communication about the crash.  The application is kicking me out of the application.  It freezes on top of re-entering.😔😔

**Comment by Coskunkolay** [comment]
I will delete the application and upload the seed sentences and try again, I hope it works

**Comment by Coskunkolay** [comment]
I deleted and reinstalled the app and the problem still persists.  When I set the shipping fee, the application closes as soon as I go back.

**Comment by Coskunkolay** [comment]
It has been 1 year, I love using the unstoppable wallet, but this problem took me a long time.  I think you will do something, I am impatiently waiting for it to be fixed, thanks in advance

**Comment by Coskunkolay** [comment]
In the past, the bitcoin shipping fee was on a single page in the send tab.  If you revert to the old system, it seems to solve my problem.

**Comment by Coskunkolay** [comment]
Thanks to all the employees, my problem was solved in 5 days.  My problem was solved with the update.  Your #1 crypto wallet in the world, always unstoppable wallet
