### ISSUE TITLE
Transactions history button inside each coin card

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6063]
My idea is having the transactions history button within the coin card.

Of course that button show only that specific coin history, not the global (all) one.

![1000012018](https://user-images.githubusercontent.com/113377431/234559120-11affada-4520-4737-a144-1d55bde4a6f4.jpg)

**Comment by esengulov** [comment]
that's something been on our radar for a while. What's your reasoning behind having it this way?

**Comment by esengulov** [comment]
> There is an other way to reveal the 'history' button in card view.
> 
> Moving coin card sidely to right. Currently this action is empty (unused).

thanks for the clarifications, we are going to think about this but for the time being ant commit to anything. There are technical reasons that would simplify things quite a bit if we are to do it the way you suggested but it comes with other drawbacks i.e. transactions would only be available when user is online. Another problem is that filtering transactions by type (send, receive, swap etc) would no longer be possible. There are other nuances as well. SO, we are not sure about it just yet but so you know this has been on our minds as well and we are yet to decide about it.
