### ISSUE TITLE
ALGO support (Algorand blockchain)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6064]
I believe that the Algorand blockchain will become in next years a substrate chain for many services.

At the same time native coin called ALGO has a lightning fast (under 4 seconds) transaction finality.

The peculiarity of this blockchain is that it can not be hacked in the past, but only in the present.

This means that if you have one million Algos registered onchain, and a hacking happens in a month, this would result in losses only from that moment to forward. All that is behind remain untouched, by protocol design.

So the entire Algorand ecosystem is now enough mature to be added in UW.

https://developer.algorand.org/

Key features:

• Under 4 seconds transaction finality
• Low fees 0.001 Algos
• Scalable: over 1000 tps
• Smart contracts
• Innovative protocol consensus PPoS
• Smart signatures
• Algorand Virtual Machine (AVM)
• Post-quantum secure Falcon Keys
• Rekeying (it allows users to change their private spending key without the need to change their public address)

and many more...

**Comment by esengulov** [comment]
> https://developer.algorand.org/

thanks for suggestion. It's on the roadmap but not on priority list. I did submit a funding request on their website and if that goes through we can expedite it :)
