### ISSUE TITLE
Exporting transactions history (filters options available)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6065]
In some cases it is useful exporting a customizable transactions history in many output formats like .pdf .csv .md .txt etc. in order to share easily some informations with third party.

**Comment by esengulov** [comment]
> In some cases it is useful exporting a customizable transactions history in many output formats like .pdf .csv .md .txt etc. in order to share easily some informations with third party.

while we can integrate such feature could you please explain what's the use case for it? why do you need such feature?

**Comment by esengulov** [comment]
> The State could break my balls because it wants an offline proof of the transaction (for example the demonstration of having paid a government tax).
> 
> This inevitably introduces another problem: I have to show to the State only that or those transactions that I want, but not the others that do not interest to it, and which I want to keep hidden (in the exported file).
> 
> So it needs the ability to select granularly among transactions.
> 
> In the end, all I have to do is acknowledge that I paid for something while I preserve my privacy.

ok noted, will keep that in mind for the future. For the time being, we are not intending to add that feature due to fairly large ongoing task list.
