### ISSUE TITLE
Reproducibility problem on v0.32.0

### ISSUE THREAD

**Issue by mohammadrafigh** [horizontalsystems/unstoppable-wallet-android#6071]
Tried to reproduce the latest release (v0.32.0) but got a diff in `/assets/dexopt/baseline.profm`. This may be related to [this](https://issuetracker.google.com/issues/231837768?pli=1) AGP bug which could be fixed easily by upgrading AGP.

**Comment by rafaelekol** [comment]
Upgraded AGP with #6068
