### ISSUE TITLE
not showing NFTs

### ISSUE THREAD

**Issue by shortwavesurfer2009** [horizontalsystems/unstoppable-wallet-android#6078]
I restored my coinbase wallet seed into unstoppable. As you can see from the screenshot below i have an NFT.
![Screenshot_20230429-162127_Wallet](https://user-images.githubusercontent.com/116814522/235322705-bfcfe1cf-c588-439c-b4b8-19f30476e2d5.png)
However, once restored and synced i tap the NFT button in the top right of unstoppable wallet and see "You don't have an NFT in your wallet"

Edit:
App version 0.32.0

**Comment by esengulov** [comment]
At the moment, Unstoppable only supports NFTs on Ethereum blockchain. Ar erthose NFTs on Ethereum?

**Comment by shortwavesurfer2009** [comment]
> At the moment, Unstoppable only supports NFTs on Ethereum blockchain. Ar erthose NFTs on Ethereum?

No, they are both on Polygon wich is an Ethereum sidechain layer 2

**Comment by esengulov** [comment]
> > At the moment, Unstoppable only supports NFTs on Ethereum blockchain. Ar erthose NFTs on Ethereum?
> 
> No, they are both on Polygon wich is an Ethereum sidechain layer 2

At the moment, only Ethereum NFTs are supported. We are planning to add support for other chains soon)
