### ISSUE TITLE
eCash (XEC) stops sync on Moto 32s 

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6080]
Similarly to what happens with BCH on my smartphone (OnePlus), this time it is ecash to stop syncing on my Moto 32s.

It works fine when I give it seed at first, but systematically after a few days of operation, the app is no longer able to recover blocks in the sync chain.

To overcome this problem, I have to eject the wallet and add it again.

UW 32
Moto 32s XT2229-2 (SKU)
Android 12
Sim on board, 4G sync

![Screenshot_20230430-104322_20230430104520](https://user-images.githubusercontent.com/113377431/235344353-a7bfb4aa-9d11-459b-8136-5bd40ff85d98.png)

**Comment by abdrasulov** [comment]
The app connects to several peers for all Bitcoin-based blockchains, including eCash. It requires a successful socket connection to peers to work correctly. So as you've mentioned, it's probably related to the VPN. Most likely the app could not connect to peers via VPN. That is why it could not sync. I've tested it with Tor enabled. It works fine.

Could you test it with Tor enabled? And let us know if the issue still persists.

**Comment by abdrasulov** [comment]
Good. Thanks. Let's close this issue.
