### ISSUE TITLE
add token app crash

### ISSUE THREAD

**Issue by shortwavesurfer2009** [horizontalsystems/unstoppable-wallet-android#6081]
I got the contract address for Aave Polygon WMATIC and tried to add it to the wallet. However when i change the chain from Etherium to Polygon the app crashes. Here is the contract address.

0x6d80113e533a2C0fe82EaBD35f1875DcEA89Ea97

Edit:
App version 0.32.0

**Comment by rafaelekol** [comment]
Fixed by #6075
