### ISSUE TITLE
Lightning network support?

### ISSUE THREAD

**Issue by Imadlekal** [horizontalsystems/unstoppable-wallet-android#6084]
Hi,

Are there any plans to support the bitcoin lightning network?
I know you have a separate project here: https://github.com/horizontalsystems/lightning-wallet-android

But it seems like it hasn't been updated for a while so I was wondering if you're working on another version in this wallet?

Thank you.

**Comment by esengulov** [comment]
> Hi,
> 
> Are there any plans to support the bitcoin lightning network? I know you have a separate project here: https://github.com/horizontalsystems/lightning-wallet-android
> 
> But it seems like it hasn't been updated for a while so I was wondering if you're working on another version in this wallet?
> 
> Thank you.

Hi , we indeed worked on lightning wallet a while back. It's nearly done but was paused. We paused it because back then it was impossible to provide it with decent user experience while keeping things decentralized. We are revisting it occasionally and do intent to implement it at some point in the future.

**Comment by MoritzKa** [comment]
You could have a look at NWC (https://nwc.dev/)
it might make the implementation and the UX a lot easier:

- No lock-in: It is an open protocol so users from different lightning wallets can connect their accounts/nodes (Strike, Umbrel, Alby, Mutiny, etc.).
- No maintenance: The lightning wallet provider takes care of support and channel management, which was one reason of pausing the development from what I read.
- it is non-custodial from the integrator point of view: So no KYC needed and everybody is free to use the app. 

Unstoppable could implement the app-side of NWC and provide a UI for connected lightning wallets in the first step.
