### ISSUE TITLE
[Feature request] custom fees for BTC

### ISSUE THREAD

**Issue by Imadlekal** [horizontalsystems/unstoppable-wallet-android#6088]
Are there any plans to implement this for BTC transactions?

It would be great if we could have more control over the fees we're paying (the ability to change sat/byte), instead of choosing the priority.

**Comment by TalgatNurdinov** [comment]
The app already has this feature. You can set the custom fee by going to settings by clicking on the icon at the top of the send page

![Uploading Screen Shot 2023-05-01 at 15.16.17.png…]()

**Comment by Imadlekal** [comment]
I haven't noticed it. I'll close the issue then, thank you.
