### ISSUE TITLE
Unable to add coins details like logo, price, 

### ISSUE THREAD

**Issue by emmanbol** [horizontalsystems/unstoppable-wallet-android#6095]
Hello community, I am trying to be able to easily add new coins or tokens to app so it can show its logo, price data, charts etc. 

Can someone please point me to the right place to implement this? 

I am workingnon the android app

**Comment by esengulov** [comment]
> Hello community, I am trying to be able to easily add new coins or tokens to app so it can show its logo, price data, charts etc.
> 
> Can someone please point me to the right place to implement this?
> 
> I am workingnon the android app

hi, the coins are fetched from coingecko. If you would like to add anything that's not there it needs to be added to our backend server which keeps market data
