### ISSUE TITLE
add a site to translate in readme.md and "About App" in the application.

### ISSUE THREAD

**Issue by Wjxfi** [horizontalsystems/unstoppable-wallet-android#6097]
https://crowdin.com/project/bank-wallet-android

It was hard to find now.

**Comment by Dianaaiym** [comment]
> > Strings for "About App" section - https://crowdin.com/translate/bank-wallet-android/2697/en-de?filter=basic&value=3#q=the%20unstoppable
> 
> No, that's not what I meant.
> 
> > Do you mean adding text from the website (unstoppable.money) for translation purposes?
> 
> I haven't seen that site.
> 
> I asked to add https://crowdin.com/project/bank-wallet-android to the app (About App) and readme.md so that kind people could translate the app better. Now it is poorly translated. But I couldn't find a site to translate it for a long time. I want other people to see this site immediately and translate my language better.
> 
> I don't want other people to make my mistakes (couldn't find a site to translate for a long time). Let the translation site be in a prominent place

Thank you, I will consider how to improve the quality of translations. Would you be interested in helping us with translations into your native language?
