### ISSUE TITLE
Hardware wallet support (revisited)

### ISSUE THREAD

**Issue by 3point14159** [horizontalsystems/unstoppable-wallet-android#6100]
I know this issue has been closed in favor of the read-only watch feature in UW. However, it should be possible to sign tx using a hardware wallet.

I don't want to be too bold in saying this, but I think this is the next BIG hurdle for the dev team for the simple reason that it is the single-most feature that would improve and have the greatest security impact for UW.

Disallowing the storage of keys on distrusted hardware will one day become a standard security feature. The fact is you cannot trust general-use, internet connected devices with high value key assets.

[Ledger has their wallet source code open here on Github](https://github.com/LedgerHQ/ledger-live/tree/develop/apps). [MyPivxWallet is a web wallet that has integrated Ledger support](https://github.com/PIVX-Labs/MyPIVXWallet/pull/31), and their code is also open.

Let's find out what we need to do to make this happen.

**Comment by esengulov** [comment]
We are considering to implement Yubikey support in version 0.34. It will provide same level of security as hardware wallets.

**Comment by junzhli** [comment]
Hello @esengulov may I know how to enable the yubikey authentication on app? I can't find this feature on app with version 0.41? Thanks 😊
