### ISSUE TITLE
Can no longer send ETH via Arbitrum, says "current ETH  balance is below the amount required"

### ISSUE THREAD

**Issue by aleqx** [horizontalsystems/unstoppable-wallet-android#6105]
Seems that the latest versions have introduced a bug as in <subj>. I'm running the latest 0.32.1 and have 1 ETH in my Arbitrum wallet and trying to send any amount (e.g. 0.1 ETH)  to another address gives the above error. Max fee is showed as N/A. Trying to edit gas price makes no difference.

**EDIT:** Can confirm that 0.31 also has the same bug. Can also confirm that 0.30.0 works fine (I just lost my bookmarked addresses as I rushed to uninstall to downgrade instead of trying it in a sandbox)

Seems like a high priority bug.

I haven't checked other chains yet, but you may want to check all chains.

**EDIT 2:** While 0.30 works to send coins on Arbitrum (using the Send button in the wallet tab), when I try to use Wallet Connect to Aave on Arbitrum and then try to provide liquidity, the transaction screen that comes up also gives the same error. It seems your codebase has older bugs

**Comment by Dianaaiym** [comment]
> Seems that the latest versions have introduced a bug as in . I'm running the latest 0.32.1 and have 1 ETH in my Arbitrum wallet and trying to send any amount (e.g. 0.1 ETH) to another address gives the above error. Max fee is showed as N/A. Trying to edit gas price makes no difference.
> 
> **EDIT:** Can confirm that 0.31 also has the same bug. Can also confirm that 0.30.0 works fine (I just lost my bookmarked addresses as I rushed to uninstall to downgrade instead of trying it in a sandbox)
> 
> Seems like a high priority bug.
> 
> I haven't checked other chains yet, but you may want to check all chains.
> 
> **EDIT 2:** While 0.30 works to send coins on Arbitrum (using the Send button in the wallet tab), when I try to use Wallet Connect to Aave on Arbitrum and then try to provide liquidity, the transaction screen that comes up also gives the same error. It seems your codebase has older bugs

Hi,

Could not reproduce the reported bug. Did you try to send ETH or token?

Please send your App Status (Settings - About App) to support.unstoppable@protonmail.com

**Comment by Dianaaiym** [comment]
Could not reproduce the reported bug

**Comment by aleqx** [comment]
Didn't see the previous replies. Note that I'm using the version from F-droid, which compiles the source code themselves.
