### ISSUE TITLE
ZEC sync issues: has someone same problems?

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6106]
![1000014616](https://user-images.githubusercontent.com/113377431/236637360-ad01a147-ada1-41b5-b76f-b0a792e41c2f.jpg)

**Comment by abdrasulov** [comment]
Hi @serrq,

Thanks for your reports. We use the official Zcash SDK. As you said, it is most likely an API issue. Let's close this issue for now. If the issue occurs we'll reopen it.
