### ISSUE TITLE
Market tab become a card in Settings tab

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6107]
I really appreciated the three tabs layout.
In order to keep clean the UI I propose to move 'Markets' into 'Settings' tab.

So I can follow the coin 'watchlist' without dirty the UI.

What do you think about it?

![1000014619](https://user-images.githubusercontent.com/113377431/236638559-d7ede754-754d-4f1a-9f15-c126d7583671.jpg)

**Comment by esengulov** [comment]
Mmoving Market to Settings tab is fairly unusual approach to UI :) we feel that current way of disabling the tab entirely is sufficient for those who want cleaner UI.

**Comment by esengulov** [comment]
> In an other UI design I asked to move market tab close to "change wallet" button, above.
> 
> My target is saving three tabs (clean view) below. Because it is very clean. But I need of the market tab too.

our designers do not approve of this :) @kansalt @TalgatNurdinov
