### ISSUE TITLE
Integrate swap with payments

### ISSUE THREAD

**Issue by eloyesp** [horizontalsystems/unstoppable-wallet-android#6108]
I see you dislike Centralized solutions on the FAQ, and that you closed #5527 and #6035 and I think that I understand the reasons.

Here I will try to make a small tweak to make this a little bit better.

The main drawback of those swap services is that those are centralized solutions, but that problem can be solved by implementing lots of them (having many options makes a system decentralized no?), there is a big list on https://kycnot.me/ ...

Obviously, implementing lots of APIs with android seems hard, and that does not fix the problem of censoring, but those two issues can be solved by implementing a proxy (open source), adding a distributed second layer swap infraestructure.

That could make the implementation more challenging, but there is another thing to add to the balance, on the other front... and is that I think that the biggest advantage is not when thinking about on swapping between own accounts, but if thinking on integrating that feature on the send and receives menu.

So, currently unstoppable does not support Lighting Network, but with this in place, the wallet would be able to send and receive through the LN swapping Dash through FixedFloat with full privacy (as fixed float will only know the IP address of the proxy and the send and receive addresses).

The exchange will not be "as instant" as with a native LN wallet, but could be fast enough.

Hope you like the idea, as for me would make the difference between being able to use cryptocurrencies on a daily basis or using it as an investment.

**Comment by esengulov** [comment]
hi there, sorry for the long overdue reply. At the moment there is some uncertainty regarding the swap feature in the app. Apple began to reject the apps with such features, as a result we had to disable swap in the iOS entirely. We will monitor this for the next few months and work on available options.
