### ISSUE TITLE
Support for Tezos (XTZ): a blockchain with stunning features

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6113]
We’ve learned about many aspects of a blockchain, including speed, scalability, energy sustainability, open protocols, and the blockchain itself, and no less important is the security of the consensus mechanism, resistance to 51% attacks, reduced fees, and an entire ecosystem scalable and open to government services (elections, CBDCs, population census, etc.).

"The Tezos network’s annual energy consumption is estimated at 0.001 TWh. Tezos’ Proof of Stake (PoS) design means it can operate in an energy-efficient manner–other popular Proof of Work (PoW) networks use significantly more energy (Bitcoin 130 TWh) – this makes it an ideal platform for building blockchain applications that are energy-efficient and sustainable."

I ask therefore that the Tezos ecosystem can become part of the UW family.

Transaction finality in less than two seconds.
Other technical aspects can be viewed in the links below.

• Tezos consensus mechanism

https://opentezos.com/tezos-basics/liquid-proof-of-stake

• Environment (energy efficiency and carbon footprint)

https://tezos.com/carbon/

• An introduction to Tezos (video)

https://www.youtube.com/watch?v=Gui_z4wSrF4

**Comment by esengulov** [comment]
For the time being we do not intend to integrate Tezos. We might change our minds in the future but for now our roadmap is rather full.

**Comment by esengulov** [comment]
For the time being we do not intend to integrate Tezos. We might change our minds in the future but for now our roadmap is rather full.
