### ISSUE TITLE
[Feature request] List of previous addresses

### ISSUE THREAD

**Issue by Imadlekal** [horizontalsystems/unstoppable-wallet-android#6124]
I understand that for privacy reasons, new addresses are generated each time you receive a transaction. That's good, but it would be nice to have the ability to see your previous addresses as well, the way Electrum allows you to do for example.

**Comment by Dianaaiym** [comment]
> I understand that for privacy reasons, new addresses are generated each time you receive a transaction. That's good, but it would be nice to have the ability to see your previous addresses as well, the way Electrum allows you to do for example.

Hi,

Thank you for the feedback! This ticket was added in the 0.35 sprint.

**Comment by abdrasulov** [comment]
> Are old addresses able to receive funds when they are no longer in service?

Yes. All of the addresses belong to your account.

**Comment by esengulov** [comment]
implemented under https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6894
