### ISSUE TITLE
SDK Build Tools 30.0.3 are used instead of the latest 33.0.2

### ISSUE THREAD

**Issue by AbakumovAlexandr** [horizontalsystems/unstoppable-wallet-android#6130]
### Current behavior
Currently when building Unstoppable app, SDK Build Tools version 30.0.3 are used instead of the latest 33.0.2.

### Expected behavior
The latest available SDK Build Tools version must be used for building the Unstoppable app.

### How to reproduce
Tested on the Unstoppable 0.32.1 sources which have a `com.android.tools.build:gradle:7.1.3` dependency:
1. Remove any installed build tools except the latest ones (33.0.2) on the Android Studio's 'SDK Tools' tab of SDK Manager.
2. Make project.
3. In the Build log window you could find that build tools version 30.0.3 were installed during the app build process. You could confirm it on the 'SDK Tools' tab of SDK Manager as well.

### More info
When `buildToolsVersion` isn't set explicitly, Android Gradle plugin uses some minimum version of the build tools required by the version of the plugin you're using ([source](https://developer.android.com/reference/tools/gradle-api/7.2/com/android/build/api/dsl/CommonExtension#buildToolsVersion())):

> buildToolsVersion
> ...
> When using Android plugin 3.0.0 or later, configuring this property is optional. By default, the plugin uses the minimum version of the build tools required by the version of the plugin you're using. To specify a different version of the build tools for the plugin to use, specify the version as follows:
### Proposed solution
Set `buildToolsVersion` explicitly to use the latest one instead of the one which is 3 major releases back. Bump the setting when a newer version of SDK Build Tools gets released.

**Comment by rafaelekol** [comment]
I updated build tools to 33.0.1. Currently we hardcode version, because [we use apksigner](https://github.com/horizontalsystems/docker-android/blob/master/DockerFile) from build tools.
