### ISSUE TITLE
Scrolling (up and down) transactions history with volume keys

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6132]
My idea is to scroll transactions history entries pushing volume keys when I am in 'transactions' tab.

This makes more comfortable reading them and it avoid dirtying the screen with fingertips (less touches).

**Comment by esengulov** [comment]
This is rather unique request to be honest ))) Taking into account that we have a fairly large backlog I will have to skip on this one. pretty sure our designers won't let me push through this ticket @kansalt @TalgatNurdinov That said if one of them decides to approve it we can give it a try. For the time being I am cloying the issue though.
