### ISSUE TITLE
this button does not work, although it worked before (in early updates)

### ISSUE THREAD

**Issue by Wjxfi** [horizontalsystems/unstoppable-wallet-android#6136]
![fc79ee1d-ac77-4ef1-be84-21282b8fd4f2.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113500363/a4f10977-7a0d-4ac6-bd4a-0dbf4f10ba7f)

**Comment by abdrasulov** [comment]
@Wjxfi, 

It works when there are actual exchange rates for both tokens. Most likely, the rates were expired in your case. And if there are no actual rates for at least one of the tokens, that button becomes disabled.
