### ISSUE TITLE
add NEXO on Polygon to the list of recognized assets

### ISSUE THREAD

**Issue by aleqx** [horizontalsystems/unstoppable-wallet-android#6137]
You have added NEXO on Ethereum and Avalanche, but not on Polygon (which is in fact the 2nd officially minted network by the token issuer Nexo). COntract address and other info here: https://polygonscan.com/token/0x41b3966b4ff7b427969ddf5da3627d6aeae9a48e

It's useful for you to add and recognize it so that it shows price.

As a general request: how about allowing to set the price and token icon of any custom token by matching against the detected name? When inputting the contract address, UW recognizes the token name and could then match it against known token names for which it has prices and icons, and the user can then select a match from a drop down list. Then you wouldn't need to keep up with tokens that are issued on more networks (e.g. like Nexo in the above case)

**Comment by Dianaaiym** [comment]
> You have added NEXO on Ethereum and Avalanche, but not on Polygon (which is in fact the 2nd officially minted network by the token issuer Nexo). COntract address and other info here: https://polygonscan.com/token/0x41b3966b4ff7b427969ddf5da3627d6aeae9a48e
> 
> It's useful for you to add and recognize it so that it shows price.
> 
> As a general request: how about allowing to set the price and token icon of any custom token by matching against the detected name? When inputting the contract address, UW recognizes the token name and could then match it against known token names for which it has prices and icons, and the user can then select a match from a drop down list. Then you wouldn't need to keep up with tokens that are issued on more networks (e.g. like Nexo in the above case)


Nexo (polygon) has been added
![2023-05-29 12 21 42](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/6871c7c3-b4c7-4eda-8321-c863bb18a231)

**Comment by abdrasulov** [comment]
As for icons and prices for the custom tokens. Matching with names may result in conflicting tokens since the name of the tokens is not unique.
