### ISSUE TITLE
recognize price of variableDebt* (debt) tokens, not just the A* (collateral) tokens, to correctly reflect it in the total balance

### ISSUE THREAD

**Issue by aleqx** [horizontalsystems/unstoppable-wallet-android#6138]
Currently, assets borrowed on Aave (or other defi lending platforms) give you a variableDebt* (e.g. variableDebtUSDC) token or equivalent which represents the borrowed tokens, and an A* token (e.g. AWETH) which reprsents the collateral token. 

UW recognizes the price of A* tokens like AWETH, and adds them to the total balance, but does not recognize the price of variableDebt* tokens like variableDebtUSDC, and the total balance shown by UW is thus incorrect (the variableDebt* should be subtracted).

The price of both tokens should be recognized.

**Comment by abdrasulov** [comment]
It depends on the exchange rate and token info provider. At the moment they don't support variableDebt* tokens

**Comment by aleqx** [comment]
It seems I failed to make myself understood (but some patience from you may be needed before dismissing it). There will likely never be any price for debt tokens provided by oracles or exchanges. My point was that UW should match them against the base token, e.g. variableDeptUSDC matched with USDC, and use the USDC price for the variabkleDebtUSDC token too.

It's not too diffcult to have a rule for matching, e.g. `s/variableDebt(\w+)/$1/` (this will match all debt tokens from Aave) and similar ones from a few other popular lending platforms, say the top 5 from DefiLlama ... or even a look up table of debt tokan name <> base token name.

It would be a great and IMO also needed addition to UW, as it would make the declared wallet balance actually correct, as I mentioned. Right now UW's wallet balance is incorrect because it uses prices for collateral tokens but not for debt tokens. Should really be either both or none.
