### ISSUE TITLE
Disable swap on high price impact

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6141]
1) If the price impact is less than 1%

- don't show price impact

2) If the price impact is less than 5%. No changes. 

- show price impact yellow text
- let the user swap

3) If the price impact is between 5-20%.

- show price impact red.
- red alert
- let the user swap

> Important! You’re getting an extremely unfavorable price. This is due to extremely low liquidity.

4) If the price impact is more than 20%. We don’t allow swap.

- show price impact red.
- red alert 
- don’t let user swap

> Unstoppable has disabled swap action for this trade because you’re getting an extremely unfavorable price. This is due to extremely low liquidity.
> If you still want to swap please use [provider] website instead.

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=71428-443346&t=tQxu8BxduuOBHIw9-11

**Comment by Dianaaiym** [comment]
2) If the price impact is less than 5%. 

- show price impact yellow text
- let the user swap
