### ISSUE TITLE
LitecoinZ (LTZ) a privacy coin (Zcash fork)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6149]
I ask to put LTZ in UW roadmap.

https://litecoinz.org/

LitecoinZ (LTZ) is an open source cryptocurrency that is the world's first Zcash fork to be merged back into the mainline Bitcoin codebase.

 LitecoinZ retains all the power and stability of Bitcoin with the additional privacy and anonymity of Zcash shielded addresses.
 LitecoinZ is a stable and highly secure alternative cryptocurrency that is true to Bitcoin's original objectives.
 LitecoinZ was not premined, has no developer fee, and is 100% community developed.
 LitecoinZ is traded on multiple exchanges and tracked by many cryptocurrency tools.
LitecoinZ is the private bank you own.

**Comment by esengulov** [comment]
thanks for th recommendation. At this point we have rather long list of chains that need to be integrated. Therefore we are not keen on adding even more chains there unless there is substantial demand for it.

**Comment by esengulov** [comment]
> > We not keen on adding even more chains there unless there is substantial demand for it.
> 
> You’re absolutely right about that. But remember, it was Steve Job who told people what they had to buy. No person would ever have imagined that they needed a 10" tablet when tablets didn’t exist at all.
> 
> So I don’t care what people want, but what people need without knowing it.
> 
> They will comply. Who decides?
> 
> Who knows the field. You.

thanks ;)
