### ISSUE TITLE
No scrolling | Moving sidely the coins pages

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6151]
My idea is not scrolling the coins list vertically, but pages with up to 6 coins cards (red dots are pages) to scroll them sidely.

What do you think?

![1000021760](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/76ef2294-6b8e-4ef8-a13d-6b5e37eba505)

**Comment by TalgatNurdinov** [comment]
Not all screen types are compatible with the six coins option, and I think that scrolling to the 25th coin is often faster than swiping sideways.
