### ISSUE TITLE
Swapika: a non-custodial, no registration coins exchange

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6157]
Adding more coins swaps with no hassles.

https://swapika.com/

**Comment by esengulov** [comment]
> Adding more coins swaps with no hassles.
> 
> https://swapika.com/

Hmmm interesting. the exchange claims to offer users full control via cross chain swaps but at the same time there are coins (it supports )which to our knowledge are not compatible with existing viable ways to perform atomic swaps. There is no documentation on the site about it either. So, closing it for the time being.
