### ISSUE TITLE
I cannot more choose between shuffle and deterministic in all Bitcoin like chains

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6202]
Android 13
UW 0.32.1
OnePlus CPH2399

![1000024656](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/6908a5b9-25d9-48bd-b98d-7c4fa2a11fa8)

**Comment by Dianaaiym** [comment]
> Android 13 UW 0.32.1 OnePlus CPH2399
> 
> ![1000024656](https://user-images.githubusercontent.com/113377431/245360044-6908a5b9-25d9-48bd-b98d-7c4fa2a11fa8.jpg)

We have moved these settings to the advanced send settings

![2023-06-13 14 40 14](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/58945b1e-99b0-4c57-ae5f-ed26363f3a30)

![2023-06-13 14 40 17](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/c5a579b7-7ddd-41eb-8bd1-a94a1418acd3)

**Comment by Dianaaiym** [comment]
> Another problem is the word 'Bitcoin' in yellow framed message. Might it replaced with 'mainnet' or something else?
> 
> Because with eCash, Dash etc. it makes no sense.

yes, we'll fix it
