### ISSUE TITLE
LTC doesn't sync in all my devices

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6210]
Also in no-vpn device. In 0.32.1 it worked properly.

UW 0.33
Android 12/13
Moto 32e
OnePlus CPH2399

![1000026654](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/1ecb5e7c-59e5-40b0-a48e-993a4dd17c23)

**Comment by abdrasulov** [comment]
We haven't released v0.33 yet. The f-droid built it from a pre-release state. We are planning to release it in about 2 days. It will contain a fix for the Litecoin syncing issue.
