### ISSUE TITLE
v0.33.0 and v0.33.1 do not allow setting maxFee below current baseFee

### ISSUE THREAD

**Issue by aleqx** [horizontalsystems/unstoppable-wallet-android#6234]
This may be related to the other issue I posted (which was closed but not confirmed fixed): https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6105

Just did a fresh install of 0.33.0 from F-droid on Android 13 (added on 2023-06-18). Tried to use a max fee that is lower than current block base fee, the app gives the error below and doesn't allow me to continue. This is the first transaction attempt since reinstalling. I thought this was already fixed.

```
fee cap less than block base fee: address 0x..., gasFeeCap: 12000000000 baseFee:18268580977
```

[![Image from Gyazo](https://i.gyazo.com/dd2161d8e73045cf9fd5f0902ef887ea.jpg)](https://gyazo.com/dd2161d8e73045cf9fd5f0902ef887ea)

**Comment by aleqx** [comment]
I can confirm that the 0.33.0 APK from Github does NOT have this problem.

... so the F-droid versions are definitely compiled from different sources ... this is concerning

**Comment by abdrasulov** [comment]
@aleqx thanks for reporting. We have rebuilt v0.33 a few times. Most likely the F-droid has not updated it yet. Let's check it after a while.

**Comment by r4v3r23** [comment]
why is there a n update on fdroid without a corresponding github release? v0.33 is no where to be found here

**Comment by aleqx** [comment]
I can confirm that 0.33.1 from Github now does exactly the same thing.
