### ISSUE TITLE
Coin Page: Disable "Tweets" tab

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-android#6246]
update bearer token

**Comment by d4f5409d** [comment]
+1

**Comment by rafaelekol** [comment]
Updating bearer token didn't help. It seems that free API was completely closed. 
https://twittercommunity.com/t/deprecation-of-legacy-access-tiers-in-the-twitter-api/196162

**Comment by d4f5409d** [comment]
Fuck Shitter. Either way, Mastodon is better
