### ISSUE TITLE
(Restricted) PIN with activity levels

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6260]
This type of pin allows at least two use cases.

1. I have to authorize a person (for example my wife) to access my wallet for a certain period of time but I don’t have to give her the master pin.

2. I am typing the pin under a video surveillance system or around prying eyes (train, plane, bus, etc.).

I create a host pin, for example 336 785, and inform the app that it must allow up to ten app unlocks and only grant level 2 events (for example, charges not exceeding 0.001 ₿ /day.

Here I also introduce action levels. Here are some examples (customizable).

Level 1 master pin (all allowed, no limit)

Level 2 (payments within the threshold of 0.003 ₿ /day are allowed)

Level 3 (payments within the threshold of 0.001 ₿ /day are allowed)

Level 4 (reading mode only, no spending activity)

**Comment by esengulov** [comment]
> This type of pin allows at least two use cases.
> 
> 1. I have to authorize a person (for example my wife) to access my wallet for a certain period of time but I don’t have to give her the master pin.
> 2. I am typing the pin under a video surveillance system or around prying eyes (train, plane, bus, etc.).
> 
> I create a host pin, for example 336 785, and inform the app that it must allow up to ten app unlocks and only grant level 2 events (for example, charges not exceeding 0.001 ₿ /day.
> 
> Here I also introduce action levels. Here are some examples (customizable).
> 
> Level 1 master pin (all allowed, no limit)
> 
> Level 2 (payments within the threshold of 0.003 ₿ /day are allowed)
> 
> Level 3 (payments within the threshold of 0.001 ₿ /day are allowed)
> 
> Level 4 (reading mode only, no spending activity)

Hi, we had a chat about the in the past in the context of duress pin. For the time being we decided to postpone this until we have ,more users and better understanding of the type of limitations this feature should have. There is definitely. place for it but we need a bit more time to understand what would be the best way to implement it.
