### ISSUE TITLE
Please might you add an icon to LTZ coin in Watchlist?

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6289]
![1000031661](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/7ff1467f-676b-466d-b5e8-7bd3d4390e22)

**Comment by Dianaaiym** [comment]
![2023-07-07 18 14 15](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/0c1ba0c3-1d8a-4a01-8547-54e8d0b703dc)

done
