### ISSUE TITLE
add support for all chains from avalanche

### ISSUE THREAD

**Issue by Wjxfi** [horizontalsystems/unstoppable-wallet-android#6291]
https://medium.com/@defidecrypted/whats-the-difference-between-the-avalanche-c-chain-x-chain-and-p-chain-9af28f6524d8

**Comment by esengulov** [comment]
the other two chains are architectually different from Ethereum like EVM chains and likely to require significant amount of work. We are postponing it for now and plan to to get back to it once the Avalanche chain Is used by wonder community.
