### ISSUE TITLE
Tron: unable to send USDT tokens: broadcastTransaction error: SIGERROR

### ISSUE THREAD

**Issue by ingvar-lynn** [horizontalsystems/unstoppable-wallet-android#6293]
Wallet has >100 trx; 0 energy; 600/600 bandwidth.

Same problem with both latest versions:
f-droid - 0.33.0-81
github - 0.33.1
 
![Screenshot_20230706_173009_1](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/23612903/f10eac5b-6c8e-4097-8b77-addb09d1cd21)

**Comment by Farizov** [comment]
Same issue. 
Money stuck in the wallet, can't send.

**Comment by Dianaaiym** [comment]
@Farizov @ingvar-lynn Not reproducible. Please send your App Status (Settings - About App) to support.unstoppable@protonmail.com

**Comment by ingvar-lynn** [comment]
Workaround: export secret words **without** passphrase to another wallet (i've used trust) all tron stuff would be there.

Given that there is also some breaking bug with LTC after file export-import, I'm done with unstoppable wallet.

@Farizov

**Comment by esengulov** [comment]
> Workaround: export secret words **without** passphrase to another wallet (i've used trust) all tron stuff would be there.
> 
> 
> 
> Given that there is also some breaking bug with LTC after file export-import, I'm done with unstoppable wallet.
> 
> 
> 
> @Farizov

Bugs happen, we will fix it and push hotfix shortly. @ingvar-lynn @Farizov

**Comment by abdrasulov** [comment]
> Workaround: export secret words **without** passphrase to another wallet (i've used trust) all tron stuff would be there.
> 
> Given that there is also some breaking bug with LTC after file export-import, I'm done with unstoppable wallet.
> 
> @Farizov

Can you please share the details for the bug with LTC after file export-import? Did LTC syncing stop working? Or did you face an issue with account restoration?

**Comment by ingvar-lynn** [comment]
Checked that LTC bug again and now I'm not sure about it - I was able to transact just fine.

**Comment by abdrasulov** [comment]
> Checked that LTC bug again and now I'm not sure about it - I was able to transact just fine.

Sounds good. As for the USDT sending issue, we could not reproduce it. Even though we tried it with a few accounts and different internet providers. In the upcoming release v0.33.2, we decided to log these error details into the App Log. The new version should be available in a day or two. Can you please check it once again with this new version?
