### ISSUE TITLE
A bug in Unstopable wallet backup

### ISSUE THREAD

**Issue by michaelliu123github** [horizontalsystems/unstoppable-wallet-android#6310]
Hey unstoppable team,

I would like to let you know that a bug has been found in the unstoppable wallet. When you create a passphrase added account, and the passphrase is longer than 12 digits(characters in my case), and when you import the backup file back, it's a different wallet, not the original one created. I looked into it and realized that it was the added passphrase was wrong and it had been automatically truncated to only 12 characters long. I tried multiple times and confirmed that this is the case at least for all android devices. I believe the problem is in either one of the two scenarios:

first possible scenario is that when you export the account with a passphrase that is longer than12characters, the passphrase is automatically truncated to only 12characters and the exported backup file is wrong when generated;

the second possible scenario is that the exported backup file is correct, but when you import the backup file, the passphrase is automatically truncated to 12 characters, and therefore it shows a different wallet after the import.

**Comment by abdrasulov** [comment]
Hey @michaelliu123github. Thanks for the report. We'll check it
