### ISSUE TITLE
Add pin or biometric before making transaction.

### ISSUE THREAD

**Issue by iv7dev** [horizontalsystems/unstoppable-wallet-android#6313]

**Comment by Dianaaiym** [comment]
Hi,

Thank you for your suggestion. Could you please provide reasons for why this functionality is needed?

**Comment by iv7dev** [comment]
Hi, sure. As a double factor of safety.  Someone could enter our wallet due to our carelessness, for example, we are absent for a few seconds or minutes with the wallet open and they could send our funds to their own wallet.  It's more common than you think

**Comment by iv7dev** [comment]
Sorry!! I wrote the title wrong, it's BEFORE, not AFTER!!

**Comment by Dianaaiym** [comment]
> Hi, sure. As a double factor of safety. Someone could enter our wallet due to our carelessness, for example, we are absent for a few seconds or minutes with the wallet open and they could send our funds to their own wallet. It's more common than you think

Thank you for the feedback! 
We have decided to postpone this task for now.
