### ISSUE TITLE
Tron (TRX) synchronization problems

### ISSUE THREAD

**Issue by TheFuzzStone** [horizontalsystems/unstoppable-wallet-android#6316]
I've been waiting a long time for the addition of Tron to use this wallet for work.

Today I decided to trust it for the first time and it let me down. I accepted n USDT, but I couldn't send any more:

![image](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/16173361/af1237b4-dcc3-4ecb-89f6-60c35b2c243c)

![image](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/16173361/92bdcad2-b149-4c57-824d-f8932b94d4c0)

----

There was no connection for 1 hour. Then it appeared for a short time, and now it is not connected again. 

This shows the unreliability of your product. Please fix it. 

Version: 0.33.2
Android version: the latest GrapheneOS on Pixel 6 Pro

**Comment by TheFuzzStone** [comment]
The problem was solved - imported the seed phrase into Trust Wallet and sent the funds, but, Unstoppable Wallet failed me at a very bad time, when I had to send USDT (TRC20) to my client.

I do OTC trading and it is critical for me that the wallet is reliable.

For now, I will put off using Unstoppable Wallet for a while. I can't let this happen in my business.

**Comment by Dianaaiym** [comment]
Hi,

Sorry to hear about your recent experience. Please send your App Status (Settings - About App) to support.unstoppable@protonmail.com, we'll check it

**Comment by TheFuzzStone** [comment]
@Dianaaiym, sent.

**Comment by iv7dev** [comment]
> The problem was solved - imported the seed phrase into Trust Wallet and sent the funds, but, Unstoppable Wallet failed me at a very bad time, when I had to send USDT (TRC20) to my client.
> 
> I do OTC trading and it is critical for me that the wallet is reliable.
> 
> For now, I will put off using Unstoppable Wallet for a while. I can't let this happen in my business.

This is open source and you should thank the programmers who make your life easier. Stop complaining and make comments that add up, not subtract. if you want to complain then pay.

**Comment by ikigai-gh** [comment]
I'm experiencing exactly the same issue on GrapheneOS with Pixel 5. The version of Unstoppable wallet is also 0.33.2. Just sent the report to your support team.

**Comment by TheFuzzStone** [comment]
> This is open source and you should thank the programmers who make your life easier. Stop complaining and make comments that add up, not subtract. if you want to complain then pay.

Dude, you don't tell me what to do and I won't tell you where to go, ok? And if you're boozing in the morning, then eat something. 

"Complaining" in open source helps make the product better. It's a pity that not everyone realizes this.

**Comment by iv7dev** [comment]
> > This is open source and you should thank the programmers who make your life easier. Stop complaining and make comments that add up, not subtract. if you want to complain then pay.
> 
> Dude, you don't tell me what to do and I won't tell you where to go, ok? And if you're boozing in the morning, then eat something. 
> 
> "Complaining" in open source helps make the product better. It's a pity that not everyone realizes this.

The drink is for men.  you should drink something then.  so you don't complain so much and instead suggest. Cheers

**Comment by TheFuzzStone** [comment]
Any updates?

**Comment by omurovch** [comment]
Hi @TheFuzzStone 

А new version 0.33.3 will be released next week that should fix Tron sync problem. How often are you getting sync error?

**Comment by TheFuzzStone** [comment]
Thanks, @omurovch. 

As @ikigai-gh said, couple times in a day. Which mean it's not usable for me.

Looking forward for the update. As I said before when I campaigned the developers to add Tron support - a lot of people among OTC traders use very dangerous (in my opinion) wallets, and they are all proprietary. So with a little publicity, UW will get a lot of users.

**Comment by TheFuzzStone** [comment]
Just updated to 0.33.3. Done few TRX transactions - they're ok. 

Received USDT (TRC20), but I can't send it:

![Screenshot_20230730-152953_1](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/16173361/dc24b6a2-ea4d-41d8-8ec8-ead1b6745dcf)

**Comment by omurovch** [comment]
New version 0.34.1 with fix for send issue is on the way.

**Comment by omurovch** [comment]
[6548](https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6548)
