### ISSUE TITLE
[QUESTION] Is the private key stored encrypted?

### ISSUE THREAD

**Issue by MasterixCZ** [horizontalsystems/unstoppable-wallet-android#6317]
Is Unstoppable storing private key encrypted defaultly or after setting passcode or never?

**Comment by BananchickPasha** [comment]
It doesn't encrypt keys, it rather keeps them on separate chip specifically designed for storing such private keys:
https://developer.android.com/training/articles/keystore

**Comment by MasterixCZ** [comment]
Interesting, thanks for answer!
