### ISSUE TITLE
Exchange wallet: UI bugs

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-android#6340]
- [x] Display login errors in the "Bottom" components
<img width="804" alt="Screen Shot 2023-07-27 at 22 39 08" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/58926737/9e8c0003-c3aa-446e-b50b-b418465554d3">

- [x] Add "paste" buttons to the input component
<img width="770" alt="Screen Shot 2023-07-27 at 22 39 26" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/58926737/e8063f3a-2f64-4f66-b768-a4eb033999ff">

- [x] Display verification errors in the "Bottom" components
<img width="800" alt="Screen Shot 2023-07-27 at 22 39 45" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/58926737/e7fa453c-3016-4dd0-9057-44299542e634">

- [x] Show the full balance along with the blocked balance 
- [x] Display blocked amount on balance cards 
<img width="793" alt="Screen Shot 2023-07-27 at 22 39 57" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/58926737/a6277610-a586-4b83-a8a6-85d2c0a61864">

- [x] Fix paddings and text type in cells 
<img width="769" alt="Screen Shot 2023-07-27 at 22 40 24" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/58926737/21fc4b0f-0fd0-4e89-9a8d-7a8c60e69149">

- [x] Change the header text to "Send [coin code]".
- [x] Fix the error texts related to the minimum/maximum amount 
- [x] Remove the "Information" button and change the text to “Fee"
- [x] Fix “important" text 
<img width="801" alt="Screen Shot 2023-07-27 at 22 40 35" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/58926737/b94e774b-a5fc-4c31-aa55-3274294195bc">

- [x] Add 2FA to the withdrawal confirmation
<img width="781" alt="Screen Shot 2023-07-27 at 22 41 38" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/58926737/2fcb82cb-5a63-4226-8931-a4374ec18f86">

**Comment by Dianaaiym** [comment]
- [ ]Remove the paste button 

![2023-07-28 15 56 56](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/6607816d-0b25-49cf-a07d-9647f945e1f4)

- [ ] Coinzix - Sign Up: Activate the button and open the Coinzix website.

![2023-07-28 15 59 14](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/56731b37-48ff-478d-a6f4-d4955c63816b)
