### ISSUE TITLE
USDC on Arbitrum should be renamed to USDC.e

### ISSUE THREAD

**Issue by aleqx** [horizontalsystems/unstoppable-wallet-android#6353]
Circle has started minting native USDC on arbitrum for a while now, so Arbitrum has two versions of USDC. The Native USDC ("USDC") and the Ethereum-bridged USDC ("USDC.e"). These are two different contracts, and two different assets. UW should correctly label these because can cause loss of funds, e.g. someone sending USDC.e to a USDC address thinking they are sending the native USDC because UW has wrongly labeled it as "USDC".

**Comment by aleqx** [comment]
The same goes for usdc on polygon, should be "USDC.e"

In fact, you should review ALL the usdc tokens on the networks you support in UW to compare the smart connect address of the bridges version versus the native version.

The networks where Circle minted native USDC are shown here, along with the respective contact addresses: https://www.circle.com/en/usdc/developers

**Comment by aleqx** [comment]
P.s. note the lowercase ".e"

**Comment by tmedetbekov** [comment]
Hi @aleqx, thank you for reporting the correction.

We have added USD Coin Bridged (USDC.e) on the networks Avalanche, Polygon, Optimism, and Arbitrum

**Comment by aleqx** [comment]
Also, don't forget `variableDebtArbUSDC.e` and `variableDebtArbUSDC` as well as `AUSDC` and `AUSDC.e` on arbitrum, polygon, optimism, etc

**Comment by esengulov** [comment]
> Also, don't forget `variableDebtArbUSDC.e` and `variableDebtArbUSDC` as well as `AUSDC` and `AUSDC.e` on arbitrum, polygon, optimism, etc

@tmedetbekov thoughts?
