### ISSUE TITLE
Decimal representation issues of balances

### ISSUE THREAD

**Issue by aleqx** [horizontalsystems/unstoppable-wallet-android#6354]
I can see UW tries to truncate balances to 4 representative digits, but it gets it wrong in many cases and it's slightly misleading. For example 60.9853 is truncated to 61, whereas it should be 60.99 (for 4 representative digits). 55.4414 is truncated to 55.4, whereas it should be 55.44, and so on.

It seems you opted for some custom shorthand which causes these issues. Why not use the established `"%.4g"` format modifier of the classic `*printf()` functions?

Also, could we please have an option to choose the number of representative digits? I for one like to see more than 4 digits.

**Comment by Andreisbb** [comment]
Hello, there is same issue with transaction values records representation.

**Comment by abdrasulov** [comment]
The number of decimals is dynamic. It depends on the number itself. So for instance, if the value > 1000 then it doesn't show its decimal part. At the same time if the value < 1, then it shows the decimal part taking a significant number of decimals. We implemented this rounding logic as a result of several discussions.

**Comment by aleqx** [comment]
I can see that you haven't actually read the message before replying and closing this issue. Disappointing. The problem is still there, and what you explain is clearly not working (nor does it fully apply).
