### ISSUE TITLE
Balance tab: Redesign

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-android#6357]
Layouts:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=74159-442569&mode=design&t=Acxzfv3tl1yoGWAJ-4

**Comment by aleqx** [comment]
Please take into account https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6354

Nice to see continued activity 👍
