### ISSUE TITLE
Unable to resolve host unstoppable.api.entreprise.1inch.exchange

### ISSUE THREAD

**Issue by zz64** [horizontalsystems/unstoppable-wallet-android#6363]
Hi,
trying today to testing swap on Polygon, i get :
```
Unable to resolve host unstoppable.api.entreprise.1inch.exchange
No address associated with hostname 
```
1inch not available ?
Version 0.33.3 from google

![Screenshot_20230807-163325](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/1113878/2d3126f6-2c2b-4676-bf2d-3961d0f8e2e3)

Thanks.

**Comment by abdrasulov** [comment]
Hello @zz64. 

We are working on this issue. Planning to release a fix in the upcoming release. 

As for now, you can use another swap provider like Uniswap or Pancakeswap
