### ISSUE TITLE
Peers Origin

### ISSUE THREAD

**Issue by mkohlhaas** [horizontalsystems/unstoppable-wallet-android#6364]
I just wonder where the peers in the _App Status_ page  come from.

Kind regards!

**Comment by abdrasulov** [comment]
The Bitcoin wallet works in SPV mode. It connects to several peers to sync with the network blockchain. Also, each time the peers get rotated. So the next time the wallet connects to a different set of peers. It is the decentralization.

This applies to all bitcoin-based blockchains, like Bitcoin itself, Bitcoin Cash, Litecoin, Dash.

**Comment by mkohlhaas** [comment]
Thanks! 

I understand. What I really wanted to know is how are these peers selected or is this completely random?

**Comment by abdrasulov** [comment]
For the first time, this is completely random. Then they are selected based on a score. The score is calculated based on the speed and usage count.

Here you can find detailed info https://developer.bitcoin.org/devguide/p2p_network.html#peer-discovery

**Comment by mkohlhaas** [comment]
Okay. Cool. Thanks a lot!!!

**Comment by abdrasulov** [comment]
Yes, it applies to eCash too.
