### ISSUE TITLE
Feature request: Please add support for KAS (kaspa) 

### ISSUE THREAD

**Issue by vanhoopstallion** [horizontalsystems/unstoppable-wallet-android#6371]
Hello

Please consider adding support for KAS (kaspa) wallet function.

https://kaspa.org/

Thank you

**Comment by esengulov** [comment]
Thanks for the recommendation. We typically integrate chains once the chain is widely used and being requested by our users.

**Comment by vanhoopstallion** [comment]
Really amazing tech, proper evolution of BTC

I'm using the Kaspium mobile app currently. It accepts 12/24 seed phrase from the community wallets. Pretty slick.

Hopefully there's more interest to generate consideration for Unstoppable to consider adding KAS. For me I could then use the app to trade between stables and KAS within the same wallet app
