### ISSUE TITLE
Fiction random names generator for wallets

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6474]
This may seem like a trivial problem, but when you start counting more than 30 wallets, I assure you that having a fiction wallet name generator simplifies things tremendously.

Furthermore, being generated randomly, the name of the wallet has no relation to the real world. This makes it ideal for a wide variety of uses.

![1000037739](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/b680f3e8-c1ee-4140-bd72-c55b2fa12cfc)

**Comment by esengulov** [comment]
thanks, we'll have a think about it though there are some obvious black boxes here like what to do with non-english apps.
