### ISSUE TITLE
[P] [E] Extending hide balance in transactions history too (optionally)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6483]
As seen in Wallets view, I would like have the possibility to hide balances in transactions history tab too.

There are some use's cases where balances aren't needed to share screenshots with others. Optionally including (hiding) also in the fields from/to.

**Comment by kansalt** [comment]
Hi. Thank you for your suggestion. We will definitely consider the possibility of implementing this function.

**Comment by TalgatNurdinov** [comment]
first, we'll just hide the amounts in the transaction cells, like here
![Uploading Screen Shot 2023-09-20 at 12.10.35.png…]()
