### ISSUE TITLE
UW on Mastodon social network

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6490]
Every day Twitter becomes more hostile and centralized.

Every day hundreds of users leave the platform and search for Mastodon or any other ActivityPub reincarnation, open and federative protocol.

If the development team is interested, I would be proud and happy to follow it on Mastodon.

Tutanota, SimpleX, Proton, and many other IT development and security companies have already shifted their communication to users there.

A new stage and a new opportunity to continue our "unstoppable" march towards decentralization and freedom.

On Mastodon, those who follow you, are already using some hashtags among which I can include #uw #unstoppablemoney #unstoppablewallet #uwallet #horizontalsystems.

**Comment by esengulov** [comment]
> Every day Twitter becomes more hostile and centralized.
> 
> Every day hundreds of users leave the platform and search for Mastodon or any other ActivityPub reincarnation, open and federative protocol.
> 
> If the development team is interested, I would be proud and happy to follow it on Mastodon.
> 
> Tutanota, SimpleX, Proton, and many other IT development and security companies have already shifted their communication to users there.
> 
> A new stage and a new opportunity to continue our "unstoppable" march towards decentralization and freedom.
> 
> On Mastodon, those who follow you, are already using some hashtags among which I can include #uw #unstoppablemoney #unstoppablewallet #uwallet #horizontalsystems.

hi @serrq at this moment we are trying to cut down on the number of networks where we are present and offer tech support. We intend to leave only following venue:

- GitHub/Twitter for feature requests and bug reporting
- Telegram for tech support

Thus we are slowly phasing out the other venues. The reason is that we are having difficulty to monitor all those and reply in a timely manner.
