### ISSUE TITLE
LTC BIP86 always fail.

### ISSUE THREAD

**Issue by N3koSempai** [horizontalsystems/unstoppable-wallet-android#6509]
As the title says, transactions made in LTC BIP86 always fail. I have tried with or without vpn, with mobile data or wifi, with random or deterministic mode. It always fails and it is in the wallet because when checking in the explorer the transaction was never sended.

**Comment by Dianaaiym** [comment]
> As the title says, transactions made in LTC BIP86 always fail. I have tried with or without vpn, with mobile data or wifi, with random or deterministic mode. It always fails and it is in the wallet because when checking in the explorer the transaction was never sended.

Hi,

Please send your App Status (Settings - About App) to unstoppable.support@protonmail.com

**Comment by esengulov** [comment]
@Dianaaiym

**Comment by N3koSempai** [comment]
send from LTCBIP86 still does not work. it syncs correctly but does not send. i have sent the app status information to the email provided.

**Comment by esengulov** [comment]
> send from LTCBIP86 still does not work. it syncs correctly but does not send. i have sent the app status information to the email provided.

looking into it @Dianaaiym
