### ISSUE TITLE
price chart data are unreadable on system large font size 

### ISSUE THREAD

**Issue by DaLiV** [horizontalsystems/unstoppable-wallet-android#6524]
1. android settings - set font size "large"/"very large"
2. wallet-prices- try to slide over price chart - price/date fields ... that will be not readable

**Comment by esengulov** [comment]
@Dianaaiym please test

**Comment by esengulov** [comment]
> * android settings - set font size "large"/"very large"
> * wallet-prices- try to slide over price chart - price/date fields ... that will be not readable

would it be an option to keep the text size fixed, regardless of the system setting?

**Comment by DaLiV** [comment]
possible, if that goes not below readability. hard to tell without testing. however some peoples has diffirent sight probleme, and "fixed" may be not for them. so - only by tests.
