### ISSUE TITLE
coin charts improvement suggestion

### ISSUE THREAD

**Issue by DaLiV** [horizontalsystems/unstoppable-wallet-android#6525]
* can make them bigger and with scalable timeranges

* add posiibility to define own custom lines (trendlines)
* + vertical lines for "important" date-times

**Comment by esengulov** [comment]
> * can make them bigger and with scalable timeranges
> * add posiibility to define own custom lines (trendlines)
> * * vertical lines for "important" date-times

thanks for the suggestion. While may sounds simple this is not something we can do at the moment. the feature is not straightforward.
