### ISSUE TITLE
Balance auto hide works even when "auto hide" is OFF if you tap on balance once

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6528]
UW 0.34

Curiously I discovered that auto hide switch always works if you tap (wallet tab) on hide balance once (even if switch is OFF).

I mean if you close the app and launch it again.

Does it works so?

**Comment by abdrasulov** [comment]
Hello @serrq,

Yes, it works in this way. It preserves the last visibility state of balance. So if it is hidden when you close the app and launch it, it will be hidden.

As for the "auto-hide" setting, if it's on then the balance will always be hidden on the app launch.
