### ISSUE TITLE
Check for the occurrence of the error message "Scalar is not in the interval [1 ' n-1]".

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6536]

**Comment by Esmail0karimi** [comment]
How did you solved this problem???
I have this problem and I can't transfer my funds please help me

**Comment by omurovch** [comment]
> How did you solved this problem??? I have this problem and I can't transfer my funds please help me

Hi @Esmail0karimi,

We are trying to reproduce your problem. So far couldn't reproduce it, send/swap works fine. We are looking into it.

**Comment by Esmail0karimi** [comment]
Thank you for your reply❤️
