### ISSUE TITLE
Add chain explorer in wallet functionality or link to an external site.

### ISSUE THREAD

**Issue by OrginalS** [horizontalsystems/unstoppable-wallet-android#6537]
Allow users to look up balance and transaction history of any public address in the wallet or by linking to popular chain explorer websites like [blockchair.com](https://blockchair.com/) or [etherscan.io](https://etherscan.io/). This feature could be accessed by inputting a public address or txn hash into the search bar in the markets tab or in its own separate tab.

**Comment by esengulov** [comment]
Thanks for the suggestions. We had an idea to add such functionality when user clicks on the address within the app but it's not scheduled for the near future. We feel adding a separate search bar for it would be an overkill. How often do you reply on such feature when using the app? what's the use case for it?
