### ISSUE TITLE
0.34 - Where did my previous account Tron disappear to?

### ISSUE THREAD

**Issue by TheFuzzStone** [horizontalsystems/unstoppable-wallet-android#6548]
Just installed update 0.34, and my Tron "account" (wallet) was changed to another one, without my confirmation or approval.

Also, I can't understand where my previous Tron account with TRX and USDT balance (TRC20) disappeared to.

**Comment by omurovch** [comment]
There was a bug in the creation of Tron wallets with a passphrase. Wallets created before version 0.34 were generated without a passphrase, even though a passphrase was indicated. After update to 0.34 passphrase was included to the seed. If you are experiencing same problem, you should restore the wallet without passphrase and transfer funds to the "correct" account, i.e. to the address shown after update.

**Comment by TheFuzzStone** [comment]
> you should restore the wallet without passphrase and transfer funds to the "correct" account, i.e. to the address shown after update.

I did it my way. 

1. Restored with mnemonic phrase without passphrase and took out TRX and USDT (TRC20);

2. Accessed the wallet with the passphrase and withdrew ETH;

3. Created a new mnemonic phrase using version 0.34 to get "all in one place".

Yes, in theory you could continue to use the "new" Tron that came after the update, but I don't like that approach.
