### ISSUE TITLE
Improve Bitcoin synchronization by integrating API sync option

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#6553]
The API key for premium will be provided by blockchair.com

There should be a note somewhere in blockchain settings for UTXO blockchains. It should say "The sync is done via Blockchair.com. Fast and private API source for all major blockhains."

**Comment by TalgatNurdinov** [comment]
Bitcoin type blockchain settings page
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=77763-42502&mode=design&t=hbHFemo1f296UQMI-11

EVM type blockchain settings page
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=67249-312816&mode=design&t=hbHFemo1f296UQMI-11

- [ ] Add new descriptions
- [ ] Remove the "RPC Source" and "Restore Source" headers above the cells (as well as the info page)

**Comment by esengulov** [comment]
> Is it possible extending the blockchair fast sync for eCash too?

@omurovch @esen does blockchair support ecash?

**Comment by omurovch** [comment]
Yes, it does

> @omurovch @esen does blockchair support ecash?
