### ISSUE TITLE
Security center improvements: duress pin

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-android#6556]
- [x] Change the default state of "Security Center”. Display all attributes regardless of the passcode enablement status.

- [x] Update the method for activating the passcode.

- [x] Add the action to set a passcode when enabling Finger Print and Duress Mode > "if the password is not set”

- [x] Move "Balance Auto Hide" from the "Appearance" section to the "Security Center" section and provide a description.

Implement a new function called "Duress Mode”

- [x] Include a description of the function, wallet selection, and passcode setting with the ability to edit and delete in the "Duress Mode" setup action. 

- [x] Duress Mode is activated only on screens with a Passcode during app unlock (at launch and app switching).

- [x] Face ID feature should unlock Duress Mode > "if Duress Mode is active"

- [x] Deleting the master passcode also deletes all Duress Mode settings

- [x] Update numpad buttons spacing 

- [x] Unlock: Implement last layouts (with top bars and back button)  

- [x] Remove status of Tor on cell in security center

Layouts:

**Comment by TalgatNurdinov** [comment]
@abdrasulov New Unlock Screen Layouts
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=77362-476430&mode=design&t=xouWmJHyQBqZ7fS7-11
