### ISSUE TITLE
Adding new contracts, with current price

### ISSUE THREAD

**Issue by arcticShadow** [horizontalsystems/unstoppable-wallet-android#6557]
I've added a couple of contracts to my wallet to track some tokens on bsc. Just wanted to check if there was a way to get a price, or current value displayed. I've had a look through past issues and search for documentation but havn't found anything that discusses this so hopefully not a duplicate.

**Comment by esengulov** [comment]
> I've added a couple of contracts to my wallet to track some tokens on bsc. Just wanted to check if there was a way to get a price, or current value displayed. I've had a look through past issues and search for documentation but havn't found anything that discusses this so hopefully not a duplicate.

sorry for the delay. you mean the current price for the token? our market database mostly uses price data from coingecko and currently counts 5000 tokens. The token needs to be listed on coinable in order for us to display its prices

**Comment by arcticShadow** [comment]
Thanks for the reply - no worries about any delays. I miss GitHub notifications all the time 😁

And example may have been valuable up front - 

I'm currently holding SHIB on the BSC chain. The coin is a BEP20 token contract address is  `0x2859e4544C4bB03966803b044A93563Bd2D0DD4D` 

I understand it's not feasible to accommodate every token on every chain and if this is not an automatic type process (which your comment suggested it should be for tokens listed on coingecko) , could there be a way for a user to link up a live price tracker? For example, given this token is a peg, I would be happy to link it to the love pricing of the shib token on the Ethereum chain. Just thoughts and ideas.

Thanks for the great app 🙂

**Comment by tmedetbekov** [comment]
@esengulov @arcticShadow I have added that smart contract to the Shiba Inu coin. Since this is a Binance-Peg token, it will display the price shown on CoinGecko for the coin "shiba-inu".

**Comment by arcticShadow** [comment]
That's awesome thanks
