### ISSUE TITLE
Random Numpad

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#6566]

**Comment by abdrasulov** [comment]
Yes, this will be optional

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=76691-97201&mode=design&t=NY0HUddwRm2nFR09-11

**Comment by TalgatNurdinov** [comment]
> Do you have any other function in mind that we can make the numpad do without typing anything? For example, showing the balance of a wallet chosen at our leisure. Or do we pollute the design too much?
> 
> Masterpiece @TalgatNurdinov

Yes, I think it's unnecessary, we block the app also so that no one can see the balance, not only manage them. It will be more convenient to keep track of the balance on widgets

**Comment by TalgatNurdinov** [comment]
Hide random numpad option on password setting pages
