### ISSUE TITLE
Sometimes coins images aren't properly loaded

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6610]
And it needs to re-launch the app in order to load them again. (UW 0.34.1)

I don't know if it is a bug or internet connection fault.

![1000040572](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/a262252e-deba-4fc2-b11d-893d92a1bc0c)

**Comment by rafaelekol** [comment]
Is it happening when Tor is active. Can you find cases when its easily reproducible.
