### ISSUE TITLE
Post Quantum Secure Technologies proposal

### ISSUE THREAD

**Issue by d4f5409d** [horizontalsystems/unstoppable-wallet-android#6621]
Here is the issue to track post quantum secure technologies to implement them later in Unstoppable Wallet.

**Comment by d4f5409d** [comment]
> To encrypt what?

Private keys, and wallet db, plus privacy coins

**Comment by esengulov** [comment]
we would love to postpone this for the time being:)

**Comment by d4f5409d** [comment]
> we would love to postpone this for the time being:)

I opened to issue to be able to track progress, we don't need to close this, as this is only a proposal. It's fine if you postpone it but don't close it

**Comment by esengulov** [comment]
The benefit of having it in discussions is that other viewers can upvote it.
