### ISSUE TITLE
TON integration

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6628]

**Comment by d4f5409d** [comment]
🤞

**Comment by d4f5409d** [comment]
> TON is not my priority, but there are also the needs of others. In my opinion the implementation of blockchain like Cardano (ADA), Stellar (XLM) and Algorand (ALGO) can give this app the right boost. Because these are full ecosystems.
> 
> All the new coins are welcome. I have some friends who use Telegram and TON will do for them.

And don't forget DigiByte
