### ISSUE TITLE
huge size for Zcash  cash

### ISSUE THREAD

**Issue by gades** [horizontalsystems/unstoppable-wallet-android#6640]
Is option to decrease Zcash cash database ?

<img width="772" alt="Screenshot 2023-09-25 at 20 14 23" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/4200730/5e8eaa4e-490e-444b-900a-41649c61766f">

**Comment by gades** [comment]
Can you add function for use API / blockchain like for LTC / BTC / DASH ?

**Comment by abdrasulov** [comment]
We use their official SDK. And that SDK requires that data to work correctly.
