### ISSUE TITLE
0.35 UW crashes all the time if you try to tap on blockchain settings during send action on BNB SC coin

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6645]
![1000041878](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/414ac07f-d3c2-4a39-a9c5-fe8701b9b740)

**Comment by Dianaaiym** [comment]
> ![1000041878](https://user-images.githubusercontent.com/113377431/270716394-414ac07f-d3c2-4a39-a9c5-fe8701b9b740.jpg)

We have already resolved this issue, and the update 0.35.1 is now available on the Play Store.

**Comment by Dianaaiym** [comment]
> I am in f-droid side, so i will wait it. Ok thank you.

We have also uploaded the APK of the new hotfix version to GitHub. Soon, F-Droid will update it on their side.
