### ISSUE TITLE
Big difference in package weight among f-droid and github versions: what happens?

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6650]
Github 0.35.1      73.9 mb
Fdroid 0.35         108.3 mb
Fdroid 0.34.1       73.8 mb

What cause this big difference?

![1000041888](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/d25ed5e9-5219-4aee-b173-bcb57d3596d6)

![1000041890](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/514f1a67-6146-4340-9db4-a14c1f5a0ee9)

**Comment by rafaelekol** [comment]
The new version 0.35.0 was bigger because we used a newer gradle version. In the fix 35.1, we put TorKit classes inside the app and removed TorKit. 
I tried to build the app with and without TorKit. TorKit made the app ~33mb bigger.
