### ISSUE TITLE
io.horizontalsystems.bitcoincore.network.peer.PeerGroup$Error: peers not

### ISSUE THREAD

**Issue by JJ-98** [horizontalsystems/unstoppable-wallet-android#6656]
Dear Community,

i am currently having a big problem with the unstoppable wallet on my phone. I cannot send any funds from it because i am always getting the issue "io.horizontalsystems.bitcoincore.network.peer.PeerGroup$Error: peers not".

I updated the wallet yesterday, so should be the newest version. Please tell me how i can fix it.

Thank you very much!

**Comment by Dianaaiym** [comment]
> Dear Community,
> 
> i am currently having a big problem with the unstoppable wallet on my phone. I cannot send any funds from it because i am always getting the issue "io.horizontalsystems.bitcoincore.network.peer.PeerGroup$Error: peers not".
> 
> I updated the wallet yesterday, so should be the newest version. Please tell me how i can fix it.
> 
> Thank you very much!

Hi,

Please send your App Status (Settings - About App) to support.unstoppable@protonmail.com
