### ISSUE TITLE
[D] [E] Really I don't need of this

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6662]
I ask for an option to hide/disable the top bar and earn space to host an other coin cell (without the need to start the inertial scrolling).

Not urgent. Just to tell you. Future development. I never used it.

![1000041935](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/5883ae4a-c92f-4d44-953b-91ca642c1a29)

**Comment by d4f5409d** [comment]
I use it sometimes, but IMO, it'd be better to have that at the bottom considering how big screens there are nowadays and it can be a pain to touch that up there

**Comment by d4f5409d** [comment]
Yeah, I agree that quick send receive menu is worthless because you either way has to choose the currency and that is 2 taps instead of one which we already could do previously.
