### ISSUE TITLE
[Updated] StealthEX doesn't recognize my FTM address

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6663]
I tried also with another one. Same result.

![1000041938](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/07337703-98d7-4654-995b-9529d9f3d4ce)

**Comment by d4f5409d** [comment]
Isn't it because your wallet is protected by passphrase, or your seed is 24 words?

**Comment by abdrasulov** [comment]
> [UPDATE] I managed to successfully complete an exchange a few minutes ago. Problem reentered by itself. What happened I don’t know.

Good. Most likely there was an issue on their side.

**Comment by abdrasulov** [comment]
> > > [UPDATE] I managed to successfully complete an exchange a few minutes ago. Problem reentered by itself. What happened I don’t know.
> > 
> > 
> > Good. Most likely there was an issue on their side.
> 
> Two exchanges have had the same problem in the same period? Very strange but all it run properly now. UW side seems not affected by issues. So probably it has been their side.

That is really strange :)
