### ISSUE TITLE
UI minor fixes

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6665]
- [x] WalletConnect - Backup Required: Replace text and buttons at the bottom.
>Create a backup copy of the recovery phrase and the associated password that will allow you to recover your wallet if your phone is lost, stolen, broken, etc.
>>Manual Backup
>> Backup to iCloud
>>Later

**Comment by d4f5409d** [comment]
It'd be better to not let force the user to write down the seed phrase, instead rely on encrypted backups.
