### ISSUE TITLE
[Environment] Statistics over CO2 and energy footprints: how many resources do I consume in a year?

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6668]
It would be interesting to include within UW a resource counter, broken down by subject: CO2 and electrical energy.

Some platforms (blockchains) release their environmental footprint in the technical specifications page.

In the case of Fantom (FTM) a transaction (incoming or outgoing) produces an energy expenditure of 30 milliwatt hour.

If we build an energy meter within UW we can know with certainty how much we consume in a certain period. And maybe later decide to plant a tree somewhere in the world for carbon neutrality. Or put back into the grid the equivalent of what is spent on energy with a cleaned one.

It’s just an idea. For fans of statistics and environment.

![1000041961](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/32a4d47c-0fb5-4382-9850-add37062bfa7)

![1000041959](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/80a29a74-1103-4d30-8401-67ab4caaf1ff)

**Comment by d4f5409d** [comment]
Considering many want a private wallet, this could mean exposing financial data to other unwanted third parties. What could be done, is to include an offline, local library to make an estimatef measure, but it wouldn't be accurate.
