### ISSUE TITLE
Consider implementing watch wallets by BTC and BCH addresses

### ISSUE THREAD

**Issue by d4f5409d** [horizontalsystems/unstoppable-wallet-android#6670]
It'd be convenient to see all of the transactions without doing anything else, since these are already public and can be viewed for example on Blockchain.com

**Comment by omurovch** [comment]
You can watch xPubKey. See "Manage Wallets" > "Watch Wallet" > select "By Account xPubKey". 
Or maybe you mean watching single BTC address?

**Comment by d4f5409d** [comment]
> You can watch xPubKey. See "Manage Wallets" > "Watch Wallet" > select "By Account xPubKey". 
> Or maybe you mean watching single BTC address?

Yeah, I mean, we don't get providee by xPubKeys by default so it would be useful to watch single addresses

**Comment by omurovch** [comment]
Hi @d4f5409d,
Watching BTC and BTC-like (BCH, LTC, DASH and XEC) addresses will be available in 0.37 version in few days. Stay tuned!

> Yeah, I mean, we don't get provided by xPubKeys by default so it would be useful to watch single addresses

**Comment by d4f5409d** [comment]
Thank you very much I love you guys
