### ISSUE TITLE
Passcode improvements

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6678]
- [x] Remove current passcode matching сheck. 
Currently, when a user attempts to change their passcode to one that matches their current passcode, the application provides feedback indicating that they are already using such a passcode. This check is unnecessary and can be confusing to users.

- [x] Display the error when entering an incorrect passcode confirmation below the passcode field 

<img width="238" alt="Screenshot 2023-10-04 at 12 50 45" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/1b324c73-db76-4e2b-9352-6ab2d55a6857">

- [x] When setting up a passcode/duress passcode, if the entered password is already being used as the standard passcode of the app or as another duress passcode, display an error indicating that the entered password is already in use.

>This passcode is already being used

**Comment by beastmode846** [comment]
right on thank you its awesome

**Comment by beastmode846** [comment]
alright wjats
 next

**Comment by beastmode846** [comment]
Thanks man
