### ISSUE TITLE
Telegram support unstoppable wallet deleted my message 

### ISSUE THREAD

**Issue by Esmail0karimi** [horizontalsystems/unstoppable-wallet-android#6687]
Why deleted my messages without solving my issue ?? 
I think about the team can understand my issue and can't able to solve my issue 
Please explain it because a lot of people want to trust your app for their investment with this issue you can't pass the exam

**Comment by Dianaaiym** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6634
