### ISSUE TITLE
Can we trust unstoppable wallet app for our investment???

### ISSUE THREAD

**Issue by Esmail0karimi** [horizontalsystems/unstoppable-wallet-android#6688]
The team without solve my problem close my issue on the other hands the customer support in telegram can't solve my problem and deleted my messages in Twitter customer support don't answer 
By the way by slandering me they want to escape of their app issue and don't solve my issue

**Comment by Dianaaiym** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6634
