### ISSUE TITLE
Why the team can't solve my issue and close it without solve my issue 

### ISSUE THREAD

**Issue by Esmail0karimi** [horizontalsystems/unstoppable-wallet-android#6694]
Hi @esen 
Hi @tmedetbekov 
Hi @ealymbaev 
Hi @tkterris 
Hi @rafaelekol 
Hi @gmale 
Hi @junzhli 
Hi @abdrasulov 
Hi @uber9 
Hi @esengulov 
Hi @omurovch 
Hi @nk-the-crazy 
Hi @Dianaaiym 
Hi @horsys 
Hi @Irvise 

first of all you deleted my messages in telegram after I opened issue in GitHub you answered me miscellaneous question
By the way I have backup file that proof me I created unstoppable wallet and I have back up I will published a part of detail my backup to proof myself
![IMG_20231004_125205.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/91189643/3ff59639-3db0-4458-ac14-8a03ba94393d)

![IMG_20231004_125143.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/91189643/9c2806b4-d9c0-43bf-b19e-4513d5ca5ab0)

#6554
#6666
#6623
#6634
#6669
#6685
#6687
#6689
#6686
#6688
#6689
#6687
#6690

I trusted your application and investment my ethereum on your app now I need solve my issue 
Unfortunately you care damn your customer and their investment and money

**Comment by rafaelekol** [comment]
Up to this point you didn't provide solid arguments that will show you as the owner of this wallet.
The only way to get error that you got during Send; is by trying to send money from Watch Account. And that means you don't have private key that allows you to control this address. 
Our wallet provides multiple ways to secure your money. But when you don't posses your seed. we can't help you.

**Comment by Esmail0karimi** [comment]
> Up to this point you didn't provide solid arguments that will show you as the owner of this wallet.
> The only way to get error that you got during Send; is by trying to send money from Watch Account. And that means you don't have private key that allows you to control this address. 
> Our wallet provides multiple ways to secure your money. But when you don't posses your seed. we can't help you.
> 

Ok ...how can I proof that this wallet is my wallet ?? I have backup file and password

I get back up file and when tried to give backup I think your app had technical issue that give me not complete backup file and now I find out ciphertext in my backup file is small than standard ciphertext
As you know ciphertext is encrypted Private key when I restored my wallet by backup file I see my private key as 00 and can't see my manual backup but there is local backup 
By the way I as customer I didn't about it your app give me a destroyed backup file 
Now you as developer team of unstoppable wallet have to find a way to solve this issue because I trusted to your app and investment my funds

**Comment by Esmail0karimi** [comment]
> Perfect customer for bank. No seed? The sunflower oil can mitigate the problem 🤣

Please be silent chatterbox this is non of your business pumpkin
