### ISSUE TITLE
Add Hedera Hashgraph (HBAR)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6707]
https://hedera.com/

ISO 20022 compliant.

![1000104289](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/e9bb4bab-5982-4f52-968a-363d004f9a31)

**Comment by Dianaaiym** [comment]
At the moment, we don't have plans to support this coin. Thank you for your understanding!
