### ISSUE TITLE
Solana tokens transactions history records not synchronising

### ISSUE THREAD

**Issue by Andreisbb** [horizontalsystems/unstoppable-wallet-android#6711]
Synchronization status just spin around in transactions about for 2 days

**Comment by Andreisbb** [comment]
All transactions since 7 Oct still not synchronized

**Comment by Andreisbb** [comment]
Still not possible to sync transactions after 0.36 update

**Comment by rafaelekol** [comment]
Som methods from Public Solscan.io API that we are using became unavailable. We will try to upgrade to their Pro Api.

**Comment by abdrasulov** [comment]
Closing for now. We'll get back to it when there is another provider
