### ISSUE TITLE
Migrate to new 1inch API

### ISSUE THREAD

**Issue by nipharry** [horizontalsystems/unstoppable-wallet-android#6758]
`Unable to resolve host "api-unstoppable.1inch.io": No address associated with hostname`

Uniswap works fine.

**Comment by Dianaaiym** [comment]
> `Unable to resolve host "api-unstoppable.1inch.io": No address associated with hostname`
> 
> Uniswap works fine.

Hi,
We are already working on it.

**Comment by esengulov** [comment]
implemented in https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6758
