### ISSUE TITLE
Might you skip this dialogue and go straight to the numpad?

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6760]
Switching from one mode to another will become incredibly faster: that control does not lead to any irreversible consequence so a dialogue there is not necessary in my opinion.

It could also adding a button instead of a switch, as you did for the "random" button in the numpad screen.

Fast, practical, essential.

![1000093078](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/3b1a1c68-5a3f-4e85-bfe0-f8005e7bfa64)

![1000092934](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/59162ddb-d9d2-4085-ae4d-cef638c8d491)

**Comment by esengulov** [comment]
> Pressing the SEND button has irreversible consequences when one performs a transaction, yet no control dialogue has been put in place. Instead, to turn on/off the Tor network one has to wait for the outcome of the dialogue.
> 
> I find the reasoning wrong in principle. Only irreversible actions need additional control. In my humble opinion.
> 
> Just it needs of a snackbar in the bottom of the screen to notifying the switching like "Tor is disabled" or "Tor is going to initializate".
> 
> This should not be seen as a criticism but as an invitation to enhance and speed up the user experience.

Good point, but in this case the dialogue is there to alert person about the fact that the app needs to be restarted for that action to kick in.
