### ISSUE TITLE
Are unstoppable wallet private keys And seed words random enough?

### ISSUE THREAD

**Issue by Coskunkolay** [horizontalsystems/unstoppable-wallet-android#6770]
Hi, I am a bit curious about how creating private keys And seed words. I know the private key And seed words space is comparable to the number of atoms in the universe. But my doubt is whether  are creating the private key And seed words in a pure random way. As we already know in reality there is nothing is random so in computer science also there is no pure random algorithm. But when comparing computer algorithms real world unpredictable values such as air pressure decimals, temperature decimals, i would say real world randoms are more random. So how  are creating random values? I am certain they are using some cpu ticks and creating this random values inside the wallet. You guys have any thoughts on it? Should we worry about it? Or is it somwthing already random enoughm?

I have been using your unstoppable wallet with pleasure for 2 years.

**Comment by rafaelekol** [comment]
We use the Java [SecureRandom](https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html) class to generate new private keys, and we have found this method to be well-suited to our needs.
