### ISSUE TITLE
Numpad random mode: it doesn't remember my last choice made

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6781]
It would be useful if UW remembered my last mode selected.

So every time I need to typing a pin I haven't to push the button again (if this is my daily habit).

**Comment by esengulov** [comment]
> It would be useful if UW remembered my last mode selected.
> 
> So every time I need to typing a pin I haven't to push the button again (if this is my daily habit).

@kansalt @TalgatNurdinov thoughts?. I agree with @serrq
