### ISSUE TITLE
[0.36] UW doesn't start with the last wallet previously used

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6782]
Every time I select Mars, after rebooting, UW starts always with Pluto. Why?

Pluto and Mars are wallet names.

**Comment by Dianaaiym** [comment]
> Maybe it is a bug because I set Pluto as duress mode associated wallet. Could it be connected to the problem I mention?

Yes, the issue you're experiencing is likely related to the duress mode ref #6784
