### ISSUE TITLE
Duress mode doesn't allow to change associated wallets after set the pin

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6784]
Please adding a way to manage "duress" wallets after that one has set a duress pin.

Currently if I change my mind about which wallets I selected, there is no way to change the associated wallets.
To solve this I have to delete the duress pin and then beginning the procedure again.

Not urgent. Improvement.

![1000094419](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/4da75c8c-ab1b-400a-8c92-11975fd03401)

**Comment by ealymbaev** [comment]
Actually this was made intentionally in order to avoid complications. Duress Mode itself is quite difficult to understand and providing interface for managing wallets would make it even more difficult.
