### ISSUE TITLE
Add support for all events supported by WalletConnect

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6785]

**Comment by rafaelekol** [comment]
https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1228
This bug is blocking upgrade of WalletConnect to latest versions

**Comment by kineita** [comment]
Hi @Dianaaiym and @rafaelekol, can we add this bug to 0.37 again ? Due to this bug, I cannot interact to any smart contracts. If you need any support in Android dev, please ping me. 
Thank you so much

**Comment by Dianaaiym** [comment]
ref #6911
