### ISSUE TITLE
Coinpage-Markets: Prioritize the display of whitelisted exchanges

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6803]
When a user navigates to the 'Coin Page - Markets' section, the following should occur:

- The list of exchanges is first populated with those that are whitelisted.
- Whitelisted exchanges are clearly marked for easy identification.
- After the list of whitelisted exchanges, the remaining exchanges should be listed.
- [Optional] Provide a toggle option for users to switch between 'All exchanges' and 'Whitelisted only'.
@TalgatNurdinov @kansalt

**Comment by TalgatNurdinov** [comment]
Decided to just display the "verified" badges

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=79619-68894&mode=design&t=cmPELUzxeBLRJqI1-11
