### ISSUE TITLE
"Receive" page improvements

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6810]
![2023-11-07 15 56 42](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/4bfdaa19-a21c-46f2-81a0-3978874bdfd0)

- [ ] Remove of Alert Text
- [ ] Implement a one-click copy-to-clipboard functionality for the address.

**Comment by TalgatNurdinov** [comment]
New design with set amount
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=80808-45694&mode=design&t=OPWX9zSTb1hXCWEm-11
