### ISSUE TITLE
Add three options for synchronizing BTC, BCH, and LTC wallets

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6815]
- API 
- Hybrid (API + Blockchain)
- Blockchain

<img width="299" alt="Screenshot 2023-11-09 at 11 43 15" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/9d1bbc53-9683-4f52-9a03-09b6294d60ad">

**Comment by kansalt** [comment]
[967225](https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=80075-193402&mode=design&t=VDVmzDPj32Y4X830-4)

**Comment by Dianaaiym** [comment]
ref #6553
