### ISSUE TITLE
HOTP as auxiliary access

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6816]
Different to what happens for the TOTP system, HOTP does not need to be connected to the internet and to synchronize with a remote server.

HOTP has a secret code that acts as a seed: through an algorithm this seed generates disposable pins.

UW will simply wait for the user types the valid pin for that step (the step counter isn't shown in UW to avoid correlation problem).

It does't need for any remote synchronization. Completely offline. All happen locally.

Since pin steps are progressive, this method – complementary to the traditional pin system that we already are using – would allow us to leave home with a list of disposable pins to use even in conditions where privacy is not guaranteed.

The user will be able to switch among the two pin systems easily through a toggle placed in UW's numpad.

![1000097197](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/4aa85fde-a716-48f7-9780-b255788d63c6)

![1000097202](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/ff904219-500e-49ab-8408-1e275697beee)

![1000097204](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/92abd345-bff7-486d-91e7-ab931f755158)

![1000097208](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/cb8ad178-96f0-4297-a71f-d9d2a41217dd)

**Comment by Andreisbb** [comment]
Why do you need HOTP if you are server ? If attacker has access to your device they can hack it without problem.

**Comment by Andreisbb** [comment]
It's no difference where client is (on smart watch or another device) if attacker has access to phone with unstoppable app (server), there's no need to hack client.
