### ISSUE TITLE
Shows the corresponding balance in each wallet's field in "switch wallet" tab (optional)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6818]
This is particularly useful when a user has many wallets and it wants having a quick and overall sight of all its balances (shown in base currency).

If the current balance is hidden, dots are shown in place of the balances' value.

This idea can be improved by developers and community users.

Wallet name limit: 10 characters

![1000097211](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/364df113-4623-4e68-8177-131e2d8e22ed)

**Comment by abdrasulov** [comment]
Good point. But as of now, there is no solution. To fetch the wallet balance it should be activated. Keeping all wallets active is resource-intensive.
