### ISSUE TITLE
Is it possible to add support for ThorChain and Maya

### ISSUE THREAD

**Issue by eloyesp** [horizontalsystems/unstoppable-wallet-android#6819]
[THORChain][] is a distributed swap service (like FixedFloat, but using a distributed protocol), [MayaProtocol][] is a fork of that adds supports for other assets. Each one has a blockchain with a native token: Rune and Cacao.

Sadly, as far as I could find, there is not a single open source wallet that have support for those protocols. It would be great to have support for this on unstoppable, as it already have support for most of the blockchains that those protocols support.

The implementation requires two different steps, on one hand query for the liquidity pool addresses and rate and the other is adding support for the memo field.

My main use case for this function is the following one: I have DASH and I require to pay an invoice on USDT as a BEP20, I need to scan the receiving address, and select an amount, then the wallet should:

1. [Query for a quote](https://mayanode.mayachain.info/mayachain/quote/swap?from_asset=DASH.DASH&to_asset=ARB.USDC&amount=500000000&destination=0x86d526d6624AbC0178cF7296cD538Ecc080A95F1) for the payment.
2. Send a dash payment with a Memo (that is in this case an OP_RETURN text value) to that address.

A secondary use case, would be adding liquidity to the pool, that requires sending to the pool address with a special memo and the same thing to withdraw from the pool but (re-)using the same sending address, that case is much harder to implement (as it requires coin control), but it is clearly a secondary use case.

Regards.

[THORChain]: https://thorchain.org/
[MayaProtocol]: https://mayaprotocol.com/

**Comment by eloyesp** [comment]
#7227 seems related, would be nice to have some feedback here :smile:

**Comment by Dianaaiym** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7230
