### ISSUE TITLE
Coins' icons not shown

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6826]
OnePlus CPH2399
Android 13
UW 0.36
Tor ON
VPN ON

![1000097345](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/1b110968-7afa-4bd6-b2a6-3f3695d33d6b)

![1000097343](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/bad4377b-1b5b-45d5-bdbb-2660a79b66ce)

**Comment by omurovch** [comment]
Icons can be loaded due to enabled TOR. The thing is, icons are loaded from CDN server which is protected by CloudFlare.

**Comment by omurovch** [comment]
Yes, this is one of the options. But there is no simple/quick solution for now. We are aiming decide with TOR in the upcoming releases.

> Cannot we downloading simply an icons pack? (and storing it locally offline)
> 
> New icons? New icons.zip. UW team could put it between released files in Github repo (in each release updated).

**Comment by rafaelekol** [comment]
Since we could not find a good solution for this issue, we decided to close it.
