### ISSUE TITLE
Sync Error on Ethereum and ERC-20 Tokens

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6838]
An issue with synchronization occurs when using the wallet on the Ethereum network and ERC-20 tokens. The reproduction process is not consistent, but there are assumptions about two possible scenarios:

- A sync error occurs when attempting to restore the wallet.
- If the application remains open for some time, it can also lead to a sync error.

**Comment by gabriel-tandil** [comment]
I think this is happening to me. It does not complete the synchronisation of ethernum or tether at any time.
Is there an alternative way?
If you need any additional information or testing, please let me know.
Thanks
Gabriel

**Comment by Dianaaiym** [comment]
> I think this is happening to me. It does not complete the synchronisation of ethernum or tether at any time. Is there an alternative way? If you need any additional information or testing, please let me know. Thanks Gabriel

Hi,

Most likely, the issue you are currently facing is unrelated to this bug. Please attempt to resolve it by changing the RPC provider. Go to Blockchain Settings, select Ethereum, and switch to Infura HTTPS.

![2023-11-29 12 00 50](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/572f570e-651c-4729-af04-a9f1157afe96)
![2023-11-29 12 00 55](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/00447e3c-f1f1-426b-8447-2c1dcc766947)
![2023-11-29 12 00 57](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/93f8b5a4-5cd3-4ad5-966a-60d60b70439a)

**Comment by gabriel-tandil** [comment]
Hello @Dianaaiym!
Thank you for your response.
The error fixed itself before I could try your suggestion.
Anyway I tried changing what you indicated and it continues to work correctly.
Best regards
Gabriel

**Comment by Dianaaiym** [comment]
not reproduced, perhaps this was due to the instability of the WebSocket
