### ISSUE TITLE
Wallets' manager: show/unshow a wallet in wallets' list

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6846]
Currently I have 8 wallets.
I plan to add other eight in next future.

16 wallets are too much to show them in wallets' list, so I ask basically an archive feature to show only wallets that currently I am using while preserve the other ones for other purposes.

This is not a security feature: it is just a way to make order between wallets.

![1000098702](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/7877e969-daf4-476b-ac65-e6222183c70a)

**Comment by ealymbaev** [comment]
What if we simply sort them by "recently used" order?
