### ISSUE TITLE
Math problem when sending BLAST token

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6848]
By its contract (BSC chain) every BLAST sent transaction include 10% in fees.

If I send 110 000 BLAST, then arrives 99 000 to recipient, by protocol design.

Of these 10%, 5% goes locked to PancakeSwap and the remain 5% is distributed between all BNB wallets in the network.

Problem is: I want sending to my recipient exactly 100 000 blast, how much I must pay to send exactly that amount?

Because:

100 000 - 10% = 90 000 
110 000 - 10% = 99 000

I’m going crazy with calculations. Please make my life easier.

**Comment by Andreisbb** [comment]
111 111.11 blast

**Comment by Andreisbb** [comment]
100 000 / 0.9
