### ISSUE TITLE
recovery usdt wallet problem

### ISSUE THREAD

**Issue by gabriel-tandil** [horizontalsystems/unstoppable-wallet-android#6857]
Hi!
I haev a question...
When I want to restore a wallet with the 12 recovery words, I don't get the option to choose the USDT currency.

Thanks
Gabriel

**Comment by gabriel-tandil** [comment]
is this 
![imagen](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/903359/6496c67f-aa18-400e-9d1f-49bf313209b0)
I think it's in ethernum

**Comment by gabriel-tandil** [comment]
If I delete the wallet and then restore it with the twelve recovery words, I choose several blockchains but it does not appear.
Maybe I'm missing a step, I don't know why it doesn't appear.
![imagen](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/903359/ae445342-673b-497a-9fcf-c9896bccfddb)

**Comment by omurovch** [comment]
@gabriel-tandil

Yes, tokens with zero balance are not shown after the import. But you can add in Coin Manager:
1) Open Coin Manager screen
2) Press search button
3) Enter name or code of the token you want to add

![photo_2023-12-05 17 19 45](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/10570497/1bd7c477-3659-4578-96d1-b06ed67dfa4e)

![photo_2023-12-05 17 19 48](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/10570497/1a0f1664-e0b3-4bed-8ac7-39128e3f59f8)

![photo_2023-12-05 17 19 49](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/10570497/be47ce04-ee89-41b9-963c-a665c039f7d6)


> Is it possible that it does not show after the import because it has a zero balance? It occurs to me that this could be the case but I don't know. If so it's confusing as the app shows me that currency when I create the wallet but if I delete it and restore it it doesn't show it anymore.
> 
> I tried as @Andreisbb suggested with Trust wallet and although it didn't show it at first it did let me add it (Unstoppable doesn't let me add it later either).

**Comment by gabriel-tandil** [comment]
Well thank you for your clarification.
It could be a possible improvement to show after the import the currencies that have zero if they are shown when creating an empty wallet, to make it more consistent for the user.

**Comment by omurovch** [comment]
> Well thank you for your clarification. It could be a possible improvement to show after the import the currencies that have zero if they are shown when creating an empty wallet, to make it more consistent for the user.

We will consider your recommendation. Closing the issue for now.
