### ISSUE TITLE
I always cannot complete the swap on DEXs due an error

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6859]
Pancake (UW)

![1000099979](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/3db240c0-5b09-41b7-8b87-280bf9011c1f)

1inch (another wallet, not UW)

![1000099982](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/9d4586c9-c15a-4a4f-8f8e-6040e12146a4)

**Comment by omurovch** [comment]
The issue was due to enabled TOR, it seems that swap APIs block requests from TOR nodes.

> This issue can be solved implementing the 1inch V5 API in UW. It works properly in its website.
> 
> ![1000100081](https://private-user-images.githubusercontent.com/113377431/288036348-b3c7a222-531b-4493-b938-800e1ebf42b8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDM3NjYsIm5iZiI6MTcwMTg0MzQ2NiwicGF0aCI6Ii8xMTMzNzc0MzEvMjg4MDM2MzQ4LWIzYzdhMjIyLTUzMWItNDQ5My1iOTM4LTgwMGUxZWJmNDJiOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwNjE3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTBjZTFiODAyNzdmMTYwMzMyZDJlNTU1MjRhNThmNThmOWJjMGU3OTg1MzZkZjYxNjZjZjI4ZGVlMDRhZGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cMT9DeRpve6TcnUf3e3IY7_zeICEZuJ2dT-q7hojXMU)

**Comment by Dianaaiym** [comment]
> Got it. Are you interested in implementing 1inch V5 within UW? I find it is a good improvement.

We have already updated 1inch to v5  https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5542
