### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#6867]
- [x] receive screen: let's remove the 'Send only...' note at the top. I believe it sever little purpose.
- [x] Blockchain Settings >> BTC and fork chains: change the wordsing in the menu as shown below
-- Blockchair API: Fast, Not Private 
-- Hybrid: Slow, Not Private
-- Bitcoin Blockchain: Slow, Private

**Comment by Dianaaiym** [comment]
Already done in version 0.37
