### ISSUE TITLE
Error when sending solana and solana tokens

### ISSUE THREAD

**Issue by Andreisbb** [horizontalsystems/unstoppable-wallet-android#6868]
Hello, I have got a error when tried to send solana.
RPC response error -32002 Transaction simulation failed: Blockhash not found.

![IMG_20231202_162524](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/139232118/b63273a0-0857-42fb-8b8f-f98a32876aee)

**Comment by omurovch** [comment]
@Andreisbb 
Is TOR enabled? How often does this error occur?

**Comment by Dianaaiym** [comment]
> Hello, I have got a error when tried to send solana. RPC response error -32002 Transaction simulation failed: Blockhash not found.
> 
> ![IMG_20231202_162524](https://private-user-images.githubusercontent.com/139232118/287453222-b63273a0-0857-42fb-8b8f-f98a32876aee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzkwMjUsIm5iZiI6MTcwMzgzODcyNSwicGF0aCI6Ii8xMzkyMzIxMTgvMjg3NDUzMjIyLWI2MzI3M2EwLTA4NTctNDJmYi04YjhmLWY5OGEzMjg3NmFlZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQwODMyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDUyZjYxYjIxZGMwYzNiM2VjMTQyMjg1NmM0MzUzZmVmNjZiYmI0OWMwNWZiMTM3ZDZlMGViYjhkMDAzNzA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1kDje5D33_cTWks3Fy2CZismEx0i82wezAsubWJTYzI)

Please send your App Status (Settings - About App) to support.unstoppable@protonmail.com
