### ISSUE TITLE
Research Liquid chain integration

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6893]
https://blockstream.com/liquid/

**Comment by abdrasulov** [comment]
The liquid chain https://blockstream.com/liquid/ provides SDK for both Android and iOS. As an example of usage, there is a green wallet app. This app is open-sourced and also developed for both Android and iOS. That app has the following features:
* Creating/restoring an account with a standard bip44 mnemonic
* Receiving/sending bitcoins and liquid chain assets (for instance L-BTC)
* Transactions history

There is no swap in the app. The blockstream provides https://sideswap.io/ for swaps.

So using their SDK we can implement the same feature list as Blockstream Green Wallet. It may take about 1 mo to implement it on Android. There may be backend tasks as well.
