### ISSUE TITLE
Problems with Tron node for several days

### ISSUE THREAD

**Issue by TheFuzzStone** [horizontalsystems/unstoppable-wallet-android#6909]
It's a very strange bug.

For several days I noticed that Tron node stops working around 23:00 ~ 00:00 (CET). And somewhere around 03:00 ~ 04:00 it starts working normally.

![Screenshot_20231215-235126](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/16173361/2d14315b-0942-4022-8609-2efe1965721b)

![Screenshot_20231215-235135](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/16173361/5effdef8-3e94-46c1-9768-3b9eb85fd31a)

![Screenshot_20231215-235216](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/16173361/18651260-e88e-4c82-87a4-49c9a08caccb)

**Comment by TheFuzzStone** [comment]
Ok, I made sure that the time of this problem can vary, and this problem can be encountered even in the evening (not night).

Please fix this problem as soon as possible. Thank you. :)

**Comment by TheFuzzStone** [comment]
The same problem with version 0.37.

Shit, I reported this problem long before 0.37 was released. It's disappointing that it wasn't fixed in 0.37.

**Comment by Dianaaiym** [comment]
> The same problem with version 0.37.
> 
> Shit, I reported this problem long before 0.37 was released. It's disappointing that it wasn't fixed in 0.37.

Please send your App Status (Settings - About App)

**Comment by Dianaaiym** [comment]
> The same problem with version 0.37.
> 
> Shit, I reported this problem long before 0.37 was released. It's disappointing that it wasn't fixed in 0.37.

Are you using a VPN service?

**Comment by TheFuzzStone** [comment]
> Please send your App Status

Here you go:

![image](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/16173361/b9a79621-e87b-478d-ba36-de831e0be476)

---

> Are you using a VPN service?

No.

---

More info: Today I updated my wallet to 0.37 via F-Droid, and as I write this post - Tron node is not working. And it's really sad because I use Unstoppable Wallet for work...

**Comment by TheFuzzStone** [comment]
And the strangest thing is that the Tron node failure time has changed (maybe changing in real time) since I first reported this problem.
