### ISSUE TITLE
Update WalletConnect SDK

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6911]
https://docs.walletconnect.com/web3modal/about

**Comment by NukeManDan** [comment]
I am trying to connect via a QR here https://tokenproof.xyz/enrollment

While I do get the scanner to recognize the scan, nothing further happens. I am dropped into the page with "you don't have any connected dapps" . I have tried on a different app  https://github.com/keepkey/keepkey-desktop/issues/667#issuecomment-1942163365  with no success. I am able to get to a signing phase on this other app though, where as I get nothing at all with unstoppable.

Will this be resolved one an update to the SDK is made?

**Comment by abdrasulov** [comment]
> I am trying to connect via a QR here https://tokenproof.xyz/enrollment
> 
> While I do get the scanner to recognize the scan, nothing further happens. I am dropped into the page with "you don't have any connected dapps" . I have tried on a different app [keepkey/keepkey-desktop#667 (comment)](https://github.com/keepkey/keepkey-desktop/issues/667#issuecomment-1942163365) with no success. I am able to get to a signing phase on this other app though, where as I get nothing at all with unstoppable.
> 
> Will this be resolved one an update to the SDK is made?

Hello @NukeManDan. We could not reproduce the issue. We successfully get connected with wallet connect to the https://tokenproof.xyz/enrollment. After scanning the QR code the unstoppable app shows the "Connect to DApp" dialog with Connect and Cancel buttons. Please try once again and let us know if the issue persists

**Comment by NukeManDan** [comment]
Indeed, it worked when trying on a different desktop just now :tada: Unclear how I could access logs to see what the error could be via the app. :shrug: 

Sorry for the noise on the OP issue, I do look forward to an update including the newer WC SDK. :grin:

**Comment by NukeManDan** [comment]
Trying to connect to https://devfolio.co `https://siwe.devfolio.co/?nonce=....&domain=api.devfolio.co...`

I get in the browser console `WalletConnect cannot connect. Error: Chains must not be empty` and on the app I must navigate away them back tot he WC page to see an `Unamed ---` pairing, but have no response in browser or on the app to try and connect at all. Again not sure if this is related to the SDK but would _love_ better support for WC overall in this otherwise great wallet app! :pray:

**Comment by rafaelekol** [comment]
@NukeManDan currently we have issues with updating WalletConnect SDK, which we haven't resolved yet.
I also tried to connect to https://devfolio.co/ with Trust wallet  and with demo app from WalletConnect, but both of them didn't connect to devfolio. I guess there is some issues on devfolio side.

**Comment by abdrasulov** [comment]
We could not update to the latest v Bom 1.31.4. 

See https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1409
