### ISSUE TITLE
Add top pairs section on market tab

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6919]

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=82407-122836&mode=design&t=DnuWWeuHpSnksaC9-11

**Comment by abdrasulov** [comment]
Clicking on the section title should open Top Market Pairs page
