### ISSUE TITLE
Litecoin funds are not sent

### ISSUE THREAD

**Issue by ZooMMaX** [horizontalsystems/unstoppable-wallet-android#6925]
Litecoin bip-86 mainnet funds are not sent to any litecoin address.  A transaction is created, waits for some time and is cancelled.

App Info:
		 - Current Time: 22 дек. 2023 г., 15:48
		 - App Version: 0.36.1
		 - Device Model: Xiaomi 21081111RG
		 - OS Version: Android 13 (33)

Version History:
		 - 0.36.1: 21 дек. 2023 г., 17:41

Wallets Status:
		 - Wallet 1:
				 - Origin: Restored
				 - Type: 12 слов

Blockchain Status:
		 - Bitcoin-BIP84:
				 - Synced Until: 22 дек. 2023 г., 15:37
				 - Syncing Peer: 34.83.54.3
				 - Derivation: bip84
				 - Sync State: Synced
				 - Last Block Height: 822389
				 - Peer 1:
						 - Status: Synced
						 - Host: 188.138.112.60
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.13.0/
						 - tasks: no tasks
				 - Peer 2:
						 - Status: Synced
						 - Host: 31.190.57.43
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.18.0/
						 - tasks: no tasks
				 - Peer 3:
						 - Status: Synced
						 - Host: 165.22.237.253
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.20.1/
						 - tasks:
								 - RequestTransactionsTask: [hashesCount: 32; receivedTransactionsCount: 0]
				 - Peer 4:
						 - Status: Synced
						 - Host: 165.22.229.88
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.20.1/
						 - tasks: no tasks
				 - Peer 5:
						 - Status: Synced
						 - Host: 198.199.82.190
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.20.1/
						 - tasks: no tasks
				 - Peer 6:
						 - Status: Not Synced
						 - Host: 34.83.54.3
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.20.1/
						 - tasks:
								 - GetBlockHashesTask: [expectedHashesMinCount: 6; allowedIdleTime: 1000]
				 - Peer 7:
						 - Status: Synced
						 - Host: 172.105.21.216
						 - Best Block: 822389
						 - User Agent: /Satoshi:25.1.0(@devinbileck)/
						 - tasks: no tasks
				 - Peer 8:
						 - Status: Synced
						 - Host: 69.4.94.226
						 - Best Block: 822389
						 - User Agent: /Satoshi:25.0.0/
						 - tasks:
								 - RequestTransactionsTask: [hashesCount: 21; receivedTransactionsCount: 38]

		 - Bitcoin-BIP86:
				 - Synced Until: 22 дек. 2023 г., 15:37
				 - Syncing Peer: 198.154.93.110
				 - Derivation: bip86
				 - Sync State: Synced
				 - Last Block Height: 822389
				 - Peer 1:
						 - Status: Not Synced
						 - Host: 188.214.129.139
						 - Best Block: 822389
						 - User Agent: /Satoshi:25.0.0/
						 - tasks: no tasks
				 - Peer 2:
						 - Status: Synced
						 - Host: 3.126.209.33
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.21.1/
						 - tasks: no tasks
				 - Peer 3:
						 - Status: Not Synced
						 - Host: 109.250.173.89
						 - Best Block: 822389
						 - User Agent: /Satoshi:25.0.0/
						 - tasks: no tasks
				 - Peer 4:
						 - Status: Synced
						 - Host: 95.217.163.234
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.20.1/
						 - tasks: no tasks
				 - Peer 5:
						 - Status: Not Synced
						 - Host: 34.125.88.170
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.21.1/
						 - tasks: no tasks
				 - Peer 6:
						 - Status: Synced
						 - Host: 167.235.9.82
						 - Best Block: 822389
						 - User Agent: /Satoshi:26.0.0/
						 - tasks: no tasks
				 - Peer 7:
						 - Status: Synced
						 - Host: 3.8.101.76
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.21.1/
						 - tasks: no tasks
				 - Peer 8:
						 - Status: Not Synced
						 - Host: 198.154.93.110
						 - Best Block: 822389
						 - User Agent: /Satoshi:25.0.0/
						 - tasks:
								 - GetBlockHashesTask: [expectedHashesMinCount: 6; allowedIdleTime: 1000]
				 - Peer 9:
						 - Status: Synced
						 - Host: 147.135.136.53
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.18.1/
						 - tasks: no tasks
				 - Peer 10:
						 - Status: Synced
						 - Host: 62.158.79.38
						 - Best Block: 822389
						 - User Agent: /Satoshi:25.0.0/
						 - tasks: no tasks

		 - Bitcoin-BIP49:
				 - Synced Until: 22 дек. 2023 г., 15:37
				 - Syncing Peer: 13.211.79.130
				 - Derivation: bip49
				 - Sync State: Synced
				 - Last Block Height: 822389
				 - Peer 1:
						 - Status: Synced
						 - Host: 34.125.190.73
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.21.1/
						 - tasks: no tasks
				 - Peer 2:
						 - Status: Synced
						 - Host: 18.232.83.28
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.21.1/
						 - tasks: no tasks
				 - Peer 3:
						 - Status: Synced
						 - Host: 34.65.142.83
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.20.1/
						 - tasks: no tasks
				 - Peer 4:
						 - Status: Synced
						 - Host: 62.24.76.122
						 - Best Block: 822389
						 - User Agent: /Satoshi:26.0.0(bitcoin-sl)/
						 - tasks: no tasks
				 - Peer 5:
						 - Status: Not Synced
						 - Host: 13.211.79.130
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.21.1/
						 - tasks:
								 - GetBlockHashesTask: [expectedHashesMinCount: 6; allowedIdleTime: 1000]
				 - Peer 6:
						 - Status: Synced
						 - Host: 69.4.94.226
						 - Best Block: 822389
						 - User Agent: /Satoshi:25.0.0/
						 - tasks: no tasks
				 - Peer 7:
						 - Status: Synced
						 - Host: 18.191.177.83
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.21.1/
						 - tasks: no tasks

		 - Bitcoin-BIP44:
				 - Synced Until: 22 дек. 2023 г., 15:37
				 - Syncing Peer: N/A
				 - Derivation: bip44
				 - Sync State: Synced
				 - Last Block Height: 822389
				 - Peer 1:
						 - Status: Synced
						 - Host: 58.96.123.120
						 - Best Block: 822389
						 - User Agent: /Satoshi:23.1.0/
						 - tasks: no tasks
				 - Peer 2:
						 - Status: Synced
						 - Host: 176.9.120.187
						 - Best Block: 822389
						 - User Agent: /Satoshi:25.0.0/
						 - tasks: no tasks
				 - Peer 3:
						 - Status: Synced
						 - Host: 31.190.57.43
						 - Best Block: 822389
						 - User Agent: /Satoshi:0.18.0/
						 - tasks: no tasks
				 - Peer 4:
						 - Status: Synced
						 - Host: 95.217.106.33
						 - Best Block: 822389
						 - User Agent: /Satoshi:24.99.0/
						 - tasks: no tasks
				 - Peer 5:
						 - Status: Synced
						 - Host: 167.235.9.82
						 - Best Block: 822389
						 - User Agent: /Satoshi:26.0.0/
						 - tasks: no tasks
				 - Peer 6:
						 - Status: Synced
						 - Host: 62.158.79.38
						 - Best Block: 822389
						 - User Agent: /Satoshi:25.0.0/
						 - tasks:
								 - RequestTransactionsTask: [hashesCount: 7; receivedTransactionsCount: 0]

		 - Litecoin-BIP86:
				 - Synced Until: 22 дек. 2023 г., 15:47
				 - Syncing Peer: 3.68.34.196
				 - Derivation: bip86
				 - Sync State: Synced
				 - Last Block Height: 2601317
				 - Peer 1:
						 - Status: Synced
						 - Host: 46.4.105.19
						 - Best Block: 2601316
						 - User Agent: /LitecoinCore:0.17.1/
						 - tasks: no tasks
				 - Peer 2:
						 - Status: Not Synced
						 - Host: 64.227.105.219
						 - Best Block: 2601317
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 3:
						 - Status: Synced
						 - Host: 173.212.197.63
						 - Best Block: 2601316
						 - User Agent: /LitecoinCore:0.17.1/
						 - tasks: no tasks
				 - Peer 4:
						 - Status: Not Synced
						 - Host: 3.68.34.196
						 - Best Block: 2601317
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks:
								 - GetBlockHashesTask: [expectedHashesMinCount: 6; allowedIdleTime: 1000]
				 - Peer 5:
						 - Status: Synced
						 - Host: 91.193.181.3
						 - Best Block: 2601317
						 - User Agent: /LitecoinCore:0.16.3/
						 - tasks: no tasks
				 - Peer 6:
						 - Status: Synced
						 - Host: 194.163.136.179
						 - Best Block: 2601317
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 7:
						 - Status: Synced
						 - Host: 65.108.238.59
						 - Best Block: 2601317
						 - User Agent: /LitecoinCore:0.16.3/
						 - tasks: no tasks
				 - Peer 8:
						 - Status: Not Synced
						 - Host: 86.71.47.11
						 - Best Block: 2601317
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks

		 - Litecoin-BIP84:
				 - Synced Until: 22 дек. 2023 г., 15:47
				 - Syncing Peer: 52.15.111.162
				 - Derivation: bip84
				 - Sync State: Synced
				 - Last Block Height: 2601317
				 - Peer 1:
						 - Status: Not Synced
						 - Host: 139.99.210.123
						 - Best Block: 2601317
						 - User Agent: /LitecoinCore:0.16.3/
						 - tasks: no tasks
				 - Peer 2:
						 - Status: Synced
						 - Host: 91.232.105.180
						 - Best Block: 2601317
						 - User Agent: /LitecoinCore:0.16.3/
						 - tasks: no tasks
				 - Peer 3:
						 - Status: Not Synced
						 - Host: 52.15.111.162
						 - Best Block: 2601316
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks:
								 - GetBlockHashesTask: [expectedHashesMinCount: 6; allowedIdleTime: 1000]
				 - Peer 4:
						 - Status: Synced
						 - Host: 37.187.29.107
						 - Best Block: 2601317
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 5:
						 - Status: Synced
						 - Host: 185.25.120.91
						 - Best Block: 2601317
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 6:
						 - Status: Synced
						 - Host: 217.182.200.177
						 - Best Block: 2601317
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 7:
						 - Status: Synced
						 - Host: 52.2.1.167
						 - Best Block: 2601316
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks

App Log:
		 - Send-LTC:b4621719-6199-424d-941b-024107fc78a7:
				 - 1: 2023-12-21 14:51:06.336 click
				 - 2: 2023-12-21 14:51:06.337 call btc-kit.send
				 - 3: 2023-12-21 14:51:06.474 success

		 - Send-LTC:9e505985-5ede-4d75-bbd3-89eb0443c055:
				 - 4: 2023-12-21 21:40:24.306 click
				 - 5: 2023-12-21 21:40:24.312 call btc-kit.send
				 - 6: 2023-12-21 21:40:24.415 success

		 - Send-LTC:64e385e7-7144-4d61-9f79-1713caaabfcd:
				 - 7: 2023-12-22 08:08:05.534 click
				 - 8: 2023-12-22 08:08:05.535 call btc-kit.send
				 - 9: 2023-12-22 08:08:05.648 success

		 - Send-LTC:27402cbb-2549-4d81-abbd-9d8362dd7b6b:
				 - 10: 2023-12-22 08:42:29.530 click
				 - 11: 2023-12-22 08:42:29.530 call btc-kit.send
				 - 12: 2023-12-22 08:42:29.630 success

		 - Send-BTC:8e5e1cf4-7f3d-46c9-bf5c-593fda367ed6:
				 - 13: 2023-12-22 09:05:28.168 click
				 - 14: 2023-12-22 09:05:28.171 call btc-kit.send
				 - 15: 2023-12-22 09:05:28.207 success

		 - Send-LTC:2251f2cd-8600-4583-b6cd-63a730dcaf85:
				 - 16: 2023-12-22 09:08:15.084 click
				 - 17: 2023-12-22 09:08:15.087 call btc-kit.send
				 - 18: 2023-12-22 09:08:15.175 success

Market Last Sync Timestamps:
		 - Coins: 1700826946
		 - Blockchains: 1700116376
		 - Tokens: 1701324916

**Comment by ZooMMaX** [comment]
Spends from bech32m to bech32m and bech32 failed.  However, I was able to spend funds on the P2SH address.

**Comment by abdrasulov** [comment]
Some peers don't support bip86. That is why there may be issues with bip86.

**Comment by ZooMMaX** [comment]
I'll try it when I have LTC.  Happy New Year!

**Comment by ZooMMaX** [comment]
Проверил. Не работает, как и прежде. Версия приложения - 0.37.1

**Comment by abdrasulov** [comment]
We tried to reproduce the issue several times. The sending Litecoin bip-86 works fine.

**Comment by Dianaaiym** [comment]
> Litecoin bip-86 mainnet funds are not sent to any litecoin address. A transaction is created, waits for some time and is cancelled.
> 
> App Info: - Current Time: 22 дек. 2023 г., 15:48 - App Version: 0.36.1 - Device Model: Xiaomi 21081111RG - OS Version: Android 13 (33)
> 
> Version History: - 0.36.1: 21 дек. 2023 г., 17:41
> 
> Wallets Status: - Wallet 1: - Origin: Restored - Type: 12 слов
> 
> Blockchain Status: - Bitcoin-BIP84: - Synced Until: 22 дек. 2023 г., 15:37 - Syncing Peer: 34.83.54.3 - Derivation: bip84 - Sync State: Synced - Last Block Height: 822389 - Peer 1: - Status: Synced - Host: 188.138.112.60 - Best Block: 822389 - User Agent: /Satoshi:0.13.0/ - tasks: no tasks - Peer 2: - Status: Synced - Host: 31.190.57.43 - Best Block: 822389 - User Agent: /Satoshi:0.18.0/ - tasks: no tasks - Peer 3: - Status: Synced - Host: 165.22.237.253 - Best Block: 822389 - User Agent: /Satoshi:0.20.1/ - tasks: - RequestTransactionsTask: [hashesCount: 32; receivedTransactionsCount: 0] - Peer 4: - Status: Synced - Host: 165.22.229.88 - Best Block: 822389 - User Agent: /Satoshi:0.20.1/ - tasks: no tasks - Peer 5: - Status: Synced - Host: 198.199.82.190 - Best Block: 822389 - User Agent: /Satoshi:0.20.1/ - tasks: no tasks - Peer 6: - Status: Not Synced - Host: 34.83.54.3 - Best Block: 822389 - User Agent: /Satoshi:0.20.1/ - tasks: - GetBlockHashesTask: [expectedHashesMinCount: 6; allowedIdleTime: 1000] - Peer 7: - Status: Synced - Host: 172.105.21.216 - Best Block: 822389 - User Agent: /Satoshi:25.1.0(@devinbileck)/ - tasks: no tasks - Peer 8: - Status: Synced - Host: 69.4.94.226 - Best Block: 822389 - User Agent: /Satoshi:25.0.0/ - tasks: - RequestTransactionsTask: [hashesCount: 21; receivedTransactionsCount: 38]
> 
> ```
> 	 - Bitcoin-BIP86:
> 			 - Synced Until: 22 дек. 2023 г., 15:37
> 			 - Syncing Peer: 198.154.93.110
> 			 - Derivation: bip86
> 			 - Sync State: Synced
> 			 - Last Block Height: 822389
> 			 - Peer 1:
> 					 - Status: Not Synced
> 					 - Host: 188.214.129.139
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:25.0.0/
> 					 - tasks: no tasks
> 			 - Peer 2:
> 					 - Status: Synced
> 					 - Host: 3.126.209.33
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:0.21.1/
> 					 - tasks: no tasks
> 			 - Peer 3:
> 					 - Status: Not Synced
> 					 - Host: 109.250.173.89
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:25.0.0/
> 					 - tasks: no tasks
> 			 - Peer 4:
> 					 - Status: Synced
> 					 - Host: 95.217.163.234
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:0.20.1/
> 					 - tasks: no tasks
> 			 - Peer 5:
> 					 - Status: Not Synced
> 					 - Host: 34.125.88.170
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:0.21.1/
> 					 - tasks: no tasks
> 			 - Peer 6:
> 					 - Status: Synced
> 					 - Host: 167.235.9.82
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:26.0.0/
> 					 - tasks: no tasks
> 			 - Peer 7:
> 					 - Status: Synced
> 					 - Host: 3.8.101.76
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:0.21.1/
> 					 - tasks: no tasks
> 			 - Peer 8:
> 					 - Status: Not Synced
> 					 - Host: 198.154.93.110
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:25.0.0/
> 					 - tasks:
> 							 - GetBlockHashesTask: [expectedHashesMinCount: 6; allowedIdleTime: 1000]
> 			 - Peer 9:
> 					 - Status: Synced
> 					 - Host: 147.135.136.53
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:0.18.1/
> 					 - tasks: no tasks
> 			 - Peer 10:
> 					 - Status: Synced
> 					 - Host: 62.158.79.38
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:25.0.0/
> 					 - tasks: no tasks
> 
> 	 - Bitcoin-BIP49:
> 			 - Synced Until: 22 дек. 2023 г., 15:37
> 			 - Syncing Peer: 13.211.79.130
> 			 - Derivation: bip49
> 			 - Sync State: Synced
> 			 - Last Block Height: 822389
> 			 - Peer 1:
> 					 - Status: Synced
> 					 - Host: 34.125.190.73
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:0.21.1/
> 					 - tasks: no tasks
> 			 - Peer 2:
> 					 - Status: Synced
> 					 - Host: 18.232.83.28
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:0.21.1/
> 					 - tasks: no tasks
> 			 - Peer 3:
> 					 - Status: Synced
> 					 - Host: 34.65.142.83
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:0.20.1/
> 					 - tasks: no tasks
> 			 - Peer 4:
> 					 - Status: Synced
> 					 - Host: 62.24.76.122
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:26.0.0(bitcoin-sl)/
> 					 - tasks: no tasks
> 			 - Peer 5:
> 					 - Status: Not Synced
> 					 - Host: 13.211.79.130
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:0.21.1/
> 					 - tasks:
> 							 - GetBlockHashesTask: [expectedHashesMinCount: 6; allowedIdleTime: 1000]
> 			 - Peer 6:
> 					 - Status: Synced
> 					 - Host: 69.4.94.226
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:25.0.0/
> 					 - tasks: no tasks
> 			 - Peer 7:
> 					 - Status: Synced
> 					 - Host: 18.191.177.83
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:0.21.1/
> 					 - tasks: no tasks
> 
> 	 - Bitcoin-BIP44:
> 			 - Synced Until: 22 дек. 2023 г., 15:37
> 			 - Syncing Peer: N/A
> 			 - Derivation: bip44
> 			 - Sync State: Synced
> 			 - Last Block Height: 822389
> 			 - Peer 1:
> 					 - Status: Synced
> 					 - Host: 58.96.123.120
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:23.1.0/
> 					 - tasks: no tasks
> 			 - Peer 2:
> 					 - Status: Synced
> 					 - Host: 176.9.120.187
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:25.0.0/
> 					 - tasks: no tasks
> 			 - Peer 3:
> 					 - Status: Synced
> 					 - Host: 31.190.57.43
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:0.18.0/
> 					 - tasks: no tasks
> 			 - Peer 4:
> 					 - Status: Synced
> 					 - Host: 95.217.106.33
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:24.99.0/
> 					 - tasks: no tasks
> 			 - Peer 5:
> 					 - Status: Synced
> 					 - Host: 167.235.9.82
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:26.0.0/
> 					 - tasks: no tasks
> 			 - Peer 6:
> 					 - Status: Synced
> 					 - Host: 62.158.79.38
> 					 - Best Block: 822389
> 					 - User Agent: /Satoshi:25.0.0/
> 					 - tasks:
> 							 - RequestTransactionsTask: [hashesCount: 7; receivedTransactionsCount: 0]
> 
> 	 - Litecoin-BIP86:
> 			 - Synced Until: 22 дек. 2023 г., 15:47
> 			 - Syncing Peer: 3.68.34.196
> 			 - Derivation: bip86
> 			 - Sync State: Synced
> 			 - Last Block Height: 2601317
> 			 - Peer 1:
> 					 - Status: Synced
> 					 - Host: 46.4.105.19
> 					 - Best Block: 2601316
> 					 - User Agent: /LitecoinCore:0.17.1/
> 					 - tasks: no tasks
> 			 - Peer 2:
> 					 - Status: Not Synced
> 					 - Host: 64.227.105.219
> 					 - Best Block: 2601317
> 					 - User Agent: /LitecoinCore:0.18.1/
> 					 - tasks: no tasks
> 			 - Peer 3:
> 					 - Status: Synced
> 					 - Host: 173.212.197.63
> 					 - Best Block: 2601316
> 					 - User Agent: /LitecoinCore:0.17.1/
> 					 - tasks: no tasks
> 			 - Peer 4:
> 					 - Status: Not Synced
> 					 - Host: 3.68.34.196
> 					 - Best Block: 2601317
> 					 - User Agent: /LitecoinCore:0.18.1/
> 					 - tasks:
> 							 - GetBlockHashesTask: [expectedHashesMinCount: 6; allowedIdleTime: 1000]
> 			 - Peer 5:
> 					 - Status: Synced
> 					 - Host: 91.193.181.3
> 					 - Best Block: 2601317
> 					 - User Agent: /LitecoinCore:0.16.3/
> 					 - tasks: no tasks
> 			 - Peer 6:
> 					 - Status: Synced
> 					 - Host: 194.163.136.179
> 					 - Best Block: 2601317
> 					 - User Agent: /LitecoinCore:0.18.1/
> 					 - tasks: no tasks
> 			 - Peer 7:
> 					 - Status: Synced
> 					 - Host: 65.108.238.59
> 					 - Best Block: 2601317
> 					 - User Agent: /LitecoinCore:0.16.3/
> 					 - tasks: no tasks
> 			 - Peer 8:
> 					 - Status: Not Synced
> 					 - Host: 86.71.47.11
> 					 - Best Block: 2601317
> 					 - User Agent: /LitecoinCore:0.18.1/
> 					 - tasks: no tasks
> 
> 	 - Litecoin-BIP84:
> 			 - Synced Until: 22 дек. 2023 г., 15:47
> 			 - Syncing Peer: 52.15.111.162
> 			 - Derivation: bip84
> 			 - Sync State: Synced
> 			 - Last Block Height: 2601317
> 			 - Peer 1:
> 					 - Status: Not Synced
> 					 - Host: 139.99.210.123
> 					 - Best Block: 2601317
> 					 - User Agent: /LitecoinCore:0.16.3/
> 					 - tasks: no tasks
> 			 - Peer 2:
> 					 - Status: Synced
> 					 - Host: 91.232.105.180
> 					 - Best Block: 2601317
> 					 - User Agent: /LitecoinCore:0.16.3/
> 					 - tasks: no tasks
> 			 - Peer 3:
> 					 - Status: Not Synced
> 					 - Host: 52.15.111.162
> 					 - Best Block: 2601316
> 					 - User Agent: /LitecoinCore:0.18.1/
> 					 - tasks:
> 							 - GetBlockHashesTask: [expectedHashesMinCount: 6; allowedIdleTime: 1000]
> 			 - Peer 4:
> 					 - Status: Synced
> 					 - Host: 37.187.29.107
> 					 - Best Block: 2601317
> 					 - User Agent: /LitecoinCore:0.18.1/
> 					 - tasks: no tasks
> 			 - Peer 5:
> 					 - Status: Synced
> 					 - Host: 185.25.120.91
> 					 - Best Block: 2601317
> 					 - User Agent: /LitecoinCore:0.18.1/
> 					 - tasks: no tasks
> 			 - Peer 6:
> 					 - Status: Synced
> 					 - Host: 217.182.200.177
> 					 - Best Block: 2601317
> 					 - User Agent: /LitecoinCore:0.18.1/
> 					 - tasks: no tasks
> 			 - Peer 7:
> 					 - Status: Synced
> 					 - Host: 52.2.1.167
> 					 - Best Block: 2601316
> 					 - User Agent: /LitecoinCore:0.18.1/
> 					 - tasks: no tasks
> ```
> 
> App Log: - Send-LTC:b4621719-6199-424d-941b-024107fc78a7: - 1: 2023-12-21 14:51:06.336 click - 2: 2023-12-21 14:51:06.337 call btc-kit.send - 3: 2023-12-21 14:51:06.474 success
> 
> ```
> 	 - Send-LTC:9e505985-5ede-4d75-bbd3-89eb0443c055:
> 			 - 4: 2023-12-21 21:40:24.306 click
> 			 - 5: 2023-12-21 21:40:24.312 call btc-kit.send
> 			 - 6: 2023-12-21 21:40:24.415 success
> 
> 	 - Send-LTC:64e385e7-7144-4d61-9f79-1713caaabfcd:
> 			 - 7: 2023-12-22 08:08:05.534 click
> 			 - 8: 2023-12-22 08:08:05.535 call btc-kit.send
> 			 - 9: 2023-12-22 08:08:05.648 success
> 
> 	 - Send-LTC:27402cbb-2549-4d81-abbd-9d8362dd7b6b:
> 			 - 10: 2023-12-22 08:42:29.530 click
> 			 - 11: 2023-12-22 08:42:29.530 call btc-kit.send
> 			 - 12: 2023-12-22 08:42:29.630 success
> 
> 	 - Send-BTC:8e5e1cf4-7f3d-46c9-bf5c-593fda367ed6:
> 			 - 13: 2023-12-22 09:05:28.168 click
> 			 - 14: 2023-12-22 09:05:28.171 call btc-kit.send
> 			 - 15: 2023-12-22 09:05:28.207 success
> 
> 	 - Send-LTC:2251f2cd-8600-4583-b6cd-63a730dcaf85:
> 			 - 16: 2023-12-22 09:08:15.084 click
> 			 - 17: 2023-12-22 09:08:15.087 call btc-kit.send
> 			 - 18: 2023-12-22 09:08:15.175 success
> ```
> 
> Market Last Sync Timestamps: - Coins: 1700826946 - Blockchains: 1700116376 - Tokens: 1701324916

Please send us the raw of the failed transaction to support.unstoppable@protonmail.com

**Comment by Dianaaiym** [comment]
resolved https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7084
