### ISSUE TITLE
Add periods to watchlist

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6937]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=82013-660618&mode=design&t=7gnAPXRvE9wvh83m-0

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=83036-154732&mode=design&t=MjkEIzF51zNwKkFX-11
