### ISSUE TITLE
Filters' choices aren't saved in "Overview" tab

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6939]
I would to see always my last setup (MCap sorted by highest value).
Unfortunately UW doesn't remember my choices made once I leave that screen.

![1000102268](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/970d7d44-ada9-4e5f-a98e-a4ed8542fe7a)

**Comment by Dianaaiym** [comment]
decided to leave it as is
