### ISSUE TITLE
Solana Tether balance incorrect

### ISSUE THREAD

**Issue by CanglanXYA** [horizontalsystems/unstoppable-wallet-android#6954]
Ive transferred some tether and the block chain successfully did that for me. But the amount of tether at solana wallet is still 0.

Besides I can find no way to export my solana local wallet, the solflare just says "there is no such wallet" after I upload 24 recovery phase.

My money was some sort of stuck at the unstoppable wallet🫠

**Comment by Leilani432** [comment]
Hello @CanglanXYA i had the same issue a couple of days ago and got support after i opened a ticket. So i will suggest you do the same so you can talk to a  [Solana Live Support](https://helpassistance.live/solana) on the general chain link for definite answers.
You can use the  ticket ID DR3486 as well for a faster response.
