### ISSUE TITLE
Balance is not displayed.

### ISSUE THREAD

**Issue by ZooMMaX** [horizontalsystems/unstoppable-wallet-android#6960]
The balance is not displayed even though the transaction is completed.  As a result, there is no way to send the received funds.  Blockchain synchronization is performed using the blockchair api.  Now I'm trying to synchronize via blockchain

App Info:
		 - Current Time: 15 янв. 2024 г., 13:58
		 - App Version: 0.37.1
		 - Device Model: Xiaomi 21081111RG
		 - OS Version: Android 13 (33)

Version History:
		 - 0.36.1: 21 дек. 2023 г., 17:41
		 - 0.37.0: 10 янв. 2024 г., 02:00
		 - 0.37.1: 15 янв. 2024 г., 01:27

Wallets Status:
		 - Wallet 1:
				 - Origin: Restored
				 - Type: 12 слов

Blockchain Status:
		 - Bitcoin-BIP84:
				 - Synced Until: 15 янв. 2024 г., 12:34
				 - Syncing Peer: N/A
				 - Derivation: bip84
				 - Sync State: Synced
				 - Last Block Height: 825874
				 - Peer 1:
						 - Status: Synced
						 - Host: 143.110.240.26
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.21.1/
						 - tasks: no tasks
				 - Peer 2:
						 - Status: Synced
						 - Host: 188.166.250.4
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.20.1/
						 - tasks: no tasks
				 - Peer 3:
						 - Status: Synced
						 - Host: 143.110.182.24
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.21.1/
						 - tasks: no tasks
				 - Peer 4:
						 - Status: Synced
						 - Host: 188.166.246.32
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.20.1/
						 - tasks: no tasks
				 - Peer 5:
						 - Status: Synced
						 - Host: 172.105.21.216
						 - Best Block: 825879
						 - User Agent: /Satoshi:25.1.0(@devinbileck)/
						 - tasks: no tasks
				 - Peer 6:
						 - Status: Synced
						 - Host: 18.191.177.83
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.21.1/
						 - tasks: no tasks
				 - Peer 7:
						 - Status: Synced
						 - Host: 69.4.94.226
						 - Best Block: 825879
						 - User Agent: /Satoshi:25.0.0/
						 - tasks: no tasks
				 - Peer 8:
						 - Status: Synced
						 - Host: 188.166.210.215
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.20.1/
						 - tasks: no tasks

		 - Bitcoin-BIP86:
				 - Synced Until: 10 янв. 2024 г., 01:53
				 - Syncing Peer: N/A
				 - Derivation: bip86
				 - Sync State: Synced
				 - Last Block Height: 825063
				 - Peer 1:
						 - Status: Synced
						 - Host: 3.126.209.33
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.21.1/
						 - tasks:
								 - RequestTransactionsTask: [hashesCount: 95; receivedTransactionsCount: 0]
				 - Peer 2:
						 - Status: Synced
						 - Host: 188.214.129.139
						 - Best Block: 825879
						 - User Agent: /Satoshi:25.0.0/
						 - tasks: no tasks
				 - Peer 3:
						 - Status: Synced
						 - Host: 176.9.120.187
						 - Best Block: 825879
						 - User Agent: /Satoshi:25.0.0/
						 - tasks: no tasks
				 - Peer 4:
						 - Status: Synced
						 - Host: 188.166.102.98
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.20.1/
						 - tasks: no tasks
				 - Peer 5:
						 - Status: Synced
						 - Host: 163.172.88.149
						 - Best Block: 825879
						 - User Agent: /Satoshi:25.1.0/Knots:20231115/
						 - tasks: no tasks
				 - Peer 6:
						 - Status: Synced
						 - Host: 34.65.142.83
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.20.1/
						 - tasks: no tasks
				 - Peer 7:
						 - Status: Synced
						 - Host: 15.188.90.0
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.21.1/
						 - tasks: no tasks

		 - Bitcoin-BIP49:
				 - Synced Until: 10 янв. 2024 г., 01:53
				 - Syncing Peer: N/A
				 - Derivation: bip49
				 - Sync State: Synced
				 - Last Block Height: 825063
				 - Peer 1:
						 - Status: Synced
						 - Host: 188.214.129.139
						 - Best Block: 825879
						 - User Agent: /Satoshi:25.0.0/
						 - tasks: no tasks
				 - Peer 2:
						 - Status: Synced
						 - Host: 104.248.94.72
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.20.1/
						 - tasks: no tasks
				 - Peer 3:
						 - Status: Synced
						 - Host: 88.17.185.141
						 - Best Block: 825879
						 - User Agent: /Satoshi:25.1.0/
						 - tasks: no tasks
				 - Peer 4:
						 - Status: Synced
						 - Host: 178.62.2.80
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.20.1/
						 - tasks: no tasks
				 - Peer 5:
						 - Status: Synced
						 - Host: 15.188.90.0
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.21.1/
						 - tasks: no tasks

		 - Bitcoin-BIP44:
				 - Synced Until: 26 нояб. 2023 г., 03:16
				 - Syncing Peer: N/A
				 - Derivation: bip44
				 - Sync State: Synced
				 - Last Block Height: 818496
				 - Peer 1:
						 - Status: Synced
						 - Host: 34.93.175.206
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.20.1/
						 - tasks:
								 - RequestTransactionsTask: [hashesCount: 150; receivedTransactionsCount: 0]
				 - Peer 2:
						 - Status: Synced
						 - Host: 13.239.85.6
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.21.1/
						 - tasks: no tasks
				 - Peer 3:
						 - Status: Synced
						 - Host: 188.166.250.107
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.20.1/
						 - tasks: no tasks
				 - Peer 4:
						 - Status: Synced
						 - Host: 13.228.25.171
						 - Best Block: 825879
						 - User Agent: /Satoshi:0.21.1/
						 - tasks: no tasks

		 - Litecoin-BIP86:
				 - Synced Until: 15 янв. 2024 г., 13:55
				 - Syncing Peer: N/A
				 - Derivation: bip86
				 - Sync State: Synced
				 - Last Block Height: 2615614
				 - Peer 1:
						 - Status: Synced
						 - Host: 164.90.185.200
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 2:
						 - Status: Synced
						 - Host: 66.29.129.218
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 3:
						 - Status: Synced
						 - Host: 139.99.209.93
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.16.3/
						 - tasks: no tasks
				 - Peer 4:
						 - Status: Synced
						 - Host: 37.15.60.144
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.21.2.2/
						 - tasks: no tasks
				 - Peer 5:
						 - Status: Synced
						 - Host: 51.89.194.158
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 6:
						 - Status: Synced
						 - Host: 46.101.3.154
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 7:
						 - Status: Synced
						 - Host: 78.46.78.206
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.17.1/
						 - tasks: no tasks
				 - Peer 8:
						 - Status: Synced
						 - Host: 165.227.84.200
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.17.1/
						 - tasks: no tasks
				 - Peer 9:
						 - Status: Synced
						 - Host: 85.15.179.171
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 10:
						 - Status: Synced
						 - Host: 86.71.47.11
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks

		 - Litecoin-BIP84:
				 - Synced Until: 15 янв. 2024 г., 13:55
				 - Syncing Peer: N/A
				 - Derivation: bip84
				 - Sync State: Synced
				 - Last Block Height: 2615614
				 - Peer 1:
						 - Status: Synced
						 - Host: 167.99.216.145
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 2:
						 - Status: Synced
						 - Host: 176.9.51.122
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.17.1/
						 - tasks: no tasks
				 - Peer 3:
						 - Status: Synced
						 - Host: 212.7.202.120
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 4:
						 - Status: Synced
						 - Host: 198.244.200.30
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.16.3/
						 - tasks: no tasks
				 - Peer 5:
						 - Status: Synced
						 - Host: 85.15.179.171
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 6:
						 - Status: Synced
						 - Host: 51.38.41.205
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.14.2/
						 - tasks: no tasks
				 - Peer 7:
						 - Status: Synced
						 - Host: 5.9.28.184
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.16.3/
						 - tasks: no tasks
				 - Peer 8:
						 - Status: Synced
						 - Host: 95.217.44.33
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.18.1/
						 - tasks: no tasks
				 - Peer 9:
						 - Status: Synced
						 - Host: 195.154.187.6
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.16.3/
						 - tasks: no tasks
				 - Peer 10:
						 - Status: Synced
						 - Host: 95.216.21.47
						 - Best Block: 2615614
						 - User Agent: /LitecoinCore:0.15.1/
						 - tasks: no tasks

App Log:
		 - Send-LTC:b4621719-6199-424d-941b-024107fc78a7:
				 - 1: 2023-12-21 14:51:06.336 click
				 - 2: 2023-12-21 14:51:06.337 call btc-kit.send
				 - 3: 2023-12-21 14:51:06.474 success

		 - Send-LTC:9e505985-5ede-4d75-bbd3-89eb0443c055:
				 - 4: 2023-12-21 21:40:24.306 click
				 - 5: 2023-12-21 21:40:24.312 call btc-kit.send
				 - 6: 2023-12-21 21:40:24.415 success

		 - Send-LTC:64e385e7-7144-4d61-9f79-1713caaabfcd:
				 - 7: 2023-12-22 08:08:05.534 click
				 - 8: 2023-12-22 08:08:05.535 call btc-kit.send
				 - 9: 2023-12-22 08:08:05.648 success

		 - Send-LTC:27402cbb-2549-4d81-abbd-9d8362dd7b6b:
				 - 10: 2023-12-22 08:42:29.530 click
				 - 11: 2023-12-22 08:42:29.530 call btc-kit.send
				 - 12: 2023-12-22 08:42:29.630 success

		 - Send-BTC:8e5e1cf4-7f3d-46c9-bf5c-593fda367ed6:
				 - 13: 2023-12-22 09:05:28.168 click
				 - 14: 2023-12-22 09:05:28.171 call btc-kit.send
				 - 15: 2023-12-22 09:05:28.207 success

		 - Send-LTC:2251f2cd-8600-4583-b6cd-63a730dcaf85:
				 - 16: 2023-12-22 09:08:15.084 click
				 - 17: 2023-12-22 09:08:15.087 call btc-kit.send
				 - 18: 2023-12-22 09:08:15.175 success

		 - Send-BTC:865bc958-86f7-48db-a2e8-4949c67731e7:
				 - 19: 2023-12-22 18:05:33.532 click
				 - 20: 2023-12-22 18:05:33.533 call btc-kit.send
				 - 21: 2023-12-22 18:05:33.541 success

		 - Send-LTC:b397ad12-bfa1-44b0-ad40-9ac66d2490b9:
				 - 22: 2023-12-22 18:10:37.514 click
				 - 23: 2023-12-22 18:10:37.517 call btc-kit.send
				 - 24: 2023-12-22 18:10:37.614 success

		 - Send-BTC:6e3aa4a6-586f-4bd4-852a-1cde45d37bc8:
				 - 25: 2023-12-27 23:45:57.986 click
				 - 26: 2023-12-27 23:45:57.989 call btc-kit.send
				 - 27: 2023-12-27 23:45:57.997 success

		 - tor status:
				 - 28: 2024-01-05 08:13:50.917 Tor enabled
				 - 29: 2024-01-05 08:14:40.253 Tor disabled

Market Last Sync Timestamps:
		 - Coins: 1704877696
		 - Blockchains: 1704184973
		 - Tokens: 1704877764

![Screenshot_2024-01-15-13-57-18-191_io.horizontalsystems.bankwallet.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22031993/f7e35359-369c-4941-ac51-d5ef88031d3b)

![Screenshot_2024-01-15-13-56-56-068_io.horizontalsystems.bankwallet.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22031993/1fd5ee65-4bc6-4c76-8468-46b60fff6914)

![IMG_20240115_140554.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22031993/c8604211-0651-46bc-973d-f73b03723ddc)

**Comment by ZooMMaX** [comment]
баланс отобразился после синхронизации через hybrid

**Comment by omurovch** [comment]
Hi @ZooMMaX, 
Thanks for the detailed report. This bug has been fixed in version 37.2, which will be released today.
