### ISSUE TITLE
Implementation of advanced filtering options in filters page

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6968]
add new options:

☑️ listed on top exchanges
☑️ solid CEX volume
☑️ solid DEX volume
☑️ good distribution

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=83405-45160&mode=design&t=7AN9NUiQlAZSwGC5-11
