### ISSUE TITLE
Token contract verifier (strings comparison)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6973]
Sometimes I meet some new tokens. And so their official websites provide me the smart contract address for each one.

It would be useful if clicking on smart contract string in UW one might having the possibility to paste the website's smart contract address in a second field in a popup, in order to have a result positive or negative comparing both strings.

![1000102938](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/aa25b24c-75cf-448b-99d2-456cda3d050e)

**Comment by esengulov** [comment]
There is no easy way to implement such feature reliably
