### ISSUE TITLE
Add defi scanner

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6975]
Add token detectors to coin analytics https://de.fi/scanner/contract/0x5a98fcbea516cf06857215779fd812ca3bef1b32?chainId=eth

UI:

* https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=82199-75379&mode=design&t=6cmp4z0PorB1hsn0-0

Backend:

* https://api-dev.blocksdecoded.com/v1/docs/#api-Analytics-GetV1AnalyticsUidIssues
* https://api-dev.blocksdecoded.com/v1/analytics/tether/issues

**Comment by TalgatNurdinov** [comment]
- [ ] Fix italic font of (high risk, attention required) counts on analytics page
- [ ] Show a list of blockchains by existing blockchain sorting
- [ ] Change the icons of items without risks and attention required marks
- [ ] Fix the paddings of cells in items list and issues
