### ISSUE TITLE
Off-ramp | Crypto to fiat with MoonPay

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6980]
This is not my favorite move, but it is necessary at certain point having a possibility to comeback.

Of course it is not mandatory.

Integrating the MoonPay provider (account and KYC are both needed) in UW can simplifying the way which a user can withdrawing their fiat assets.

https://www.moonpay.com/business/offramps

**Comment by notpri** [comment]
no i dont want that. UW is for privacy and MoonPay just destroys it.

**Comment by notpri** [comment]
also , we dont need to convert crypto to fiat right from UW as future is crypto and we have other several options of getting fiat assets.
