### ISSUE TITLE
Export private keys for specific currency.

### ISSUE THREAD

**Issue by oblak-be** [horizontalsystems/unstoppable-wallet-android#6982]
Hello!

I have unstoppable wallet with two coins (BTC & ETH).

I want to export the ETH keys and import them in another wallet (Metamask).

I haven't found a way to do this in unstoppable wallet, it seems that I can only backup the whole wallet.

Excuse me if I overlooked the feature, please point it out to me. If not, please consider implementing this feature!

**Comment by Dianaaiym** [comment]
> Hello!
> 
> I have unstoppable wallet with two coins (BTC & ETH).
> 
> I want to export the ETH keys and import them in another wallet (Metamask).
> 
> I haven't found a way to do this in unstoppable wallet, it seems that I can only backup the whole wallet.
> 
> Excuse me if I overlooked the feature, please point it out to me. If not, please consider implementing this feature!

There is already an option to back up not only the recovery phrase but also the private keys for certain chains.
![2024-01-29 14 25 07](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/d15b8cfe-2131-4bb9-a9c2-d9c0c17b4633)

![2024-01-29 14 25 11](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/c29e8c76-33e8-4462-a4d8-4ea4a0f48f78)

![2024-01-29 14 25 13](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/b37b8cec-5560-4a44-a757-c125fdefe469)
