### ISSUE TITLE
Wallet Connect: Do not start QR scanner automatically

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6984]
I would like an option that allow me to choose how Wallet Connect has to start when its button is pressed.

Basically two choises:

1. Start with opening the camera
2. Start with dapps connections list

![1000105676](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/5af21f2a-a348-4a27-be38-ce8c99d716d0)

![1000105671](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/57968797-96cf-40c5-aca9-624a2886b8e4)

**Comment by abdrasulov** [comment]
When you open the Wallet Connect page, it shows you the list of connected dApps, if any. If the list is empty, it takes the user to the new connection page. Also, there is an option to connect to dApp right from the balance screen by clicking the qr scanner icon.

**Comment by ealymbaev** [comment]
@serrq 

Why would you need an empty page with empty list? The only action you can do there is to tap "New Connection", so the app is doing it automatically )

**Comment by abdrasulov** [comment]
@serrq 

Good point. We've discussed it with a team. We decided to not start QR scanner automatically.
