### ISSUE TITLE
Please add EURC and USDP tokens on Solana. USDC on Tron

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7004]
https://www.circle.com/en/eurc

https://paxos.com/usdp/

https://www.circle.com/en/usdc-multichain/tron

**Comment by ealymbaev** [comment]
> Please add also EURC on Avalanche if you can. Because we have Avalanche network too in UW.
> 
> https://www.circle.com/en/eurc

Yes, the coin could be added, but meanwhile you can add it using Add Token feature yourself, FYI

**Comment by tmedetbekov** [comment]
@serrq I added all the token contracts you requested.
