### ISSUE TITLE
I cannot see some Solana activities in transactions history

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7010]
[0.37.2] [0.37.3] Both versions are affected.

![1000105842](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/b55c5c12-6c34-439a-9469-14204d1d64a2)

![1000105844](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/53b10894-6219-4527-9560-eb85441660f6)

**Comment by Dianaaiym** [comment]
Yes, we will not display transaction history at the moment because SolScan has changed its pricing structure, and now we need to purchase a subscription to access transaction data.
