### ISSUE TITLE
New app name proposal

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7015]
The problem is that "Unstoppable" exceeds the characters app name length in launcher.

Every time I must to see things like: Unstopp... in launcher.

So my proposal is "Unstopp" as new name for this app.

Do you have a better/shorter name to solve this little "issue"?

**Comment by notpri** [comment]
> Instead to put thumb down why do not contribute to conversation tell me a solution or an explanation about your point of view?

I like the name Unstoppable because of its meaning and I dont care about the name being long because this wallet cannot be stopped and gives you full freedom and Unstoppable name just is perfect here. Icon is enough for me to recognize the wallet. So again the name is perfect.
