### ISSUE TITLE
Where did you take USDC on Fantom chain from? It seems inexistent.

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7016]
On official Circle website:

https://www.circle.com/en/usdc

![1000105879](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/ccf35459-f8f6-44f8-8e02-ba0baaf7417d)

![1000105882](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/de5a377c-5cda-400e-aac3-2a9a1dea2da6)

**Comment by tmedetbekov** [comment]
This token on Fantom is bridged over from its native chain using the Multichain bridge.

https://www.circle.com/blog/ushering-in-the-next-chapter-for-usdc

https://ftmscan.com/address/0x04068da6c83afcfa0e13ba15a6696662335d5b75

<img width="431" alt="Screenshot 2024-02-05 at 3 27 38 PM" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/299661/2d49eb68-0de3-4021-8667-9dec24e958fc">

**Comment by tmedetbekov** [comment]
We already have bridged coin USDC.e on Avalanche, Optimism, Arbitrum, and Polygon. Does the Multichain's bridging operate similarly to Avalanche, Optimism, Arbitrum, and Polygon? As far as I know, CoinGecko and CoinMarketCap didn’t add this contract to USDC.e

**Comment by tmedetbekov** [comment]
Since there is no specific understanding I will leave it as it is for now as both Coingecko and CoinMarketCap display it as a native token and if there is clarity in the future, we will reopen.
