### ISSUE TITLE
Polygon sync doesn't work help 

### ISSUE THREAD

**Issue by Wjxfi** [horizontalsystems/unstoppable-wallet-android#7022]
0.37.2 f-droid android 12 miui 13.0.5

The problem is not my internet. Tried several vpn. other rpc tried. The problem is with your app and getting data, almost exactly. The other blockchains work perfectly, but this one stopped working after some update, and new updates don't fix it.

**Comment by Dianaaiym** [comment]
> 0.37.2 f-droid android 12 miui 13.0.5
> 
> The problem is not my internet. Tried several vpn. other rpc tried. The problem is with your app and getting data, almost exactly. The other blockchains work perfectly, but this one stopped working after some update, and new updates don't fix it.

Hi, Please send your App Status (Settings - About App) to support.unstoppable@protonmail.com
