### ISSUE TITLE
Solana tokens sync doesn't work 

### ISSUE THREAD

**Issue by Andreisbb** [horizontalsystems/unstoppable-wallet-android#7031]
Hello. There's error while syncing solana token balance, also this error cause inability of sending token.
' Expected a long but was 18446744073709551615 at path $.result.value[0].rentEpoch '
It's seems unstoppable app unable to make synchronization due to large amount of unsynchronized transactions before.

**Comment by Dianaaiym** [comment]
> Hello. There's error while syncing solana token balance, also this error cause inability of sending token. ' Expected a long but was 18446744073709551615 at path $.result.value[0].rentEpoch ' It's seems unstoppable app unable to make synchronization due to large amount of unsynchronized transactions before.

Hello,

Have you already updated the application to the latest version 0.37.3?

**Comment by egabosh** [comment]
Same error here. Please fix soon.

**Comment by abdrasulov** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/pull/7142#issuecomment-1985860426

**Comment by notpri** [comment]
@abdrasulov @rafaelekol 
![Screenshot_2024-03-11-12-47-00-28](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/93900ef2-f9cc-4300-939e-fbfbeb05ee49)
works for me too

**Comment by notpri** [comment]
@abdrasulov @rafaelekol 
![Screenshot_2024-03-11-12-48-46-19](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/da1eb6e1-646c-4e51-9bda-590768b1e2de)
my oldest wallet also have no issues

**Comment by notpri** [comment]
> Still same error for all my wallets v0.37.5

you guys must have a setting/blocker enabled in your device which cause the error.

**Comment by molitona** [comment]
> Still same error for all my wallets v0.37.5

yep, for me i cannot send usdt/usdc in latest version with the 2 solana apis...

**Comment by molitona** [comment]
> I can confirming that 0.37.5 doesn't solve the issue.
> 
> ![1000107926](https://private-user-images.githubusercontent.com/113377431/311523176-9048b61d-41aa-4af6-917e-803d951b7280.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMDAwNTMsIm5iZiI6MTcxMjA5OTc1MywicGF0aCI6Ii8xMTMzNzc0MzEvMzExNTIzMTc2LTkwNDhiNjFkLTQxYWEtNGFmNi05MTdlLTgwM2Q5NTFiNzI4MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQyMzE1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWEyZTYxZmM4ODc0ZDUzOTg2YTBlYjdhZWEzZjA1MDI1YzA3Y2QxMjRhZDBiMjY0NGI0MDU4NjZkYjQxZTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.it9OGMZ_7MNOqKOZieBsGdIIu8otvBIkFeeWsL4Epww)
> 
> ![1000107924](https://private-user-images.githubusercontent.com/113377431/311523179-56fbe29f-e844-44c3-aef7-cb54a8184f5c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMDAwNTMsIm5iZiI6MTcxMjA5OTc1MywicGF0aCI6Ii8xMTMzNzc0MzEvMzExNTIzMTc5LTU2ZmJlMjlmLWU4NDQtNDRjMy1hZWY3LWNiNTRhODE4NGY1Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQyMzE1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmUzZGIwZGFhZWQ1NTZjYTk1YjNhZWY3ZmJiN2Y2ZGVmNjBhYjU4ZGQzOWFlNGFhMTMzY2VkN2E1N2Q4YzY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J-IKrPhqXWCqwIBii2P9LdS3nQnt4SDxQii_csCyOFg)

confirm it

**Comment by omurovch** [comment]
@Andreisbb @serrq @egabosh @molitona @notpri 

Thanks for heads up! Reported bugs were fixed and will be available in version 0.38 soon! Stay tuned.

**Comment by molitona** [comment]
@Andreisbb @Dianaaiym @omurovch 

same problem again after months waiting, send on solana doesn't work. this is really frustrating!

![ee](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/35532337/58f91182-6303-4b0f-abce-310fad1c9533)

**Comment by omurovch** [comment]
Does it always fail? I have tried to send now and it worked fine. Probably, the issue is on the rpc provider side. Can you send us app status?

**Comment by molitona** [comment]
> Does it always fail? I have tried to send now and it worked fine. Probably, the issue is on the rpc provider side. Can you send us app status?
```

App Info:
   - Current Time: Apr 18, 2024, 17:31
   - App Version: 0.38.0
   - Device Model: xxx
   - OS Version: Android 14 (34)

Version History:
   - 0.38.0: Apr 18, 2024, 16:47

Wallets Status:
   - Wallet 1:
     - Origin: Restored
     - Type: 24 words with passphrase


Blockchain Status:
   - Solana:
     - Last Block Height: 240985762
     - Sync State: Synced


App Log:

Market Last Sync Timestamps:
   - Coins: 1712812046
   - Blockchains: 1712812046
   - Tokens: 1712812046
```

**Comment by molitona** [comment]
> I have several wallets, all wallets are fine for solana tokens sending (I have tried USDC) but some of them cannot sync solana itself (SOL solana). V0.38.0.

for me. i have only USDC and it failed. do u use passpharse?

**Comment by molitona** [comment]
> > I have several wallets, all wallets are fine for solana tokens sending (I have tried USDC) but some of them cannot sync solana itself (SOL solana). V0.38.0.
> 
> And it's still not possible for app to sync incoming and outgoing transactions for solana tokens. Tokens transactions aren't shown in transactions list.

same here.

**Comment by molitona** [comment]
> > > I have several wallets, all wallets are fine for solana tokens sending (I have tried USDC) but some of them cannot sync solana itself (SOL solana). V0.38.0.
> > 
> > 
> > for me. i have only USDC and it failed. do u use passpharse?
> 
> No, just 24 words seed.

u succeded to send USDC on solana ?

**Comment by molitona** [comment]
> > > > > I have several wallets, all wallets are fine for solana tokens sending (I have tried USDC) but some of them cannot sync solana itself (SOL solana). V0.38.0.
> > > > 
> > > > 
> > > > for me. i have only USDC and it failed. do u use passpharse?
> > > 
> > > 
> > > No, just 24 words seed.
> > 
> > 
> > u succeded to send USDC on solana ?
> 
> Yes successful

not the case for me hope @omurovch found any explanation...

**Comment by omurovch** [comment]
Transaction history was already removed starting from version 0.37. Transaction list shows just outgoing txs which were sent from this device. That's because api which was used for fetching txs was removed by solscan. We are looking for alternative ways to sync txs. 

Regarding sending sol and tokens, was able to successfully send several times. @molitona can you try to restore the wallet again? Is sol and tokens syncing fine?

**Comment by molitona** [comment]
> > > > > I have several wallets, all wallets are fine for solana tokens sending (I have tried USDC) but some of them cannot sync solana itself (SOL solana). V0.38.0.
> > > > 
> > > > 
> > > > for me. i have only USDC and it failed. do u use passpharse?
> > > 
> > > 
> > > No, just 24 words seed.
> > 
> > 
> > u succeded to send USDC on solana ?
> 
> Yes successful

not the case for me hope @omurovch found any explanation...

> Transaction history was already removed starting from version 0.37. Transaction list shows just outgoing txs which were sent from this device. That's because api which was used for fetching txs was removed by solscan. We are looking for alternative ways to sync txs.
> 
> Regarding sending sol and tokens, was able to successfully send several times. @molitona can you try to restore the wallet again? Is sol and tokens syncing fine?

yes SOL/USDC syncs fine. tried restore wallet again and in other phone too with same error..
can u come to telegram unstoppable support chat to talk faster?

**Comment by omurovch** [comment]
> @omurovch Transactions which have been sent from my device either not showing in txs history.
> 
> 
 
Txs sent before 0.38 were stuck in pending state, and all tx history was cleared in 0.38. Starting from 0.38 outgoing txs sent from that device should be shown in list.

**Comment by omurovch** [comment]
> > @omurovch Transactions which have been sent from my device either not showing in txs history.
> > 
> > 
>  
> Txs sent before 0.38 were stuck in pending state, and all tx history was cleared in 0.38. Starting from 0.38 outgoing txs sent from that device should be shown in list.

Note: This applies only to txs on solana.

**Comment by omurovch** [comment]
> > > @omurovch Transactions which have been sent from my device either not showing in txs history.
> > 
> > Txs sent before 0.38 were stuck in pending state, and all tx history was cleared in 0.38. Starting from 0.38 outgoing txs sent from that device should be shown in list.
> 
> I have tried make some transactions in 0.38.0v and it's not showing in tx history

Wallet instance should be the one from which you've sent.

**Comment by molitona** [comment]
> > > > > I have several wallets, all wallets are fine for solana tokens sending (I have tried USDC) but some of them cannot sync solana itself (SOL solana). V0.38.0.
> > > > 
> > > > 
> > > > for me. i have only USDC and it failed. do u use passpharse?
> > > 
> > > 
> > > No, just 24 words seed.
> > 
> > 
> > u succeded to send USDC on solana ?
> 
> Yes successful

not the case for me hope @omurovch found any explanation...

> Transaction history was already removed starting from version 0.37. Transaction list shows just outgoing txs which were sent from this device. That's because api which was used for fetching txs was removed by solscan. We are looking for alternative ways to sync txs.
> 
> Regarding sending sol and tokens, was able to successfully send several times. @molitona can you try to restore the wallet again? Is sol and tokens syncing fine?

yes SOL/USDC syncs fine. tried restore wallet again and in other phone too with same error..
can u come to telegram unstoppable support chat to talk faster?

> > yes SOL/USDC syncs fine. tried restore wallet again and in other phone too with same error..
> > can u come to telegram unstoppable support chat to talk faster?
> 
> Hmm.. It seems error happens to some wallets only. We will try to reproduce it.

how can i help ? i have passphrase for ur knowledge

**Comment by molitona** [comment]
@omurovch 

the send works well sorry man for wasting ur time really sorry it's mine mistake don't have SOL

**Comment by Dianaaiym** [comment]
The issue has been resolved; the user didn't have enough Solana to complete the transaction. We need to display an error message when there are insufficient Solana funds to send a transaction @omurovch

**Comment by Dianaaiym** [comment]
> After restoring with seed all the issues magically are disappeared. Just SOL/SPL tx history doesn't work.

After restoring your wallet, transaction histories won't be available. Transaction history appears only when sending from the wallet and solely on the device used for sending
