### ISSUE TITLE
Some considerations about Toncoin (after tests)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7036]
Generally the token is sent properly, but I experienced some issues.

One time the transaction fallen because "timeout".
Another time the toastbar reported "Sent" but no funds have been moved.
In another occasion I get a strange error and after I seen in history "unknown transaction".

Is all normal?

Last but not least, I got stuck in Toncoin because to swap it I need of the memo field.

![1000105924](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/31dd6c8e-894c-4778-b348-e14856a44416)

**Comment by Dianaaiym** [comment]
We were unable to reproduce the issue with sending; the memo has already been added in 0.38.
