### ISSUE TITLE
Wallet uses alot of network traffic without stopping when BTC is enabled.

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7043]
When I open the wallet. It starts using alot of data without stopping even when i do nothing and just keep it on. Please look into it. It always uses like 1.4MB/s, 1.3Mb/s of network data.

**Comment by notpri** [comment]
@abdrasulov @rafaelekol Update:
I worked on this issue as why UW contionusly uses as much data as it can even when the wallet is just kept open.
The problem is with BTC.
Steps: 
1. Turn on Real Time network speed in android.
2. Enable BTC BIP84 if disabled
3. Start watching the network traffic UW starts to consume
4. Disable BTC and UW won't use that much data and will just be normal.
 So please fix this problem with BTC BIP84. I didn't tested other BIPS of BTC.

**Comment by abdrasulov** [comment]
@notpri 

The Bitcoin-based blockchains sync with the network by downloading block headers. This is called SPV. It is true for Bitcoin, Bitcoin Cash, Litecoin, Dash, and XEC.

**Comment by notpri** [comment]
> @notpri
> 
> The Bitcoin-based blockchains sync with the network by downloading block headers. This is called SPV. It is true for Bitcoin, Bitcoin Cash, Litecoin, Dash, and XEC.

Thank for time but I have XEC enabled and I have good amount of it. But it never consumes that large amount of data without stopping. Same is the case for BCH. however BTC starts to consume alot of data when i enable it. Thanks!

**Comment by abdrasulov** [comment]
I guess it is related to block sizes. Blocks in Bitcoin usually are full of transactions. It leads to larger data size compared to other blockchains.

**Comment by notpri** [comment]
ok
