### ISSUE TITLE
Please adding the USDY token on Solana

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7049]
https://solscan.io/token/A1KLoBrKBde8Ty9qtNQUtq3C2ortoC3u7twggz7sEto6

I cannot do this by myself because lack the blockchain in the list.

https://docs.ondo.finance/addresses

https://blog.ondo.finance/introducing-ondo-usd-yield-usdy/

![1000105930](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/e00e4c66-ad66-40e8-b8e7-75050146e7e9)

**Comment by abdrasulov** [comment]
Need to research if we can support adding custom tokens for the Solana blockchain

**Comment by Dianaaiym** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/pull/7581
Please check our latest update 0.39
