### ISSUE TITLE
Red dot over the transaction (in history) until it doesn't reach the finality

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7050]
One of the most important thing when we make a money movement is the irreversibility.

When (for example) you send 0.001 ETH to another wallet (recipient) the funds are moved in ~15 seconds but "time to finality" (or TTF) happens after ~85 seconds.

So, how to do user to realize its idea that the transaction is irreversible or canceled?

Solution:

When the red dot on transaction disappear, then the transaction is irreversible.

**Comment by abdrasulov** [comment]
The transaction has a field named Status. The purpose of this field is exactly what you've described. When the Status is Completed, the transaction has been included in the block and is irreversible. When the Status is Pending, the transaction has not yet been confirmed on the blockchain.
