### ISSUE TITLE
Support for Injective (INJ) network

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7052]
25,000 tps
800 milliseconds block time
TTF instant (sub second finality)
Ultra low fees (0.0001 INJ ≈0.000 $)
Smart contracts in Rust language
Highly secure

No more waiting to move your assets.

https://injective.com/developers

![1000105940](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/10bd687d-61cc-4560-915b-0913da1008b6)

![Average-Gas-Fee-Comparison--2-](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/4efc601d-789a-433c-a7e1-95495daa161a)

**Comment by Dianaaiym** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7197
