### ISSUE TITLE
ZEC SYNC problem

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7061]
I imported this wallet and when i try to add ZEC. It gives me this and when I click on "Existing Walet" then the blockchans starts syncing for 2014. How will I be able to trade ZEC? 
![Screenshot_2024-02-09-13-52-14-73](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/17b8a9c7-0dd4-4c62-8f37-2fefcdb98965)
![Screenshot_2024-02-09-13-53-24-93](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/f69f1b93-57e0-412e-98ea-376bee765806)

**Comment by notpri** [comment]
also unstoppable never gave me "Birthday Height" and it asks here for faster sync.

**Comment by rafaelekol** [comment]
![photo_2024-02-16_15-00-19](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/1390965/f2c1756f-92c2-41a0-95c7-76a064eb219c)
You can find Zec birthday height in Coin Manager screen.

**Comment by rafaelekol** [comment]
It's a bug.  After enabling Zec, try to return back to Balance page, then open Coin Manager again, and check if you can see this info button.

**Comment by notpri** [comment]
> It's a bug. After enabling Zec, try to return back to Balance page, then open Coin Manager again, and check if you can see this info button.

please fix the bug you found and here is what i get. im unable to retrieve my existing ZEC wallet.
![Screenshot_2024-02-16-14-29-18-33](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/c5f69242-2466-476d-9085-fde02c6be4ff)

**Comment by rafaelekol** [comment]
If you didn't set a birthday height, the button will be blank like yours. To restore you have now 2 options:

1. Sync from 2014 (slow but complete).
2. Find your creation date using explorers like https://zcashblockexplorer.com/blocks/2004222  Use the corresponding block number as your birthday height (e.g., 2004222 was mined in March 4th, 2023).

**Comment by notpri** [comment]
@rafaelekol So, When you enable ZEC and get back to Coin Manager, then the info mark for Birthday Height is shown. But when you disable ZEC again  then the info button for Birthday height is also gone. Fix these issues please

**Comment by rafaelekol** [comment]
> After creating ZEC wallet once, the Birthday height should be there even if we disable ZEC again.
Currently its working the way it was designed. 
`New Wallet` option only changes from which block height to sync. Its not making to lose your old wallets funds. In case you clicked by mistake, you can resync wallet with older block height and get your funds.
