### ISSUE TITLE
price not shown correctly.

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7063]
here you can see the price is shown 0.01$ while its 0.001$. 
![IMG_20240210_002233](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/a88b5058-9420-4200-854a-cd7ae37e57cd)
![IMG_20240210_002305](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/31de127f-34a9-4bf7-87f2-0bcbcb27fe67)

**Comment by abdrasulov** [comment]
The maximum number of digits after the dot is 2 for the fiat values on that screen. That is why it's shown with a "<" sign. It means that the value is lower than the lowest possible value. We can increase the number of dots, for example to 3. In that case, the same scenario will be with values less than 0.001.
