### ISSUE TITLE
Coin buy indicators: strength bar and floor/roof price in the time range (24H/7D/1M/3M/1Y)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7066]
Is it possible doing something similar in UW? (weak --- strong)

![1000106108](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/7d025611-70bc-4764-abbe-76f67d1ce8af)

**Comment by esengulov** [comment]
The last one looks interesting, I will see with our designers if we can integrate them.

Also not that we are currently working on AI powered trend analysis for coins price based on RSI, BB, MACD indicators. I think they may go live next update or one after🙂🙏🏻
