### ISSUE TITLE
Is UW immune to mnemonic attack?

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7079]
“An attacker can systematically generate mnemonics for each timestamp within an applicable timeframe, and link them to specific wallet addresses in order to steal funds from those wallets”, the NIST statement reads.

https://coincodecap.com/nist-probes-vulnerability-in-binance-trust-wallet-app

https://crypto.news/nist-investigates-security-flaw-in-binance-trust-wallets-ios-app/

https://bitcoinist.com/binance-us-govt-investigates-potential-hack-risk/

**Comment by kineita** [comment]
I see reply from Binance 
"Though there was a previous vulnerability in our open-source code in early 2018 affecting a few thousand users only, the vulnerability was quickly patched with the support of the security community—and affected users were notified and migrated into safe wallets."
In this point, how about our wallet implementation when comparing to 2018's trust wallet ?
