### ISSUE TITLE
Disable biometric login when fingerprints are added or changed

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7094]
It would be really helpful if you disable biometric login when device fingerprints are changed or new ones are added to the device for security because a person can add his/her fingerprint and use it to open the UW.

**Comment by abdrasulov** [comment]
Need to research if we can implement it in a reasonable time

**Comment by rafaelekol** [comment]
We decided not to do this feature at the moment
