### ISSUE TITLE
UW crashes when clicked on paste address when sending

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7095]
Steps:
1. Don't copy anything (no address)
2. go to UW and click on BTC
3. click on Send
4. hit the paste button
5. UW crashes
6. Fix the crash bug when no address is copied you click the paste button while sending.

**Comment by notpri** [comment]
> Number one for discovering bugs. The bug hunter. 😉

i can make these issues numbers to 200 right away in 1 hour. I installed UW in a IPAD and believe me its totally broken. I east surprised to see 1star rating for UW in app store and when i download it. I came to know why it has 1 star. Right now I want them to make it the best for android, after that I will specify the bugs for Ipads if my friend hold his ipad.

**Comment by notpri** [comment]
> Number one for discovering bugs. The bug hunter. 😉

and yeah, im pretty good at finding bugs.

**Comment by esengulov** [comment]
@notpri olease post all bugs you discovered 🙏🏻🙂 we will have them fixed asap.

You mentioned, 1 star rating, where was it?

**Comment by notpri** [comment]
> @notpri olease post all bugs you discovered 🙏🏻🙂 we will have them fixed asap.
> 
> You mentioned, 1 star rating, where was it?

Thanks for the beautiful response. However, those bugs are in app store version of UW. I'm not gonna blow the issues section here for app store right now, You first need to work on th android version of the app as I'm not into iphones and ipads. I actually love UW and I'm promoting it on my end and spreading the word. That's how i downloaded UW in my friends Ipad for him and I saw 1star rating in the app store. I was shocked at rating but after using UW in ipad, it was clear to me. So for now I care about android version more and that's why I don't want you to give time to ipads and iphones version.

**Comment by Dianaaiym** [comment]
> Steps:
> 
> 1. Don't copy anything (no address)
> 2. go to UW and click on BTC
> 3. click on Send
> 4. hit the paste button
> 5. UW crashes
> 6. Fix the crash bug when no address is copied you click the paste button while sending.

What is the Android version?

**Comment by notpri** [comment]
> > Steps:
> > 
> > 1. Don't copy anything (no address)
> > 2. go to UW and click on BTC
> > 3. click on Send
> > 4. hit the paste button
> > 5. UW crashes
> > 6. Fix the crash bug when no address is copied you click the paste button while sending.
> 
> What is the Android version?

0.37.3

**Comment by Dianaaiym** [comment]
> > > Steps:
> > > 
> > > 1. Don't copy anything (no address)
> > > 2. go to UW and click on BTC
> > > 3. click on Send
> > > 4. hit the paste button
> > > 5. UW crashes
> > > 6. Fix the crash bug when no address is copied you click the paste button while sending.
> > 
> > 
> > What is the Android version?
> 
> 0.37.3

not app version, android version?

**Comment by notpri** [comment]
> > > > Steps:
> > > > 
> > > > 1. Don't copy anything (no address)
> > > > 2. go to UW and click on BTC
> > > > 3. click on Send
> > > > 4. hit the paste button
> > > > 5. UW crashes
> > > > 6. Fix the crash bug when no address is copied you click the paste button while sending.
> > > 
> > > 
> > > What is the Android version?
> > 
> > 
> > 0.37.3
> 
> not app version, android version?

10

**Comment by notpri** [comment]
> > > > Steps:
> > > > 
> > > > 1. Don't copy anything (no address)
> > > > 2. go to UW and click on BTC
> > > > 3. click on Send
> > > > 4. hit the paste button
> > > > 5. UW crashes
> > > > 6. Fix the crash bug when no address is copied you click the paste button while sending.
> > > 
> > > 
> > > What is the Android version?
> > 
> > 
> > 0.37.3
> 
> not app version, android version?

android 10 (my device) and android 13 (my brothers device)

**Comment by rafaelekol** [comment]
Already fixed by #6999
