### ISSUE TITLE
Another bug in UW with Tron

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7100]
so, this bug is also only with Tron contract addresses of coins.
1. Open UW and go to Coins Manager
2. click on the info icon of coin that is on a blockchain with a contract address
3. You will see the contract addresses of BSC, POLYGON, OPTIMISM,ETH etc with the globe icon that lets you to their website.
4. However By clicking that info button on any coin that is on Tron, that globe button is missing.
![Screenshot_2024-02-19-21-19-34-85](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/8d2a22d7-6a8c-4a8a-ad0d-9d54af01dd7d)
![Screenshot_2024-02-19-21-19-37-80](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/90c50ae0-4593-48d3-b250-aa60a8803d39)

**Comment by rafaelekol** [comment]
> Also, it will really be useful if you allow us to copy that contract address by clicking on it...

We intentionally removed address copy here. The reason is some users mistakenly can think that this is their Receive address.

**Comment by notpri** [comment]
@rafaelekol i just sent some TRX to my wallet and they are received but still the transaction is not showing up. Make sure this is fixed in 0m38
![Screenshot_2024-02-20-16-54-33-40](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/58cf9948-fbff-4324-9bdd-83a76eca143b)

**Comment by notpri** [comment]
@rafaelekol i never sent a TRC12 token, here in transactions tab this history is shown.
![Screenshot_2024-02-26-08-03-47-15](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/1e263640-965e-4b74-8256-07009e582b49)
![Screenshot_2024-02-26-08-03-50-74](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/fe70aac2-79bc-4f53-bc79-456a1db76284)
