### ISSUE TITLE
Tether 

### ISSUE THREAD

**Issue by DeadSecTr** [horizontalsystems/unstoppable-wallet-android#7111]
Where can i find tether USDT?
How can i enable it? I need it :(

**Comment by notpri** [comment]
> Where can i find tether USDT? How can i enable it? I need it :(

when you open wallet, There will be an icon opposite the Balance written, see in image
![Screenshot_2024-02-21-21-37-02-96](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/d3010351-cacc-4f73-a501-286b2574df13)

**Comment by notpri** [comment]
the  below swap.button is the icon im talking about, then there will.be a search icon and there search for it

**Comment by notpri** [comment]
> Thx...to clearify that...i must firt swap my coins to tether so that can show in my wallet?
> 
> Is that correct?
> 
> (Sorry for my bad english)

no

**Comment by notpri** [comment]
> How i do that then?

open your wallet a

> ![Screenshot_20240221-180143.png](https://private-user-images.githubusercontent.com/90558189/306709234-947cdca8-1401-4259-9ca9-c8f374679dd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MzUyMzMsIm5iZiI6MTcwODUzNDkzMywicGF0aCI6Ii85MDU1ODE4OS8zMDY3MDkyMzQtOTQ3Y2RjYTgtMTQwMS00MjU5LTljYTktYzhmMzc0Njc5ZGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE3MDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZjI2OTM0MDQ1N2Y1NDI3NTg4MzIzOWNjYjcyOTYwOThhZGZmNGU2OGI3ZTg3OGViZjljYWY0Y2IzOWM2MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pBrFe5kXi4cietcc1ykONP79CfLLbGCt1WbzMyq0Cxg)
> 
> There is no tether to activate

there is the 🔍 icon click on it and type usdt. But be advised that if you want to transfer USDT on TRC20 then you will first need to activate the tron wallet by transfering at least 1TRX to it.

**Comment by notpri** [comment]
if its solved the  you ca close the issue :)

**Comment by notpri** [comment]
> One last question:
> 
> Why dont show me withdraw not in my tether wallet?
> 
> That say i must activate with withdraw for the first time,i did it.....but nothing happens

can you send a screenshot?

**Comment by notpri** [comment]
> ![Screenshot_20240221-182051.png](https://private-user-images.githubusercontent.com/90558189/306714700-e0920a76-5394-4265-969c-d79ba6356e7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MzY0MTgsIm5iZiI6MTcwODUzNjExOCwicGF0aCI6Ii85MDU1ODE4OS8zMDY3MTQ3MDAtZTA5MjBhNzYtNTM5NC00MjY1LTk2OWMtZDc5YmE2MzU2ZTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE3MjE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4OWU0Nzk3M2ZhOTk4MzEwZGZiNTBmODIwMGU1MzEzOWVkYTI5ZTc4ZDlkNTE4MmQ3MGI1NTZjZTA1ZDFhMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DGUO-i4diiFyDzWBbJB0ubfxO_zgJvflgWxgaVFKGOE)
> 
> Thats in german

i dont know whats written but if you are receiving USDT on Tron , then you first need to activate the wallet by sending atlast 1 TRX to your TRX address of Unstoppable wallet

**Comment by notpri** [comment]
> Ok thanks... Must it be 1 TRX or it can more at least 1 TRX? Like 10TRX (1 for activate 9 for wallet?)

it can be any amount you want, and also you will lose nothing, all it wants to activate the Tron wallet is a TRX transaction. you will get all your TRX

**Comment by notpri** [comment]
> > Your first incoming transaction will be charged of 1 TRX by the network.
> > So if one the first time send you 10 TRX, you will receive 9. 1 TRX is charged for "account activation". You pay it once.
> 
> I did it...but nothing happens... It shows 0 and says "inactive"
> 
> How long it takes to activate?

restart the Wallet

**Comment by notpri** [comment]
serrq is right and my advice for you is to buy as much TRX as you can and hold them in your Unstoppable wallet as TRX is very low price of today and it will be $1 soon. So buying and holding TRX is a great choice.

**Comment by notpri** [comment]
> > serrq is right and my advice for you is to buy as much TRX as you can and hold them in your Unstoppable wallet as TRX is very low price of today and it will be $1 soon. So buying and holding TRX is a great choice.
> 
> Thx for the info,i will do that soon a.p

also make sure to never invest all your funds in 1 coin. Balance them and invest in others too. not just TRX

**Comment by abdrasulov** [comment]
@serrq @notpri, you guys rock

**Comment by notpri** [comment]
> What about the new Bitcoin fork? I heard that Bitcoin community is on the way to fork. However I cannot understand what new ticker they have choosen.

i also dont know about the new fork, if you know tell me. I will have a look at it

**Comment by notpri** [comment]
> What about the new Bitcoin fork? I heard that Bitcoin community is on the way to fork. However I cannot understand what new ticker they have choosen.

Whats your  X and Telegram? we can be good.

**Comment by notpri** [comment]
> I don't use Social networks. I am a literature man, so I prefer more relaxed books rather than social networks.
> 
> I discontinued Facebook (and all Meta accounts) in 2019. Google in 2022, after I discovered Fdroid and NewPipe as Play Market and YouTube replacements.

https://simplex.chat/invitation#/?v=1-4&smp=smp%3A%2F%2FenEkec4hlR3UtKx2NMpOUK_K4ZuDxjWBO1d9Y4YXVaA%3D%40smp14.simplex.im%2F_OjLrzEr_A0u654xQEB4UZb1tn5kSRZt%23%2F%3Fv%3D1-2%26dh%3DMCowBQYDK2VuAyEAQwMwFfW92CYNTHaqDg_5RynUEyML5lRWQSWQp-nt_Rs%253D%26srv%3Daspkyu2sopsnizbyfabtsicikr2s4r3ti35jogbcekhm3fsoeyjvgrid.onion&e2e=v%3D1-2%26x3dh%3DMEIwBQYDK2VvAzkA5KWb6UBlhepCCZjRqgjYHmWDxUXxMA2wK823xcgpb6Ujm0zNzXwgXBjal4I_qaMaADIEtC8DOdA%3D%2CMEIwBQYDK2VvAzkAp9jZs0XW6zc6FyoRJQQbCFYghe2gv8j_1spfWkIXey8l6ZVR4FY2Qnqe2njWVJYv8QrcNaaBv_I%3D
