### ISSUE TITLE
Tor 

### ISSUE THREAD

**Issue by DeadSecTr** [horizontalsystems/unstoppable-wallet-android#7114]
If tor activated,the app try's to connect then crashes.

After that the app doesnt start anymore it  crashes continuesly

**Comment by rafaelekol** [comment]
Can you share your Android version, device name. Do you use other VPN?

**Comment by rafaelekol** [comment]
I tried enabling Tor with pdnsf app installed. I couldn't reproduce this crash.

**Comment by rafaelekol** [comment]
@DeadSecTr The problem is with Solana initial sync.
pdnsf and Tor and enabled Solana causes crash.
To restore without deleting app, you can turn off internet, open app and disable Solana, or Tor
We will release hotfix ASAP
