### ISSUE TITLE
Text enhancement: Sent and Received

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7115]
In my opinion it makes more sense text in past, because these actions belong to the past (history). This is made in order to improve understanding.

![1000106276](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/1ed458f2-6f30-421b-b1f9-a2ffd005713c)

**Comment by notpri** [comment]
> Thanks guys. I sent you a donation. No way to lighten the TRX fees next time?
> 
> ![1000106279](https://private-user-images.githubusercontent.com/113377431/306904518-3321e00e-2b7a-429e-89aa-b5b691cd2300.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODczNjEsIm5iZiI6MTcwODU4NzA2MSwicGF0aCI6Ii8xMTMzNzc0MzEvMzA2OTA0NTE4LTMzMjFlMDBlLTJiN2EtNDI5ZS04OWFhLWI1YjY5MWNkMjMwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQwNzMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDAyYWVmYTZlOGZkNGYzZjRhODgxMzQxZjFlNjRlMDNkNmVlZWMxMGNlZTUxOTNmNjJkODhjNTVlMjA5MjRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jcvfi_1BsPWsshpRPAUiIf8zy0x8Ddl2_r4_zAdwin0)

i have that in mind too. It should be "Sent" and "Received" but i didnt opened issue because i want other bugs to be fixed.

**Comment by notpri** [comment]
> Thanks guys. I sent you a donation. No way to lighten the TRX fees next time?
> 
> ![1000106279](https://private-user-images.githubusercontent.com/113377431/306904518-3321e00e-2b7a-429e-89aa-b5b691cd2300.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODc1MTgsIm5iZiI6MTcwODU4NzIxOCwicGF0aCI6Ii8xMTMzNzc0MzEvMzA2OTA0NTE4LTMzMjFlMDBlLTJiN2EtNDI5ZS04OWFhLWI1YjY5MWNkMjMwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQwNzMzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmYyYzdkNDAxODBmZDQ1YmVlMWFiMmQ3Zjg5OTdlMWY5ZmUyZWI4MDYzYWViYjA1ODRlZDkyOTNjZTUzNzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sfknjX_kRus85deF4ZqH1Wf27OAGCp3b3kM49KpxUT8)

is the fee always that high on Tron?

**Comment by ealymbaev** [comment]
@notpri @serrq 

1. These `Sent` and other texts have already been changed in 0.38.
2. We are investigating high TRON network fee issue and will get back to you soon

**Comment by abdrasulov** [comment]
Texts will be updated by #7116
