### ISSUE TITLE
TRON high network fee issue

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#7116]
Issue created from https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7115#issuecomment-1958853667

**Comment by notpri** [comment]
> I believe that this isn't an error, but the natural consequence of not staking TRX.
> 
> Because staking TRX it allow to earn bandwidth/energy for transactions fees.
> 
> Thus no stacking, no earn energy points. And so you pay every time high fees.
> 
> Just a my feeling.

if what you said is true than i will avoid Tron network but i think you are wrong because a few days ago i transferred TRX from my UW to bybit and fee was 1.1TRX ( which is still high because in Binance the fee is 1TRX).

**Comment by Dianaaiym** [comment]
The fee in the Tron network depends on the type of transaction and is paid for using resources such as Bandwidth Points (BP) and Energy. Transactions involving TRC-10 tokens utilize Bandwidth Points, while transactions with TRC-20 tokens require both Bandwidth Points and Energy. If a user lacks these resources, fees can be paid in TRX. The calculation of the fee is based on the number of bytes in the transaction, and for TRC-10 token transactions, it is 1 BP per 1 byte. In contrast, the fee for TRC-20 token transactions depends on the specific smart contract involved.
