### ISSUE TITLE
Blocked by Adblock

### ISSUE THREAD

**Issue by DeadSecTr** [horizontalsystems/unstoppable-wallet-android#7117]
Should I whitelist these red ones? Or are they irrelevant and can be blocked? 
I'm using pdnsf and these entries are being blocked.

![Screenshot_20240222-151120.png](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/90558189/686620c9-a23f-4962-ab14-31dc18c3ad27)

**Comment by abdrasulov** [comment]
Yes, they should be whitelisted. The app uses those domains for bitcoin-based blockchains syncing
