### ISSUE TITLE
Support Kaspa (KAS)

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7121]

**Comment by notpri** [comment]
Update: @serrq @abdrasulov @rafaelekol 
Kaspa is available in ipad versions of UW but not in the android version. Here is the image my friend sent me taken of his ipad and kaspa is available for him but we don't have kaspa available in android. 
![IMG-20240224-WA0003](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/097cd838-ec6f-47e5-a054-1105d159e703)

**Comment by notpri** [comment]
> Yes, Kaspa ($KAS) blockchain in UW is also a my need.

its the need of you, me and all my friends too. I don't know when will they support it.

**Comment by notpri** [comment]
@abdrasulov @rafaelekol Please 🙏 support this chain.

**Comment by notpri** [comment]
@abdrasulov please assign someone to this also, I dont trust exchanges and wants to move my KAS to UW. for more about Kaspa:
[https://kaspa.org](url)

**Comment by notpri** [comment]
> Instead praying, try to solve the problem in another way: find sponsors for the development team in order to have the possibility to hire more developers. This makes sense. They are a small team that relies on their own (financial) strength.
> 
> It needs sponsorship. Thus the team can grow. Just my opinion.

i know that but I don't know how to get more developers.

**Comment by notpri** [comment]
> > @serrq this is link to my twitter profile. I just created it recently and will start spreading the word about UW.[Twitter](https://twitter.com/SpellBTrader/status/1763562759805911446?s=19) See the post and my bio.
> 
> It would be more correct (in my opinion) to ask their permission before attempting any action.
> 
> Maybe they don’t want or feel bothered by this unsolicited "attention".
> 
> Why? Imagine a beautiful woman who is about to open the door of her car, you arrive and as a gentleman you open the door, but she just did not want your attention, she turns angry and leaves without thanking you.
> 
> Bottom line: it’s better to ask if you can help than just help.

They liked my post.

**Comment by notpri** [comment]
> About your Twitter "Spread the word" post.
> 
> There isn't no reference to "hire new developers or sponsorships" for built our financial freedom.
> 
> Just you written "Okay, it is open source, I suggest it", in summary.

then what should I write? I tried to explain what UW is.

**Comment by notpri** [comment]
![Screenshot_2024-03-03-23-02-25-33](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/6bc6ec3c-3d27-44da-b663-f33b9fba7ed8)
just typed K in markets tab and see what comes first.

**Comment by notpri** [comment]
@rafaelekol @abdrasulov I am in touch with Kaspa team, If you needed help with integration then Just reply to me here.

**Comment by Dianaaiym** [comment]
Currently, there are no plans to support Kaspa. Thank you for your suggestion!
