### ISSUE TITLE
Search bar: Add a clear function:

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#7138]
X icon to erase text in the search bar (market tab search)

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=81513-212797&mode=design&t=XSTioe3kQAyKdCuK-11

**Comment by notpri** [comment]
@rafaelekol we need this function in:
1. Swap option on the  balance screen
2. Send and receive options in balance screen
3. Markets tab
4. Donation tab
5. Contacts

**Comment by notpri** [comment]
@rafaelekol we need this function in Contacts search as well.
