### ISSUE TITLE
TON wallet address is different

### ISSUE THREAD

**Issue by arkadym** [horizontalsystems/unstoppable-wallet-android#7143]
It is related to [#7108](https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7108) - i did an test: 
1) Using Unstoppable created new wallet with 24 words, created BNB, BTC, ETH, ARB, AVAX, TRX, TON to the waller. 
2) Took same seed (24 words) imported wallet to TrustWallet - all the addresses are same except TON, somehow TON address is different
3) Took same seed and imported wallet to SafePal - same issue, all is ok except TON. 
4) Tried use native ton wallets: MyTonWallet, Toncoin wallet, Tonhub, Tonkeeper, Tonkeeper X. All except Tonkeeper X cannot restore with error 'words are incorrect'. Tonkeeper X - did restore, but address is different, actually all 3 addresses are different.

Concluding in total - TON wallet cannot be restore anywhere outside of Unstoppable. Btw, having TON wallet created i dont remember exactly which app (one of above, mostly it was Toncoin wallet), and can now restore in any of above TON specific wallets. But cannot restore (invalid seed phrase) in any of Unstoppable, TW, SafePal.

What i would be glad is - having something compatible with TON wallets. Creating seed which will work there, allow choose network version...

**Comment by notpri** [comment]
Also note that the old addresses are linked to your wallet so you can also use the old addresses again and again even if UW shows a new one.

**Comment by arkadym** [comment]
Did few steps further
1) sent TONs to SafePal - TW and UW cannot see it
2) send TONs to TW - UW can see, SP - cannot (obviously)
3) send TONs to UW - TW can see, SP - cannot.
So yet it is confirmed, TW using old EQ address and UW using modern address UQ (prefered) but in fact it is same wallet.

Ticket can be closed, probably to add that somewhere.

Yet still there is an issue with seed compatibility between UW and TON wallets. Would appreciate if that can be done. It could be separate single crypto wallet for TON, like TW when creating/importing wallet it asks if that multi crypto of single crypto wallet.

And yet would be super great to have private key for TRON and TON.

**Comment by Dianaaiym** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7429
