### ISSUE TITLE
UW passcode issue

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7147]
So I don't think of a title for this issue.
A month ago I download Unstoppable wallet version 0.37.2. And setted up a passcode of "091258". Then 1 week ago, I tested duress mode. Setted passocde for duress "125800".
Then , after the release of 0.37.4 l, I deleted UW   and reinstalled from playstore. Now, I setted passcode "125800" after installing when 0.37.4 was released. Today I settee passcode for duress mode. Now, I tried to set "091258" for duress mode and UW says its already used. Then i tried 125800 and UW again says it is already used. So , here I dont know if UW is checking a file and how is this happening. I have no idea , i just tried to explain it.

**Comment by notpri** [comment]
in short , once you set passcode in UW (duress mode or not). And then reinstall and use one of those passcodes then you can use it for simple lock but not for duress mode.

**Comment by rafaelekol** [comment]
@notpri What is your Android version?

**Comment by notpri** [comment]
@rafaelekol Android version: 10 , Device RMX2030

**Comment by rafaelekol** [comment]
@notpri we can't reproduce this bug

**Comment by notpri** [comment]
> @notpri we can't reproduce this bug

not a big problem for me. Please focus on Kaspa. Thanks!
