### ISSUE TITLE
Impossible verifying a contract address after one has added it

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7149]
Please, might you adding an "i" button that shows (popup) a copyable contract address?

![1000106397](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/5f7f7e66-ecef-445c-a8d4-2324af81ca1a)

**Comment by abdrasulov** [comment]
You can see the contract address for all enabled tokens in the Coin Manager screen.

**Comment by notpri** [comment]
> Ok, thanks. Might you make that field copyable? In example if I want sending that contract address to a friend days later the added.

it was copyable before, they removed the copy function on purpose saying that people thinks of it as their wallets receive address and use it wrong.

**Comment by notpri** [comment]
> Mmm okay.

their idea of removing the copy function from there is good as you can always click on the globe icon to explore and copy it from there + newbies won't be able to use the wrong address for receiving coins.
