### ISSUE TITLE
CEXs integration: FF and Exchang

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7155]
These two (centralized) exchanges have the best swap rates in the market (currently).

FixedFloat is a little more money saving than Exchang, but unfortunately it hasn't all the pairs.

With these two exchanges I cover all my needs (when a dex it is not available).

“No registration and no need to share your personal details.”

https://ff.io/

https://exchang.io/

**Comment by notpri** [comment]
As far as I know UW is focused on DEX not CEX. CEX are not my choice either way.
