### ISSUE TITLE
(KYC free) Ethereum buying provider integration

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7156]
This broker sell Ethereum (ETH) and IOTA coins with only signup process (email + password). No KYC procedure is needed. No identity card, etc. More crypto are coming soon.

Daily order limit: 699€
Monthly order limit: 20,000€

Just you have to send them a SEPA bank transfer in order to convert your FIAT (EUR) to ETH.
Conversion takes about 1-3 days. 
Minimum order 15€.

I would like to login directly within UW, generating a unique token from the provider website account.

If UW team is interested:

https://www.viviswap.com/

**Comment by notpri** [comment]
> This broker sell Ethereum (ETH) and IOTA coins with only signup process (email + password). No KYC procedure is needed. No identity card, etc. More crypto are coming soon.
> 
> Daily order limit: 699€ Monthly order limit: 20,000€
> 
> Just you have to send them a SEPA bank transfer in order to convert your FIAT (EUR) to ETH. Conversion takes about 1-3 days. Minimum order 15€.
> 
> If UW team is interested:
> 
> https://www.viviswap.com/

thats a no , telling you in advance, We already have swap with exchanges like 1inch and for what you are looking for: Bisq is the answer.

**Comment by notpri** [comment]
> This broker sell Ethereum (ETH) and IOTA coins with only signup process (email + password). No KYC procedure is needed. No identity card, etc. More crypto are coming soon.
> 
> Daily order limit: 699€ Monthly order limit: 20,000€
> 
> Just you have to send them a SEPA bank transfer in order to convert your FIAT (EUR) to ETH. Conversion takes about 1-3 days. Minimum order 15€.
> 
> If UW team is interested:
> 
> https://www.viviswap.com/

you can buy any coin you want from Bisq.network. Check that out and then send it to your UW.

**Comment by notpri** [comment]
> This broker sell Ethereum (ETH) and IOTA coins with only signup process (email + password). No KYC procedure is needed. No identity card, etc. More crypto are coming soon.
> 
> Daily order limit: 699€ Monthly order limit: 20,000€
> 
> Just you have to send them a SEPA bank transfer in order to convert your FIAT (EUR) to ETH. Conversion takes about 1-3 days. Minimum order 15€.
> 
> I would like to login directly within UW, generating a unique token from the provider website account.
> 
> If UW team is interested:
> 
> https://www.viviswap.com/

and I do believe you might also have accounts in CEX like binance, You can always buy from there and transfer to UW (what others do including myself)

**Comment by notpri** [comment]
> I cannot using Bisq and that require a desktop PC. I haven't it. It requires some tech skills. I looking for an easy way.

then probably CEX is your answer.

**Comment by notpri** [comment]
> I cannot using Bisq and that require a desktop PC. I haven't it. It requires some tech skills. I looking for an easy way.


> I cannot using Bisq and that require a desktop PC. I haven't it. It requires some tech skills. I looking for an easy way.

you can use their websites in mobile too and your are using Graphene OS which have restricted mode for apps like binance and other apps.

**Comment by notpri** [comment]
> Hey Robin Hood you don't know your enemy. Greeting for your "out of standard" life.

the biggest downsides in the exchange you suggested are 1. Profiling system through which they track all your activities 2. Conversion in 3 days.
