### ISSUE TITLE
BTC Lightning Wallet Research & Dev

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#716]
- [ ] research Lightning Network
- [ ] prepare task list for other domains (do we need to setup a lighting node or any other infrastructure? This information should be provided in advance so that everything is ready once integration starts)
- [ ] Lightning wallet will appear as any other wallet in the list, https://github.com/horizontalsystems/bank-wallet-android/issues/737

**Comment by rafaelekol** [comment]
[Lnd](https://github.com/lightningnetwork/lnd) Lightning Network Daemon - is a complete implementation of a Lightning Network node. lnd has several pluggable back-end chain services including btcd (a full-node), bitcoind, and [neutrino](https://github.com/lightninglabs/neutrino) (a new experimental light client).
I think Neutrino (light client) will help us understand how to become light client in Lightning Network.

**Comment by rafaelekol** [comment]
> The redesigned Lightning App bundles lnd and is meant to run as a standalone wallet in light client mode (using Neutrino, BIP 157 + 158) both on desktop as well as mobile devices. By default the app will connect to a bitcoin full node cluster hosted by Lightning Labs. As Neutrino support progresses however, we will remove our hosted cluster. Optionally, users can also run their own full node and have the app connect to it if they want to. Users do not however need to run a separate lnd node. The goal is to build an application that is easily approachable and that can simply be opened with a double click.

https://blog.lightning.engineering/announcement/2018/09/10/lightning-app.html

**Comment by rafaelekol** [comment]
> The primary problems that Neutrino addresses are the leakage of information with bloom filters in SPV nodes that can be used to deanonymize users and to provide a more user-friendly experience while retaining a non-custodial, secure and decentralized wallet.

https://blockonomi.com/bitcoin-lightning-network-neutrino-protocol/

**Comment by rafaelekol** [comment]
Technical details about Neutrino

> Neutrino is based on the chain of ‘filters’ that each correspond to a block in the Bitcoin blockchain. These filters use a special compression algorithm called Golomb-Rice coding to represent the addresses contained in a block. Neutrino filters (called GCS filters, for 'Golomb-Coded Set') are a much more compressed way of representing a block and are ~15KB each, whereas the source blocks can be over 250 times as large (up to ~4MB).

https://finrazor.com/news/lightning-labs-releases-light-client-protocol-neutrino

**Comment by esengulov** [comment]
Upon the completion fo the research and several meetings with the protocol team we decided to postpone this task to the future. At this point the implementation fo the lighting within the wallet in  a desired manner (fully decentralized and yet user friendly) seems a bit costly in terms of time. We are estimating over 6 months of work ... not justifiable at this point.
