### ISSUE TITLE
XEC fee is higher when I try to send some amount but lower when I try to send Max amount

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7166]
When I try to send lower amount of XEC, the fee is a bit higher campared to sending max amount. Is that supposed to be like that or is it a bug? See in images below.
![Screenshot_2024-03-05-15-06-05-33](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/a9c24e5c-0582-420c-bac7-e52e20416b6c)
Lower amount = 2.26xec fee
![Screenshot_2024-03-05-15-06-09-69](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/e2ec3352-d09a-4638-a7fd-1eb73a7b02b3)
Max amount = 1.92xec fee

**Comment by abdrasulov** [comment]
The fee depends on the transaction size. The transaction is built from inputs and outputs. The transaction will have only one output when you send the whole available balance. And when you send less it will have 2 outputs. The 2nd output is a change output. It leads to a bigger transaction size. That is why the fee is higher. It is true for all bitcoin-based blockchains, like BTC, BCH, LTC, Dash, eCash
