### ISSUE TITLE
What is happening with ETH gas fees?

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7167]
Solutions to lower fees?

![1000107821](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/9baaddba-7731-4c74-9a2e-c94358181dc6)

**Comment by notpri** [comment]
> Solutions to lower fees?
> 
> ![1000107821](https://private-user-images.githubusercontent.com/113377431/310122533-9baaddba-7731-4c74-9a2e-c94358181dc6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NjMzODksIm5iZiI6MTcwOTY2MzA4OSwicGF0aCI6Ii8xMTMzNzc0MzEvMzEwMTIyNTMzLTliYWFkZGJhLTc3MzEtNGM3NC05YTJlLWM5NDM1ODE4MWRjNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxODI0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2VhMTJhOWI1NjEyNzI3ZjRkZjYwNTU2MWRiN2FiYjM4ZDVlM2RlNWFkZDY0ZmU3OTg2Yjc5MjBmNjc4ZDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fVT43Msi8ZDyPrNijM4NeolM-pNZTjbBohz3w_SW4tw)

that not an UW problem, my friends using other wallets paid upto $141 per transaction, ETH not good for any of us. Only rich people afford to use ETH
