### ISSUE TITLE
Settings: Add links to our telegram and twitter 

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#7169]
Remove the "experimental" section from Settings, the timelock option should appear in the advanced settings

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=85759-60195&mode=design&t=LjMm7UEAUAjXOdZ8-11
