### ISSUE TITLE
Visualization of a long balance amount in a small display: a trick to shorten its length (good to know)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7171]
We often have numbers very long. This means amount like 0.0000003487.

The number above can also be represented as follow: 0.0₆3487.

Could it be useful in UW? I find it a brilliant solution.

![1000107832](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/533db7ce-3cd4-441e-9f3f-b4099eb29123)

**Comment by notpri** [comment]
No, The current normal display is ok for me.
