### ISSUE TITLE
Use DiffUtils in Transactions List 

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-android#718]

**Comment by rafaelekol** [comment]
I tried to implement DiffUtils, but it involved to change significantly code in TransactionPresenter and other Module classes. After discussing it with @abdrasulov we decided not to merge this #793 code since Android code will become different from iOs project.

**Comment by rafaelekol** [comment]
After doing research for better solution to show Transaction List on Android phones I came up with following:

> I think it would be better to use app database that will store all transactions.
> For showing these transaction Android has Paging Library(that already includes DiffUtils inside it).
> https://developer.android.com/topic/libraries/architecture/paging
> When use will click on Coin filters we will just make different queries to database.
> When some data updates in database it will automatically update in recyclerview list via this library.
