### ISSUE TITLE
How to work the gas fees in Arbitrum network?

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7180]
Is not ARB the native token of this chain?

In Arbitrum network must I paying fees with ETH (Arbitrum) or ETH (Ethereum)? I didn't understand.

![1000107871](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/93f9eb1c-cf7d-4965-a1f2-853bfe83d6ae)

**Comment by abdrasulov** [comment]
ETH (Arbitrum) is the currency used to pay gas fees on Arbitrum
