### ISSUE TITLE
TON balance loading

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7186]
Don't know if its a bug or not. Only found it to happen with TON.
![Screenshot_2024-03-12-10-21-34-39](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/b2637469-627e-44a4-92d0-42164c82933a)
Check the "Available Balance" . It loads after 2-3 seconds like it gets the balance from internet.

**Comment by abdrasulov** [comment]
It should get the account state from the internet for available balance
