### ISSUE TITLE
Support for Base, Celo and Metis (EVM)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7195]
These are three satellites (L2) of Ethereum (L1) mainnet, like Optimism and Arbitrum.

More scalable than L1, thus they ask for less gas fees.

Easy to implement in already existing Ethereum environment.

Base
https://www.base.org/

Celo
https://celo.org/

Metis
https://www.metis.io/

**Comment by Dianaaiym** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/pull/7684
