### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by d4f5409d** [horizontalsystems/unstoppable-wallet-android#7222]
$WIFI - https://www.coingecko.com/en/coins/wifi
$NEOX - https://www.coingecko.com/en/coins/neoxa
$SHRAP - https://www.coingecko.com/en/coins/shrapnel

**Comment by Dianaaiym** [comment]
Icons for these tokens are now displayed. Please check our latest version 0.39

**Comment by d4f5409d** [comment]
We are still unable to see Wifi token icon because UW doesn't recognize well the contract address.

**Comment by Dianaaiym** [comment]
> We are still unable to see Wifi token icon in the wallet section (search and data tab works fine) because UW doesn't recognize well the contract address.

For custom-added tokens, icons are not displaying yet.
