### ISSUE TITLE
Very long values as output when swapping no matter what coin or dex

### ISSUE THREAD

**Issue by d4f5409d** [horizontalsystems/unstoppable-wallet-android#7268]
![Screenshot_2024-04-04-09-20-18-67_c871ba0c2328d2f949307d9493eb5319.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/76624594/7b4b8951-e75d-476c-ba83-fec7a03112b3)

**Comment by abdrasulov** [comment]
It will be fixed in the upcoming release (#6945)
