### ISSUE TITLE
0.38 (early release): no transactions history for TRX

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7337]
![1000109104](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/f27434e4-d298-44a2-82bd-ac4afb311b98)

**Comment by Dianaaiym** [comment]
> ![1000109104](https://private-user-images.githubusercontent.com/113377431/323640423-f27434e4-d298-44a2-82bd-ac4afb311b98.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0Njg0MzcsIm5iZiI6MTcxMzQ2ODEzNywicGF0aCI6Ii8xMTMzNzc0MzEvMzIzNjQwNDIzLWYyNzQzNGU0LWQyOTgtNDRhMi04MmJkLWFjNGFmYjMxMWI5OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxOTIyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDE3Y2NhMDRlZjVhM2I1NmQwNzBmNTEzN2Y3MjYzODUwZDQ1Y2ViOWQzNGYxMGM1OWE0N2FiNWZhMTU0NWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FCpksD9FFi6ix0S6TsbIAyXhYlnCYKPmbCzoIIJuNZ4)

Hi,

The transaction history is available; we were unable to reproduce your issue.
![2024-04-19 01 22 55](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/9f4b3f44-d299-4a87-9de8-022a710b924b)
