### ISSUE TITLE
Switching wallets bug

### ISSUE THREAD

**Issue by Andreisbb** [horizontalsystems/unstoppable-wallet-android#7338]
I have several wallets in app, wallet 1 and wallet 2, if I switching between them synchronization to any token not working until I re-open the app and if I'm switching from wallet 1 to wallet 2 I will see wallet 1 transactions records in history tab. App V 0.38.0

**Comment by Dianaaiym** [comment]
duplicate https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7380
