### ISSUE TITLE
Minor Markets tab bug

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7345]
Fix this minor bug . The Blockchain icons not displayed.![Screenshot_2024-04-21-11-45-11-87.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/fd584faf-2506-448e-8ab9-25562873fc90)

**Comment by d4f5409d** [comment]
Related to #7223

**Comment by notpri** [comment]
no, its a bug

**Comment by notpri** [comment]
This icon issue is with many coins/tokens.
