### ISSUE TITLE
Please adding USDT and XAUT tokens on The Open Network (TON)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7346]
Recently Tether has added USDT (USD dollar) and XAUT (gold) tokens on The Open Network.

https://cointelegraph.com/news/tether-usdt-stablecoin-ton-blockchain

https://www.cryptonewsz.com/tethers-worth-stands-at-60-million-on-ton-blockchain/

**Comment by d4f5409d** [comment]
Wait there is XAUT on TON?

**Comment by d4f5409d** [comment]
Hold on, this is wonderful news!

**Comment by tmedetbekov** [comment]
> Any updates on this work? Planning for 0.40 will be okay?

USDT has already been added to TON, but as for XAUT, I couldn't find the official contract. If you have it, could you please share the link? I'll add it.

**Comment by Dianaaiym** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7430
