### ISSUE TITLE
Markets tab sync error

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7348]
MCap when selected for 5Y gives error.![Screenshot_2024-04-21-14-03-28-58.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/7391c04f-7791-45fc-ae18-528586c2e7a8)

**Comment by d4f5409d** [comment]
Same as #7347

**Comment by notpri** [comment]
![Screenshot_2024-04-22-13-27-19-62.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/c5dc0962-9f47-43e8-a073-443eb0bcd83d)

Update: The All button als gives sync error.
