### ISSUE TITLE
While syncing, I still experience unexpected slowness

### ISSUE THREAD

**Issue by d4f5409d** [horizontalsystems/unstoppable-wallet-android#7349]
Sluggishness bug didn't disappear completely. Maybe there are too much elements rendering on the screen, or at least this is what I am thinking of. Can you optimalize it even more? Other than the balance tab syncing, UW really did become faster and I can't see this sluggishness anywhere else.

**Comment by abdrasulov** [comment]
@d4f5409d thanks for your report. We've applied all solutions we've found for performance optimizations in v. 0.38.0. We'll get back to this when we find other solutions
