### ISSUE TITLE
Wallet Connect: Can't change network from Ethereum -> Polygon

### ISSUE THREAD

**Issue by Weeb3Lulz** [horizontalsystems/unstoppable-wallet-android#7351]
in a lot of dapps when you first connect it connects you to ETH by default, then you can select from a list of other network that you want to connect, this functionally doesn't currently work in Unstoppable Wallet via walletconnect.
![uw](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/140255818/238bfa7f-69db-41c5-8f03-e4cc143483fe)

**Comment by Weeb3Lulz** [comment]
> UW version?

0.38.0 downloaded from https://f-droid.org/en/packages/io.horizontalsystems.bankwallet/

**Comment by abdrasulov** [comment]
It should have been fixed in v.0.38.3. Need to check
