### ISSUE TITLE
Coins/Tokens Icon not displayed.

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7352]
In recent v0.38 update, Many token/coin icons are not shown in the markets tab section areas. Like the one below![Screenshot_2024-04-21-21-53-03-16.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/113f9d93-4a07-426b-a1b2-6b0583711bc2)

**Comment by notpri** [comment]
![Screenshot_2024-04-24-23-03-04-16.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/2d6eca26-ce8b-432f-b99a-336f96e2a7a3)

![Screenshot_2024-04-24-23-05-28-82.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/743a764f-a5ef-4f3d-8ef6-b398eccd4f98)

No Icons... Coins search in Coin Manager tab

**Comment by Dianaaiym** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7223
