### ISSUE TITLE
Wrong info given when pasted invalid contract address for BEP2 chain

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7353]
Here, ![Screenshot_2024-04-21-21-58-45-97.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/1eee7e73-9cff-45f8-83a8-8cfe32db4353)

It should say "Invalid contract address" as it say for other chains. Newbies will be confused.

**Comment by abdrasulov** [comment]
That is a terminology used in BNB Beacon Chain
