### ISSUE TITLE
Unstoppable Wallet crashes when trying to connect to certain dapps

### ISSUE THREAD

**Issue by Weeb3Lulz** [horizontalsystems/unstoppable-wallet-android#7354]
tested on https://hey.xyz/ and https://www.lens.xyz/
scanning the walletconnect QR code works fine
however when you click "Connect" the whole wallet crashes
after opening the wallet you can see the dapp in the "Paired dApps" list but you cannot interact with the dapp in any way (cannot sign messages/transactions etc..)

tested on android 9 on the latest version of unstoppable wallet from f-droid

**Comment by abdrasulov** [comment]
We are working on this issue

**Comment by rafaelekol** [comment]
@Nyanraltotlapun opened this problem as separate issue #7371
