### ISSUE TITLE
Unintialized TONCoin address

### ISSUE THREAD

**Issue by imto1** [horizontalsystems/unstoppable-wallet-android#7372]
I've sent some TONCOIN to my wallet today. But i didn't receive my TONCOIN. I've checked the transaction on tonscan.org and the transaction status is success. But when I checked my address, The state is inactive and int contract tab this message displayed:
**Uninitialized address**
_This address doesn't contain any data in blockchain — it was either never used or the contract was deleted. Now it just aimlessly floats in the digital void._

What's goes wrong?

My TONCOIN address is: UQDCiBdozS4CqTXw0eYE9WO5ayDIWK57z501GPad9h4KsB01

 
App Info:
   - Current Time: Apr 26, 2024, 21:30
   - App Version: 0.38.1
   - Installed from f-droid
   - Device Model: HMD Global Nokia 6.1
   - OS Version: Android 14 (34)

Version History:
   - 0.38.1: Apr 26, 2024, 19:16

Wallets Status:
   - MultiCC:
     - Origin: Restored
     - Type: 12 words with passphrase

Blockchain Status:
   - Bitcoin-BIP84:
     - Sync Mode: Blockchair
     - Synced Until: Apr 26, 2024, 21:16
     - Syncing Peer: N/A
     - Derivation: bip84
     - Sync State: Synced
     - Last Block Height: 840984
     - Peer 1:
       - Status: Synced
       - Host: 84.247.180.248
       - Best Block: 840985
       - User Agent: /Satoshi:26.1.0/
       - tasks: no tasks
     - Peer 2:
       - Status: Synced
       - Host: 89.116.31.110
       - Best Block: 840985
       - User Agent: /Satoshi:27.0.0/
       - tasks: no tasks
     - Peer 3:
       - Status: Synced
       - Host: 154.26.137.105
       - Best Block: 840984
       - User Agent: /Satoshi:25.1.0/Knots:20231115/
       - tasks: no tasks
     - Peer 4:
       - Status: Synced
       - Host: 165.22.227.235
       - Best Block: 840987
       - User Agent: /Satoshi:0.20.1/
       - tasks: no tasks
     - Peer 5:
       - Status: Synced
       - Host: 185.206.122.23
       - Best Block: 840984
       - User Agent: /Satoshi:26.0.0/
       - tasks: no tasks
     - Peer 6:
       - Status: Synced
       - Host: 187.3.160.20
       - Best Block: 840986
       - User Agent: /Satoshi:25.0.0/
       - tasks: no tasks
     - Peer 7:
       - Status: Synced
       - Host: 87.236.195.198
       - Best Block: 840984
       - User Agent: /Satoshi:27.99.0/
       - tasks: no tasks
     - Peer 8:
       - Status: Synced
       - Host: 188.165.244.143
       - Best Block: 840984
       - User Agent: /Satoshi:0.18.1/
       - tasks: no tasks
     - Peer 9:
       - Status: Synced
       - Host: 51.75.242.135
       - Best Block: 840984
       - User Agent: /Satoshi:0.18.1/
       - tasks: no tasks
     - Peer 10:
       - Status: Synced
       - Host: 172.105.21.216
       - Best Block: 840984
       - User Agent: /Satoshi:25.1.0(@devinbileck)/
       - tasks: no tasks

   - BNB Smart Chain:
     - Last Block Height: 38204156
     - Sync State: Synced
     - Blockchain source: RPC API bsc-dataseed.binance.org
     - Transactions source: Infura, Etherscan

   - Ethereum:
     - Last Block Height: 19741171
     - Sync State: Synced
     - Blockchain source: RPC API api.blocksdecoded.com
     - Transactions source: Infura, Etherscan

   - Polygon:
     - Last Block Height: 56283255
     - Sync State: Synced
     - Blockchain source: RPC API polygon-rpc.com
     - Transactions source: Infura, Etherscan

   - Tron:
     - Started: true
     - Last Block Height: 61170602
     - Sync State: Synced
     - Chain Parameters Sync State: NotSynced UnknownHostException - message: Unable to resolve host "api.trongrid.io": No address associated with hostname

App Log:

Market Last Sync Timestamps:
   - Coins: 1712812046
   - Blockchains: 1712812046
   - Tokens: 1712812046

**Comment by rafaelekol** [comment]
I tried to watch your Toncoin address with Unstoppable app, and I can see your  balance and transaction.

**Comment by imto1** [comment]
I've removed and imported my wallet again. Nothing changed.
Is there any chance to import it in another wallet? I checked MyTonWallet and Tonkeeper. But they need 24 seeds to import wallet.

**Comment by imto1** [comment]
> I tried to watch your Toncoin address with Unstoppable app, and I can see your  balance and transaction.

I've contacted ton.org support about my problem and the responded as follow:

**Hello!
This address has 5.6 Toncoin. If the wallet does not display them, then the problem is with the wallet. We don't know what kind of wallet it is, if the 24 secret words are compatible with native TON wallets, you can install for example Tonkeeper (https://tonkeeper.com/) and import your address there.**

My wallet secret is 12 seeds with password. Is there any chance to convert it to 24 or something 🥴.
Thank you.

**Comment by imto1** [comment]
according to [this article](http://tonhelloworld.com/01-wallet/), It seems the address initialization smart contract will execute when the 1st outgoing transaction is done. To get this done we need to sent some TON Coin to somewhere. I tried to do this but Next button in Sent TONCOIN page remains disabled because of Insufficient balance message.
Is there any way to pass this warning message.
Do anyone experienced this situation like me?

**Comment by abdrasulov** [comment]
Hello @imto1,

The app should show your TON balance despite your TON address state.

The app correctly shows your TON address balance in watch-only mode as @rafaelekol mentioned before. The balance is equal to 5.6

Can you reimport your account and share your address and the balance?

**Comment by imto1** [comment]
> Hello @imto1,
> 
> The app should show your TON balance despite your TON address state.
> 
> The app correctly shows your TON address balance in watch-only mode as @rafaelekol mentioned before. The balance is equal to 5.6
> 
> Can you reimport your account and share your address and the balance?

I've done this before in multiple devices. But nothing changed!
