### ISSUE TITLE
Logo covers qr code. Feature request

### ISSUE THREAD

**Issue by johncenaaaaaaa** [horizontalsystems/unstoppable-wallet-android#7378]
Hello,

Thank you for creating Unstoppable wallet. It’s great and I love using it! I have perhaps a little bit silly problem with the wallet. Sometimes I use Unstoppable wallet to buy litecoins using a local bitcoin ATM machine in my town. Sadly the scanner in the bitcoin ATM machine I use is unable to properly read my qr-code from the wallet because there is Unstoppable logo covering big part of the qr code. It used to work just fine before you added this logo covering qr-code in an update sometime ago. Is there any chance the tech team can implement a new option in the app settings that would allow the user to disable this annoying logo covering my qr-code? I know that other wallets have such a feature in their settings. For example Selene wallet has such an option. I am attaching you pictures so that you can see what I am talking about. Please take a look at them. Can you please pass the message on to the tech team?

Best Regards,
Mathew

![Untitled](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/161508555/c9b57947-cffa-472a-83e3-6e9b4cc45b8f)
![Untitled](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/161508555/246e2d63-d880-45c4-a031-2c8b63ff49b7)

**Comment by d4f5409d** [comment]
We could make the QR smaller and when tapping on it the logo could disappear

**Comment by rafaelekol** [comment]
@johncenaaaaaaa 
The source of problem scanning QRcode with ATM camera should the small size of cubes in image.
In fix #7417, I enlarged the cube size within the QR code and reduced the logo size. This should significantly improve scannability for older camera technology. 
Also the covered qrcode part by logo is not lost entirely, remaining visible cubes has enough information to represent the data.
