### ISSUE TITLE
Issue arising when switching between wallets

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#7380]
- Restore the wallet with the TON enabled;
- Launch the wallet with TON;
- Switch between wallets;
- Notice that data from the previous wallet is retained upon switching.

https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/9ca22354-5051-4487-9692-fc50c4693df2

**Comment by abdrasulov** [comment]
We could not reproduce it. Closing for now
