### ISSUE TITLE
Markets: Implement new design for coins page

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#7382]
https://www.figma.com/design/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=88984-271719&t=F7UW7ZW3kgZGkeHM-0

**Comment by d4f5409d** [comment]
Will we finally be able to swipe between tabs? 👀

**Comment by Dianaaiym** [comment]
- [ ] Add filtering for the top 500

-[ ] Rename Top 100, Top 200, Top 300, Top 500

<img width="177" alt="Screenshot 2024-05-23 at 15 38 18" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/51ca0387-b845-487d-87e6-3bc95f0c8e3e">
