### ISSUE TITLE
Support for Kaspa

### ISSUE THREAD

**Issue by Pinipon73** [horizontalsystems/unstoppable-wallet-android#7389]
It would be very nice to see the Kaspa (KAS) token supported by this wallet.
Even though the project is quite new, it is more than interesting IMO, and although there're some wallets that support it already, Unstoppable Wallet I think is my primary app, and it would be very good if that's supported, said by a bitcoiner.

https://kaspa.org/

**Comment by notpri** [comment]
#7121

**Comment by Dianaaiym** [comment]
Currently, there are no plans to support Kaspa. Thank you for your suggestion!
