### ISSUE TITLE
QR Scanner fails to parse transparent addresses with a set amount

### ISSUE THREAD

**Issue by PirateDigger** [horizontalsystems/unstoppable-wallet-android#7391]
In case if QR CODE have additional information like amount or something else it can't parse string and app put everything to address

this one was generated service https://changenow.io/ and it doesn't work correctly

t1crSpFxxAEzWfbK4xMPtpbRmEsrM6NLUgp?amount=200

<img width="784" alt="Screenshot 2024-05-01 at 08 55 26" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/45685052/b8caded3-cdc9-46de-924e-5bd6a4bec179">

but in case add zcash: it will work:

zcash:t1crSpFxxAEzWfbK4xMPtpbRmEsrM6NLUgp?amount=200

<img width="1090" alt="Screenshot 2024-05-01 at 08 56 24" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/45685052/6711b637-d8e3-45e8-be96-979b03e4f3fc">

i think need to add improvements in case t1crSpFxxAEzWfbK4xMPtpbRmEsrM6NLUgp?amount=200

**Comment by Dianaaiym** [comment]
We cannot parse such addresses, as they could potentially be addresses for Solana
