### ISSUE TITLE
Native DASH can't sync

### ISSUE THREAD

**Issue by PirateDigger** [horizontalsystems/unstoppable-wallet-android#7392]
Both options Hybrid and Blockchain doesn't work for DASH

App Info:
   - Current Time: 1 мая 2024 г., 09:01
   - App Version: 0.38.3
   - Device Model: Xiaomi M2103K19PG
   - OS Version: Android 13 (33)

Version History:
   - 0.30.0: 22 февр. 2023 г., 10:19
   - 0.36.0: 9 нояб. 2023 г., 10:07
   - 0.36.1: 17 нояб. 2023 г., 18:54
   - 0.37.5: 21 мар. 2024 г., 20:12
   - 0.37.6: 10 апр. 2024 г., 21:50
   - 0.38.3: 30 апр. 2024 г., 21:47

Wallets Status:
   - Wallet 1:
     - Origin: Restored
     - Type: 12 слов

Blockchain Status:
   - Bitcoin-BIP84:
     - Sync Mode: Blockchair
     - Synced Until: 1 мая 2024 г., 08:06
     - Syncing Peer: N/A
     - Derivation: bip84
     - Sync State: Synced
     - Last Block Height: 841603
     - Peer 1:
       - Status: Synced
       - Host: 192.187.121.46
       - Best Block: 841603
       - User Agent: /Satoshi:0.18.1/
       - tasks: no tasks
     - Peer 2:
       - Status: Synced
       - Host: 74.96.184.197
       - Best Block: 841605
       - User Agent: /Satoshi:0.17.1/
       - tasks: no tasks
     - Peer 3:
       - Status: Synced
       - Host: 35.245.230.216
       - Best Block: 841605
       - User Agent: /Satoshi:0.20.1/
       - tasks: no tasks
     - Peer 4:
       - Status: Synced
       - Host: 54.217.136.122
       - Best Block: 841604
       - User Agent: /Satoshi:0.21.1/
       - tasks: no tasks

   - Dash-DASH:
     - Sync Mode: Blockchain
     - Synced Until: 1 мар. 2014 г., 17:18
     - Syncing Peer: N/A
     - Derivation: bip44
     - Sync State: Syncing-0.0
     - Last Block Height: 25992

   - BNB Smart Chain:
     - Last Block Height: 38333537
     - Sync State: Synced
     - Blockchain source: RPC API bsc-dataseed.binance.org
     - Transactions source: Infura, Etherscan

   - Ethereum:
     - Last Block Height: 19773355
     - Sync State: Synced
     - Blockchain source: RPC API api.blocksdecoded.com
     - Transactions source: Infura, Etherscan

   - Polygon:
     - Last Block Height: 56447842
     - Sync State: Synced
     - Blockchain source: RPC API polygon-rpc.com
     - Transactions source: Infura, Etherscan

App Log:

Market Last Sync Timestamps:
   - Coins: 1714464132
   - Blockchains: 1712812046
   - Tokens: 1714386112

**Comment by abdrasulov** [comment]
We could not reproduce this issue. Can you please update to the latest version 0.38.4 and check it once again?

**Comment by PirateDigger** [comment]
I'm in EU region and don't have any issues with peers. Also, i removed all blockchains except DASH and try to switch between hybrid / blockchain and it doesn't help

![2024-05-25 07 57 18](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/45685052/0145f868-2b02-4f8c-b5a9-cb095bf03322)
![2024-05-25 07 57 14](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/45685052/8959e922-987c-482d-8e6d-062c434f9155)

**Comment by PirateDigger** [comment]
I did change to Hybrid and swap wallet and it start syncing, looks like there is issue with blockchain type
