### ISSUE TITLE
Feat Req: Support for Base L2

### ISSUE THREAD

**Issue by nuke-web3** [horizontalsystems/unstoppable-wallet-android#7403]
I see Optimism has support, I wonder if there is plans to support Base directly? It's quite [close in many respects](https://basehub.org/docs/FAQs/how-is-base-different-from-optimism/) AFAIU  so I would think relatively easy to add).

**Comment by Dianaaiym** [comment]
completed https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7512
