### ISSUE TITLE
Link to UW reddit is a banned channel

### ISSUE THREAD

**Issue by notpri** [horizontalsystems/unstoppable-wallet-android#7406]
In Whats new tab , the icon of reddit leads to a banned channel.![Screenshot_2024-05-05-22-53-40-78.jpg](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/159254193/c4c4d13c-0979-4136-b843-3d0121c406ed)

**Comment by Dianaaiym** [comment]
will be fixed https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7412
