### ISSUE TITLE
0.38.3 Swap | coins' icons not aligned

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7413]
![1000111329](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/d25b1c93-f3be-417c-8655-19472ed3b58c)

**Comment by Dianaaiym** [comment]
There is no swap functionality between EVM chains Fantom and Arbitrumone

**Comment by abdrasulov** [comment]
They are right-aligned
