### ISSUE TITLE
Minor updates to  "Privacy" Pages

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#7427]
https://www.figma.com/design/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=85601-337968&t=OjK4C7qzDLOZCQh9-0)](https://www.figma.com/design/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=85601-337968&t=OjK4C7qzDLOZCQh9-0)

https://www.figma.com/design/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=90071-184526&t=OjK4C7qzDLOZCQh9-0

**Comment by kineita** [comment]
You said you don't collect any sensitive and wallet info, how do you know that wallet is eligible to participate in the airdrop distribution ?

**Comment by esengulov** [comment]
> You said you don't collect any sensitive and wallet info, how do you know that wallet is eligible to participate in the airdrop distribution ?

the ticket description is incomplete. there are a few things here:

1. there will be an option to turn on/off usage stats collection

2. those who decide to keep it on would be eligible to future airdrop IF THEY choose to share their EVM address. This is still need to be designed.
