### ISSUE TITLE
Add Support for eth_signTypedData_v4

### ISSUE THREAD

**Issue by 48-mq** [horizontalsystems/unstoppable-wallet-android#7442]
When trying to use WalletConnect with a DEX, I get the following error: Missing or invalid. request() method: eth_signTypedData_v4

Is this wallet not fully EIP-712 compliant?

**Comment by 48-mq** [comment]
Sure looks like it, thanks @serrq !

**Comment by abdrasulov** [comment]
This should be resolved by #7395
