### ISSUE TITLE
Pending Incoming Transaction not shown from Mempool

### ISSUE THREAD

**Issue by ghost** [horizontalsystems/unstoppable-wallet-android#7452]
I have an incoming BTC transaction which has been pending in the mempool for 3 days, is visible using several blockhain explorers, but is not being picked up by the wallet regardless of whether I sync directly with the Blockchain, with the blockchair API, or hybrid.

I can send the transaction ID by private message if needed, but would prefer to not post it publicly.

**Comment by 48-mq** [comment]
Thanks @serrq , why do you think this happened in the first place? Is there a way the app could have prevented it from occurring?
