### ISSUE TITLE
Question: How to access the NFTs section?

### ISSUE THREAD

**Issue by sbahrami-vz** [horizontalsystems/unstoppable-wallet-android#7463]
Hi,

Just opened it in the Android Studio and started playing around, seems like there is no visual section for the NFTs yet?

if so how can I enable and test it?

Thanks!

**Comment by sbahrami-vz** [comment]
Hopefully it comes back in the next release ⛓️

**Comment by sbahrami-vz** [comment]
I see in the last update v0.35, the NFT has been removed, what is the reason behind it? is it out of support for good? or ... are we going to get it back in the near future?

**Comment by sobhanb-eth** [comment]
Hi @serrq is it planned to have the NFT section back on the Android side? or it is completely gone for good?

**Comment by Dianaaiym** [comment]
> Hi,
> 
> Just opened it in the Android Studio and started playing around, seems like there is no visual section for the NFTs yet?
> 
> if so how can I enable and test it?
> 
> Thanks!

Thank you for reaching out with your question. We have removed the NFT section from our app to focus on enhancing other features.
