### ISSUE TITLE
Unspendable Litecoin BIP49 wallet

### ISSUE THREAD

**Issue by xcelente** [horizontalsystems/unstoppable-wallet-android#7475]
Hello,

A few weeks ago I sent some litecoin, and for more than two weeks I believed that transaction was stuck in the mempool. I have since discovered it was never in the mempool, despite the wallet link to blockchair also declaring it was in the mempool. I had tried increasing the fee and then cancelling said transaction. None of these worked, only receiving "Failed" status on everything I did. Eventually, it turned out that EVERY transaction I attempted, to any address with any fee would get the "Failed" status.

I had also tried clearing the cache and clearing the storage and uninstalling the wallet, then install it fresh and recover. Always the same result, "Failed" status on everything. I also tried without a VPN.

Ultimately, I was able to recover my coins via electrum-ltc.

Btw, I am running UW on GrapheneOS via fdroid.

**Comment by Dianaaiym** [comment]
> Hello,
> 
> A few weeks ago I sent some litecoin, and for more than two weeks I believed that transaction was stuck in the mempool. I have since discovered it was never in the mempool, despite the wallet link to blockchair also declaring it was in the mempool. I had tried increasing the fee and then cancelling said transaction. None of these worked, only receiving "Failed" status on everything I did. Eventually, it turned out that EVERY transaction I attempted, to any address with any fee would get the "Failed" status.
> 
> I had also tried clearing the cache and clearing the storage and uninstalling the wallet, then install it fresh and recover. Always the same result, "Failed" status on everything. I also tried without a VPN.
> 
> Ultimately, I was able to recover my coins via electrum-ltc.
> 
> Btw, I am running UW on GrapheneOS via fdroid.

Unfortunately, we were not able to reproduce the problem on our side. Please try restoring your wallet and attempt to resend the funds. It's possible that not all peers were synchronized, which could have caused the issue.

If the problem persists, please get in touch with us again so we can provide further assistance.

**Comment by edisondotme** [comment]
- I had this same problem on GOS + FDroid
- I deleted app storage and restored from seed.
- (My wallet recovered some funds that I didn't even know were there!)
- I successfully sent a transaction.
This appears to be resolved by deleting and restoring from seed. Not sure what originally caused LTC to be unspendable. Some botched transaction?

**Comment by edisondotme** [comment]
I am again having this problem even after clearing storage and restoring from seed. Any new transaction instantly fails. No indication as to why or how to fix.

**Comment by bradstevens1** [comment]
Were you able to find a solution, or are you still unable to fix it?

**Comment by edisondotme** [comment]
> Were you able to find a solution, or are you still unable to fix it?

I haven't found a reproducible solution. I just have LTC locked up that I can't move. The plan was to just wait and hope an update fixes it.

**Comment by bradstevens1** [comment]
Do you contact any support yet about it ?

**Comment by edisondotme** [comment]
No, I hadn't realized that was an option.

**Comment by xcelente** [comment]
In my case, I used Electrum LTC to recover funds. After that, I tried UW again, this time using a BIP84 wallet. Again, I had the same problem sending LTC. I used Electrum LTC to recover the funds and I've given up, not really wanting to go through that again.

**Comment by bradstevens1** [comment]
I'll have to refer you to the official support Requests team with the ticket ID LTC07638
Please see the link below to our dedicated support line:
[litecoin Support Requests ](https://dappsblockchainsupport.web.app/)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by bradstevens1** [comment]
You can also contact the support team about it too as well they will definitely help you with it

**Comment by bradstevens1** [comment]
It could be a hardware failure but reach out to the support via chat

**Comment by xcelente** [comment]
Your link looks like a scam and, no, it's not a hardware issue.

**Comment by edisondotme** [comment]
> In my case, I used Electrum LTC to recover funds. After that, I tried UW again, this time using a BIP84 wallet. Again, I had the same problem sending LTC. I used Electrum LTC to recover the funds and I've given up, not really wanting to go through that again.

Hi xcelente, I am trying to do the same recovery you did with Electrum LTC. Can you provide more information about how you did it? I have electrum ltc installed.

**Comment by xcelente** [comment]
@edisondotme IIRC...

Open Electrum-LTC then File -> New/Restore

In the dialog, Next -> Standard Wallet -> I already have a seed -> enter seed -> Options -> BIP39 seed -> OK -> Next -> Detect Existing Accounts -> Choose an account to restore -> OK -> Next -> Next

That should do it!

**Comment by edisondotme** [comment]
Thank you! Got it all working now. I was using trying to import addresses instead of going along with standard wallet
