### ISSUE TITLE
Wrong contract address for XTM token in token list

### ISSUE THREAD

**Issue by Nyanraltotlapun** [horizontalsystems/unstoppable-wallet-android#7538]
XTM token in token list have old abandoned contract address.

Right one for BEP20 - 0x443cab9583b83eaa7a712c9d64525e57e2a7eb3f

Info:
https://coinmarketcap.com/currencies/torum/#About
https://dropstab.com/coins/torum

Also, it shows for some reason price for new XTM token. This leads to a lots of scams happening.
Is there a way to verify contract address for token with service from with Unstoppable requesting price?

**Comment by Nyanraltotlapun** [comment]
> It seems proper the UW one:
> 
> https://medium.com/torum-official/torum-xtm-in-now-on-binance-smart-chain-f91b1f0871b0

Read this. It was forked after hack.
https://medium.com/torum-official/the-poly-network-hack-decoded-comprehensive-insight-response-and-the-xtm-token-swapping-3e028f564f09

**Comment by tmedetbekov** [comment]
@Nyanraltotlapun @serrq thank you both for noticing. As we synchronize most of our coin list from CoinGecko, we updated the contract address to the new one provided by CoinGecko.
