### ISSUE TITLE
Rango DEX | Wallet Connect gets error

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7542]
![1000113641](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/a0179817-b96c-48f7-abe3-a87088bc23d1)

![1000113646](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/8e18b49b-4c29-4ee4-b972-de065289f193)

![1000113644](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/5e12d6f8-b3cd-437a-b3c5-7d14f69c5cef)

Rango DEX
https://app.rango.exchange/bridge

**Comment by omurovch** [comment]
successfully connected to both dapps. which version of the wallet are you using? @serrq

**Comment by omurovch** [comment]
is tor enabled?

**Comment by omurovch** [comment]
> Yes, in Invizible app, not in UW. Have I to disable it?
Can you try with tor disabled?

**Comment by omurovch** [comment]
do you use mullvad and invizible apps?

**Comment by omurovch** [comment]
Then it could be mullvad. Connected successfully to https://v2.app.squidrouter.com/ with Invizible DNScrypt + tor.
