### ISSUE TITLE
Possibility to add SPL (Solana) tokens by myself

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7549]
Like Ethereum, Tron, etc. do in "add new token" section.

![1000113657](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/edd71e27-2e23-4acd-ae42-f0856f165c04)

![1000113655](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/1a34fad1-955c-41ec-857e-692b83a401bb)

**Comment by Dianaaiym** [comment]
already done. please check the latest version 0.39
