### ISSUE TITLE
Add Pepecoin support

### ISSUE THREAD

**Issue by marek-guran** [horizontalsystems/unstoppable-wallet-android#7570]
Pepecoin is not a token, but real coin forked from dogecoin with own blockchain. It wants to expand in near future to wallets and this wallet would be great to keep our coins there.

Expected behavior: Be able to sync blockchain of Pepecoin, send and accept transactions.

Github: https://github.com/pepecoinppc/pepecoin
Website: https://pepecoin.org/
Block explorer: https://pepeexplorer.com/

**Comment by marek-guran** [comment]
> Waste of time, resources and money.
> 
> There are coins like XRP with little price (.49$) and ETF in next years.
> 
> This means investments from bottom. Small investors can having its possibility to make money (if they believe) purchasing some XRP tokens today.
> 
> XRP will be also the backbone of the SWIFT payment system of the future (cross-border payments).

What do you mean by that? What I have seen this is Open Source wallet/coin tracker. So what do you mean by waste of money? Anyone can pick up from here and build support for it.

**Comment by marek-guran** [comment]
> Is it different from Pepu (pepe unchained)?
> 
> I wanted investing some dollars on it (pepu).

Yes, it is different. It is like dogecoin, Bitcoin, Litecoin. Crypto with own Blockchain, not a token.

**Comment by Dianaaiym** [comment]
At the moment, we don't have plans to support this coin. Thank you for your understanding!
