### ISSUE TITLE
SPL | Manually added tokens don't fetch icon and insights data

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7590]
UW 0.39

![1000114011](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/093e9358-95ad-47af-9a24-5ce5f70d55ce)

**Comment by abdrasulov** [comment]
That is expected behavior. The same is true for manually added tokens in other blockchains, like Ethereum, Binance Smartchain
