### ISSUE TITLE
Adding The Open Network in the 'Blockchain Settings'

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7592]
![1000114025](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/7a44ff52-5c7f-442f-81f2-307921304db7)

![1000114028](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/07e03e2a-fd70-41f3-a974-33972817d595)

**Comment by abdrasulov** [comment]
As of now, there is only one source for the TON blockchain. That is why it is not shown in that section.
