### ISSUE TITLE
Add support watchonly for z-addresses (zec)

### ISSUE THREAD

**Issue by PirateDigger** [horizontalsystems/unstoppable-wallet-android#7593]
Could you please add watchonly for z-addresses (zec) and export view key to wallet like it's working in ywallet?

**Comment by Dianaaiym** [comment]
> Could you please add watchonly for z-addresses (zec) and export view key to wallet like it's working in ywallet?

It is not possible to watch z-addresses as they are private addresses. Regarding the export/import of the view key, this feature is currently unavailable in the SDK.
