### ISSUE TITLE
Toncoin out of sync intermittently

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7594]
UW 0.39
Android 14
OnePlus CPH2399

Generally it works, but the sync continuously goes away and come back.

I don’t understand what’s causing this temporary instability.

![1000114035](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/17d2e9eb-f59a-409e-a186-efff110db3b2)

----------------------------------------------------------------

![1000114039](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/f3bf8e93-87d6-40ea-80a6-d38fbaa2a10b)

**Comment by Dianaaiym** [comment]
> In the latest two days Toncoin sync has ran smoothly. Can close it or further investigations?

I will close the ticket. If the issue recurs, please reopen it
