### ISSUE TITLE
Token Unlocks API to see a market behavior weeks in advance

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7601]
• https://token.unlocks.app/

• https://insights.unlocks.app/

This is a fee service that releases detailed information on what blockchains will issue new coins in a certain period.

Since releasing coins generates inflation, it is very probable that coin price goes below.

Since these releases are mostly programmed, an investor can knows weeks ahead when sell its coins, before they lose their value.

We have finding an alternative to this crucial service.

**Comment by abdrasulov** [comment]
#7526
