### ISSUE TITLE
Contacts book doesn't see other (mine) wallets addresses

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7613]
![1000114293](https://github.com/user-attachments/assets/42791ddb-3c01-4e0b-bee8-d5410073d4ad)

**Comment by Dianaaiym** [comment]
> I just discovered that contacts button appears only when the app finds a match in contact book in the same wallet.
> 
> The problem is following: why contact book doesn't see the other wallets addresses?
> 
> I own other seven BNB addresses, but the app doesn't see them if I don't write them in contacts book before.
> 
> Trust Wallet shows addresses of all my (recovered) wallets, regardless of which wallet I am connected to.

We do not automatically add addresses to your address book. Only contacts that you manually add will appear there
