### ISSUE TITLE
What happens with Safememe (SME) token?

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7618]
Cannot swap, cannot fetch insights...

![1000115765](https://github.com/user-attachments/assets/30374941-ec9d-463f-b3bb-3b39cdfa4acd)

![1000115767](https://github.com/user-attachments/assets/02c3df6b-5da2-405f-9e1d-5de9ef74932b)

**Comment by Dianaaiym** [comment]
Try changing the swap provider
