### ISSUE TITLE
Cannot completing some swaps

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7628]
0.39.1 Perpetual loading after push "refresh".
Neither on 1inch nor on Uniswap (within UW through APIs). Why?

![1000115997](https://github.com/user-attachments/assets/40bae114-3dda-486c-b4ec-27ad2124c7af)

![1000115999](https://github.com/user-attachments/assets/eb20e4e9-7f95-47b1-8f91-a0fa2e99ecf8)

**Comment by Dianaaiym** [comment]
> 0.39.1 Perpetual loading after push "refresh". Neither on 1inch nor on Uniswap (within UW through APIs). Why?

Please try connecting your wallet directly through WalletConnect to 1inch or Uniswap. This may help resolve the perpetual loading issue you're experiencing in the app.
