### ISSUE TITLE
Add UAH (Ukrainian Hryvnia) as a currency

### ISSUE THREAD

**Issue by notlet** [horizontalsystems/unstoppable-wallet-android#7634]
I'm a newbie crypto user from Ukraine, and I finally found a good self-custodial open source wallet, and it would be great if it supported UAH as a base currency, however I'm not good enough at understanding Java/Kotlin to add it myself.

**Comment by Dianaaiym** [comment]
Thank you for your suggestion! Currently, we don't have plans to support UAH as a base currency, but we appreciate your feedback and will keep it in mind for future updates.
