### ISSUE TITLE
UW suggests disadvantageous conversion rates while trading

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7636]
UW 0.39.2 

Why UW suggests me the less advantageous swap?

![1000116128](https://github.com/user-attachments/assets/72db5033-350d-4300-bdf7-69e373da6522)

**Comment by Dianaaiym** [comment]
Thank you for your feedback and understanding.

We will add labels to provider results to indicate sponsored offers or those that support the development of our project. This page will be updated accordingly in the next update (version 0.40).

I will close this ticket and create a new one to track the changes.
