### ISSUE TITLE
Reproducibility problem in 0.39.2

### ISSUE THREAD

**Issue by xrviv** [horizontalsystems/unstoppable-wallet-android#7638]
Hello team Unstoppable! 

Danny here from @WalletScrutiny 

This is in relation to the current [MR.](https://gitlab.com/walletscrutiny/walletScrutinyCom/-/merge_requests/748)

Here are the results for the latest build. 

```
===== Begin Results =====
appId:          io.horizontalsystems.bankwallet
signer:         c1899493e440489178b8748851b72cbed50c282aaa8c03ae236a4652f8c4f27b
apkVersionName: 0.39.2
apkVersionCode: 112
verdict:        
appHash:        4d76c4345dce50f1e18850dfc2ca9c311876a8ba10dd9f5c57a77a530027c2fc
commit:         d9d1b855a7a4df87278941264ed2da2b1f4aae00

Diff:
Files /tmp/fromPlay_io.horizontalsystems.bankwallet_112/assets/dexopt/baseline.prof and /tmp/fromBuild_io.horizontalsystems.bankwallet_112/assets/dexopt/baseline.prof differ
Files /tmp/fromPlay_io.horizontalsystems.bankwallet_112/classes6.dex and /tmp/fromBuild_io.horizontalsystems.bankwallet_112/classes6.dex differ
Files /tmp/fromPlay_io.horizontalsystems.bankwallet_112/classes7.dex and /tmp/fromBuild_io.horizontalsystems.bankwallet_112/classes7.dex differ

Revision, tag (and its signature):

===== End Results =====
```
The diffoscope results are 442 MB. 
The results are here: [mega.nz](https://mega.nz/file/TNJQkSYa#0eYOae8jzMHglPBVig4u3nf__fqTuKriAtr9ojpfOAc)

**Comment by rafaelekol** [comment]
The differences in version 0.39.2 were caused by the Android Studio build process. To ensure consistency across tests, we use Docker to create a uniform build environment. We recently released version 0.39.3, which should resolve the reproducibility issue.

**Comment by xrviv** [comment]
Thank you. I've noted this and the new tests came out as reproducible.

https://gitlab.com/walletscrutiny/walletScrutinyCom/-/merge_requests/772

**Comment by rafaelekol** [comment]
@xrviv Hi Danny,
I tried to find way to communicate with WalletScrutiny team, but couldn't find how.
Thats why I decided to write our issue here.
Recently our apk size has grown more than 100mb. And now we have issue with upload limit to Play Store.
Currently one of the solutions to fix our issue to use Bundle for uploading to Store.
Do you already support bundles for reproduce tests?
Or is there any other options for this?

**Comment by xrviv** [comment]
Hi Rafael, sorry for the late reply. re: I have responded to the LinkedIn message. 

Yes, we can accommodate for AABs via our [testAAB.sh](https://gitlab.com/walletscrutiny/walletScrutinyCom/-/blob/master/testAAB.sh)

It would be helpful if you can provide us with an app-specific script and an app-specific Dockerfile if needed. 

Here is a sample that we have for nunchuk:

### [io.nunchuk.android.sh](https://gitlab.com/walletscrutiny/walletScrutinyCom/-/blob/master/scripts/test/android/io.nunchuk.android.sh)

### [io.nunchuk.android.dockerfile](https://gitlab.com/walletscrutiny/walletScrutinyCom/-/blob/master/scripts/test/android/io.nunchuk.android.dockerfile)
