### ISSUE TITLE
Tron (TRX) sync problems [again]

### ISSUE THREAD

**Issue by TheFuzzStone** [horizontalsystems/unstoppable-wallet-android#7662]
In the past we had [#6316](https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6316).

---

Today I had the same problem. This affects the reliability of the wallet.

Please add to "Blockchain Settings" the ability for users to specify nodes that they can search for online. 

Do I understand correctly, you have the Tron node hardcoded right now? So, as we can see is not the best choice.

**Comment by Dianaaiym** [comment]
> In the past we had [#6316](https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6316).
> 
> Today I had the same problem. This affects the reliability of the wallet.
> 
> Please add to "Blockchain Settings" the ability for users to specify nodes that they can search for online.
> 
> Do I understand correctly, you have the Tron node hardcoded right now? So, as we can see is not the best choice.

Hi,

Everything is working fine on our side. Please check again, and if the issue persists, kindly provide more details so we can assist you further.
