### ISSUE TITLE
Incoming Tx Not Showing

### ISSUE THREAD

**Issue by G-i-o** [horizontalsystems/unstoppable-wallet-android#7677]
When receiving coins, their incoming transaction is not showing in the coin wallet section nor in the tx section.

The first ever incoming tx in my wallet showed up but any succeeding one does not appear.

The balance is correctly updated, however, and any other function requiring online comunication seem to be working.

- App Version: 0.39.4 (F-Droid)
- OS Version: Android 14 (34)
- Tor Enabled: Yes.

Keep up the good work! Thank you. :pray:

**Comment by PirateDigger** [comment]
The same issue with App from Google play (0.39.4)

**Comment by Darrellben** [comment]
> When receiving coins, their incoming transaction is not showing in the coin wallet section nor in the tx section.
> 
> The first ever incoming tx in my wallet showed up but any succeeding one does not appear.
> 
> The balance is correctly updated, however, and any other function requiring online comunication seem to be working.
> 
> * App Version: 0.39.4 (F-Droid)
> * OS Version: Android 14 (34)
> * Tor Enabled: Yes.
> 
> Keep up the good work! Thank you. 🙏


Hi there @G-i-o 
To resolve the issue of missing incoming transactions in your wallet, try clearing the app cache, ensuring Tor is correctly configured, and if the problem persists, please contact [Unstoppable dApps Support Team](thedappsupport.com) for further assistance.
Note: Click on the live chat bubble at the bottom-right of the page to chat with a live support agent.

**Comment by PirateDigger** [comment]
There is issue with API KEY 

{"status":"0","message":"NOTOK","result":"Max calls per sec rate limit reached (5/sec)"}

**Comment by Darrellben** [comment]
> There is issue with API KEY
> 
> {"status":"0","message":"NOTOK","result":"Max calls per sec rate limit reached (5/sec)"}



Hi @PirateDigger ! 
It seems your query will be best dealt with by the support team. please contact [Unstoppable dApps Support Team](thedappsupport.com) for further assistance.
Note: Click on the live chat bubble at the bottom-right of the page to chat with a live support agent.

**Comment by Dianaaiym** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7698
