### ISSUE TITLE
Add TON Connect

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#7678]

**Comment by Unb0rn** [comment]
So, was this implemented? I can't  find the feature in 0.41 and standard WalletConnect  returns "wrong URL". Maybe we should re-open this?

**Comment by Dianaaiym** [comment]
> So, was this implemented? I can't find the feature in 0.41 and standard WalletConnect returns "wrong URL". Maybe we should re-open this?

TON Connect has been added but has not yet been fully integrated into the app. Additionally, the 0.41 changelogs did not mention the inclusion of TON Connect.
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7772
