### ISSUE TITLE
Implementing BIP-47

### ISSUE THREAD

**Issue by retrnull** [horizontalsystems/unstoppable-wallet-android#7694]
I would like to work on implementing send and receive support for BIP-47 payment codes. However, before I start the work, I have a few questions:

- Would such a feature be accepted into the codebase?
- I expect to take about a month to implement it. Approximately when would a release including the functionality be made available for download?

Thanks in advance. Please let me know of any concerns about BIP-47 and this particular endeavor. I'll start working on the implementation once I get answers.

**Comment by Dianaaiym** [comment]
duplicate https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7537

**Comment by retrnull** [comment]
@Dianaaiym I would like to argue that it is not a duplicate.

This issue is concerned with whether the feature would accepted in a PR if an external contributor were to implement it, and how long it would take, approximately, for it to be included in a release that can be downloaded by Android users. On the other hand, the linked issue is only concerned with the implementation itself, without regards to who implements it or when it woul
d be included in a release.

That said, I have posted my questions there as well. Please take a look at it.
