### ISSUE TITLE
The newest POL (Polygon) token can't swap anything

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7695]
![1000124503](https://github.com/user-attachments/assets/d43f2de3-56d4-4fed-8f3f-6a479436b9e3)

![1000124506](https://github.com/user-attachments/assets/509b90cc-6b24-4568-9429-22598fddc7c9)

**Comment by Dianaaiym** [comment]
Hi,

If the new POL (Polygon) token isn't swapping, this issue isn't on our end as we use swap APIs. We have updated the coin code for MATIC to POL, and your MATIC balance should automatically migrate to POL. Please note that swapping works for the native POL.
