### ISSUE TITLE
Why XAUT/ETH pair isn't swappable?

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7702]
Unbelievable! The most traded pair is not available.

![1000124555](https://github.com/user-attachments/assets/156ec2c4-f249-4e54-8e2a-d55c457c13ee)

![1000124553](https://github.com/user-attachments/assets/c6266ffd-1812-4718-8a5a-16a9d8387f98)

**Comment by Aster36-kEth** [comment]
@serrq Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://chainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Aster36-kEth** [comment]
@serrq I experienced a similar problem, and the support team was able to assist me effectively.

**Comment by LeoNore-ort** [comment]
I experienced a similar problem, and the support team was able to assist me effectively.

**Comment by Dianaaiym** [comment]
> Unbelievable! The most traded pair is not available.
> 
> ![1000124555](https://private-user-images.githubusercontent.com/113377431/374441726-156ec2c4-f249-4e54-8e2a-d55c457c13ee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NTcyMjQsIm5iZiI6MTcyODQ1NjkyNCwicGF0aCI6Ii8xMTMzNzc0MzEvMzc0NDQxNzI2LTE1NmVjMmM0LWYyNDktNGU1NC04ZTJhLWQ1NWM0NTdjMTNlZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwNjU1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTYwNjA1YWFlM2U4NGFiNzYyYjRkOGYwOWM1ZWE0YjFlZjVhMTNlNjUyYjg5OGEyNzlmODlmYTg5NTM5MTMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.02IxneNYYiUl1chSKgWlt9zNYttvtz5rjeN64ieHp0M)
> 
> ![1000124553](https://private-user-images.githubusercontent.com/113377431/374441744-c6266ffd-1812-4718-8a5a-16a9d8387f98.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NTcyMjQsIm5iZiI6MTcyODQ1NjkyNCwicGF0aCI6Ii8xMTMzNzc0MzEvMzc0NDQxNzQ0LWM2MjY2ZmZkLTE4MTItNDcxOC04YTVhLTE2YTlkODM4N2Y5OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwNjU1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTliOTRjYzYzNjNmMzI1Zjg1YmQ4ZGRjNWZlOGNmODllMjY1MGYwMGRkM2NhMTgxOWI3ODgwOTkxNmMzNDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o_EFmBOH0ZE4rWct8zdCqBkBhNnrabzBjxu6U7Pwks0)

We use what the Uniswap and PancakeSwap APIs provide us. Try swapping through the Uniswap website by connecting via WalletConnect and confirming the following message: "This token isn’t traded on leading U.S. centralized exchanges or frequently swapped on Uniswap. Always do your own research before proceeding."
