### ISSUE TITLE
Markets tab sync error

### ISSUE THREAD

**Issue by aaricksage** [horizontalsystems/unstoppable-wallet-android#7705]
It's not syncing no matter how much I wait.
UW: 0.40.1
Android: 10
https://github.com/user-attachments/assets/f406aa35-6e49-4877-890a-d04cee9c12f8

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by abdrasulov** [comment]
Hello @aaricksage,

We could not reproduce the issue. Can you please check it once again and let us know if the issue still persists?
