### ISSUE TITLE
Request for Native Dogecoin Support

### ISSUE THREAD

**Issue by cosifresco** [horizontalsystems/unstoppable-wallet-android#7729]
I would like to request the inclusion of native Dogecoin support in the wallet. Dogecoin is an extremely popular cryptocurrency and is already supported by other free and open-source software, such as BTCPay Server.

Dogecoin utilizes a Scrypt-based proof-of-work algorithm similar to Litecoin, but with faster block times. Given its similarities to Litecoin and Bitcoin in terms of blockchain framework, it seems unusual that it hasn't been included yet.

Adding native support for Dogecoin would not only enhance the wallet’s functionality but also appeal to a broader user base.

**Comment by Dianaaiym** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7751
