### ISSUE TITLE
USDT TRC20 never stops syncing.

### ISSUE THREAD

**Issue by hsynkrtl** [horizontalsystems/unstoppable-wallet-android#7730]

**Comment by ztx-lyghters** [comment]
This is still a problem.

**Comment by ztx-lyghters** [comment]
> _No description provided._

I'm going to take a guess that you have restored a backup of your wallet. Probably via an older version of the app. If that's the case, you've got a backup bug. Update your app from where you've exported the wallet and export it again.

**Comment by Dianaaiym** [comment]
The issue with USDT TRC20 not syncing doesn't seem to be happening on our end.
