### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [horizontalsystems/unstoppable-wallet-android#7766]
https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8452771515 Firebase is included in the apk which seems to be caused by the upgrade of walletconnect, https://github.com/horizontalsystems/unstoppable-wallet-android/commit/31668be3fe523a5c3dbf1b5333592bc7d28c2a20#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R300. Could you please take a look? Thanks!

**Comment by rafaelekol** [comment]
We reverted WalletConnect to older version.

**Comment by linsui** [comment]
Thanks!

**Comment by rafaelekol** [comment]
@linsui 
We want to know how many users are using our Unstoppable Wallet from F-Droid. Is there known ways how to count them?
It would be a great help for us.

**Comment by Dianaaiym** [comment]
Hi @linsui ,

I hope you’re doing well!

We uploaded a new update (APK) to GitHub a week ago, and I wanted to check when this update will be available on F-Droid. 

Thank you in advance for your assistance!
