### ISSUE TITLE
LTC not getting removed from Balance Page

### ISSUE THREAD

**Issue by grichee** [horizontalsystems/unstoppable-wallet-android#7790]
Steps:
1. Open UW.
2. Go to Coin Manager and enable LTC.
3. Come back to Balance page and swipe LTC.
4. Click on "-" button and LTC will be still there unless you restart UW.

Android 10
UW 0.41.0 F-droid build

Note: It happens only on the 1st time you try to do it. So it is most likely a one-time issue with new wallets.

**Comment by Dianaaiym** [comment]
> Steps:
> 
> 1. Open UW.
> 2. Go to Coin Manager and enable LTC.
> 3. Come back to Balance page and swipe LTC.
> 4. Click on "-" button and LTC will be still there unless you restart UW.
> 
> Android 10 UW 0.41.0 F-droid build
> 
> Note: It happens only on the 1st time you try to do it. So it is most likely a one-time issue with new wallets.

We couldn’t reproduce the issue on our side. If it happens again, please let us know!
