### ISSUE TITLE
Allow selection of wallet format types in coin Manager

### ISSUE THREAD

**Issue by grichee** [horizontalsystems/unstoppable-wallet-android#7791]
![Screenshot_2024-12-07-16-11-11-54.jpg](https://github.com/user-attachments/assets/dc88b4e5-020d-4300-8a06-e1afff12e100)

Here you gave us the option to select wallet type in markets tab but not in Coin Manager.

**Comment by Dianaaiym** [comment]
You can select the wallet format type in the Coin Manager as well.
![2024-12-13 12 15 32](https://github.com/user-attachments/assets/601e09bc-e9d4-4d46-b8ab-032184899037)
