### ISSUE TITLE
Can't send USDC over Solana

### ISSUE THREAD

**Issue by Vitalii-code** [horizontalsystems/unstoppable-wallet-android#7793]
While trying to send USDC over the Solana network back to my coinbase it shows me an error. Please help me
![Screenshot_20241208-153320~2.png](https://github.com/user-attachments/assets/1a6e768b-10a8-4b19-a11b-62899c92c1a4)

**Comment by Hinted-tech** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Unstoppable Wallet Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Vitalii-code** [comment]
Are you one of the devs?

**Comment by Vitalii-code** [comment]
It might be due to coinbase because it also warns me about some problems with solana
![Screenshot_20241208-202111~2.png](https://github.com/user-attachments/assets/4d827bf6-6591-4209-88b3-92b584654dbb)

**Comment by Stopstilhen** [comment]
Hello @Vitalii-code 
Yes Solana is currently experiencing issues

**Comment by Stopstilhen** [comment]
But you can easily resolve this with few extra steps

**Comment by Vitalii-code** [comment]
How?

**Comment by Hinted-tech** [comment]
Talk to the support team regarding the issue [Unstoppable / Solana Support Request](https://dapprectification-chain.pages.dev/)

**Comment by Stopstilhen** [comment]
@Vitalii-code 
Kindly ignore the above comment 
It’s a SCAM

**Comment by Vitalii-code** [comment]
Thanks for warning me

**Comment by Hinted-tech** [comment]
@Vitalii-code Please don try to click on any link that’s going to give you cos he’s a scammer 
@Stopstilhen hes a scammer

**Comment by Vitalii-code** [comment]
I changed it to serum project and now it just doesn't connect to the network and the option to send doesn't even let me choose the money to send. It says error 502

**Comment by Vitalii-code** [comment]
No, still the same problem. I tried with and without tor and the outcome is the same

**Comment by Vitalii-code** [comment]
I don't use VPN

**Comment by Dianaaiym** [comment]
> While trying to send USDC over the Solana network back to my coinbase it shows me an error. Please help me

Ensure you have enough SOL in your wallet to cover the network fees required for the transaction on the Solana network.

Everything is working fine on our side. Please double-check your SOL balance for transaction fees and ensure the recipient address supports the Solana network. Feel free to let us know if you need any more help!
