### ISSUE TITLE
Blank screen on App restore

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#7801]
Sometime when I open app, it shows blank screen.

**Comment by rafaelekol** [comment]
Similar case
![photo_2024-12-13_16-55-53](https://github.com/user-attachments/assets/da165340-9f8d-42be-814d-b7924186e828)

**Comment by grichee** [comment]
> Similar case
> ![photo_2024-12-13_16-55-53](https://github.com/user-attachments/assets/da165340-9f8d-42be-814d-b7924186e828)
> 

same here. often gets the blank screen and need to restart. Fix it asap.
