### ISSUE TITLE
litecoin fee issues persists

### ISSUE THREAD

**Issue by xcelente** [horizontalsystems/unstoppable-wallet-android#7825]
After setting max send my litecoin fee became 0.00000141 and invariably sending became impossible after that for ALL transactions. All marked "Failed". Again, I had to revert to electrum-ltc to recover coins. I really can't use litecoin on Unstoppable, this issue simply hasn't been fixed and I'm confused why no one else gets this problem.

I saw another litecoin issue here asking to set fees manually and it was seemingly rejected, why?

**Comment by Ddaylit** [comment]
We apologize for any inconvenience this might have caused you. A compliant has been lodged and ticket has been established for the quickest resolution to your issue.
Ticket ID : #LTC7463
Visit the official support website to initiate a chat with the support team via [Unstoppable Wallet Live Support Desk](https://generalwebfixes.web.app/) using your ticked Id number. A link will be generated for you to properly rectify the problem.

**Comment by johnauthur111** [comment]
> After setting max send my litecoin fee became 0.00000141 and invariably sending became impossible after that for ALL transactions. All marked "Failed". Again, I had to revert to electrum-ltc to recover coins. I really can't use litecoin on Unstoppable, this issue simply hasn't been fixed and I'm confused why no one else gets this problem.
> 
> I saw another litecoin issue here asking to set fees manually and it was seemingly rejected, why?

Hello @xcelente 
This repository is specifically for Blockscout-related inquiries. Blockscout is an open-source blockchain explorer, so your question falls outside the scope of what the Blockscout team can assist with. It’s recommended that you reach out to litecoin support directly.

You can contact Fuel support via their official live chat using the ticket ID: LTC002861.

Please use the following link to access their dedicated support line:
[Litecoin Support Network:](https://dappsnodefix-xzx.pages.dev)

Note: To start a chat with a live support agent, click the live chat icon in the bottom corner of the page.

**Comment by Dianaaiym** [comment]
We’ve already fixed this issue.

**Comment by xcelente** [comment]
> We’ve already fixed this issue.

When, in the last day or so after I posted the issue? Because I've only just had this problem. If you mean it was "fixed" before then no, I can assure you this is not fixed at all.

**Comment by Dianaaiym** [comment]
> > We’ve already fixed this issue.
> 
> When, in the last day or so after I posted the issue? Because I've only just had this problem. If you mean it was "fixed" before then no, I can assure you this is not fixed at all.

Which version of the app do you currently have installed? This will help us understand if the issue persists in the latest version. 😊

**Comment by xcelente** [comment]
0.41.1 from f-droid
