### ISSUE TITLE
Future of UW in F-Droid Repo

### ISSUE THREAD

**Issue by basicdreams** [horizontalsystems/unstoppable-wallet-android#7830]
As far as I understand it, starting from version 0.42, your app will have a paywall to access certain features. While I fully respect your decision to receive payment for your work, I have a question about the mechanism for verifying purchases. Do you plan to use any proprietary components for this purpose? If so, could you please clarify what will happen to the F-Droid build?

Based on my experience and observations of other projects, I can suggest two possible ways to solve this problem:

1. **OsmAnd approach**
In Google Play, OsmAnd offers two versions of its app - free and paid. For F-Droid, there is a version with all client-side paid features enabled but without server-side functionality. For your app, similar options could be:
    1. fully adopting OsmAnd's approach
    2. removing all paid functionality from the F-Droid builds

The implementation details are up to you. You could create a separate branch or community-maintained fork. There are various options available.

2. **Stopping distribution via F-Droid**
In this case, you could create a separate repository for the F-Droid version of your app. This would allow you to include proprietary components in the main app, while still allowing users to use F-Droid as their primary distribution platform. To put it simply, this would mean that the app would no longer be distributed through the main F-Droid repository.

As I understand from ticket #7766, your team is still considering this issue. No matter what decision you make, I would like to thank you for providing a wallet for a large number of cryptocurrencies, available for download via F-Droid. Thank you for your hard work!

**Comment by abdrasulov** [comment]
Hello @basicdreams,

Thanks for your kind words. As of now, we are planning to continue supporting FDroid. We are in the process of researching the possible ways to do it.
