### ISSUE TITLE
work on scroll animation on balance tab and transaction tabs

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#885]
- [x] when scrolled down: on scroll up the tab header (BALANCE / TRANSACTIONS) should appear only when the list has finished scrolling. only after the entire list has scrolled through the header should appear.

- [x] when the user has reached the end of the scroll ( the very bottom / top ) show the expanding over scroll edge effect that's custom to Android. Such effect can be observed on Telegram's chats screen.

**Comment by TalgatNurdinov** [comment]
try resizing the title and changing transparency when scrolling 9 (like whatsapp contact info)
