### ISSUE TITLE
fee rate / exchange rate syncer: connection /fallback logic

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#890]
**Exchange Rates**

- [x] the first request should be made to HS IPFS node. If that doesn't respond in 10 seconds then request from ipfs.io (timeout after 60 seconds)
- [x] apply logic for real time rates (ex: balance tab, send controller, etc)
- [x] apply logic for historical exchange rates (transactions tab, transaction info, etc)

**Comment by rafaelekol** [comment]
Created issue for estimate fees in related project 
https://github.com/horizontalsystems/blockchain-fee-rate-kit-android/issues/5

**Comment by esengulov** [comment]
@rafaelekol I have updated timeout values, please make changes accordingly
