### ISSUE TITLE
hard code max possible fee values as a safeguard against bugs in fee logic

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#891]
There should a hardcoded check on the client side that would never allow a fee value above certain threshold, even if the client receives such value from fee-rate-kit. 

In other words there should be an absolute allowed max fee. If for some reason the client receives a value from fee-rate-kit that's higher than that amount it would be disregarded.

These values should be as follow:

- BTC: 0.04
- ETH: 0.1
- BCH: 0.1
- Dash: 0.1

**Comment by rafaelekol** [comment]
Moved issue to related project https://github.com/horizontalsystems/blockchain-fee-rate-kit-android/issues/7
