### ISSUE TITLE
Implement Wallet Restore layout

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#918]
The Bitcoin Kit is being prepared now for the full network sync. once it's ready we are ready to proceed to implement this on the wallet UI giving user an option to choose what kind of sync mode to use on Wallet remote 

- [ ] implement new restore screen. It will appear as a first step in wallet restore, https://zpl.io/2pM1Rwo

- [ ] restore texts: @Dianaaiym 
-- (for fast mode) Restores your past transactions via secure third party server. For users with a long history of transactions involving very large sums this method may pose privacy risks.
-- (for slow mode) Restores your past transactions directly from the network. Significantly more private but very slow. The more coins you restore the longer it takes. If the restore takes way too much time go to Security section in Settings tab and select “Unlink This Device” option.

**Comment by esengulov** [comment]
@TalgatNurdinov upload the designs here

@Dianaaiym localize the new layouts

**Comment by TalgatNurdinov** [comment]
<img width="1466" alt="Screen Shot 2019-05-31 at 3 17 28 PM" src="https://user-images.githubusercontent.com/42367908/58695439-38fefe80-83b7-11e9-8cd3-078799986121.png">

https://zpl.io/2j5oReA
https://zpl.io/amdEwr9
https://zpl.io/2ZrG8y4
https://zpl.io/bzq0vvM

**Comment by TalgatNurdinov** [comment]
new restore options screen
https://zpl.io/2pM1Rwo

**Comment by TalgatNurdinov** [comment]
New Settings Page
https://zpl.io/Vx6Kj9x

**Comment by esengulov** [comment]
> New Settings Page
> https://zpl.io/Vx6Kj9x

no longer relevant!
