### ISSUE TITLE
check if wallet keeps any logs, if so deactivate them. 

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#959]
No logging should be taking place, even if it's native ones from Android/Google

**Comment by rafaelekol** [comment]
We can follow ideas from this article to implement centralized Logging system in our project
https://proandroiddev.com/managing-logging-in-a-multi-module-android-application-eb966fb7fedc

**Comment by rafaelekol** [comment]
Make sure that logger is not printing logs when build has MainNet
