### ISSUE TITLE
Balance tab sorting

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-android#980]
Sort by

Value
A-Z
Manual (managed)

*if rate not available sort by value should be disabled (grey50)

<img width="734" alt="Screen Shot 2019-06-19 at 5 08 23 PM" src="https://user-images.githubusercontent.com/42367908/59760801-f98c4980-92b4-11e9-9dc0-102bf74b4920.png">

https://zpl.io/agkO59N

**Comment by esengulov** [comment]
please include mockups that have ONLY sorting by price/value/custom. no other elements should be included @TalgatNurdinov

**Comment by TalgatNurdinov** [comment]
- [ ] Sorting menu should be activate after 5+ added coins
