### ISSUE TITLE
Introduce Protocol for External Libraries 

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#999]
Not so long ago, there was an attack on one of the wallets in the market. You may read about this here, https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm

With that in mind let's review all third party libraries used in the wallet as well as wallet kits and introduce a protocol about pulling 3rd party library updates moving forward.

**Comment by abdrasulov** [comment]
We've reviewed our source code and external libraries. We didn't find any potential security vulnerabilities. Data encryption/decryption is implemented using the Android OS. As for the libs, it is recommended to keep them up to date. We already have this point in our dev process.
